FROM centos:7

MAINTAINER Zach Rhoads (https://github.com/rhoads-zach)

USER root

# Install asciidoctor
RUN yum install -y rubygems libxml2 && \
    gem install asciidoctor -v 1.5.8 && \
    yum clean all

COPY scripts/ scripts/
COPY docs/ docs/

RUN scripts/validate_guides.sh

