# appdev.openshift.io Documentation

This repository holds the documentation for appdev.openshift.io.

Generated docs are built and deployed on every push to the `production` branch of the authoritative repository (https://github.com/openshiftio/appdev-documentation[upstream/production]) and are available at http://appdev.openshift.io/[http://appdev.openshift.io].  To test changes before pushing to the `production` branch, put all forward development in `upstream/master` and see its current state reflected in the staging environment at http://appdev-stage.openshift.io/[http://appdev-stage.openshift.io].  The `upstream/production` branch should typically be updated only via merges from `upstream/master` when it's determined the docs are ready to go live.

## Directory Structure

* `docs/` - This folder contains all the appdev.openshift.io guides and related content.
** `topics/` - This folder contains `adoc` files representing shared content between guides.
*** `images/` - This folder contains all images used in the guides.
*** `styles/` - This folder contains all stylesheets used in the guides.
*** `templates/` - This folder contains template data, such as common attributes, used in the guides.
** `GUIDE_NAME/` - There is a folder for each guide.
*** `master.adoc` - This is the primary file for the guide. Common files or _topics_ are included from the `topics/` folder.
*** `buildGuide.sh` - This is a script to build this individual guide.
*** `topics/` - This is a symlink to `../topics/`, which makes building each guide a lot easier.
* `scripts/` - This folder contains scripts needed for building guides in the repository.

## Building the Guides

. Ensure you have link:http://asciidoctor.org[AsciiDoctor] installed and configured.
. Run the `scripts/buildGuides.sh` script to build all guides.
. All guides will be generated as single HTML files in `html/`.

## Contributing

To start contributing:

. Fork the link:https://github.com/openshiftio/appdev-documentation[upstream repository] into your user namespace

. Clone your fork.
+
[source,options="nowrap"]
----
$ git clone git@github.com:USERNAME/appdev-documentation.git
----

. Add the main project as a remote.
+
[source,options="nowrap"]
----
$ cd appdev-documentation
$ git remote add upstream git@github.com:openshiftio/appdev-documentation.git
$ git fetch upstream
----

. Create a branch for your contribution based on `upstream/master`.
+
[source,options="nowrap"]
----
$ git checkout -b my-awesome-idea upstream/master
----

. Make your changes.

. Commit your work and push it to your fork.
+
[source,options="nowrap"]
----
$ git add docs/topics/my-awesome-idea.adoc
$ git commit -m "Added my awesome idea."
$ git push origin HEAD
----

. File a pull request to `upstream/master`.

### Add a New Guide

. Create a new folder for the guide under `docs/` e.g. `docs/my-new-guide`.

. Under that folder:
** Create a `master.adoc` file.

** Create a symlink called `topics` to `../topics`.
+
[source,options="nowrap"]
----
ln -s ../topics topics
----

** Copy the `buildGuide.sh` script from another guide's folder and modify line 3. This defines the output name of the html file. This should match the folder name.

. Add the default content to master.adoc.
+
[source,options="nowrap"]
----
include::topics/templates/document-attributes.adoc[]

:my-new-guide:

= {my-new-guide-guide-name}
----

. Update `docs/topics/templates/document-attributes.adoc` by adding the guide name attribute.
+
[source,options="nowrap"]
----
:my-new-guide-guide-name: My Awesome New guide
----

. Run the `scripts/buildGuides.sh` script to ensure the new guide builds with the others.

. Open the generated html file to ensure everything looks correct.

You have now created the scaffolding for a new guide. When you are ready for some initial review and feedback, file a pull request to `upstream/master`.

### Merging Contributions
// title OK?
// following content up for revision.
// externalize naming examples to variables?
//add note about signing commits?

. Once the changes in a pull request have been approved, you can merge them into `upstream/master`.
+
[IMPORTANT]
--
Do not merge your own pull requests unless absolutely necessary. You are accountable for any errors, merge conflicts, or bugs resulting from incorrect merging. Let another contributor with the appropriate repository access privileges do it.
--
+
[NOTE]
--
As a best practice, always link:https://help.github.com/articles/signing-commits-with-gpg/[sign your contributions using a GPG key].
--
+
. Before merging, ensure that you have the contributor's fork of the link:https://github.com/openshiftio/appdev-documentation[upstream repository] in your list of remotes:
+
[source,options="nowrap"]
--
git remote -v
--
+
. To add a remote fork for to you Git directory:
+
.. Navigate to the contributor's fork on link:https://github.com/[GitHub].
.. Click the _Clone or Download_ button.
.. Select _Use SSH_.
.. Copy the repository URL beginning with `git@github.com:`.
.. Execute the following command, replacing `username` with the user name of the contributor:
+
[source,options="nowrap"]
--
git remote add username git@github.com:username/appdev-documentation.git
--
+
.. Use `git remote -v` to verify that the fork is now listed among your remotes.
.. Execute `git remote update` to fetch the latest state of the remotes to your working directory.
+
. Create a new branch and set it to track the remote branch that introduces the changes in the pull request:
+
[source,options="nowrap"]
--
git checkout -b pr-to-merge username/featurebranch
--
+
----
Branch pr-to-merge set up to track remote branch <topic_branch> from <username> by rebasing.
Switched to a new branch 'pr-to-merge'
----
+
. Fetch the latest state of `upstream` and rebase your topic branch:
+
[source,options="nowrap"]
--
git fetch upstream
--
+
[source,options="nowrap"]
--
git rebase upstream/master
--
+
If you have multiple commits on your feature branch, squash them into a single commit before merging.
+
. Test if all the books build correctly with your changes, by executing the script `/scripts/buildGuides.sh`. If the output contains no errors, the guides build correctly.
+
. Checkout your local `master`:
+
[source,options="nowrap"]
--
git checkout master
--
+
. Rebase your local `master` against `upstream/master`:
+
[source,options="nowrap"]
--
git rebase upstream/master
--
+
. Merge your topic branch into `master`:
+
[source,options="nowrap"]
--
git merge pr-to-merge
--
+
. Execute `/scripts/buildGuides.sh` to test whether the guides build correctly with the changes introduced by your merge.
+
. Push the latest changes into `upstream`:
+
[source,options="nowrap"]
--
git push upstream master
--
+
The changes are now merged into `upstream/master`.
+
. Close the pull request for the changes you just merged:
.. Obtain the commit hash of the last commit on `master`:
+
[source,options="nowrap"]
--
git log -1 HEAD
--
+
.. Navigate to the pull request on GitHub.
.. Paste the commit following line into a new comment, replacing <commit-hash> with the SHA-1 of your commit:
+
----
merged: <commit-hash>
----
+
.. Click _Close and comment_.
