= launcher.fabric8.io Documentation

This repository holds the documentation for link:https://launcher.fabric8.io[launcher.fabric8.io]. The source language is AsciiDoc.

== Building and Health

link:https://ci.centos.org/job/devtools-launcher-documentation-generator-build-master/[image:https://ci.centos.org/buildStatus/icon?job=devtools-launcher-documentation-generator-build-master[]]

The documentation is built on link:https://ci.centos.org/job/devtools-launcher-documentation-generator-build-master/[ci.centos.org]. Both the `master` branch and individual pull requests are subject to testing.

== Providing Feedback

If you see an error or would like to provide feedback, please file an issue in our link:https://issues.jboss.org/projects/RHOARDOC/[Jira] project.


== Running locally

Run the `scripts/preview-server.sh` script. Because it requires Docker, you need to have sudo access to run it.

== Contributing

For information about contributing to this repository, its contents and processes, see the link:https://launcher.fabric8.io/docs/contrib-guide.html#_documentation[Documentation] chapter of the __Contribution Guide.__

For general information about missions and boosters, see the link:https://launcher.fabric8.io/docs/getting-started.html[Getting Started Guide]. For information about their development, see the link:https://github.com/fabric8-launcher/launcher-documentation/wiki[Wiki].

== Publishing

Basic information about publishing a release is described in the link:https://launcher.fabric8.io/docs/contrib-guide.html#releasing_new_version[Releasing New Version] chapter of the __Contribution Guide.__

