= Batch (JBeret)

The Batch fraction provides support for scheduled job execution,
through JSR-352.

For additional information about JBeret please see the
https://jberet.gitbooks.io/jberet-user-guide/content/[JBeret User's Guide].



.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>batch-jberet</artifactId>
</dependency>
----

.Configuration

swarm.batch.default-job-repository:: 
The name of the default job repository.

swarm.batch.default-thread-pool:: 
The name of the default thread-pool.

swarm.batch.jdbc-job-repositories._KEY_.data-source:: 
The data source name used to connect to the database.

swarm.batch.restart-jobs-on-resume:: 
If set to true when a resume operation has be invoked after a suspend operation any jobs stopped during the suspend will be restarted. A value of false will leave the jobs in a stopped state.

swarm.batch.thread-factories._KEY_.group-name:: 
Specifies the name of a  thread group to create for this thread factory.

swarm.batch.thread-factories._KEY_.name:: 
The name of the created thread factory.

swarm.batch.thread-factories._KEY_.priority:: 
May be used to specify the thread priority of created threads.

swarm.batch.thread-factories._KEY_.thread-name-pattern:: 
The template used to create names for threads.  The following patterns may be used:
	%% - emit a percent sign
	%t - emit the per-factory thread sequence number
	%g - emit the global thread sequence number
	%f - emit the factory sequence number
	%i - emit the thread ID.

swarm.batch.thread-pools._KEY_.active-count:: 
The approximate number of threads that are actively executing tasks.

swarm.batch.thread-pools._KEY_.completed-task-count:: 
The approximate total number of tasks that have completed execution.

swarm.batch.thread-pools._KEY_.current-thread-count:: 
The current number of threads in the pool.

swarm.batch.thread-pools._KEY_.keepalive-time:: 
Used to specify the amount of time that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

swarm.batch.thread-pools._KEY_.largest-thread-count:: 
The largest number of threads that have ever simultaneously been in the pool.

swarm.batch.thread-pools._KEY_.max-threads:: 
The maximum thread pool size. Note this should always be greater than 3. Two threads are reserved to ensure partition jobs can execute as expected.

swarm.batch.thread-pools._KEY_.name:: 
The name of the thread pool.

swarm.batch.thread-pools._KEY_.queue-size:: 
The queue size.

swarm.batch.thread-pools._KEY_.rejected-count:: 
The number of tasks that have been rejected.

swarm.batch.thread-pools._KEY_.task-count:: 
The approximate total number of tasks that have ever been scheduled for execution.

swarm.batch.thread-pools._KEY_.thread-factory:: 
Specifies the name of a specific thread factory to use to create worker threads. If not defined an appropriate default thread factory will be used.


