# IO

Primarily an internal fraction supporting I/O activities
for higher-level fractions.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>io</artifactId>
</dependency>
----

.Configuration

swarm.io.buffer-pools._KEY_.buffer-size:: 
The size of each buffer slice in bytes, if not set optimal value is calculated based on available RAM resources in your system.

swarm.io.buffer-pools._KEY_.buffers-per-slice:: 
How many buffers per slice, if not set optimal value is calculated based on available RAM resources in your system.

swarm.io.buffer-pools._KEY_.direct-buffers:: 
Does the buffer pool use direct buffers, some platforms don't support direct buffers

swarm.io.workers._KEY_.io-threads:: 
Specify the number of I/O threads to create for the worker.  If not specified, a default will be chosen, which is calculated by cpuCount * 2

swarm.io.workers._KEY_.stack-size:: 
The stack size (in bytes) to attempt to use for worker threads.

swarm.io.workers._KEY_.task-keepalive:: 
Specify the number of milliseconds to keep non-core task threads alive.

swarm.io.workers._KEY_.task-max-threads:: 
Specify the maximum number of threads for the worker task thread pool.If not set, default value used which is calculated by formula cpuCount * 16


