= JGroups


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jgroups</artifactId>
</dependency>
----

.Configuration

swarm.default.multicast.address:: 
Default multicast address for JGroups

swarm.j-groups.channels._KEY_.address:: 
The IP address of the channel.

swarm.j-groups.channels._KEY_.address-as-uuid:: 
The address of the channel as a UUID.

swarm.j-groups.channels._KEY_.cluster:: 
The cluster name of the JGroups channel. If undefined, the name of the channel will be used.

swarm.j-groups.channels._KEY_.discard-own-messages:: 
If true, do not receive messages sent by this node (ourself).

swarm.j-groups.channels._KEY_.forks._KEY_.protocols._KEY_.module:: 
The module with which to resolve the protocol type.

swarm.j-groups.channels._KEY_.forks._KEY_.protocols._KEY_.properties:: 
The properties of this protocol.

swarm.j-groups.channels._KEY_.forks._KEY_.protocols._KEY_.properties._KEY_.value:: 
The value of a protocol property.

swarm.j-groups.channels._KEY_.forks._KEY_.protocols._KEY_.socket-binding:: 
The socket binding specification for this protocol layer, used to specify IP interfaces and ports for communication.

swarm.j-groups.channels._KEY_.module:: 
The module from which to load channel services

swarm.j-groups.channels._KEY_.num-tasks-in-timer:: 
The current number of timer tasks.

swarm.j-groups.channels._KEY_.num-timer-threads:: 
The number of timer threads.

swarm.j-groups.channels._KEY_.received-bytes:: 
The number of bytes received by this channel.

swarm.j-groups.channels._KEY_.received-messages:: 
The number of messages received by this channel.

swarm.j-groups.channels._KEY_.sent-bytes:: 
The number of bytes sent by this channel.

swarm.j-groups.channels._KEY_.sent-messages:: 
The number of messages sent by this channel.

swarm.j-groups.channels._KEY_.stack:: 
The protocol stack of the JGroups channel

swarm.j-groups.channels._KEY_.state:: 
The state of the channel (OPEN, CONNECTING, CONNECTED, CLOSED).

swarm.j-groups.channels._KEY_.stats-enabled:: 
If enabled, collect channel statistics.

swarm.j-groups.channels._KEY_.version:: 
The JGroups software version.

swarm.j-groups.channels._KEY_.view:: 
The channel's view of group membership.

swarm.j-groups.default-channel:: 
The default JGroups channel.

swarm.j-groups.stacks._KEY_.R-e-l-a-y2.properties:: 
The properties of this protocol.

swarm.j-groups.stacks._KEY_.R-e-l-a-y2.properties._KEY_.value:: 
The value of a protocol property.

swarm.j-groups.stacks._KEY_.R-e-l-a-y2.remote-sites._KEY_.channel:: 
The name of the bridge channel used to communicate with this remote site.

swarm.j-groups.stacks._KEY_.R-e-l-a-y2.site:: 
The name of the local site.

swarm.j-groups.stacks._KEY_.protocols._KEY_.module:: 
The module with which to resolve the protocol type.

swarm.j-groups.stacks._KEY_.protocols._KEY_.properties:: 
The properties of this protocol.

swarm.j-groups.stacks._KEY_.protocols._KEY_.properties._KEY_.value:: 
The value of a protocol property.

swarm.j-groups.stacks._KEY_.protocols._KEY_.socket-binding:: 
The socket binding specification for this protocol layer, used to specify IP interfaces and ports for communication.

swarm.j-groups.stacks._KEY_.transports._KEY_.default-thread-pool.keepalive-time:: 
Used to specify the amount of milliseconds that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

swarm.j-groups.stacks._KEY_.transports._KEY_.default-thread-pool.max-threads:: 
The maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.default-thread-pool.min-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.default-thread-pool.queue-length:: 
The queue length.

swarm.j-groups.stacks._KEY_.transports._KEY_.diagnostics-socket-binding:: 
The diagnostics socket binding specification for this protocol layer, used to specify IP interfaces and ports for communication.

swarm.j-groups.stacks._KEY_.transports._KEY_.internal-thread-pool.keepalive-time:: 
Used to specify the amount of milliseconds that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

swarm.j-groups.stacks._KEY_.transports._KEY_.internal-thread-pool.max-threads:: 
The maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.internal-thread-pool.min-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.internal-thread-pool.queue-length:: 
The queue length.

swarm.j-groups.stacks._KEY_.transports._KEY_.machine:: 
The machine (i.e. host) identifier for this node. Used by Infinispan topology-aware consistent hash.

swarm.j-groups.stacks._KEY_.transports._KEY_.module:: 
The module with which to resolve the protocol type.

swarm.j-groups.stacks._KEY_.transports._KEY_.oob-thread-pool.keepalive-time:: 
Used to specify the amount of milliseconds that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

swarm.j-groups.stacks._KEY_.transports._KEY_.oob-thread-pool.max-threads:: 
The maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.oob-thread-pool.min-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.oob-thread-pool.queue-length:: 
The queue length.

swarm.j-groups.stacks._KEY_.transports._KEY_.properties:: 
The properties of this protocol.

swarm.j-groups.stacks._KEY_.transports._KEY_.properties._KEY_.value:: 
The value of a protocol property.

swarm.j-groups.stacks._KEY_.transports._KEY_.rack:: 
The rack (i.e. server rack) identifier for this node. Used by Infinispan topology-aware consistent hash.

swarm.j-groups.stacks._KEY_.transports._KEY_.site:: 
The site (i.e. data centre) identifier for this node. Used by Infinispan topology-aware consistent hash.

swarm.j-groups.stacks._KEY_.transports._KEY_.socket-binding:: 
The socket binding specification for this protocol layer, used to specify IP interfaces and ports for communication.

swarm.j-groups.stacks._KEY_.transports._KEY_.timer-thread-pool.keepalive-time:: 
Used to specify the amount of milliseconds that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

swarm.j-groups.stacks._KEY_.transports._KEY_.timer-thread-pool.max-threads:: 
The maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.timer-thread-pool.min-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

swarm.j-groups.stacks._KEY_.transports._KEY_.timer-thread-pool.queue-length:: 
The queue length.


