# Logging

Provides facilities to configure logging categories, levels and handlers.

When specifying log-levels through properties, since
they include dots, they should be placed between
square brackets, such as `swarm.logging.loggers.[com.mycorp.logger].level`.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>logging</artifactId>
</dependency>
----

.Configuration

swarm.logging.add-logging-api-dependencies:: 
Indicates whether or not logging API dependencies should be added to deployments during the deployment process. A value of true will add the dependencies to the deployment. A value of false will skip the deployment from being processed for logging API dependencies.

swarm.logging.async-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.async-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.async-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this handler. Message levels lower than this value will be discarded.

swarm.logging.async-handlers._KEY_.overflow-action:: 
Specify what action to take when the overflowing.  The valid options are 'block' and 'discard'

swarm.logging.async-handlers._KEY_.queue-length:: 
The queue length to use before flushing writing

swarm.logging.async-handlers._KEY_.subhandlers:: 
The Handlers associated with this async handler.

swarm.logging.console-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.console-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.console-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.console-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.console-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.console-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.console-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.console-handlers._KEY_.target:: 
Defines the target of the console handler. The value can be System.out, System.err or console.

swarm.logging.custom-formatters._KEY_.attribute-class:: 
The logging handler class to be used.

swarm.logging.custom-formatters._KEY_.module:: 
The module that the logging handler depends on.

swarm.logging.custom-formatters._KEY_.properties:: 
Defines the properties used for the logging handler. All properties must be accessible via a setter method.

swarm.logging.custom-handlers._KEY_.attribute-class:: 
The logging handler class to be used.

swarm.logging.custom-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.custom-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.custom-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.custom-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.custom-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.custom-handlers._KEY_.module:: 
The module that the logging handler depends on.

swarm.logging.custom-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.custom-handlers._KEY_.properties:: 
Defines the properties used for the logging handler. All properties must be accessible via a setter method.

swarm.logging.file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.log-files._KEY_.file-size:: 
The size of the log file in bytes.

swarm.logging.log-files._KEY_.last-modified-time:: 
The date, in milliseconds, the file was last modified.

swarm.logging.log-files._KEY_.last-modified-timestamp:: 
The date, in ISO 8601 format, the file was last modified.

swarm.logging.log-files._KEY_.stream:: 
Provides the server log as a response attachment. The response result value is the unique id of the attachment.

swarm.logging.loggers._KEY_.category:: 
Specifies the category for the logger.

swarm.logging.loggers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.loggers._KEY_.handlers:: 
The handlers associated with the logger.

swarm.logging.loggers._KEY_.level:: 
The log level specifying which message levels will be logged by the logger. Message levels lower than this value will be discarded.

swarm.logging.loggers._KEY_.use-parent-handlers:: 
Specifies whether or not this logger should send its output to it's parent Logger.

swarm.logging.logging-profiles._KEY_.async-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.async-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.async-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this handler. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.async-handlers._KEY_.overflow-action:: 
Specify what action to take when the overflowing.  The valid options are 'block' and 'discard'

swarm.logging.logging-profiles._KEY_.async-handlers._KEY_.queue-length:: 
The queue length to use before flushing writing

swarm.logging.logging-profiles._KEY_.async-handlers._KEY_.subhandlers:: 
The Handlers associated with this async handler.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.logging-profiles._KEY_.console-handlers._KEY_.target:: 
Defines the target of the console handler. The value can be System.out, System.err or console.

swarm.logging.logging-profiles._KEY_.custom-formatters._KEY_.attribute-class:: 
The logging handler class to be used.

swarm.logging.logging-profiles._KEY_.custom-formatters._KEY_.module:: 
The module that the logging handler depends on.

swarm.logging.logging-profiles._KEY_.custom-formatters._KEY_.properties:: 
Defines the properties used for the logging handler. All properties must be accessible via a setter method.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.attribute-class:: 
The logging handler class to be used.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.module:: 
The module that the logging handler depends on.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.logging-profiles._KEY_.custom-handlers._KEY_.properties:: 
Defines the properties used for the logging handler. All properties must be accessible via a setter method.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.logging-profiles._KEY_.log-files._KEY_.file-size:: 
The size of the log file in bytes.

swarm.logging.logging-profiles._KEY_.log-files._KEY_.last-modified-time:: 
The date, in milliseconds, the file was last modified.

swarm.logging.logging-profiles._KEY_.log-files._KEY_.last-modified-timestamp:: 
The date, in ISO 8601 format, the file was last modified.

swarm.logging.logging-profiles._KEY_.log-files._KEY_.stream:: 
Provides the server log as a response attachment. The response result value is the unique id of the attachment.

swarm.logging.logging-profiles._KEY_.loggers._KEY_.category:: 
Specifies the category for the logger.

swarm.logging.logging-profiles._KEY_.loggers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.loggers._KEY_.handlers:: 
The handlers associated with the logger.

swarm.logging.logging-profiles._KEY_.loggers._KEY_.level:: 
The log level specifying which message levels will be logged by the logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.loggers._KEY_.use-parent-handlers:: 
Specifies whether or not this logger should send its output to it's parent Logger.

swarm.logging.logging-profiles._KEY_.pattern-formatters._KEY_.color-map:: 
The color-map attribute allows for a comma delimited list of colors to be used for different levels with a pattern formatter. The format for the color mapping pattern is level-name:color-name.Valid Levels; severe, fatal, error, warn, warning, info, debug, trace, config, fine, finer, finest Valid Colors; black, green, red, yellow, blue, magenta, cyan, white, brightblack, brightred, brightgreen, brightblue, brightyellow, brightmagenta, brightcyan, brightwhite

swarm.logging.logging-profiles._KEY_.pattern-formatters._KEY_.pattern:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.logging-profiles._KEY_.periodic-rotating-file-handlers._KEY_.suffix:: 
Set the suffix string.  The string is in a format which can be understood by java.text.SimpleDateFormat. The period of the rotation is automatically calculated based on the suffix.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.max-backup-index:: 
The maximum number of backups to keep.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.rotate-on-boot:: 
Indicates the file should be rotated each time the file attribute is changed. This always happens when at initialization time.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.rotate-size:: 
The size at which to rotate the log file.

swarm.logging.logging-profiles._KEY_.periodic-size-rotating-file-handlers._KEY_.suffix:: 
Set the suffix string.  The string is in a format which can be understood by java.text.SimpleDateFormat. The period of the rotation is automatically calculated based on the suffix.

swarm.logging.logging-profiles._KEY_.root-logger.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.root-logger.handlers:: 
The handlers associated with the root logger.

swarm.logging.logging-profiles._KEY_.root-logger.level:: 
The log level specifying which message levels will be logged by the root logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.max-backup-index:: 
The maximum number of backups to keep.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.rotate-on-boot:: 
Indicates the file should be rotated each time the file attribute is changed. This always happens when at initialization time.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.rotate-size:: 
The size at which to rotate the log file.

swarm.logging.logging-profiles._KEY_.size-rotating-file-handlers._KEY_.suffix:: 
Set the suffix string. The string is in a format which can be understood by java.text.SimpleDateFormat. The suffix does not determine when the file should be rotated.

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.app-name:: 
The app name used when formatting the message in RFC5424 format. By default the app name is "java".

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.facility:: 
Facility as defined by RFC-5424 (http://tools.ietf.org/html/rfc5424)and RFC-3164 (http://tools.ietf.org/html/rfc3164).

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.hostname:: 
The name of the host the messages are being sent from. For example the name of the host the application server is running on.

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.port:: 
The port the syslog server is listening on.

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.server-address:: 
The address of the syslog server.

swarm.logging.logging-profiles._KEY_.syslog-handlers._KEY_.syslog-format:: 
Formats the log message according to the RFC specification.

swarm.logging.pattern-formatters._KEY_.color-map:: 
The color-map attribute allows for a comma delimited list of colors to be used for different levels with a pattern formatter. The format for the color mapping pattern is level-name:color-name.Valid Levels; severe, fatal, error, warn, warning, info, debug, trace, config, fine, finer, finest Valid Colors; black, green, red, yellow, blue, magenta, cyan, white, brightblack, brightred, brightgreen, brightblue, brightyellow, brightmagenta, brightcyan, brightwhite

swarm.logging.pattern-formatters._KEY_.pattern:: 
Defines a pattern for the formatter.

swarm.logging.periodic-rotating-file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.periodic-rotating-file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.periodic-rotating-file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.periodic-rotating-file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.periodic-rotating-file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.periodic-rotating-file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.periodic-rotating-file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.periodic-rotating-file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.periodic-rotating-file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.periodic-rotating-file-handlers._KEY_.suffix:: 
Set the suffix string.  The string is in a format which can be understood by java.text.SimpleDateFormat. The period of the rotation is automatically calculated based on the suffix.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.periodic-size-rotating-file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.max-backup-index:: 
The maximum number of backups to keep.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.rotate-on-boot:: 
Indicates the file should be rotated each time the file attribute is changed. This always happens when at initialization time.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.rotate-size:: 
The size at which to rotate the log file.

swarm.logging.periodic-size-rotating-file-handlers._KEY_.suffix:: 
Set the suffix string.  The string is in a format which can be understood by java.text.SimpleDateFormat. The period of the rotation is automatically calculated based on the suffix.

swarm.logging.root-logger.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.root-logger.handlers:: 
The handlers associated with the root logger.

swarm.logging.root-logger.level:: 
The log level specifying which message levels will be logged by the root logger. Message levels lower than this value will be discarded.

swarm.logging.size-rotating-file-handlers._KEY_.append:: 
Specify whether to append to the target file.

swarm.logging.size-rotating-file-handlers._KEY_.autoflush:: 
Automatically flush after each write.

swarm.logging.size-rotating-file-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.size-rotating-file-handlers._KEY_.encoding:: 
The character encoding used by this Handler.

swarm.logging.size-rotating-file-handlers._KEY_.file:: 
The file description consisting of the path and optional relative to path.

swarm.logging.size-rotating-file-handlers._KEY_.filter-spec:: 
A filter expression value to define a filter. Example for a filter that does not match a pattern: not(match("JBAS.*"))

swarm.logging.size-rotating-file-handlers._KEY_.formatter:: 
Defines a pattern for the formatter.

swarm.logging.size-rotating-file-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.size-rotating-file-handlers._KEY_.max-backup-index:: 
The maximum number of backups to keep.

swarm.logging.size-rotating-file-handlers._KEY_.named-formatter:: 
The name of the defined formatter to be used on the handler.

swarm.logging.size-rotating-file-handlers._KEY_.rotate-on-boot:: 
Indicates the file should be rotated each time the file attribute is changed. This always happens when at initialization time.

swarm.logging.size-rotating-file-handlers._KEY_.rotate-size:: 
The size at which to rotate the log file.

swarm.logging.size-rotating-file-handlers._KEY_.suffix:: 
Set the suffix string. The string is in a format which can be understood by java.text.SimpleDateFormat. The suffix does not determine when the file should be rotated.

swarm.logging.syslog-handlers._KEY_.app-name:: 
The app name used when formatting the message in RFC5424 format. By default the app name is "java".

swarm.logging.syslog-handlers._KEY_.enabled:: 
If set to true the handler is enabled and functioning as normal, if set to false the handler is ignored when processing log messages.

swarm.logging.syslog-handlers._KEY_.facility:: 
Facility as defined by RFC-5424 (http://tools.ietf.org/html/rfc5424)and RFC-3164 (http://tools.ietf.org/html/rfc3164).

swarm.logging.syslog-handlers._KEY_.hostname:: 
The name of the host the messages are being sent from. For example the name of the host the application server is running on.

swarm.logging.syslog-handlers._KEY_.level:: 
The log level specifying which message levels will be logged by this logger. Message levels lower than this value will be discarded.

swarm.logging.syslog-handlers._KEY_.port:: 
The port the syslog server is listening on.

swarm.logging.syslog-handlers._KEY_.server-address:: 
The address of the syslog server.

swarm.logging.syslog-handlers._KEY_.syslog-format:: 
Formats the log message according to the RFC specification.

swarm.logging.use-deployment-logging-config:: 
Indicates whether or not deployments should use a logging configuration file found in the deployment to configure the log manager. If set to true and a logging configuration file was found in the deployments META-INF or WEB-INF/classes directory, then a log manager will be configured with those settings. If set false the servers logging configuration will be used regardless of any logging configuration files supplied in the deployment.


