= Mail


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>mail</artifactId>
</dependency>
----

.Configuration

swarm.mail.mail-sessions._KEY_.customs._KEY_.outbound-socket-binding-ref:: 
Outbound Socket binding to mail server

swarm.mail.mail-sessions._KEY_.customs._KEY_.password:: 
Password to authenticate on server

swarm.mail.mail-sessions._KEY_.customs._KEY_.properties:: 
JavaMail properties

swarm.mail.mail-sessions._KEY_.customs._KEY_.ssl:: 
Does server require SSL?

swarm.mail.mail-sessions._KEY_.customs._KEY_.tls:: 
Does server require TLS?

swarm.mail.mail-sessions._KEY_.customs._KEY_.username:: 
Username to authenticate on server

swarm.mail.mail-sessions._KEY_.debug:: 
Enables JavaMail debugging

swarm.mail.mail-sessions._KEY_.from:: 
From address that is used as default from, if not set when sending

swarm.mail.mail-sessions._KEY_.imap-server.outbound-socket-binding-ref:: 
Outbound Socket binding to mail server

swarm.mail.mail-sessions._KEY_.imap-server.password:: 
Password to authenticate on server

swarm.mail.mail-sessions._KEY_.imap-server.ssl:: 
Does server require SSL?

swarm.mail.mail-sessions._KEY_.imap-server.tls:: 
Does server require TLS?

swarm.mail.mail-sessions._KEY_.imap-server.username:: 
Username to authenticate on server

swarm.mail.mail-sessions._KEY_.jndi-name:: 
JNDI name to where mail session should be bound

swarm.mail.mail-sessions._KEY_.pop3-server.outbound-socket-binding-ref:: 
Outbound Socket binding to mail server

swarm.mail.mail-sessions._KEY_.pop3-server.password:: 
Password to authenticate on server

swarm.mail.mail-sessions._KEY_.pop3-server.ssl:: 
Does server require SSL?

swarm.mail.mail-sessions._KEY_.pop3-server.tls:: 
Does server require TLS?

swarm.mail.mail-sessions._KEY_.pop3-server.username:: 
Username to authenticate on server

swarm.mail.mail-sessions._KEY_.smtp-server.outbound-socket-binding-ref:: 
Outbound Socket binding to mail server

swarm.mail.mail-sessions._KEY_.smtp-server.password:: 
Password to authenticate on server

swarm.mail.mail-sessions._KEY_.smtp-server.ssl:: 
Does server require SSL?

swarm.mail.mail-sessions._KEY_.smtp-server.tls:: 
Does server require TLS?

swarm.mail.mail-sessions._KEY_.smtp-server.username:: 
Username to authenticate on server

swarm.mail.smtp.host:: 
Host name of the default SMTP server

swarm.mail.smtp.port:: 
Port of the default SMTP server


