# Management

Provides the WildFly management API.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>management</artifactId>
</dependency>
----

.Configuration

swarm.management.audit-access.audit-log-logger.enabled:: 
Whether audit logging is enabled.

swarm.management.audit-access.audit-log-logger.log-boot:: 
Whether operations should be logged on server boot.

swarm.management.audit-access.audit-log-logger.log-read-only:: 
Whether operations that do not modify the configuration or any runtime services should be logged.

swarm.management.audit-access.file-handlers._KEY_.disabled-due-to-failure:: 
Whether this handler has been disabled due to logging failures.

swarm.management.audit-access.file-handlers._KEY_.failure-count:: 
The number of logging failures since the handler was initialized.

swarm.management.audit-access.file-handlers._KEY_.formatter:: 
The formatter used to format the log messages.

swarm.management.audit-access.file-handlers._KEY_.max-failure-count:: 
The maximum number of logging failures before disabling this handler.

swarm.management.audit-access.file-handlers._KEY_.path:: 
The path of the audit log file.

swarm.management.audit-access.file-handlers._KEY_.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.audit-access.in-memory-handlers._KEY_.max-history:: 
The maximum number of operation stored in history for this handler.

swarm.management.audit-access.json-formatters._KEY_.compact:: 
If true will format the JSON on one line. There may still be values containing new lines, so if having the whole record on one line is important, set escape-new-line or escape-control-characters to true.

swarm.management.audit-access.json-formatters._KEY_.date-format:: 
The date format to use as understood by {@link java.text.SimpleDateFormat}. Will be ignored if include-date="false".

swarm.management.audit-access.json-formatters._KEY_.date-separator:: 
The separator between the date and the rest of the formatted log message. Will be ignored if include-date="false".

swarm.management.audit-access.json-formatters._KEY_.escape-control-characters:: 
If true will escape all control characters (ascii entries with a decimal value < 32) with the ascii code in octal, e.g.'
 becomes '#012'. If this is true, it will override escape-new-line="false".

swarm.management.audit-access.json-formatters._KEY_.escape-new-line:: 
If true will escape all new lines with the ascii code in octal, e.g. "#012".

swarm.management.audit-access.json-formatters._KEY_.include-date:: 
Whether or not to include the date in the formatted log record.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.disabled-due-to-failure:: 
Whether this handler has been disabled due to logging failures.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.failure-count:: 
The number of logging failures since the handler was initialized.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.formatter:: 
The formatter used to format the log messages.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.max-failure-count:: 
The maximum number of logging failures before disabling this handler.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.path:: 
The path of the audit log file.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.audit-access.periodic-rotating-file-handlers._KEY_.suffix:: 
The suffix string in a format which can be understood by java.text.SimpleDateFormat. The period of the rotation is automatically calculated based on the suffix.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.disabled-due-to-failure:: 
Whether this handler has been disabled due to logging failures.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.failure-count:: 
The number of logging failures since the handler was initialized.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.formatter:: 
The formatter used to format the log messages.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.max-backup-index:: 
The maximum number of backups to keep.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.max-failure-count:: 
The maximum number of logging failures before disabling this handler.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.path:: 
The path of the audit log file.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.audit-access.size-rotating-file-handlers._KEY_.rotate-size:: 
The size at which to rotate the log file.

swarm.management.audit-access.syslog-handlers._KEY_.app-name:: 
The application name to add to the syslog records as defined in section 6.2.5 of RFC-5424. If not specified it will default to the name of the product.

swarm.management.audit-access.syslog-handlers._KEY_.disabled-due-to-failure:: 
Whether this handler has been disabled due to logging failures.

swarm.management.audit-access.syslog-handlers._KEY_.facility:: 
The facility to use for syslog logging as defined in section 6.2.1 of RFC-5424, and section 4.1.1 of RFC-3164.

swarm.management.audit-access.syslog-handlers._KEY_.failure-count:: 
The number of logging failures since the handler was initialized.

swarm.management.audit-access.syslog-handlers._KEY_.formatter:: 
The formatter used to format the log messages.

swarm.management.audit-access.syslog-handlers._KEY_.max-failure-count:: 
The maximum number of logging failures before disabling this handler.

swarm.management.audit-access.syslog-handlers._KEY_.max-length:: 
The maximum length in bytes a log message, including the header, is allowed to be. If undefined, it will default to 1024 bytes if the syslog-format is RFC3164, or 2048 bytes if the syslog-format is RFC5424.

swarm.management.audit-access.syslog-handlers._KEY_.syslog-format:: 
Whether to set the syslog format to the one specified in RFC-5424 or RFC-3164.

swarm.management.audit-access.syslog-handlers._KEY_.tcp-protocol.host:: 
The host of the syslog server for the tcp requests.

swarm.management.audit-access.syslog-handlers._KEY_.tcp-protocol.message-transfer:: 
The message transfer setting as described in section 3.4 of RFC-6587. This can either be OCTET_COUNTING as described in section 3.4.1 of RFC-6587, or NON_TRANSPARENT_FRAMING as described in section 3.4.1 of RFC-6587. See your syslog provider's documentation for what is supported.

swarm.management.audit-access.syslog-handlers._KEY_.tcp-protocol.port:: 
The port of the syslog server for the tcp requests.

swarm.management.audit-access.syslog-handlers._KEY_.tcp-protocol.reconnect-timeout:: 
If a connection drop is detected, the number of seconds to wait before reconnecting. A negative number means don't reconnect automatically.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.client-certificate-store-authentication.key-password:: 
The password for the keystore key.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.client-certificate-store-authentication.keystore-password:: 
The password for the keystore.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.client-certificate-store-authentication.keystore-path:: 
=The path of the keystore.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.client-certificate-store-authentication.keystore-relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'keystore-relative-to' is provided, the value of the 'keystore-path' attribute is treated as relative to the path specified by this attribute.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.host:: 
The host of the syslog server for the tls over tcp requests.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.message-transfer:: 
The message transfer setting as described in section 3.4 of RFC-6587. This can either be OCTET_COUNTING as described in section 3.4.1 of RFC-6587, or NON_TRANSPARENT_FRAMING as described in section 3.4.1 of RFC-6587. See your syslog provider's documentation for what is supported.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.port:: 
The port of the syslog server for the tls over tcp requests.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.reconnect-timeout:: 
If a connection drop is detected, the number of seconds to wait before reconnecting. A negative number means don't reconnect automatically.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.truststore-authentication.keystore-password:: 
The password for the truststore.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.truststore-authentication.keystore-path:: 
=The path of the truststore.

swarm.management.audit-access.syslog-handlers._KEY_.tls-protocol.truststore-authentication.keystore-relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'keystore-relative-to' is provided, the value of the 'keystore-path' attribute is treated as relative to the path specified by this attribute.

swarm.management.audit-access.syslog-handlers._KEY_.truncate:: 
Whether or not a message, including the header, should truncate the message if the length in bytes is greater than the maximum length. If set to false messages will be split and sent with the same header values.

swarm.management.audit-access.syslog-handlers._KEY_.udp-protocol.host:: 
The host of the syslog server for the udp requests.

swarm.management.audit-access.syslog-handlers._KEY_.udp-protocol.port:: 
The port of the syslog server for the udp requests.

swarm.management.authorization-access.all-role-names:: 
The official names of all roles supported by the current management access control provider. This includes any standard roles as well as any user-defined roles.

swarm.management.authorization-access.application-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.address:: 
Address pattern describing a resource or resources to which the constraint applies.

swarm.management.authorization-access.application-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.attributes:: 
List of the names of attributes to which the constraint specifically applies.

swarm.management.authorization-access.application-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.entire-resource:: 
True if the constraint applies to the resource as a whole; false if it only applies to one or more attributes or operations.

swarm.management.authorization-access.application-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.operations:: 
List of the names of operations to which the constraint specifically applies.

swarm.management.authorization-access.application-classification-constraint.types._KEY_.classifications._KEY_.configured-application:: 
Set to override the default as to whether the constraint is considered an application resource.

swarm.management.authorization-access.application-classification-constraint.types._KEY_.classifications._KEY_.default-application:: 
Whether targets having this application type constraint are considered application resources.

swarm.management.authorization-access.permission-combination-policy:: 
The policy for combining access control permissions when the authorization policy grants the user more than one type of permission for a given action. In the standard role based authorization policy, this would occur when a user maps to multiple roles. The 'permissive' policy means if any of the permissions allow the action, the action is allowed. The 'rejecting' policy means the existence of multiple permissions should result in an error.

swarm.management.authorization-access.provider:: 
The provider to use for management access control decisions.

swarm.management.authorization-access.role-mappings._KEY_.excludes._KEY_.name:: 
The name of the user or group being mapped.

swarm.management.authorization-access.role-mappings._KEY_.excludes._KEY_.realm:: 
An optional attribute to map based on the realm used for authentication.

swarm.management.authorization-access.role-mappings._KEY_.excludes._KEY_.type:: 
The type of the Principal being mapped, either 'group' or 'user'.

swarm.management.authorization-access.role-mappings._KEY_.include-all:: 
Configure if all authenticated users should be automatically assigned this role.

swarm.management.authorization-access.role-mappings._KEY_.includes._KEY_.name:: 
The name of the user or group being mapped.

swarm.management.authorization-access.role-mappings._KEY_.includes._KEY_.realm:: 
An optional attribute to map based on the realm used for authentication.

swarm.management.authorization-access.role-mappings._KEY_.includes._KEY_.type:: 
The type of the Principal being mapped, either 'group' or 'user'.

swarm.management.authorization-access.sensitivity-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.address:: 
Address pattern describing a resource or resources to which the constraint applies.

swarm.management.authorization-access.sensitivity-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.attributes:: 
List of the names of attributes to which the constraint specifically applies.

swarm.management.authorization-access.sensitivity-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.entire-resource:: 
True if the constraint applies to the resource as a whole; false if it only applies to one or more attributes or operations.

swarm.management.authorization-access.sensitivity-classification-constraint.types._KEY_.classifications._KEY_.applies-tos._KEY_.operations:: 
List of the names of operations to which the constraint specifically applies.

swarm.management.authorization-access.sensitivity-classification-constraint.types._KEY_.classifications._KEY_.configured-application:: 
Set to override the default as to whether the constraint is considered an application resource.

swarm.management.authorization-access.sensitivity-classification-constraint.types._KEY_.classifications._KEY_.default-application:: 
Whether targets having this application type constraint are considered application resources.

swarm.management.authorization-access.standard-role-names:: 
The official names of the standard roles supported by the current management access control provider.

swarm.management.authorization-access.vault-expression-constraint.configured-requires-read:: 
Set to override the default as to whether reading attributes containing vault expressions should be considered sensitive.

swarm.management.authorization-access.vault-expression-constraint.configured-requires-write:: 
Set to override the default as to whether writing attributes containing vault expressions should be considered sensitive.

swarm.management.authorization-access.vault-expression-constraint.default-requires-read:: 
Whether reading attributes containing vault expressions should be considered sensitive.

swarm.management.authorization-access.vault-expression-constraint.default-requires-write:: 
Whether writing attributes containing vault expressions should be considered sensitive.

swarm.management.bind.interface:: 
Interface to bind for the management ports

swarm.management.configuration-changes-service.max-history:: 
The maximum number of configuration changes stored in history.

swarm.management.http-interface-management-interface.allowed-origins:: 
Comma separated list of trusted Origins for sending Cross-Origin Resource Sharing requests on the management API once the user is authenticated.

swarm.management.http-interface-management-interface.console-enabled:: 
Flag that indicates admin console is enabled

swarm.management.http-interface-management-interface.http-upgrade-enabled:: 
Flag that indicates HTTP Upgrade is enabled, which allows HTTP requests to be upgraded to native remoting connections

swarm.management.http-interface-management-interface.sasl-protocol:: 
The name of the protocol to be passed to the SASL mechanisms used for authentication.

swarm.management.http-interface-management-interface.secure-socket-binding:: 
The name of the socket binding configuration to use for the HTTPS management interface's socket.

swarm.management.http-interface-management-interface.security-realm:: 
The security realm to use for the HTTP management interface.

swarm.management.http-interface-management-interface.server-name:: 
The name of the server used in the initial Remoting exchange and within the SASL mechanisms.

swarm.management.http-interface-management-interface.socket-binding:: 
The name of the socket binding configuration to use for the HTTP management interface's socket.

swarm.management.http.disable:: 
Flag to disable HTTP access to management interface

swarm.management.http.port:: 
Port for HTTP access to management interface

swarm.management.https.port:: 
Port for HTTPS access to management interface

swarm.management.ldap-connections._KEY_.handles-referrals-for:: 
List of URLs that this connection handles referrals for.

swarm.management.ldap-connections._KEY_.initial-context-factory:: 
The initial context factory to establish the LdapContext.

swarm.management.ldap-connections._KEY_.properties._KEY_.value:: 
The optional value of the property.

swarm.management.ldap-connections._KEY_.referrals:: 
The referral handling mode for this connection.

swarm.management.ldap-connections._KEY_.search-credential:: 
The credential to use when connecting to perform a search.

swarm.management.ldap-connections._KEY_.search-dn:: 
The distinguished name to use when connecting to the LDAP server to perform searches.

swarm.management.ldap-connections._KEY_.security-realm:: 
The security realm to reference to obtain a configured SSLContext to use when establishing the connection.

swarm.management.ldap-connections._KEY_.url:: 
The URL to use to connect to the LDAP server.

swarm.management.management-operations-service.active-operations._KEY_.access-mechanism:: 
The mechanism used to submit a request to the server.

swarm.management.management-operations-service.active-operations._KEY_.address:: 
The address of the resource targeted by the operation. The value in the final element of the address will be '<hidden>' if the caller is not authorized to address the operation's target resource.

swarm.management.management-operations-service.active-operations._KEY_.caller-thread:: 
The name of the thread that is executing the operation.

swarm.management.management-operations-service.active-operations._KEY_.cancelled:: 
Whether the operation has been cancelled.

swarm.management.management-operations-service.active-operations._KEY_.domain-rollout:: 
True if the operation is a subsidiary request on a domain process other than the one directly handling the original operation, executing locally as part of the rollout of the original operation across the domain.

swarm.management.management-operations-service.active-operations._KEY_.domain-uuid:: 
Identifier of an overall multi-process domain operation of which this operation is a part, or undefined is this operation is not associated with such a domain operation.

swarm.management.management-operations-service.active-operations._KEY_.exclusive-running-time:: 
Amount of time the operation has been executing with the exclusive operation execution lock held, or -1 if the operation does not hold the exclusive execution lock.

swarm.management.management-operations-service.active-operations._KEY_.execution-status:: 
The current activity of the operation.

swarm.management.management-operations-service.active-operations._KEY_.operation:: 
The name of the operation, or '<hidden>' if the caller is not authorized to address the operation's target resource.

swarm.management.management-operations-service.active-operations._KEY_.running-time:: 
Amount of time the operation has been executing.

swarm.management.native-interface-management-interface.sasl-protocol:: 
The name of the protocol to be passed to the SASL mechanisms used for authentication.

swarm.management.native-interface-management-interface.security-realm:: 
The security realm to use for the native management interface.

swarm.management.native-interface-management-interface.server-name:: 
The name of the server used in the initial Remoting exchange and within the SASL mechanisms.

swarm.management.native-interface-management-interface.socket-binding:: 
The name of the socket binding configuration to use for the native management interface's socket.

swarm.management.security-realms._KEY_.jaas-authentication.assign-groups:: 
Map the roles loaded by JAAS to groups.

swarm.management.security-realms._KEY_.jaas-authentication.name:: 
The name of the JAAS configuration to use.

swarm.management.security-realms._KEY_.kerberos-authentication.remove-realm:: 
After authentication should the realm name be stripped from the users name.

swarm.management.security-realms._KEY_.kerberos-server-identity.keytabs._KEY_.debug:: 
Should additional debug logging be enabled during TGT acquisition?

swarm.management.security-realms._KEY_.kerberos-server-identity.keytabs._KEY_.for-hosts:: 
A server can be accessed using different host names, this attribute specifies which host names this keytab can be used with.

swarm.management.security-realms._KEY_.kerberos-server-identity.keytabs._KEY_.path:: 
The path to the keytab.

swarm.management.security-realms._KEY_.kerberos-server-identity.keytabs._KEY_.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.security-realms._KEY_.ldap-authentication.advanced-filter:: 
The fully defined filter to be used to search for the user based on their entered user ID. The filter should contain a variable in the form {0} - this will be replaced with the username supplied by the user.

swarm.management.security-realms._KEY_.ldap-authentication.allow-empty-passwords:: 
Should empty passwords be accepted from the user being authenticated.

swarm.management.security-realms._KEY_.ldap-authentication.base-dn:: 
The base distinguished name to commence the search for the user.

swarm.management.security-realms._KEY_.ldap-authentication.by-access-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authentication.by-access-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authentication.by-access-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authentication.by-access-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authentication.by-search-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authentication.by-search-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authentication.by-search-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authentication.by-search-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authentication.connection:: 
The name of the connection to use to connect to LDAP.

swarm.management.security-realms._KEY_.ldap-authentication.recursive:: 
Whether the search should be recursive.

swarm.management.security-realms._KEY_.ldap-authentication.user-dn:: 
The name of the attribute which is the user's distinguished name.

swarm.management.security-realms._KEY_.ldap-authentication.username-attribute:: 
The name of the attribute to search for the user. This filter will then perform a simple search where the username entered by the user matches the attribute specified here.

swarm.management.security-realms._KEY_.ldap-authentication.username-load:: 
The name of the attribute that should be loaded from the authenticated users LDAP entry to replace the username that they supplied, e.g. convert an e-mail address to an ID or correct the case entered.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.base-dn:: 
The starting point of the search for the user.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-access-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-access-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-access-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-access-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-search-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-search-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-search-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.by-search-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.filter:: 
The filter to use for the LDAP search.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.force:: 
Authentication may have already converted the username to a distinguished name, force this to occur again before loading groups.

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.recursive:: 
Should levels below the starting point be recursively searched?

swarm.management.security-realms._KEY_.ldap-authorization.advanced-filter-username-to-dn.user-dn-attribute:: 
The attribute on the user entry that contains their distinguished name.

swarm.management.security-realms._KEY_.ldap-authorization.connection:: 
The name of the connection to use to connect to LDAP.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.base-dn:: 
The starting point of the search for the group.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-access-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-access-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-access-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-access-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-search-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-search-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-search-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.by-search-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.group-dn-attribute:: 
Which attribute on a group entry is it's distinguished name.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.group-name:: 
An enumeration to identify if groups should be referenced using a simple name or their distinguished name.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.group-name-attribute:: 
Which attribute on a group entry is it's simple name.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.iterative:: 
Should further searches be performed to identify groups that the groups identified are a member of?

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.prefer-original-connection:: 
After following a referral should subsequent searches prefer the original connection or use the connection of the last referral.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.principal-attribute:: 
The attribute on the group entry that references the principal.

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.recursive:: 
Should levels below the starting point be recursively searched?

swarm.management.security-realms._KEY_.ldap-authorization.group-to-principal-group-search.search-by:: 
Should searches be performed using simple names or distinguished names?

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-access-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-access-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-access-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-access-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-search-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-search-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-search-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.by-search-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.group-attribute:: 
The attribute on the principal which references the group the principal is a member of.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.group-dn-attribute:: 
Which attribute on a group entry is it's distinguished name.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.group-name:: 
An enumeration to identify if groups should be referenced using a simple name or their distinguished name.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.group-name-attribute:: 
Which attribute on a group entry is it's simple name.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.iterative:: 
Should further searches be performed to identify groups that the groups identified are a member of?

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.prefer-original-connection:: 
After following a referral should subsequent searches prefer the original connection or use the connection of the last referral.

swarm.management.security-realms._KEY_.ldap-authorization.principal-to-group-group-search.skip-missing-groups:: 
If a non-existent group is referenced should it be quietly ignored.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.attribute:: 
The attribute on the user entry that is their username.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.base-dn:: 
The starting point of the search for the user.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-access-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-access-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-access-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-access-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-search-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-search-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-search-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.by-search-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.force:: 
Authentication may have already converted the username to a distinguished name, force this to occur again before loading groups.

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.recursive:: 
Should levels below the starting point be recursively searched?

swarm.management.security-realms._KEY_.ldap-authorization.username-filter-username-to-dn.user-dn-attribute:: 
The attribute on the user entry that contains their distinguished name.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-access-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-access-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-access-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-access-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-search-time-cache.cache-failures:: 
Should failures be cached?

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-search-time-cache.cache-size:: 
The current size of the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-search-time-cache.eviction-time:: 
The time in seconds until an entry should be evicted from the cache.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.by-search-time-cache.max-cache-size:: 
The maximum size of the cache before the oldest items are removed to make room for new entries.

swarm.management.security-realms._KEY_.ldap-authorization.username-is-dn-username-to-dn.force:: 
Authentication may have already converted the username to a distinguished name, force this to occur again before loading groups.

swarm.management.security-realms._KEY_.local-authentication.allowed-users:: 
The comma separated list of users that will be accepted using the JBOSS-LOCAL-USER mechanism or '*' to accept all. If specified the default-user is always assumed allowed.

swarm.management.security-realms._KEY_.local-authentication.default-user:: 
The name of the default user to assume if no user specified by the remote client.

swarm.management.security-realms._KEY_.local-authentication.skip-group-loading:: 
Disable the loading of the users group membership information after local authentication has been used.

swarm.management.security-realms._KEY_.map-groups-to-roles:: 
After a users group membership has been loaded should a 1:1 relationship be assumed regarding group to role mapping.

swarm.management.security-realms._KEY_.plug-in-authentication.mechanism:: 
Allow the mechanism this plug-in is compatible with to be overridden from DIGEST.

swarm.management.security-realms._KEY_.plug-in-authentication.name:: 
The short name of the plug-in (as registered) to use.

swarm.management.security-realms._KEY_.plug-in-authentication.properties._KEY_.value:: 
The optional value of the property.

swarm.management.security-realms._KEY_.plug-in-authorization.name:: 
The short name of the plug-in (as registered) to use.

swarm.management.security-realms._KEY_.plug-in-authorization.properties._KEY_.value:: 
The optional value of the property.

swarm.management.security-realms._KEY_.properties-authentication.path:: 
The path of the properties file containing the users.

swarm.management.security-realms._KEY_.properties-authentication.plain-text:: 
Are the credentials within the properties file stored in plain text. If not the credential is expected to be the hex encoded Digest hash of 'username : realm : password'.

swarm.management.security-realms._KEY_.properties-authentication.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.security-realms._KEY_.properties-authorization.path:: 
The path of the properties file containing the users roles.

swarm.management.security-realms._KEY_.properties-authorization.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.security-realms._KEY_.secret-server-identity.value:: 
The secret / password - Base64 Encoded.

swarm.management.security-realms._KEY_.ssl-server-identity.alias:: 
The alias of the entry to use from the keystore.

swarm.management.security-realms._KEY_.ssl-server-identity.enabled-cipher-suites:: 
The cipher suites that can be enabled on the underlying SSLEngine.

swarm.management.security-realms._KEY_.ssl-server-identity.enabled-protocols:: 
The protocols that can be enabled on the underlying SSLEngine.

swarm.management.security-realms._KEY_.ssl-server-identity.generate-self-signed-certificate-host:: 
If the keystore does not exist and this attribute is set then a self signed certificate will be generated for the specified host name. This is not intended for production use.

swarm.management.security-realms._KEY_.ssl-server-identity.key-password:: 
The password to obtain the key from the keystore.

swarm.management.security-realms._KEY_.ssl-server-identity.keystore-password:: 
The password to open the keystore.

swarm.management.security-realms._KEY_.ssl-server-identity.keystore-path:: 
The path of the keystore, will be ignored if the keystore-provider is anything other than JKS.

swarm.management.security-realms._KEY_.ssl-server-identity.keystore-provider:: 
The provider for loading the keystore, defaults to JKS.

swarm.management.security-realms._KEY_.ssl-server-identity.keystore-relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.security-realms._KEY_.ssl-server-identity.protocol:: 
The protocol to use when creating the SSLContext.

swarm.management.security-realms._KEY_.truststore-authentication.keystore-password:: 
The password to open the keystore.

swarm.management.security-realms._KEY_.truststore-authentication.keystore-path:: 
The path of the keystore, will be ignored if the keystore-provider is anything other than JKS.

swarm.management.security-realms._KEY_.truststore-authentication.keystore-provider:: 
The provider for loading the keystore, defaults to JKS.

swarm.management.security-realms._KEY_.truststore-authentication.keystore-relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute.

swarm.management.security-realms._KEY_.users-authentication.users._KEY_.password:: 
The user's password.


