= Messaging


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>messaging</artifactId>
</dependency>
----

.Configuration

swarm.messaging.jms-bridges._KEY_.add-messageid-in-header:: 
If true, then the original message's message ID will be appended in the message sent to the destination in the header AMQ_BRIDGE_MSG_ID_LIST. If the message is bridged more than once, each message ID will be appended.

swarm.messaging.jms-bridges._KEY_.client-id:: 
The JMS client ID to use when creating/looking up the subscription if it is durable and the source destination is a topic.

swarm.messaging.jms-bridges._KEY_.failure-retry-interval:: 
The amount of time in milliseconds to wait between trying to recreate connections to the source or target servers when the bridge has detected they have failed.

swarm.messaging.jms-bridges._KEY_.max-batch-size:: 
The maximum number of messages to consume from the source destination before sending them in a batch to the target destination. Its value must >= 1.

swarm.messaging.jms-bridges._KEY_.max-batch-time:: 
The maximum number of milliseconds to wait before sending a batch to target, even if the number of messages consumed has not reached max-batch-size. Its value must be -1 to represent 'wait forever', or >= 1 to specify an actual time.

swarm.messaging.jms-bridges._KEY_.max-retries:: 
The number of times to attempt to recreate connections to the source or target servers when the bridge has detected they have failed. The bridge will give up after trying this number of times. -1 represents 'try forever'.

swarm.messaging.jms-bridges._KEY_.module:: 
The name of AS7 module containing the resources required to lookup source and target JMS resources.

swarm.messaging.jms-bridges._KEY_.paused:: 
Whether the JMS bridge is paused.

swarm.messaging.jms-bridges._KEY_.quality-of-service:: 
The desired quality of service mode (AT_MOST_ONCE, DUPLICATES_OK or ONCE_AND_ONLY_ONCE).

swarm.messaging.jms-bridges._KEY_.selector:: 
A JMS selector expression used for consuming messages from the source destination. Only messages that match the selector expression will be bridged from the source to the target destination.

swarm.messaging.jms-bridges._KEY_.source-connection-factory:: 
The name of the source connection factory to lookup on the source messaging server.

swarm.messaging.jms-bridges._KEY_.source-context:: 
The properties used to configure the source JNDI initial context.

swarm.messaging.jms-bridges._KEY_.source-destination:: 
The name of the source destination to lookup on the source messaging server.

swarm.messaging.jms-bridges._KEY_.source-password:: 
The password for creating the source connection.

swarm.messaging.jms-bridges._KEY_.source-user:: 
The name of the user for creating the source connection.

swarm.messaging.jms-bridges._KEY_.started:: 
Whether the JMS bridge is started.

swarm.messaging.jms-bridges._KEY_.subscription-name:: 
The name of the subscription if it is durable and the source destination is a topic.

swarm.messaging.jms-bridges._KEY_.target-connection-factory:: 
The name of the target connection factory to lookup on the target messaging server.

swarm.messaging.jms-bridges._KEY_.target-context:: 
The properties used to configure the target JNDI initial context.

swarm.messaging.jms-bridges._KEY_.target-destination:: 
The name of the target destination to lookup on the target messaging server.

swarm.messaging.jms-bridges._KEY_.target-password:: 
The password for creating the target connection.

swarm.messaging.jms-bridges._KEY_.target-user:: 
The name of the user for creating the target connection.

swarm.messaging.remote:: 
Flag to enable the remote connection

swarm.messaging.remote.host:: 
Host of the remote connection

swarm.messaging.remote.jndi-name:: 
JNDI name of the remote connection

swarm.messaging.remote.name:: 
Name of the remote connection

swarm.messaging.remote.port:: 
Port of the remote connection

swarm.messaging.servers._KEY_.acceptors._KEY_.factory-class:: 
Class name of the factory class that can instantiate the acceptor.

swarm.messaging.servers._KEY_.acceptors._KEY_.params:: 
A key-value pair understood by the acceptor factory-class and used to configure it.

swarm.messaging.servers._KEY_.acceptors._KEY_.socket-binding:: 
The socket binding that the acceptor will use to accept connections.

swarm.messaging.servers._KEY_.acceptors._KEY_.started:: 
Whether this acceptor is started.

swarm.messaging.servers._KEY_.active:: 
Whether the server is active (and accepting connections) or passive (in backup mode, waiting for failover).

swarm.messaging.servers._KEY_.address-settings._KEY_.address-full-policy:: 
Determines what happens when an address where max-size-bytes is specified becomes full. (PAGE, DROP or BLOCK)

swarm.messaging.servers._KEY_.address-settings._KEY_.auto-create-jms-queues:: 
Determines whether ActiveMQ should automatically create a JMS queue corresponding to the address-settings match when a JMS producer or a consumer is tries to use such a queue.

swarm.messaging.servers._KEY_.address-settings._KEY_.auto-delete-jms-queues:: 
Determises Whether ActiveMQ should automatically delete auto-created JMS queues when they have no consumers and no messages.

swarm.messaging.servers._KEY_.address-settings._KEY_.dead-letter-address:: 
The dead letter address

swarm.messaging.servers._KEY_.address-settings._KEY_.expiry-address:: 
Defines where to send a message that has expired.

swarm.messaging.servers._KEY_.address-settings._KEY_.expiry-delay:: 
Defines the expiration time that will be used for messages using the default expiration time

swarm.messaging.servers._KEY_.address-settings._KEY_.last-value-queue:: 
Defines whether a queue only uses last values or not

swarm.messaging.servers._KEY_.address-settings._KEY_.max-delivery-attempts:: 
Defines how many time a cancelled message can be redelivered before sending to the dead-letter-address

swarm.messaging.servers._KEY_.address-settings._KEY_.max-redelivery-delay:: 
Maximum value for the redelivery-delay (in ms).

swarm.messaging.servers._KEY_.address-settings._KEY_.max-size-bytes:: 
The max bytes size.

swarm.messaging.servers._KEY_.address-settings._KEY_.message-counter-history-day-limit:: 
Day limit for the message counter history.

swarm.messaging.servers._KEY_.address-settings._KEY_.page-max-cache-size:: 
The number of page files to keep in memory to optimize IO during paging navigation.

swarm.messaging.servers._KEY_.address-settings._KEY_.page-size-bytes:: 
The paging size.

swarm.messaging.servers._KEY_.address-settings._KEY_.redelivery-delay:: 
Defines how long to wait before attempting redelivery of a cancelled message

swarm.messaging.servers._KEY_.address-settings._KEY_.redelivery-multiplier:: 
Multiplier to apply to the redelivery-delay parameter

swarm.messaging.servers._KEY_.address-settings._KEY_.redistribution-delay:: 
Defines how long to wait when the last consumer is closed on a queue before redistributing any messages

swarm.messaging.servers._KEY_.address-settings._KEY_.send-to-dla-on-no-route:: 
If this parameter is set to true for that address, if the message is not routed to any queues it will instead be sent to the dead letter address (DLA) for that address, if it exists.

swarm.messaging.servers._KEY_.address-settings._KEY_.slow-consumer-check-period:: 
How often to check for slow consumers on a particular queue.

swarm.messaging.servers._KEY_.address-settings._KEY_.slow-consumer-policy:: 
Determine what happens when a slow consumer is identified.

swarm.messaging.servers._KEY_.address-settings._KEY_.slow-consumer-threshold:: 
The minimum rate of message consumption allowed before a consumer is considered slow.

swarm.messaging.servers._KEY_.async-connection-execution-enabled:: 
Whether incoming packets on the server should be handed off to a thread from the thread pool for processing. False if they should be handled on the remoting thread.

swarm.messaging.servers._KEY_.bindings-directory-path.path:: 
The actual filesystem path. Treated as an absolute path, unless the 'relative-to' attribute is specified, in which case the value is treated as relative to that path. <p>If treated as an absolute path, the actual runtime pathname specified by the value of this attribute will be determined as follows: </p>If this value is already absolute, then the value is directly used.  Otherwise the runtime pathname is resolved in a system-dependent way.  On UNIX systems, a relative pathname is made absolute by resolving it against the current user directory. On Microsoft Windows systems, a relative pathname is made absolute by resolving it against the current directory of the drive named by the pathname, if any; if not, it is resolved against the current user directory.

swarm.messaging.servers._KEY_.bindings-directory-path.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute. The standard paths provided by the system include:<ul><li>jboss.home - the root directory of the JBoss AS distribution</li><li>user.home - user's home directory</li><li>user.dir - user's current working directory</li><li>java.home - java installation directory</li><li>jboss.server.base.dir - root directory for an individual server instance</li><li>jboss.server.data.dir - directory the server will use for persistent data file storage</li><li>jboss.server.log.dir - directory the server will use for log file storage</li><li>jboss.server.tmp.dir - directory the server will use for temporary file storage</li><li>jboss.domain.servers.dir - directory under which a host controller will create the working area for individual server instances</li></ul>

swarm.messaging.servers._KEY_.bridges._KEY_.check-period:: 
The period (in milliseconds) between client failure check.

swarm.messaging.servers._KEY_.bridges._KEY_.confirmation-window-size:: 
The confirmation-window-size to use for the connection used to forward messages to the target node.

swarm.messaging.servers._KEY_.bridges._KEY_.connection-ttl:: 
The maximum time (in milliseconds) for which the connections used by the bridges are considered alive (in the absence of heartbeat).

swarm.messaging.servers._KEY_.bridges._KEY_.discovery-group:: 
The name of the discovery group used by this bridge. Must be undefined (null) if 'static-connectors' is defined.

swarm.messaging.servers._KEY_.bridges._KEY_.filter:: 
An optional filter string. If specified then only messages which match the filter expression specified will be forwarded. The filter string follows the ActiveMQ filter expression syntax described in the ActiveMQ documentation.

swarm.messaging.servers._KEY_.bridges._KEY_.forwarding-address:: 
The address on the target server that the message will be forwarded to. If a forwarding address is not specified then the original destination of the message will be retained.

swarm.messaging.servers._KEY_.bridges._KEY_.ha:: 
Whether or not this bridge should support high availability. True means it will connect to any available server in a cluster and support failover.

swarm.messaging.servers._KEY_.bridges._KEY_.initial-connect-attempts:: 
The number of attempts to connect initially with this bridge.

swarm.messaging.servers._KEY_.bridges._KEY_.max-retry-interval:: 
The maximum interval of time used to retry connections

swarm.messaging.servers._KEY_.bridges._KEY_.min-large-message-size:: 
The minimum size (in bytes) for a message before it is considered as a large message.

swarm.messaging.servers._KEY_.bridges._KEY_.password:: 
The password to use when creating the bridge connection to the remote server. If it is not specified the default cluster password specified by the cluster-password attribute in the root messaging subsystem resource will be used.

swarm.messaging.servers._KEY_.bridges._KEY_.queue-name:: 
The unique name of the local queue that the bridge consumes from.

swarm.messaging.servers._KEY_.bridges._KEY_.reconnect-attempts:: 
The total number of reconnect attempts the bridge will make before giving up and shutting down. A value of -1 signifies an unlimited number of attempts.

swarm.messaging.servers._KEY_.bridges._KEY_.reconnect-attempts-on-same-node:: 
The total number of reconnect attempts on the same node the bridge will make before giving up and shutting down. A value of -1 signifies an unlimited number of attempts.

swarm.messaging.servers._KEY_.bridges._KEY_.retry-interval:: 
The period in milliseconds between subsequent reconnection attempts, if the connection to the target server has failed.

swarm.messaging.servers._KEY_.bridges._KEY_.retry-interval-multiplier:: 
A multiplier to apply to the time since the last retry to compute the time to the next retry. This allows you to implement an exponential backoff between retry attempts.

swarm.messaging.servers._KEY_.bridges._KEY_.started:: 
Whether the bridge is started.

swarm.messaging.servers._KEY_.bridges._KEY_.static-connectors:: 
A list of names of statically defined connectors used by this bridge. Must be undefined (null) if 'discovery-group-name' is defined.

swarm.messaging.servers._KEY_.bridges._KEY_.transformer-class-name:: 
The name of a user-defined class which implements the org.apache.activemq.artemis.core.server.cluster.Transformer interface.

swarm.messaging.servers._KEY_.bridges._KEY_.use-duplicate-detection:: 
Whether the bridge will automatically insert a duplicate id property into each message that it forwards.

swarm.messaging.servers._KEY_.bridges._KEY_.user:: 
The user name to use when creating the bridge connection to the remote server. If it is not specified the default cluster user specified by the cluster-user attribute in the root messaging subsystem resource will be used.

swarm.messaging.servers._KEY_.broadcast-groups._KEY_.broadcast-period:: 
The period in milliseconds between consecutive broadcasts.

swarm.messaging.servers._KEY_.broadcast-groups._KEY_.connectors:: 
Specifies the names of connectors that will be broadcast.

swarm.messaging.servers._KEY_.broadcast-groups._KEY_.jgroups-channel:: 
The name used by a JGroups channel to join a cluster.

swarm.messaging.servers._KEY_.broadcast-groups._KEY_.jgroups-stack:: 
The name of a stack defined in the org.jboss.as.clustering.jgroups subsystem that is used to form a cluster.

swarm.messaging.servers._KEY_.broadcast-groups._KEY_.socket-binding:: 
The broadcast group socket binding.

swarm.messaging.servers._KEY_.broadcast-groups._KEY_.started:: 
Whether the broadcast group is started.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.allow-direct-connections-only:: 
Whether, if a node learns of the existence of a node that is more than 1 hop away, we do not create a bridge for direct cluster connection. Only relevant if 'static-connectors' is defined.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.call-failover-timeout:: 
The timeout to use when fail over is in process (in ms) for remote calls made by the cluster connection.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.call-timeout:: 
The timeout (in ms) for remote calls made by the cluster connection.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.check-period:: 
The period (in milliseconds) between client failure check.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.cluster-connection-address:: 
Each cluster connection only applies to messages sent to an address that starts with this value.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.confirmation-window-size:: 
The confirmation-window-size to use for the connection used to forward messages to a target node.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.connection-ttl:: 
The maximum time (in milliseconds) for which the connections used by the cluster connections are considered alive (in the absence of heartbeat).

swarm.messaging.servers._KEY_.cluster-connections._KEY_.connector-name:: 
The name of connector to use for live connection

swarm.messaging.servers._KEY_.cluster-connections._KEY_.discovery-group:: 
The discovery group used to obtain the list of other servers in the cluster to which this cluster connection will make connections. Must be undefined (null) if 'static-connectors' is defined.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.initial-connect-attempts:: 
The number of attempts to connect initially with this cluster connection.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.max-hops:: 
The maximum number of times a message can be forwarded. ActiveMQ can be configured to also load balance messages to nodes which might be connected to it only indirectly with other ActiveMQ servers as intermediates in a chain.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.max-retry-interval:: 
The maximum interval of time used to retry connections

swarm.messaging.servers._KEY_.cluster-connections._KEY_.message-load-balancing-type:: 
The type of message load balancing provided by the cluster connection.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.min-large-message-size:: 
The minimum size (in bytes) for a message before it is considered as a large message.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.node-id:: 
The node ID used by this cluster connection.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.notification-attempts:: 
How many times the cluster connection will broadcast itself

swarm.messaging.servers._KEY_.cluster-connections._KEY_.notification-interval:: 
How often the cluster connection will broadcast itself

swarm.messaging.servers._KEY_.cluster-connections._KEY_.reconnect-attempts:: 
The total number of reconnect attempts the bridge will make before giving up and shutting down. A value of -1 signifies an unlimited number of attempts.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.retry-interval:: 
The period in milliseconds between subsequent attempts to reconnect to a target server, if the connection to the target server has failed.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.retry-interval-multiplier:: 
A multiplier to apply to the time since the last retry to compute the time to the next retry. This allows you to implement an exponential backoff between retry attempts.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.started:: 
Whether the cluster connection is started.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.static-connectors:: 
The statically defined list of connectors to which this cluster connection will make connections. Must be undefined (null) if 'discovery-group-name' is defined.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.topology:: 
The topology of the nodes that this cluster connection is aware of.

swarm.messaging.servers._KEY_.cluster-connections._KEY_.use-duplicate-detection:: 
Whether the bridge will automatically insert a duplicate id property into each message that it forwards.

swarm.messaging.servers._KEY_.cluster-password:: 
The password used by cluster connections to communicate between the clustered nodes.

swarm.messaging.servers._KEY_.cluster-user:: 
The user used by cluster connections to communicate between the clustered nodes.

swarm.messaging.servers._KEY_.connection-factories._KEY_.auto-group:: 
Whether or not message grouping is automatically used

swarm.messaging.servers._KEY_.connection-factories._KEY_.block-on-acknowledge:: 
True to set block on acknowledge.

swarm.messaging.servers._KEY_.connection-factories._KEY_.block-on-durable-send:: 
True to set block on durable send.

swarm.messaging.servers._KEY_.connection-factories._KEY_.block-on-non-durable-send:: 
True to set block on non durable send.

swarm.messaging.servers._KEY_.connection-factories._KEY_.cache-large-message-client:: 
True to cache large messages.

swarm.messaging.servers._KEY_.connection-factories._KEY_.call-failover-timeout:: 
The timeout to use when fail over is in process (in ms).

swarm.messaging.servers._KEY_.connection-factories._KEY_.call-timeout:: 
The call time out.

swarm.messaging.servers._KEY_.connection-factories._KEY_.client-failure-check-period:: 
The client failure check period.

swarm.messaging.servers._KEY_.connection-factories._KEY_.client-id:: 
The client id.

swarm.messaging.servers._KEY_.connection-factories._KEY_.compress-large-messages:: 
Whether large messages should be compressed.

swarm.messaging.servers._KEY_.connection-factories._KEY_.confirmation-window-size:: 
The confirmation window size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.connection-load-balancing-policy-class-name:: 
Name of a class implementing a client-side load balancing policy that a client can use to load balance sessions across different nodes in a cluster.

swarm.messaging.servers._KEY_.connection-factories._KEY_.connection-ttl:: 
The connection ttl.

swarm.messaging.servers._KEY_.connection-factories._KEY_.connectors:: 
Defines the connectors. These are stored in a map by connector name (with an undefined value). It is possible to pass a list of connector names when writing this attribute.

swarm.messaging.servers._KEY_.connection-factories._KEY_.consumer-max-rate:: 
The consumer max rate.

swarm.messaging.servers._KEY_.connection-factories._KEY_.consumer-window-size:: 
The consumer window size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.discovery-group:: 
The discovery group name.

swarm.messaging.servers._KEY_.connection-factories._KEY_.dups-ok-batch-size:: 
The dups ok batch size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.entries:: 
The jndi names the connection factory should be bound to.

swarm.messaging.servers._KEY_.connection-factories._KEY_.factory-type:: 
The type of connection factory.

swarm.messaging.servers._KEY_.connection-factories._KEY_.failover-on-initial-connection:: 
True to fail over on initial connection.

swarm.messaging.servers._KEY_.connection-factories._KEY_.group-id:: 
The group id.

swarm.messaging.servers._KEY_.connection-factories._KEY_.ha:: 
Whether the connection factory supports High Availability.

swarm.messaging.servers._KEY_.connection-factories._KEY_.max-retry-interval:: 
The max retry interval.

swarm.messaging.servers._KEY_.connection-factories._KEY_.min-large-message-size:: 
The min large message size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.pre-acknowledge:: 
True to pre-acknowledge.

swarm.messaging.servers._KEY_.connection-factories._KEY_.producer-max-rate:: 
The producer max rate.

swarm.messaging.servers._KEY_.connection-factories._KEY_.producer-window-size:: 
The producer window size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.protocol-manager-factory:: 
The protocol manager factory used by this connection factory.

swarm.messaging.servers._KEY_.connection-factories._KEY_.reconnect-attempts:: 
The reconnect attempts.

swarm.messaging.servers._KEY_.connection-factories._KEY_.retry-interval:: 
The retry interval.

swarm.messaging.servers._KEY_.connection-factories._KEY_.retry-interval-multiplier:: 
The retry interval multiplier.

swarm.messaging.servers._KEY_.connection-factories._KEY_.scheduled-thread-pool-max-size:: 
The scheduled thread pool max size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.thread-pool-max-size:: 
The thread pool max size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.transaction-batch-size:: 
The transaction batch size.

swarm.messaging.servers._KEY_.connection-factories._KEY_.use-global-pools:: 
True to use global pools.

swarm.messaging.servers._KEY_.connection-ttl-override:: 
If set, this will override how long (in ms) to keep a connection alive without receiving a ping.

swarm.messaging.servers._KEY_.connector-services._KEY_.factory-class:: 
Class name of the factory class that can instantiate the connector service.

swarm.messaging.servers._KEY_.connector-services._KEY_.params:: 
A key/value pair understood by the connector service's factory-class

swarm.messaging.servers._KEY_.connectors._KEY_.factory-class:: 
Class name of the factory class that can instantiate the connector.

swarm.messaging.servers._KEY_.connectors._KEY_.params:: 
A key-value pair understood by the connector factory-class and used to configure it.

swarm.messaging.servers._KEY_.connectors._KEY_.socket-binding:: 
The socket binding that the connector will use to create connections.

swarm.messaging.servers._KEY_.core-address._KEY_.binding-names:: 
The names of all bindings (both queues and diverts) bound to this address.

swarm.messaging.servers._KEY_.core-address._KEY_.number-of-bytes-per-page:: 
The number of bytes used by each page for this address.

swarm.messaging.servers._KEY_.core-address._KEY_.number-of-pages:: 
The number of pages used by this address.

swarm.messaging.servers._KEY_.core-address._KEY_.queue-names:: 
The names of the queues associated with the address.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.consume:: 
his permission allows the user to consume a message from a queue bound to matching addresses.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.create-durable-queue:: 
This permission allows the user to create a durable queue.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.create-non-durable-queue:: 
This permission allows the user to create a temporary queue.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.delete-durable-queue:: 
This permission allows the user to delete a durable queue.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.delete-non-durable-queue:: 
This permission allows the user to delete a temporary queue.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.manage:: 
This permission allows the user to invoke management operations by sending management messages to the management address.

swarm.messaging.servers._KEY_.core-address._KEY_.roles._KEY_.send:: 
This permission allows the user to send a message to matching addresses.

swarm.messaging.servers._KEY_.create-bindings-dir:: 
Whether the server should create the bindings directory on start up.

swarm.messaging.servers._KEY_.create-journal-dir:: 
Whether the server should create the journal directory on start up.

swarm.messaging.servers._KEY_.discovery-groups._KEY_.initial-wait-timeout:: 
Period, in ms, to wait for an initial broadcast to give us at least one node in the cluster.

swarm.messaging.servers._KEY_.discovery-groups._KEY_.jgroups-channel:: 
The name used by a JGroups channel to join a cluster.

swarm.messaging.servers._KEY_.discovery-groups._KEY_.jgroups-stack:: 
The name of a stack defined in the org.jboss.as.clustering.jgroups subsystem that is used to form a cluster.

swarm.messaging.servers._KEY_.discovery-groups._KEY_.refresh-timeout:: 
Period the discovery group waits after receiving the last broadcast from a particular server before removing that server's connector pair entry from its list.

swarm.messaging.servers._KEY_.discovery-groups._KEY_.socket-binding:: 
The discovery group socket binding.

swarm.messaging.servers._KEY_.diverts._KEY_.divert-address:: 
Address to divert from

swarm.messaging.servers._KEY_.diverts._KEY_.exclusive:: 
Whether the divert is exclusive, meaning that the message is diverted to the new address, and does not go to the old address at all.

swarm.messaging.servers._KEY_.diverts._KEY_.filter:: 
An optional filter string. If specified then only messages which match the filter expression specified will be diverted. The filter string follows the ActiveMQ filter expression syntax described in the ActiveMQ documentation.

swarm.messaging.servers._KEY_.diverts._KEY_.forwarding-address:: 
Address to divert to

swarm.messaging.servers._KEY_.diverts._KEY_.routing-name:: 
Routing name of the divert

swarm.messaging.servers._KEY_.diverts._KEY_.transformer-class-name:: 
The name of a class used to transform the message's body or properties before it is diverted.

swarm.messaging.servers._KEY_.grouping-handlers._KEY_.group-timeout:: 
How long a group binding will be used, -1 means for ever. Bindings are removed after this wait elapses (valid for both LOCAL and REMOTE handlers).

swarm.messaging.servers._KEY_.grouping-handlers._KEY_.grouping-handler-address:: 
A reference to a cluster connection and the address it uses.

swarm.messaging.servers._KEY_.grouping-handlers._KEY_.reaper-period:: 
How often the reaper will be run to check for timed out group bindings (only valid for LOCAL handlers).

swarm.messaging.servers._KEY_.grouping-handlers._KEY_.timeout:: 
How long to wait for a handling decision to be made; an exception will be thrown during the send if this timeout is reached, ensuring that strict ordering is kept.

swarm.messaging.servers._KEY_.grouping-handlers._KEY_.type:: 
Whether the handler is the single "Local" handler for the cluster, which makes handling decisions, or a "Remote" handler which converses with the local handler.

swarm.messaging.servers._KEY_.http-acceptors._KEY_.http-listener:: 
The Undertow's http-listener that handles HTTP upgrade requests.

swarm.messaging.servers._KEY_.http-acceptors._KEY_.params:: 
A key-value pair understood by the acceptor factory-class and used to configure it.

swarm.messaging.servers._KEY_.http-acceptors._KEY_.upgrade-legacy:: 
Also accepts to upgrade HTTP request from legacy (HornetQ) clients.

swarm.messaging.servers._KEY_.http-connectors._KEY_.endpoint:: 
The http-acceptor that serves as the endpoint of this http-connector.

swarm.messaging.servers._KEY_.http-connectors._KEY_.params:: 
A key-value pair understood by the connector factory-class and used to configure it.

swarm.messaging.servers._KEY_.http-connectors._KEY_.socket-binding:: 
The socket binding that the connector will use to create connections.

swarm.messaging.servers._KEY_.id-cache-size:: 
The size of the cache for pre-creating message IDs.

swarm.messaging.servers._KEY_.in-vm-acceptors._KEY_.params:: 
A key-value pair understood by the acceptor factory-class and used to configure it.

swarm.messaging.servers._KEY_.in-vm-acceptors._KEY_.server-id:: 
The server id.

swarm.messaging.servers._KEY_.in-vm-acceptors._KEY_.started:: 
Whether this acceptor is started.

swarm.messaging.servers._KEY_.in-vm-connectors._KEY_.params:: 
A key-value pair understood by the connector factory-class and used to configure it.

swarm.messaging.servers._KEY_.in-vm-connectors._KEY_.server-id:: 
The server id.

swarm.messaging.servers._KEY_.incoming-interceptors:: 
The list of incoming interceptor classes used by this server.

swarm.messaging.servers._KEY_.jms-queues._KEY_.consumer-count:: 
The number of consumers consuming messages from this queue.

swarm.messaging.servers._KEY_.jms-queues._KEY_.dead-letter-address:: 
The address to send dead messages to.

swarm.messaging.servers._KEY_.jms-queues._KEY_.delivering-count:: 
The number of messages that this queue is currently delivering to its consumers.

swarm.messaging.servers._KEY_.jms-queues._KEY_.durable:: 
Whether the queue is durable or not.

swarm.messaging.servers._KEY_.jms-queues._KEY_.entries:: 
The jndi names the queue will be bound to.

swarm.messaging.servers._KEY_.jms-queues._KEY_.expiry-address:: 
The address to send expired messages to.

swarm.messaging.servers._KEY_.jms-queues._KEY_.legacy-entries:: 
The jndi names the queue will be bound to.

swarm.messaging.servers._KEY_.jms-queues._KEY_.message-count:: 
The number of messages currently in this queue.

swarm.messaging.servers._KEY_.jms-queues._KEY_.messages-added:: 
The number of messages added to this queue since it was created.

swarm.messaging.servers._KEY_.jms-queues._KEY_.paused:: 
Whether the queue is paused.

swarm.messaging.servers._KEY_.jms-queues._KEY_.queue-address:: 
The queue address defines what address is used for routing messages.

swarm.messaging.servers._KEY_.jms-queues._KEY_.scheduled-count:: 
The number of scheduled messages in this queue.

swarm.messaging.servers._KEY_.jms-queues._KEY_.selector:: 
The queue selector.

swarm.messaging.servers._KEY_.jms-queues._KEY_.temporary:: 
Whether the queue is temporary.

swarm.messaging.servers._KEY_.jms-topics._KEY_.delivering-count:: 
The number of messages that this queue is currently delivering to its consumers.

swarm.messaging.servers._KEY_.jms-topics._KEY_.durable-message-count:: 
The number of messages for all durable subscribers for this topic.

swarm.messaging.servers._KEY_.jms-topics._KEY_.durable-subscription-count:: 
The number of durable subscribers for this topic.

swarm.messaging.servers._KEY_.jms-topics._KEY_.entries:: 
The jndi names the topic will be bound to.

swarm.messaging.servers._KEY_.jms-topics._KEY_.legacy-entries:: 
The legacy jndi names the topic will be bound to.

swarm.messaging.servers._KEY_.jms-topics._KEY_.message-count:: 
The number of messages currently in this queue.

swarm.messaging.servers._KEY_.jms-topics._KEY_.messages-added:: 
The number of messages added to this queue since it was created.

swarm.messaging.servers._KEY_.jms-topics._KEY_.non-durable-message-count:: 
The number of messages for all non-durable subscribers for this topic.

swarm.messaging.servers._KEY_.jms-topics._KEY_.non-durable-subscription-count:: 
The number of non-durable subscribers for this topic.

swarm.messaging.servers._KEY_.jms-topics._KEY_.subscription-count:: 
The number of (durable and non-durable) subscribers for this topic.

swarm.messaging.servers._KEY_.jms-topics._KEY_.temporary:: 
Whether the topic is temporary.

swarm.messaging.servers._KEY_.jms-topics._KEY_.topic-address:: 
The address the topic points to.

swarm.messaging.servers._KEY_.jmx-domain:: 
The JMX domain used to register internal ActiveMQ MBeans in the MBeanServer.

swarm.messaging.servers._KEY_.jmx-management-enabled:: 
Whether ActiveMQ should expose its internal management API via JMX. This is not recommended, as accessing these MBeans can lead to inconsistent configuration.

swarm.messaging.servers._KEY_.journal-buffer-size:: 
The size of the internal buffer on the journal.

swarm.messaging.servers._KEY_.journal-buffer-timeout:: 
The timeout (in nanoseconds) used to flush internal buffers on the journal.

swarm.messaging.servers._KEY_.journal-compact-min-files:: 
The minimal number of journal data files before we can start compacting.

swarm.messaging.servers._KEY_.journal-compact-percentage:: 
The percentage of live data on which we consider compacting the journal.

swarm.messaging.servers._KEY_.journal-directory-path.path:: 
The actual filesystem path. Treated as an absolute path, unless the 'relative-to' attribute is specified, in which case the value is treated as relative to that path. <p>If treated as an absolute path, the actual runtime pathname specified by the value of this attribute will be determined as follows: </p>If this value is already absolute, then the value is directly used.  Otherwise the runtime pathname is resolved in a system-dependent way.  On UNIX systems, a relative pathname is made absolute by resolving it against the current user directory. On Microsoft Windows systems, a relative pathname is made absolute by resolving it against the current directory of the drive named by the pathname, if any; if not, it is resolved against the current user directory.

swarm.messaging.servers._KEY_.journal-directory-path.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute. The standard paths provided by the system include:<ul><li>jboss.home - the root directory of the JBoss AS distribution</li><li>user.home - user's home directory</li><li>user.dir - user's current working directory</li><li>java.home - java installation directory</li><li>jboss.server.base.dir - root directory for an individual server instance</li><li>jboss.server.data.dir - directory the server will use for persistent data file storage</li><li>jboss.server.log.dir - directory the server will use for log file storage</li><li>jboss.server.tmp.dir - directory the server will use for temporary file storage</li><li>jboss.domain.servers.dir - directory under which a host controller will create the working area for individual server instances</li></ul>

swarm.messaging.servers._KEY_.journal-file-size:: 
The size (in bytes) of each journal file.

swarm.messaging.servers._KEY_.journal-max-io:: 
The maximum number of write requests that can be in the AIO queue at any one time.

swarm.messaging.servers._KEY_.journal-min-files:: 
How many journal files to pre-create.

swarm.messaging.servers._KEY_.journal-pool-files:: 
The number of journal files that can be reused. ActiveMQ will create as many files as needed however when reclaiming files it will shrink back to the value (-1 means no limit).

swarm.messaging.servers._KEY_.journal-sync-non-transactional:: 
Whether to wait for non transaction data to be synced to the journal before returning a response to the client.

swarm.messaging.servers._KEY_.journal-sync-transactional:: 
Whether to wait for transaction data to be synchronized to the journal before returning a response to the client.

swarm.messaging.servers._KEY_.journal-type:: 
The type of journal to use.

swarm.messaging.servers._KEY_.large-messages-directory-path.path:: 
The actual filesystem path. Treated as an absolute path, unless the 'relative-to' attribute is specified, in which case the value is treated as relative to that path. <p>If treated as an absolute path, the actual runtime pathname specified by the value of this attribute will be determined as follows: </p>If this value is already absolute, then the value is directly used.  Otherwise the runtime pathname is resolved in a system-dependent way.  On UNIX systems, a relative pathname is made absolute by resolving it against the current user directory. On Microsoft Windows systems, a relative pathname is made absolute by resolving it against the current directory of the drive named by the pathname, if any; if not, it is resolved against the current user directory.

swarm.messaging.servers._KEY_.large-messages-directory-path.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute. The standard paths provided by the system include:<ul><li>jboss.home - the root directory of the JBoss AS distribution</li><li>user.home - user's home directory</li><li>user.dir - user's current working directory</li><li>java.home - java installation directory</li><li>jboss.server.base.dir - root directory for an individual server instance</li><li>jboss.server.data.dir - directory the server will use for persistent data file storage</li><li>jboss.server.log.dir - directory the server will use for log file storage</li><li>jboss.server.tmp.dir - directory the server will use for temporary file storage</li><li>jboss.domain.servers.dir - directory under which a host controller will create the working area for individual server instances</li></ul>

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.auto-group:: 
Whether or not message grouping is automatically used

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.block-on-acknowledge:: 
True to set block on acknowledge.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.block-on-durable-send:: 
True to set block on durable send.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.block-on-non-durable-send:: 
True to set block on non durable send.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.cache-large-message-client:: 
True to cache large messages.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.call-failover-timeout:: 
The timeout to use when fail over is in process (in ms).

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.call-timeout:: 
The call time out.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.client-failure-check-period:: 
The client failure check period.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.client-id:: 
The client id.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.compress-large-messages:: 
Whether large messages should be compressed.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.confirmation-window-size:: 
The confirmation window size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.connection-load-balancing-policy-class-name:: 
Name of a class implementing a client-side load balancing policy that a client can use to load balance sessions across different nodes in a cluster.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.connection-ttl:: 
The connection ttl.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.connectors:: 
Defines the connectors. These are stored in a map by connector name (with an undefined value). It is possible to pass a list of connector names when writing this attribute.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.consumer-max-rate:: 
The consumer max rate.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.consumer-window-size:: 
The consumer window size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.discovery-group:: 
The discovery group name.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.dups-ok-batch-size:: 
The dups ok batch size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.entries:: 
The jndi names the connection factory should be bound to.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.factory-type:: 
The type of connection factory.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.failover-on-initial-connection:: 
True to fail over on initial connection.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.group-id:: 
The group id.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.ha:: 
Whether the connection factory supports High Availability.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.initial-connect-attempts:: 
The number of attempts for the initial connection to the server.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.initial-message-packet-size:: 
The initial size of messages created through this factory.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.max-retry-interval:: 
The max retry interval.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.min-large-message-size:: 
The min large message size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.pre-acknowledge:: 
True to pre-acknowledge.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.producer-max-rate:: 
The producer max rate.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.producer-window-size:: 
The producer window size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.reconnect-attempts:: 
The reconnect attempts.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.retry-interval:: 
The retry interval.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.retry-interval-multiplier:: 
The retry interval multiplier.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.scheduled-thread-pool-max-size:: 
The scheduled thread pool max size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.thread-pool-max-size:: 
The thread pool max size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.transaction-batch-size:: 
The transaction batch size.

swarm.messaging.servers._KEY_.legacy-connection-factories._KEY_.use-global-pools:: 
True to use global pools.

swarm.messaging.servers._KEY_.live-only-ha-policy.scale-down:: 
Configure whether this server send its messages to another live server in the scale-down cluster when it is shutdown cleanly.

swarm.messaging.servers._KEY_.live-only-ha-policy.scale-down-cluster-name:: 
Name of the cluster used to scale down.

swarm.messaging.servers._KEY_.live-only-ha-policy.scale-down-connectors:: 
List of connectors used to form the scale-down cluster.

swarm.messaging.servers._KEY_.live-only-ha-policy.scale-down-discovery-group:: 
Name of the discovery group used to build the scale-down cluster

swarm.messaging.servers._KEY_.live-only-ha-policy.scale-down-group-name:: 
Name of the group used to scale down.

swarm.messaging.servers._KEY_.log-journal-write-rate:: 
Whether to periodically log the journal's write rate and flush rate.

swarm.messaging.servers._KEY_.management-address:: 
Address to send management messages to.

swarm.messaging.servers._KEY_.management-notification-address:: 
The name of the address that consumers bind to  to receive management notifications.

swarm.messaging.servers._KEY_.memory-measure-interval:: 
Frequency to sample JVM memory in ms (or -1 to disable memory sampling)

swarm.messaging.servers._KEY_.memory-warning-threshold:: 
Percentage of available memory which if exceeded results in a warning log

swarm.messaging.servers._KEY_.message-counter-max-day-history:: 
How many days to keep message counter history.

swarm.messaging.servers._KEY_.message-counter-sample-period:: 
The sample period (in ms) to use for message counters.

swarm.messaging.servers._KEY_.message-expiry-scan-period:: 
How often (in ms) to scan for expired messages.

swarm.messaging.servers._KEY_.message-expiry-thread-priority:: 
The priority of the thread expiring messages.

swarm.messaging.servers._KEY_.outgoing-interceptors:: 
The list of outgoing interceptor classes used by this server.

swarm.messaging.servers._KEY_.override-in-vm-security:: 
Whether the ActiveMQ server will override security credentials for in-vm connections.

swarm.messaging.servers._KEY_.page-max-concurrent-io:: 
The maximum number of concurrent reads allowed on paging

swarm.messaging.servers._KEY_.paging-directory-path.path:: 
The actual filesystem path. Treated as an absolute path, unless the 'relative-to' attribute is specified, in which case the value is treated as relative to that path. <p>If treated as an absolute path, the actual runtime pathname specified by the value of this attribute will be determined as follows: </p>If this value is already absolute, then the value is directly used.  Otherwise the runtime pathname is resolved in a system-dependent way.  On UNIX systems, a relative pathname is made absolute by resolving it against the current user directory. On Microsoft Windows systems, a relative pathname is made absolute by resolving it against the current directory of the drive named by the pathname, if any; if not, it is resolved against the current user directory.

swarm.messaging.servers._KEY_.paging-directory-path.relative-to:: 
The name of another previously named path, or of one of the standard paths provided by the system. If 'relative-to' is provided, the value of the 'path' attribute is treated as relative to the path specified by this attribute. The standard paths provided by the system include:<ul><li>jboss.home - the root directory of the JBoss AS distribution</li><li>user.home - user's home directory</li><li>user.dir - user's current working directory</li><li>java.home - java installation directory</li><li>jboss.server.base.dir - root directory for an individual server instance</li><li>jboss.server.data.dir - directory the server will use for persistent data file storage</li><li>jboss.server.log.dir - directory the server will use for log file storage</li><li>jboss.server.tmp.dir - directory the server will use for temporary file storage</li><li>jboss.domain.servers.dir - directory under which a host controller will create the working area for individual server instances</li></ul>

swarm.messaging.servers._KEY_.perf-blast-pages:: 
TODO

swarm.messaging.servers._KEY_.persist-delivery-count-before-delivery:: 
Whether the delivery count is persisted before delivery. False means that this only happens after a message has been cancelled.

swarm.messaging.servers._KEY_.persist-id-cache:: 
Whether IDs are persisted to the journal.

swarm.messaging.servers._KEY_.persistence-enabled:: 
Whether the server will use the file based journal for persistence.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.auto-group:: 
The autogroup.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.block-on-acknowledge:: 
True to set block on acknowledge.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.block-on-durable-send:: 
True to set block on durable send.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.block-on-non-durable-send:: 
True to set block on non durable send.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.cache-large-message-client:: 
True to cache large messages.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.call-failover-timeout:: 
The timeout to use when fail over is in process (in ms).

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.call-timeout:: 
The call time out.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.client-failure-check-period:: 
The client failure check period.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.client-id:: 
The client id.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.compress-large-messages:: 
Whether large messages should be compressed.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.confirmation-window-size:: 
The confirmation window size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.connection-load-balancing-policy-class-name:: 
Name of a class implementing a client-side load balancing policy that a client can use to load balance sessions across different nodes in a cluster.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.connection-ttl:: 
The connection ttl.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.connectors:: 
Defines the connectors. These are stored in a map by connector name (with an undefined value). It is possible to pass a list of connector names when writing this attribute.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.consumer-max-rate:: 
The consumer max rate.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.consumer-window-size:: 
The consumer window size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.discovery-group:: 
The discovery group name.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.dups-ok-batch-size:: 
The dups ok batch size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.enlistment-trace:: 
Enables IronJacamar to record enlistment traces for this pooled-connection-factory. This attribute is undefined by default and the behaviour is driven by the presence of the ironjacamar.disable_enlistment_trace system property.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.entries:: 
The jndi names the connection factory should be bound to.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.failover-on-initial-connection:: 
True to fail over on initial connection.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.group-id:: 
The group id.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.ha:: 
Whether the connection factory supports High Availability.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.initial-connect-attempts:: 
The number of attempts to connect initially with this factory.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.initial-message-packet-size:: 
The initial size of messages created through this factory.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.jndi-params:: 
The JNDI params to use for locating the destination for incoming connections.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.managed-connection-pool:: 
The class name of the managed connection pool used by this pooled-connection-factory.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.max-pool-size:: 
The maximum size for the pool

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.max-retry-interval:: 
The max retry interval.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.min-large-message-size:: 
The min large message size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.min-pool-size:: 
The minimum size for the pool

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.password:: 
The default password to use with this connection factory. This is only needed when pointing the connection factory to a remote host.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.pre-acknowledge:: 
True to pre-acknowledge.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.producer-max-rate:: 
The producer max rate.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.producer-window-size:: 
The producer window size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.protocol-manager-factory:: 
The protocol manager factory used by this pooled connection factory.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.reconnect-attempts:: 
The reconnect attempts. By default, a pooled connection factory will try to reconnect infinitely to the messaging server(s).

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.retry-interval:: 
The retry interval.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.retry-interval-multiplier:: 
The retry interval multiplier.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.scheduled-thread-pool-max-size:: 
The scheduled thread pool max size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.setup-attempts:: 
The number of times to set up an MDB endpoint

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.setup-interval:: 
The interval between attempts at setting up an MDB endpoint.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.thread-pool-max-size:: 
The thread pool max size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.transaction:: 
TODO

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.transaction-batch-size:: 
The transaction batch size.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.use-auto-recovery:: 
True to use auto recovery.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.use-global-pools:: 
True to use global pools.

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.use-jndi:: 
Use JNDI to locate the destination for incoming connections

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.use-local-tx:: 
Use a local transaction for incoming sessions

swarm.messaging.servers._KEY_.pooled-connection-factories._KEY_.user:: 
The default username to use with this connection factory. This is only needed when pointing the connection factory to a remote host.

swarm.messaging.servers._KEY_.queues._KEY_.consumer-count:: 
The number of consumers consuming messages from this queue.

swarm.messaging.servers._KEY_.queues._KEY_.dead-letter-address:: 
The address to send the queue's dead messages to.

swarm.messaging.servers._KEY_.queues._KEY_.delivering-count:: 
The number of messages that this queue is currently delivering to its consumers.

swarm.messaging.servers._KEY_.queues._KEY_.durable:: 
Defines whether the queue is durable.

swarm.messaging.servers._KEY_.queues._KEY_.expiry-address:: 
The address to send the queue's expired messages to.

swarm.messaging.servers._KEY_.queues._KEY_.filter:: 
A queue message filter definition. An undefined or empty filter will match all messages.

swarm.messaging.servers._KEY_.queues._KEY_.id:: 
The id of the queue.

swarm.messaging.servers._KEY_.queues._KEY_.message-count:: 
The number of messages currently in this queue.

swarm.messaging.servers._KEY_.queues._KEY_.messages-added:: 
The number of messages added to this queue since it was created.

swarm.messaging.servers._KEY_.queues._KEY_.paused:: 
Whether the queue is paused.

swarm.messaging.servers._KEY_.queues._KEY_.queue-address:: 
The queue address defines what address is used for routing messages.

swarm.messaging.servers._KEY_.queues._KEY_.scheduled-count:: 
The number of scheduled messages in this queue.

swarm.messaging.servers._KEY_.queues._KEY_.temporary:: 
Whether the queue is temporary.

swarm.messaging.servers._KEY_.remote-acceptors._KEY_.params:: 
A key-value pair understood by the acceptor factory-class and used to configure it.

swarm.messaging.servers._KEY_.remote-acceptors._KEY_.socket-binding:: 
The socket binding that the acceptor will use to accept connections.

swarm.messaging.servers._KEY_.remote-acceptors._KEY_.started:: 
Whether this acceptor is started.

swarm.messaging.servers._KEY_.remote-connectors._KEY_.params:: 
A key-value pair understood by the connector factory-class and used to configure it.

swarm.messaging.servers._KEY_.remote-connectors._KEY_.socket-binding:: 
The socket binding that the connector will use to create connections.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.backup-port-offset:: 
The offset to use for the Connectors and Acceptors when creating a new backup server.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.backup-request-retries:: 
How many times the live server will try to request a backup, -1 means for ever.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.backup-request-retry-interval:: 
How long (in ms) to wait for retries between attempts to request a backup server.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.excluded-connectors:: 
The connectors that must not have their port offset.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.master-configuration.check-for-live-server:: 
Whether to check the cluster for another server using the same server ID when starting up.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.master-configuration.cluster-name:: 
Name of the cluster used for replication.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.master-configuration.group-name:: 
If set, backup servers will only pair with live servers with matching group-name.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.master-configuration.initial-replication-sync-timeout:: 
How long to wait until the initiation replication is synchronized.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.max-backups:: 
Whether or not this live server will accept backup requests from other live servers.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.request-backup:: 
If true then the server will request a backup on another node.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.allow-failback:: 
Whether a server will automatically stop when a another places a request to take over its place. The use case is when a regular server stops and its backup takes over its duties, later the main server restarts and requests the server (the former backup) to stop operating.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.cluster-name:: 
Name of the cluster used for replication.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.group-name:: 
If set, backup servers will only pair with live servers with matching group-name.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.initial-replication-sync-timeout:: 
How long to wait until the initiation replication is synchronized.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.max-saved-replicated-journal-size:: 
This specifies how many times a replicated backup server can restart after moving its files on start. Once there are this number of backup journal files the server will stop permanently after if fails back.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.restart-backup:: 
Will this server, if a backup, restart once it has been stopped because of failback or scaling down.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.scale-down:: 
Configure whether this server send its messages to another live server in the scale-down cluster when it is shutdown cleanly.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.scale-down-cluster-name:: 
Name of the cluster used to scale down.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.scale-down-connectors:: 
List of connectors used to form the scale-down cluster.

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.scale-down-discovery-group:: 
Name of the discovery group used to build the scale-down cluster

swarm.messaging.servers._KEY_.replication-colocated-ha-policy.slave-configuration.scale-down-group-name:: 
Name of the group used to scale down.

swarm.messaging.servers._KEY_.replication-master-ha-policy.check-for-live-server:: 
Whether to check the cluster for another server using the same server ID when starting up.

swarm.messaging.servers._KEY_.replication-master-ha-policy.cluster-name:: 
Name of the cluster used for replication.

swarm.messaging.servers._KEY_.replication-master-ha-policy.group-name:: 
If set, backup servers will only pair with live servers with matching group-name.

swarm.messaging.servers._KEY_.replication-master-ha-policy.initial-replication-sync-timeout:: 
How long to wait until the initiation replication is synchronized.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.allow-failback:: 
Whether a server will automatically stop when a another places a request to take over its place. The use case is when a regular server stops and its backup takes over its duties, later the main server restarts and requests the server (the former backup) to stop operating.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.cluster-name:: 
Name of the cluster used for replication.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.group-name:: 
If set, backup servers will only pair with live servers with matching group-name.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.initial-replication-sync-timeout:: 
How long to wait until the initiation replication is synchronized.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.max-saved-replicated-journal-size:: 
This specifies how many times a replicated backup server can restart after moving its files on start. Once there are this number of backup journal files the server will stop permanently after if fails back.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.restart-backup:: 
Will this server, if a backup, restart once it has been stopped because of failback or scaling down.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.scale-down:: 
Configure whether this server send its messages to another live server in the scale-down cluster when it is shutdown cleanly.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.scale-down-cluster-name:: 
Name of the cluster used to scale down.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.scale-down-connectors:: 
List of connectors used to form the scale-down cluster.

swarm.messaging.servers._KEY_.replication-slave-ha-policy.scale-down-discovery-group:: 
Name of the discovery group used to build the scale-down cluster

swarm.messaging.servers._KEY_.replication-slave-ha-policy.scale-down-group-name:: 
Name of the group used to scale down.

swarm.messaging.servers._KEY_.run-sync-speed-test:: 
Whether on startup to perform a diagnostic test on how fast your disk can sync. Useful when determining performance issues.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.consumer-count:: 
The number of consumers consuming messages from this queue.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.dead-letter-address:: 
The address to send the queue's dead messages to.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.delivering-count:: 
The number of messages that this queue is currently delivering to its consumers.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.durable:: 
Defines whether the queue is durable.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.expiry-address:: 
The address to send the queue's expired messages to.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.filter:: 
A queue message filter definition. An undefined or empty filter will match all messages.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.id:: 
The id of the queue.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.message-count:: 
The number of messages currently in this queue.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.messages-added:: 
The number of messages added to this queue since it was created.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.paused:: 
Whether the queue is paused.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.queue-address:: 
The queue address defines what address is used for routing messages.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.scheduled-count:: 
The number of scheduled messages in this queue.

swarm.messaging.servers._KEY_.runtime-queues._KEY_.temporary:: 
Whether the queue is temporary.

swarm.messaging.servers._KEY_.scheduled-thread-pool-max-size:: 
The number of threads that the main scheduled thread pool has.

swarm.messaging.servers._KEY_.security-domain:: 
The security domain to use to verify user and role information

swarm.messaging.servers._KEY_.security-enabled:: 
Whether security is enabled.

swarm.messaging.servers._KEY_.security-invalidation-interval:: 
How long (in ms) to wait before invalidating the security cache.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.consume:: 
his permission allows the user to consume a message from a queue bound to matching addresses.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.create-durable-queue:: 
This permission allows the user to create a durable queue.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.create-non-durable-queue:: 
This permission allows the user to create a temporary queue.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.delete-durable-queue:: 
This permission allows the user to delete a durable queue.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.delete-non-durable-queue:: 
This permission allows the user to delete a temporary queue.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.manage:: 
This permission allows the user to invoke management operations by sending management messages to the management address.

swarm.messaging.servers._KEY_.security-settings._KEY_.roles._KEY_.send:: 
This permission allows the user to send a message to matching addresses.

swarm.messaging.servers._KEY_.server-dump-interval:: 
How often to dump basic runtime information to the server log. A value less than 1 disables this feature.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.backup-port-offset:: 
The offset to use for the Connectors and Acceptors when creating a new backup server.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.backup-request-retries:: 
How many times the live server will try to request a backup, -1 means for ever.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.backup-request-retry-interval:: 
How long (in ms) to wait for retries between attempts to request a backup server.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.master-configuration.failover-on-server-shutdown:: 
Whether the server must failover when it is normally shutdown.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.max-backups:: 
Whether or not this live server will accept backup requests from other live servers.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.request-backup:: 
If true then the server will request a backup on another node.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.allow-failback:: 
Whether a server will automatically stop when a another places a request to take over its place. The use case is when a regular server stops and its backup takes over its duties, later the main server restarts and requests the server (the former backup) to stop operating.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.failover-on-server-shutdown:: 
Whether the server must failover when it is normally shutdown.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.restart-backup:: 
Will this server, if a backup, restart once it has been stopped because of failback or scaling down.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.scale-down:: 
Configure whether this server send its messages to another live server in the scale-down cluster when it is shutdown cleanly.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.scale-down-cluster-name:: 
Name of the cluster used to scale down.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.scale-down-connectors:: 
List of connectors used to form the scale-down cluster.

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.scale-down-discovery-group:: 
Name of the discovery group used to build the scale-down cluster

swarm.messaging.servers._KEY_.shared-store-colocated-ha-policy.slave-configuration.scale-down-group-name:: 
Name of the group used to scale down.

swarm.messaging.servers._KEY_.shared-store-master-ha-policy.failover-on-server-shutdown:: 
Whether the server must failover when it is normally shutdown.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.allow-failback:: 
Whether a server will automatically stop when a another places a request to take over its place. The use case is when a regular server stops and its backup takes over its duties, later the main server restarts and requests the server (the former backup) to stop operating.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.failover-on-server-shutdown:: 
Whether the server must failover when it is normally shutdown.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.restart-backup:: 
Will this server, if a backup, restart once it has been stopped because of failback or scaling down.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.scale-down:: 
Configure whether this server send its messages to another live server in the scale-down cluster when it is shutdown cleanly.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.scale-down-cluster-name:: 
Name of the cluster used to scale down.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.scale-down-connectors:: 
List of connectors used to form the scale-down cluster.

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.scale-down-discovery-group:: 
Name of the discovery group used to build the scale-down cluster

swarm.messaging.servers._KEY_.shared-store-slave-ha-policy.scale-down-group-name:: 
Name of the group used to scale down.

swarm.messaging.servers._KEY_.started:: 
Whether this server is started.

swarm.messaging.servers._KEY_.statistics-enabled:: 
Whether gathering of statistics such as message counters are enabled.

swarm.messaging.servers._KEY_.thread-pool-max-size:: 
The number of threads that the main thread pool has. -1 means no limit.

swarm.messaging.servers._KEY_.transaction-timeout:: 
How long (in ms) before a transaction can be removed from the resource manager after create time.

swarm.messaging.servers._KEY_.transaction-timeout-scan-period:: 
How often (in ms) to scan for timeout transactions.

swarm.messaging.servers._KEY_.version:: 
The server's version.

swarm.messaging.servers._KEY_.wild-card-routing-enabled:: 
Whether the server supports wild card routing.


