= Modcluster


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>mod_cluster</artifactId>
</dependency>
----

.Configuration

swarm.modcluster.configuration-mod-cluster-config.advertise:: 
Use Advertise logic or not.

swarm.modcluster.configuration-mod-cluster-config.advertise-security-key:: 
String containing the security key for the Advertise logic.

swarm.modcluster.configuration-mod-cluster-config.advertise-socket:: 
Name of Socket binding to use for the Advertise socket.

swarm.modcluster.configuration-mod-cluster-config.auto-enable-contexts:: 
Enable contexts even if disabled in mod_cluster_manager (httpd).

swarm.modcluster.configuration-mod-cluster-config.balancer:: 
The balancer name.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.custom-load-metrics._KEY_.attribute-class:: 
Class name of the custom metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.custom-load-metrics._KEY_.capacity:: 
Capacity of the metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.custom-load-metrics._KEY_.property:: 
Properties for the metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.custom-load-metrics._KEY_.weight:: 
Weight of the metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.decay:: 
Decay

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.history:: 
History

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.load-metrics._KEY_.capacity:: 
Capacity of the metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.load-metrics._KEY_.property:: 
Properties for the metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.load-metrics._KEY_.type:: 
Type of the metric

swarm.modcluster.configuration-mod-cluster-config.configuration-dynamic-load-provider.load-metrics._KEY_.weight:: 
Weight of the metric.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.ca-certificate-file:: 
Certificate authority.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.ca-revocation-url:: 
Certificate authority revocation list.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.certificate-key-file:: 
Key file for the certificate.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.cipher-suite:: 
The allowed cipher suite.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.key-alias:: 
The key alias.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.password:: 
Password.

swarm.modcluster.configuration-mod-cluster-config.configuration-ssl.protocol:: 
The SSL protocols that are enabled.

swarm.modcluster.configuration-mod-cluster-config.connector:: 
The name of Undertow listener that mod_cluster reverse proxy will connect to.

swarm.modcluster.configuration-mod-cluster-config.excluded-contexts:: 
List of contexts mod_cluster should ignore, Format String separated with commas.

swarm.modcluster.configuration-mod-cluster-config.flush-packets:: 
Enables/disables packet flushing in httpd.

swarm.modcluster.configuration-mod-cluster-config.flush-wait:: 
Time to wait before flushing packets in httpd.

swarm.modcluster.configuration-mod-cluster-config.load-balancing-group:: 
loadBalancingGroup name.

swarm.modcluster.configuration-mod-cluster-config.max-attempts:: 
Max attempts to process an idempotent request.

swarm.modcluster.configuration-mod-cluster-config.node-timeout:: 
Timeout (in seconds) for proxy connections to a node.

swarm.modcluster.configuration-mod-cluster-config.ping:: 
Time (in seconds) in which to wait for a pong answer to a ping.

swarm.modcluster.configuration-mod-cluster-config.proxies:: 
List of proxies for mod_cluster to register with defined by outbound-socket-binding in socket-binding-group.

swarm.modcluster.configuration-mod-cluster-config.proxy-url:: 
Base URL for MCMP requests.

swarm.modcluster.configuration-mod-cluster-config.session-draining-strategy:: 
Session draining strategy used during undeployment of a web application

swarm.modcluster.configuration-mod-cluster-config.simple-load-provider:: 
Simple load provider

swarm.modcluster.configuration-mod-cluster-config.smax:: 
Soft maximum idle connection count in httpd

swarm.modcluster.configuration-mod-cluster-config.socket-timeout:: 
Timeout to wait for httpd to answer a MCMP message.

swarm.modcluster.configuration-mod-cluster-config.status-interval:: 
Number of seconds a STATUS message is sent from the application server to the reverse proxy.

swarm.modcluster.configuration-mod-cluster-config.sticky-session:: 
Use sticky sessions for requests.

swarm.modcluster.configuration-mod-cluster-config.sticky-session-force:: 
Don't failover a request with session information.

swarm.modcluster.configuration-mod-cluster-config.sticky-session-remove:: 
Remove session information on failover.

swarm.modcluster.configuration-mod-cluster-config.stop-context-timeout:: 
Max time to wait for context to process pending requests.

swarm.modcluster.configuration-mod-cluster-config.ttl:: 
Time to live (in seconds) for idle connections above smax

swarm.modcluster.configuration-mod-cluster-config.worker-timeout:: 
Timeout to wait in httpd for an available worker to process the requests.

swarm.modcluster.multicast-address:: 
Multicast address

swarm.modcluster.multicast-port:: 
Multicast port


