# Remoting

Primarily an internal fraction providing remote invocation
support for higher-level fractions such as EJB.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>remoting</artifactId>
</dependency>
----

.Configuration

swarm.remoting.connectors._KEY_.authentication-provider:: 
The "authentication-provider" element contains the name of the authentication provider to use for incoming connections.

swarm.remoting.connectors._KEY_.properties._KEY_.value:: 
The property value.

swarm.remoting.connectors._KEY_.sasl-protocol:: 
The protocol to pass into the SASL mechanisms used for authentication.

swarm.remoting.connectors._KEY_.sasl-security.include-mechanisms:: 
The optional nested "include-mechanisms" element contains a whitelist of allowed SASL mechanism names. No mechanisms will be allowed which are not present in this list.

swarm.remoting.connectors._KEY_.sasl-security.policy-sasl-policy.forward-secrecy:: 
The optional nested "forward-secrecy" element contains a boolean value which specifies whether mechanisms that implement forward secrecy between sessions are required. Forward secrecy means that breaking into one session will not automatically provide information for breaking into future sessions.

swarm.remoting.connectors._KEY_.sasl-security.policy-sasl-policy.no-active:: 
The optional nested "no-active" element contains a boolean value which specifies whether mechanisms susceptible to active (non-dictionary) attacks are not permitted. "false" to permit, "true" to deny.

swarm.remoting.connectors._KEY_.sasl-security.policy-sasl-policy.no-anonymous:: 
The optional nested "no-anonymous" element contains a boolean value which specifies whether mechanisms that accept anonymous login are permitted.  "false" to permit, "true" to deny.

swarm.remoting.connectors._KEY_.sasl-security.policy-sasl-policy.no-dictionary:: 
The optional nested "no-dictionary" element contains a boolean value which specifies whether mechanisms susceptible to passive dictionary attacks are permitted.  "false" to permit, "true" to deny.

swarm.remoting.connectors._KEY_.sasl-security.policy-sasl-policy.no-plain-text:: 
The optional nested "no-plain-text" element contains a boolean value which specifies whether mechanisms susceptible to simple plain passive attacks (e.g., "PLAIN") are not permitted.    "false" to permit, "true" to deny.

swarm.remoting.connectors._KEY_.sasl-security.policy-sasl-policy.pass-credentials:: 
The optional nested "pass-credentials" element contains a boolean value which specifies whether mechanisms that pass client credentials are required.

swarm.remoting.connectors._KEY_.sasl-security.properties._KEY_.value:: 
The property value.

swarm.remoting.connectors._KEY_.sasl-security.qop:: 
The optional nested "qop" element contains a list of quality-of-protection values, in decreasing order of preference.

swarm.remoting.connectors._KEY_.sasl-security.reuse-session:: 
The optional nested "reuse-session" boolean element specifies whether or not the server should attempt to reuse previously authenticated session information.  The mechanism may or may not support such reuse, and other factors may also prevent it.

swarm.remoting.connectors._KEY_.sasl-security.server-auth:: 
The optional nested "server-auth" boolean element specifies whether the server should authenticate to the client.  Not all mechanisms may support this setting.

swarm.remoting.connectors._KEY_.sasl-security.strength:: 
The optional nested "strength" element contains a list of cipher strength values, in decreasing order of preference.

swarm.remoting.connectors._KEY_.security-realm:: 
The associated security realm to use for authentication for this connector.

swarm.remoting.connectors._KEY_.server-name:: 
The server name to send in the initial message exchange and for SASL based authentication.

swarm.remoting.connectors._KEY_.socket-binding:: 
The name (or names) of the socket binding(s) to attach to.

swarm.remoting.endpoint-configuration.auth-realm:: 
The authentication realm to use if no authentication {@code CallbackHandler} is specified.

swarm.remoting.endpoint-configuration.authentication-retries:: 
Specify the number of times a client is allowed to retry authentication before closing the connection.

swarm.remoting.endpoint-configuration.authorize-id:: 
The SASL authorization ID.  Used as authentication user name to use if no authentication {@code CallbackHandler} is specifiedand the selected SASL mechanism demands a user name.

swarm.remoting.endpoint-configuration.buffer-region-size:: 
The size of allocated buffer regions.

swarm.remoting.endpoint-configuration.heartbeat-interval:: 
The interval to use for connection heartbeat, in milliseconds.  If the connection is idle in the outbound directionfor this amount of time, a ping message will be sent, which will trigger a corresponding reply message.

swarm.remoting.endpoint-configuration.max-inbound-channels:: 
The maximum number of concurrent inbound messages on a channel.

swarm.remoting.endpoint-configuration.max-inbound-message-size:: 
The maximum inbound message size to be allowed.  Messages exceeding this size will cause an exception to be thrown on the reading side as well as the writing side.

swarm.remoting.endpoint-configuration.max-inbound-messages:: 
The maximum number of inbound channels to support for a connection.

swarm.remoting.endpoint-configuration.max-outbound-channels:: 
The maximum number of concurrent outbound messages on a channel.

swarm.remoting.endpoint-configuration.max-outbound-message-size:: 
The maximum outbound message size to send.  No messages larger than this well be transmitted; attempting to do so will cause an exception on the writing side.

swarm.remoting.endpoint-configuration.max-outbound-messages:: 
The maximum number of outbound channels to support for a connection.

swarm.remoting.endpoint-configuration.receive-buffer-size:: 
The size of the largest buffer that this endpoint will accept over a connection.

swarm.remoting.endpoint-configuration.receive-window-size:: 
The maximum window size of the receive direction for connection channels, in bytes.

swarm.remoting.endpoint-configuration.sasl-protocol:: 
Where a SaslServer or SaslClient are created by default the protocol specified it 'remoting', this can be used to override this.

swarm.remoting.endpoint-configuration.send-buffer-size:: 
The size of the largest buffer that this endpoint will transmit over a connection.

swarm.remoting.endpoint-configuration.server-name:: 
The server side of the connection passes it's name to the client in the initial greeting, by default the name is automatically discovered from the local address of the connection or it can be overridden using this.

swarm.remoting.endpoint-configuration.transmit-window-size:: 
The maximum window size of the transmit direction for connection channels, in bytes.

swarm.remoting.endpoint-configuration.worker:: 
Worker to use

swarm.remoting.http-connectors._KEY_.authentication-provider:: 
The "authentication-provider" element contains the name of the authentication provider to use for incoming connections.

swarm.remoting.http-connectors._KEY_.connector-ref:: 
The name (or names) of a connector in the Undertow subsystem to connect to.

swarm.remoting.http-connectors._KEY_.properties._KEY_.value:: 
The property value.

swarm.remoting.http-connectors._KEY_.sasl-protocol:: 
The protocol to pass into the SASL mechanisms used for authentication.

swarm.remoting.http-connectors._KEY_.sasl-security.include-mechanisms:: 
The optional nested "include-mechanisms" element contains a whitelist of allowed SASL mechanism names. No mechanisms will be allowed which are not present in this list.

swarm.remoting.http-connectors._KEY_.sasl-security.policy-sasl-policy.forward-secrecy:: 
The optional nested "forward-secrecy" element contains a boolean value which specifies whether mechanisms that implement forward secrecy between sessions are required. Forward secrecy means that breaking into one session will not automatically provide information for breaking into future sessions.

swarm.remoting.http-connectors._KEY_.sasl-security.policy-sasl-policy.no-active:: 
The optional nested "no-active" element contains a boolean value which specifies whether mechanisms susceptible to active (non-dictionary) attacks are not permitted. "false" to permit, "true" to deny.

swarm.remoting.http-connectors._KEY_.sasl-security.policy-sasl-policy.no-anonymous:: 
The optional nested "no-anonymous" element contains a boolean value which specifies whether mechanisms that accept anonymous login are permitted.  "false" to permit, "true" to deny.

swarm.remoting.http-connectors._KEY_.sasl-security.policy-sasl-policy.no-dictionary:: 
The optional nested "no-dictionary" element contains a boolean value which specifies whether mechanisms susceptible to passive dictionary attacks are permitted.  "false" to permit, "true" to deny.

swarm.remoting.http-connectors._KEY_.sasl-security.policy-sasl-policy.no-plain-text:: 
The optional nested "no-plain-text" element contains a boolean value which specifies whether mechanisms susceptible to simple plain passive attacks (e.g., "PLAIN") are not permitted.    "false" to permit, "true" to deny.

swarm.remoting.http-connectors._KEY_.sasl-security.policy-sasl-policy.pass-credentials:: 
The optional nested "pass-credentials" element contains a boolean value which specifies whether mechanisms that pass client credentials are required.

swarm.remoting.http-connectors._KEY_.sasl-security.properties._KEY_.value:: 
The property value.

swarm.remoting.http-connectors._KEY_.sasl-security.qop:: 
The optional nested "qop" element contains a list of quality-of-protection values, in decreasing order of preference.

swarm.remoting.http-connectors._KEY_.sasl-security.reuse-session:: 
The optional nested "reuse-session" boolean element specifies whether or not the server should attempt to reuse previously authenticated session information.  The mechanism may or may not support such reuse, and other factors may also prevent it.

swarm.remoting.http-connectors._KEY_.sasl-security.server-auth:: 
The optional nested "server-auth" boolean element specifies whether the server should authenticate to the client.  Not all mechanisms may support this setting.

swarm.remoting.http-connectors._KEY_.sasl-security.strength:: 
The optional nested "strength" element contains a list of cipher strength values, in decreasing order of preference.

swarm.remoting.http-connectors._KEY_.security-realm:: 
The associated security realm to use for authentication for this connector.

swarm.remoting.http-connectors._KEY_.server-name:: 
The server name to send in the initial message exchange and for SASL based authentication.

swarm.remoting.local-outbound-connections._KEY_.outbound-socket-binding-ref:: 
Name of the outbound-socket-binding which will be used to determine the destination address and port for the connection.

swarm.remoting.local-outbound-connections._KEY_.properties._KEY_.value:: 
The property value.

swarm.remoting.outbound-connections._KEY_.properties._KEY_.value:: 
The property value.

swarm.remoting.outbound-connections._KEY_.uri:: 
The connection URI for the outbound connection.

swarm.remoting.port:: 
Port for legacy remoting connector

swarm.remoting.remote-outbound-connections._KEY_.outbound-socket-binding-ref:: 
Name of the outbound-socket-binding which will be used to determine the destination address and port for the connection.

swarm.remoting.remote-outbound-connections._KEY_.properties._KEY_.value:: 
The property value.

swarm.remoting.remote-outbound-connections._KEY_.protocol:: 
The protocol to use for the remote connection. Defaults to http-remoting.

swarm.remoting.remote-outbound-connections._KEY_.security-realm:: 
Reference to the security realm to use to obtain the password and SSL configuration.

swarm.remoting.remote-outbound-connections._KEY_.username:: 
The user name to use when authenticating against the remote server.

swarm.remoting.required:: 
(not yet documented)


