= Teiid


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>teiid</artifactId>
</dependency>
----

.Configuration

swarm.teiid.active-session-count:: 
Number of active sessions in the system

swarm.teiid.allow-env-function:: 
Allow the execution of ENV function. (default false)

swarm.teiid.async-thread-pool:: 
Thread Pool to be used with Asynchronous operations in Teiid

swarm.teiid.async-thread-pool-max-thread-count:: 
Maximum number of threads for asynchronous processing

swarm.teiid.authentication-allow-security-domain-qualifier:: 
Allow user names to be qualified with @security-domain.

swarm.teiid.authentication-max-sessions-allowed:: 
Maximum number of sessions allowed by the system (default 10000)

swarm.teiid.authentication-security-domain:: 
Security domain to be enforced with the transport

swarm.teiid.authentication-sessions-expiration-timelimit:: 
Max allowed time in milliseconds before the session is terminated by the system, 0 indicates unlimited (default 0)

swarm.teiid.authentication-trust-all-local:: 
Allow all local pass-through connections regardless of whether they are in the configured security domain.

swarm.teiid.authentication-type:: 
Default authentication type to use with this transport. Allowed values are (USERPASSWORD, GSS)  

swarm.teiid.authorization-validator-module:: 
Authorization Module; Implementation of org.teiid.dqp.internal.process.AuthorizationValidator class.

swarm.teiid.buffer-service-encrypt-files:: 
Set to true to encrypt temporary data files with 128-bit AES. (default false)

swarm.teiid.buffer-service-inline-lobs:: 
Set to true to allow inlining of memory based and small lobs into results. However inline lob values are not supported by pre-7.6 clients, so disable this property if using older clients utilizing lobs. (default true)	

swarm.teiid.buffer-service-max-buffer-space:: 
Max storage space, in MB, to be used for buffer files (default 50G)

swarm.teiid.buffer-service-max-file-size:: 
Max File size in MB (default 2GB)

swarm.teiid.buffer-service-max-open-files:: 
Max open buffer files (default 64)

swarm.teiid.buffer-service-max-processing-kb:: 
The approximate amount of buffer memory in kilobytes allowable for a single processing operation (sort, grouping, etc.) regardless of existing memory commitments. -1 means to automatically calculate a value (default -1)

swarm.teiid.buffer-service-max-reserve-kb:: 
The approximate amount of memory in kilobytes allowed to be held by the buffer manager. -1 means to automatically calculate a value (default -1)

swarm.teiid.buffer-service-max-storage-object-size:: 
The maximum size of a buffer managed object (typically a table page or a results batch) in bytes (default 8388608 or 8MB). Setting this value too high will reduce the effectiveness of the memory buffer.

swarm.teiid.buffer-service-memory-buffer-off-heap:: 
Set to true to hold the memory buffer off-heap. If true you must ensure that the VM can allocate that much direct memory (default false).

swarm.teiid.buffer-service-memory-buffer-space:: 
Memory buffer space used by the buffer manager in MB.  -1 determines the setting automatically from the max-reserve-kb (default -1). This value cannot be smaller than max-storage-object-size

swarm.teiid.buffer-service-processor-batch-size:: 
The nominal row count of a batch sent internally within the query processor.  The actual batch size used will depend upon the data width as well. (default 256)

swarm.teiid.buffer-service-use-disk:: 
Use disk for buffer management

swarm.teiid.data-roles-required:: 
WorkManager name to use in processing. (default name is "default")

swarm.teiid.detect-change-events:: 
Set to true for the engine to detect local change events. Should be disabled if using external change data capture tools. (default true)

swarm.teiid.distributed-cache-jgroups-stack:: 
JGroups stack name for cache replication channel

swarm.teiid.exception-on-max-source-rows:: 
Indicates if an exception should be thrown if the specified value for Maximum Source Rows is exceeded; only up to the maximum rows will be consumed. (default true)

swarm.teiid.is-jdbc-transport-installed:: 
(not yet documented)

swarm.teiid.jdbc.port:: 
Set the port for the default JDBC socket listener

swarm.teiid.lob-chunk-size-in-kb:: 
The max lob chunk size in KB transferred each time when processing blobs, clobs (100KB default)

swarm.teiid.max-active-plans:: 
Max active plans (default 20).  Increase this value on highly concurrent systems - but ensure that the underlying pools can handle the increased load without timeouts.

swarm.teiid.max-row-fetch-size:: 
Maximum allowed fetch size, set via JDBC. User requested value ignored above this value. (default 20480)

swarm.teiid.max-source-rows-allowed:: 
Maximum rows allowed from a source query. -1 indicates no limit. (default -1)

swarm.teiid.max-threads:: 
Process pool maximum thread count. (default 64)

swarm.teiid.odbc.port:: 
Set the port for the default ODBC socket listener

swarm.teiid.policy-decider-module:: 
Policy Module; Implementation of org.teiid.PolicyDecider class 

swarm.teiid.preparedplan-cache-enable:: 
Prepared Plan cache enabled (default true)

swarm.teiid.preparedplan-cache-infinispan-container:: 
Infinispan cache container name

swarm.teiid.preparedplan-cache-name:: 
Infinispan cache name for prepared plans

swarm.teiid.preparser-module:: 
Incoming SQL can be modified by an "org.teiid.PreParser"

swarm.teiid.query-threshold-in-seconds:: 
Long running query threshold, after which a alert can be generated by tooling if configured

swarm.teiid.query-timeout:: 
Set the default query timeout for all queries in milliseconds. 0 indicates no timeout.  Lesser timeout values may be set per VDB or by clients. (default 0)

swarm.teiid.resultset-cache-enable:: 
Resultset cache enabled (default true)

swarm.teiid.resultset-cache-infinispan-container:: 
Infinispan cache container name

swarm.teiid.resultset-cache-max-staleness:: 
Max staleness in seconds.  Modifications are based upon data updates -1 indicates no max. (default 60 - 1 minute)

swarm.teiid.resultset-cache-name:: 
Infinispan cache name for resultset; if not specified default cache on infinispan container is used.

swarm.teiid.runtime-version:: 
Teiid Runtime Version

swarm.teiid.thread-count-for-source-concurrency:: 
Max source query concurrency per user request (default 0).  0 indicates use the default calculated value based on max active plans and max threads - approximately 2*(max threads)/(max active plans).   

swarm.teiid.time-slice-in-milliseconds:: 
Query processor time slice, in milliseconds. (default 2000)

swarm.teiid.translators._KEY_.module:: 
Name of the module that implements the translator

swarm.teiid.translators._KEY_.slot:: 
Name of the module slot that implements the translator

swarm.teiid.transports._KEY_.input-buffer-size:: 
SO_RCVBUF size, 0 indicates that system default should be used (default 0)

swarm.teiid.transports._KEY_.keystore-key-alias:: 
key alias name

swarm.teiid.transports._KEY_.keystore-key-password:: 
key password

swarm.teiid.transports._KEY_.keystore-name:: 
Keystore file name

swarm.teiid.transports._KEY_.keystore-password:: 
Keystore password

swarm.teiid.transports._KEY_.keystore-type:: 
Keystore type

swarm.teiid.transports._KEY_.max-socket-threads:: 
Max number of threads dedicated to initial request processing. Zero indicates the system default of max available processors. (default 0)  Setting this value above the max available processors is not recommended.

swarm.teiid.transports._KEY_.output-buffer-size:: 
SO_SNDBUF size, 0 indicates that system default should be used (default 0)

swarm.teiid.transports._KEY_.pg-max-lob-size-in-bytes:: 
Max LOB size in Postgres protocol, as streaming is not supported

swarm.teiid.transports._KEY_.protocol:: 
Transport protocol (allowed=teiid, pg) 

swarm.teiid.transports._KEY_.socket-binding:: 
Socket binding to be used for the transport

swarm.teiid.transports._KEY_.ssl-authentication-mode:: 
Authentication Mode (1-way, 2-way, anonymous)             

swarm.teiid.transports._KEY_.ssl-enabled-cipher-suites:: 
Comma separated cipher suites that are allowed to be used for SSL. Use to restrict encryption strength(128 bit, 256 bit). Only provide encryption suites that are supported by the server JVM. ex:SSL_RSA_WITH_RC4_128_MD5, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_KRB5_WITH_RC4_128_MD5, TLS_KRB5_WITH_RC4_128_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_KRB5_WITH_3DES_EDE_CBC_MD5, TLS_KRB5_WITH_3DES_EDE_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA

swarm.teiid.transports._KEY_.ssl-keymanagement-algorithm:: 
Use key management algorithm

swarm.teiid.transports._KEY_.ssl-mode:: 
can be one of disabled, login, or enabled disabled = no transport or message level security will be used; login = only the login traffic will be encrypted at a message level using 128 bit AES with an ephemerial DH key exchange. No other config values are needed in this mode; and it only applies to the JDBC transport enabled = traffic will be secured using this configuration, if the client supports SSL

swarm.teiid.transports._KEY_.ssl-ssl-protocol:: 
SSL protocol used

swarm.teiid.transports._KEY_.truststore-check-expired:: 
Truststore check expired

swarm.teiid.transports._KEY_.truststore-name:: 
Truststore file name

swarm.teiid.transports._KEY_.truststore-password:: 
Truststore password

swarm.teiid.workmanager:: 
WorkManager name to use in processing. (default name is "default")


