= Web Services


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>webservices</artifactId>
</dependency>
----

.Configuration

swarm.web-services.client-configs._KEY_.post-handler-chains._KEY_.handlers._KEY_.attribute-class:: 
Handler class

swarm.web-services.client-configs._KEY_.post-handler-chains._KEY_.protocol-bindings:: 
Protocol binding

swarm.web-services.client-configs._KEY_.pre-handler-chains._KEY_.handlers._KEY_.attribute-class:: 
Handler class

swarm.web-services.client-configs._KEY_.pre-handler-chains._KEY_.protocol-bindings:: 
Protocol binding

swarm.web-services.client-configs._KEY_.properties._KEY_.value:: 
Endpoint configuration property value

swarm.web-services.endpoint-configs._KEY_.post-handler-chains._KEY_.handlers._KEY_.attribute-class:: 
Handler class

swarm.web-services.endpoint-configs._KEY_.post-handler-chains._KEY_.protocol-bindings:: 
Protocol binding

swarm.web-services.endpoint-configs._KEY_.pre-handler-chains._KEY_.handlers._KEY_.attribute-class:: 
Handler class

swarm.web-services.endpoint-configs._KEY_.pre-handler-chains._KEY_.protocol-bindings:: 
Protocol binding

swarm.web-services.endpoint-configs._KEY_.properties._KEY_.value:: 
Endpoint configuration property value

swarm.web-services.modify-wsdl-address:: 
Whether the soap address can be modified.

swarm.web-services.statistics-enabled:: 
Whether statistics are to be gathered for endpoints, default value is 'false'.

swarm.web-services.wsdl-host:: 
The WSDL, that is a required deployment artifact for an endpoint, has a <soap:address> element which points to the location of the endpoint. JBoss supports rewriting of that SOAP address. If the content of <soap:address> is a valid URL, JBossWS will not rewrite it unless 'modify-wsdl-address' is true. If the content of <soap:address> is not a valid URL, JBossWS will rewrite it using the attribute values given below. If 'wsdl-host' is set to 'jbossws.undefined.host', JBossWS uses requesters host when rewriting the <soap:address>

swarm.web-services.wsdl-path-rewrite-rule:: 
This string defines a SED substitution command (e.g., 's/regexp/replacement/g') that JBossWS executes against the path component of each <soap:address> URL published from the server. When wsdl-path-rewrite-rule is not defined, JBossWS retains the original path component of each <soap:address> URL. When 'modify-wsdl-address' is set to "false" this element is ignored.

swarm.web-services.wsdl-port:: 
The non-secure port that will be used for rewriting the SOAP address. If absent the port will be identified by querying the list of installed connectors.

swarm.web-services.wsdl-secure-port:: 
The secure port that will be used for rewriting the SOAP address. If absent the port will be identified by querying the list of installed connectors.

swarm.web-services.wsdl-uri-scheme:: 
The URI scheme to use for rewriting <soap:address> . Valid values are 'http' and 'https'. This configuration overrides scheme computed by processing the endpoint (even if a transport guarantee is specified). The provided values for 'wsdl-port' and 'wsdl-secure-port' (or their default values) are used depending on specified scheme.


