= ${mission} - ${runtime} Booster

IMPORTANT: While you can run and interact with this booster on our local host, you cannot take advantage of using ConfigMap with this booster without using OpenShift. For more details on using this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:${guideURL}[${runtime} Runtime Guide].

== Run this Booster Locally
To run this booster on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ ${gitCMD}

$ cd ${targetRepository}

$ ${localRunCMD}
----

== Interact with this Booster Locally
To interact with your booster while its running, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----

== Run this Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:

. Log in and create your project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME
----

. Add a policy for the project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc policy add-role-to-user view -n $(oc project -q) -z default
----

. Navigate to the root directory of your booster.

. Deploy your ConfigMap configuration using `${configmapFileName}`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=${configmapFileName}
----

. Deploy your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ ${OSORunCMD}
----



== Interact with this Booster on a Single-node OpenShift Cluster

To interact with your booster while it's running on a Single-node Openshift Cluster, you first need to obtain it's URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route ${app-name} -o jsonpath={$.spec.host}

${app-name}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME
----


You can use the form at your application's url or you can use the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://${app-name}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting
{"content":"Hello World from a ConfigMap!"}

$ curl http://${app-name}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting?name=Sarah
{"content":"Hello Sarah from a ConfigMap!"}
----

== CI/CD Deployment
As part of the process of creating this booster, launch.openshift.io set up a project with a CI/CD deployment of this booster. You can see the status of this deployment in your Single-node OpenShift Cluster Web Console. You can also learn more about this booster and rest of the ${runtime} runtime in the link:${guideURL}[${runtime} Runtime Guide].