= ${mission} - ${runtime} Example Application

IMPORTANT: While you can run and interact with this example application on localhost, you cannot take advantage of using the health check functionality with this example application without using OpenShift. For more details on using this example application with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:${guideURL}[${runtime} Runtime Guide].

${prerequisite}

${cicdSection}

== Running the Example Application Locally
To run this example application on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ ${gitCMD}

$ cd ${targetRepository}

$ ${localRunCMD}
----

== Interacting with the Example Application Locally
To interact with your example application while it is running, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----

== Running the Example Application on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, installed and running, you can also deploy your example application there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your example application to a running single-node OpenShift cluster:

. Log in and create your project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

$ ${OSORunCMD}
----


== Interacting with the Example Application on a Single-node OpenShift Cluster

To interact with your example application while it is running on a Single-node OpenShift Cluster, you first need to obtain its URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route ${value-name-app} -o jsonpath={$.spec.host}

${value-name-app}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME
----


You can use the form at your application's URL or you can use the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://${value-name-app}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting
{"content":"Hello World!"}

$ curl http://${value-name-app}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting?name=Sarah
{"content":"Hello Sarah!"}

$ curl http://${value-name-app}-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/stop

$ oc get pods -w
NAME                           READY     STATUS    RESTARTS   AGE
${value-name-app}-1-26iy7   1/1       Running   5          18m
----

When `READY` changes to `0/1`, if you re-execute a `curl` command to `api/greeting` or attempt to access the application's URL, it will be unavailable. When `READY` changes back to `1/1`, `curl` commands and the application URL will be available again.

== More Information
You can learn more about this example application and rest of the ${runtime} runtime in the link:${guideURL}[${runtime} Runtime Guide].

${integrationTestSection}
