= IO

Primarily an internal fraction supporting I/O activities
for higher-level fractions.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>io</artifactId>
</dependency>
----

.Configuration

swarm.io.buffer-pools._KEY_.buffer-size:: 
The size of each buffer slice in bytes, if not set optimal value is calculated based on available RAM resources in your system.

swarm.io.buffer-pools._KEY_.buffers-per-slice:: 
How many buffers per slice, if not set optimal value is calculated based on available RAM resources in your system.

swarm.io.buffer-pools._KEY_.direct-buffers:: 
Does the buffer pool use direct buffers, some platforms don't support direct buffers

swarm.io.workers._KEY_.core-pool-size:: 
Minimum number of threads to keep in the underlying java.util.concurrent.ThreadPoolExecutor even if they are idle. Threads over this limit will be terminated over time specified by task-keepalive attribute.

swarm.io.workers._KEY_.io-thread-count:: 
I/O thread count

swarm.io.workers._KEY_.io-threads:: 
Specify the number of I/O threads to create for the worker.  If not specified, a default will be chosen, which is calculated by cpuCount * 2

swarm.io.workers._KEY_.max-pool-size:: 
The maximum number of threads to allow in the thread pool. Depending on implementation, when this limit is reached, tasks which cannot be queued may be rejected.

swarm.io.workers._KEY_.outbound-bind-address._KEY_.bind-address:: 
The address to bind to when the destination address matches

swarm.io.workers._KEY_.outbound-bind-address._KEY_.bind-port:: 
The port number to bind to when the destination address matches

swarm.io.workers._KEY_.outbound-bind-address._KEY_.match:: 
The destination address range to match

swarm.io.workers._KEY_.queue-size:: 
An estimate of the number of tasks in the worker queue.

swarm.io.workers._KEY_.servers._KEY_.connection-count:: 
Estimate of the current connection count

swarm.io.workers._KEY_.servers._KEY_.connection-limit-high-water-mark:: 
If the connection count hits this number, no new connections will be accepted until the count drops below the low-water mark.

swarm.io.workers._KEY_.servers._KEY_.connection-limit-low-water-mark:: 
If the connection count has previously hit the high water mark, once it drops back down below this count, connections will be accepted again.

swarm.io.workers._KEY_.shutdown-requested:: 
True is shutdown of the pool was requested

swarm.io.workers._KEY_.stack-size:: 
The stack size (in bytes) to attempt to use for worker threads.

swarm.io.workers._KEY_.task-keepalive:: 
Specify the number of milliseconds to keep non-core task threads alive.

swarm.io.workers._KEY_.task-max-threads:: 
Specify the maximum number of threads for the worker task thread pool.If not set, default value used which is calculated by formula cpuCount * 16,as long as MaxFileDescriptorCount jmx property allows that number, otherwise calculation takes max into account to adjust it accordingly.


