= JCA

Provides support for the Java Connector Architecture (JCA)
according to JSR 322.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>jca</artifactId>
</dependency>
----

.Configuration

thorntail.jca.archive-validation.enabled:: 
Specify whether archive validation is enabled

thorntail.jca.archive-validation.fail-on-error:: 
Should an archive validation error report fail the deployment

thorntail.jca.archive-validation.fail-on-warn:: 
Should an archive validation warning report fail the deployment

thorntail.jca.bean-validation.enabled:: 
Specify whether bean validation is enabled

thorntail.jca.bootstrap-contexts._KEY_.name:: 
The name of the BootstrapContext

thorntail.jca.bootstrap-contexts._KEY_.workmanager:: 
The WorkManager instance for the BootstrapContext

thorntail.jca.cached-connection-manager.debug:: 
Enable/disable debug information logging

thorntail.jca.cached-connection-manager.error:: 
Enable/disable error information logging

thorntail.jca.cached-connection-manager.ignore-unknown-connections:: 
Do not cache unknown connections

thorntail.jca.cached-connection-manager.install:: 
Enable/disable the cached connection manager valve and interceptor

thorntail.jca.distributed-workmanagers._KEY_.elytron-enabled:: 
Enables Elytron security for this workmanager.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.allow-core-timeout:: 
Whether core threads may time out.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.core-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.current-thread-count:: 
The current number of threads in the pool.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.handoff-executor:: 
An executor to delegate tasks to in the event that a task cannot be accepted. If not specified, tasks that cannot be accepted will be silently discarded.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.keepalive-time:: 
Used to specify the amount of time that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.largest-thread-count:: 
The largest number of threads that have ever simultaneously been in the pool.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.max-threads:: 
The maximum thread pool size.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.name:: 
The name of the thread pool.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.queue-length:: 
The queue length.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.queue-size:: 
The queue size.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.rejected-count:: 
The number of tasks that have been passed to the handoff-executor (if one is specified) or discarded.

thorntail.jca.distributed-workmanagers._KEY_.long-running-threads._KEY_.thread-factory:: 
Specifies the name of a specific thread factory to use to create worker threads. If not defined an appropriate default thread factory will be used.

thorntail.jca.distributed-workmanagers._KEY_.name:: 
The name of the DistributedWorkManager

thorntail.jca.distributed-workmanagers._KEY_.policy:: 
The policy decides when to redistribute a Work instance

thorntail.jca.distributed-workmanagers._KEY_.policy-options:: 
List of policy's options key/value pairs

thorntail.jca.distributed-workmanagers._KEY_.selector:: 
The selector decides to which nodes in the network to redistribute the Work instance to

thorntail.jca.distributed-workmanagers._KEY_.selector-options:: 
List of selector's options key/value pairs

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.allow-core-timeout:: 
Whether core threads may time out.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.core-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.current-thread-count:: 
The current number of threads in the pool.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.handoff-executor:: 
An executor to delegate tasks to in the event that a task cannot be accepted. If not specified, tasks that cannot be accepted will be silently discarded.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.keepalive-time:: 
Used to specify the amount of time that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.largest-thread-count:: 
The largest number of threads that have ever simultaneously been in the pool.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.max-threads:: 
The maximum thread pool size.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.name:: 
The name of the thread pool.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.queue-length:: 
The queue length.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.queue-size:: 
The queue size.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.rejected-count:: 
The number of tasks that have been passed to the handoff-executor (if one is specified) or discarded.

thorntail.jca.distributed-workmanagers._KEY_.short-running-threads._KEY_.thread-factory:: 
Specifies the name of a specific thread factory to use to create worker threads. If not defined an appropriate default thread factory will be used.

thorntail.jca.tracer.enabled:: 
Specify whether tracer is enabled

thorntail.jca.workmanagers._KEY_.elytron-enabled:: 
Enables Elytron security for this workmanager.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.allow-core-timeout:: 
Whether core threads may time out.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.core-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.current-thread-count:: 
The current number of threads in the pool.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.handoff-executor:: 
An executor to delegate tasks to in the event that a task cannot be accepted. If not specified, tasks that cannot be accepted will be silently discarded.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.keepalive-time:: 
Used to specify the amount of time that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.largest-thread-count:: 
The largest number of threads that have ever simultaneously been in the pool.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.max-threads:: 
The maximum thread pool size.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.name:: 
The name of the thread pool.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.queue-length:: 
The queue length.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.queue-size:: 
The queue size.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.rejected-count:: 
The number of tasks that have been passed to the handoff-executor (if one is specified) or discarded.

thorntail.jca.workmanagers._KEY_.long-running-threads._KEY_.thread-factory:: 
Specifies the name of a specific thread factory to use to create worker threads. If not defined an appropriate default thread factory will be used.

thorntail.jca.workmanagers._KEY_.name:: 
The name of the WorkManager

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.allow-core-timeout:: 
Whether core threads may time out.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.core-threads:: 
The core thread pool size which is smaller than the maximum pool size. If undefined, the core thread pool size is the same as the maximum thread pool size.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.current-thread-count:: 
The current number of threads in the pool.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.handoff-executor:: 
An executor to delegate tasks to in the event that a task cannot be accepted. If not specified, tasks that cannot be accepted will be silently discarded.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.keepalive-time:: 
Used to specify the amount of time that pool threads should be kept running when idle; if not specified, threads will run until the executor is shut down.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.largest-thread-count:: 
The largest number of threads that have ever simultaneously been in the pool.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.max-threads:: 
The maximum thread pool size.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.name:: 
The name of the thread pool.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.queue-length:: 
The queue length.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.queue-size:: 
The queue size.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.rejected-count:: 
The number of tasks that have been passed to the handoff-executor (if one is specified) or discarded.

thorntail.jca.workmanagers._KEY_.short-running-threads._KEY_.thread-factory:: 
Specifies the name of a specific thread factory to use to create worker threads. If not defined an appropriate default thread factory will be used.


