= Keycloak


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>keycloak</artifactId>
</dependency>
----

.Configuration

thorntail.keycloak.json.path:: 
Path to Keycloak adapter configuration

thorntail.keycloak.multitenancy.paths:: 
Map of the relative request paths to Keycloak adapter configuration locations

thorntail.keycloak.realms._KEY_.allow-any-hostname:: 
SSL Setting

thorntail.keycloak.realms._KEY_.always-refresh-token:: 
Refresh token on every single web request

thorntail.keycloak.realms._KEY_.auth-server-url:: 
Base URL of the Realm Auth Server

thorntail.keycloak.realms._KEY_.auth-server-url-for-backend-requests:: 
URL to use to make background calls to auth server

thorntail.keycloak.realms._KEY_.autodetect-bearer-only:: 
autodetect bearer-only requests

thorntail.keycloak.realms._KEY_.client-key-password:: 
n/a

thorntail.keycloak.realms._KEY_.client-keystore:: 
n/a

thorntail.keycloak.realms._KEY_.client-keystore-password:: 
n/a

thorntail.keycloak.realms._KEY_.confidential-port:: 
Specify the confidential port (SSL/TLS) used by the Realm Auth Server

thorntail.keycloak.realms._KEY_.connection-pool-size:: 
Connection pool size for the client used by the adapter

thorntail.keycloak.realms._KEY_.cors-allowed-headers:: 
CORS allowed headers

thorntail.keycloak.realms._KEY_.cors-allowed-methods:: 
CORS allowed methods

thorntail.keycloak.realms._KEY_.cors-exposed-headers:: 
CORS exposed headers

thorntail.keycloak.realms._KEY_.cors-max-age:: 
CORS max-age header

thorntail.keycloak.realms._KEY_.disable-trust-manager:: 
Adapter will not use a trust manager when making adapter HTTPS requests

thorntail.keycloak.realms._KEY_.enable-cors:: 
Enable Keycloak CORS support

thorntail.keycloak.realms._KEY_.expose-token:: 
Enable secure URL that exposes access token

thorntail.keycloak.realms._KEY_.ignore-oauth-query-parameter:: 
disable query parameter parsing for access_token

thorntail.keycloak.realms._KEY_.principal-attribute:: 
token attribute to use to set Principal name

thorntail.keycloak.realms._KEY_.proxy-url:: 
The URL for the HTTP proxy if one is used.

thorntail.keycloak.realms._KEY_.realm-public-key:: 
Public key of the realm

thorntail.keycloak.realms._KEY_.register-node-at-startup:: 
Cluster setting

thorntail.keycloak.realms._KEY_.register-node-period:: 
how often to re-register node

thorntail.keycloak.realms._KEY_.ssl-required:: 
Specify if SSL is required (valid values are all, external and none)

thorntail.keycloak.realms._KEY_.token-store:: 
cookie or session storage for auth session data

thorntail.keycloak.realms._KEY_.truststore:: 
Truststore used for adapter client HTTPS requests

thorntail.keycloak.realms._KEY_.truststore-password:: 
Password of the Truststore

thorntail.keycloak.realms._KEY_.verify-token-audience:: 
If true, then during bearer-only authentication, the adapter will verify if token contains this client name (resource) as an audience

thorntail.keycloak.secure-deployments._KEY_.adapter-state-cookie-path:: 
If set, defines the path used in cookies set by the adapter. Useful when deploying the application in the root context path.

thorntail.keycloak.secure-deployments._KEY_.allow-any-hostname:: 
SSL Setting

thorntail.keycloak.secure-deployments._KEY_.always-refresh-token:: 
Refresh token on every single web request

thorntail.keycloak.secure-deployments._KEY_.auth-server-url:: 
Base URL of the Realm Auth Server

thorntail.keycloak.secure-deployments._KEY_.auth-server-url-for-backend-requests:: 
URL to use to make background calls to auth server

thorntail.keycloak.secure-deployments._KEY_.autodetect-bearer-only:: 
autodetect bearer-only requests

thorntail.keycloak.secure-deployments._KEY_.bearer-only:: 
Bearer Token Auth only

thorntail.keycloak.secure-deployments._KEY_.client-key-password:: 
n/a

thorntail.keycloak.secure-deployments._KEY_.client-keystore:: 
n/a

thorntail.keycloak.secure-deployments._KEY_.client-keystore-password:: 
n/a

thorntail.keycloak.secure-deployments._KEY_.confidential-port:: 
Specify the confidential port (SSL/TLS) used by the Realm Auth Server

thorntail.keycloak.secure-deployments._KEY_.connection-pool-size:: 
Connection pool size for the client used by the adapter

thorntail.keycloak.secure-deployments._KEY_.cors-allowed-headers:: 
CORS allowed headers

thorntail.keycloak.secure-deployments._KEY_.cors-allowed-methods:: 
CORS allowed methods

thorntail.keycloak.secure-deployments._KEY_.cors-exposed-headers:: 
CORS exposed headers

thorntail.keycloak.secure-deployments._KEY_.cors-max-age:: 
CORS max-age header

thorntail.keycloak.secure-deployments._KEY_.credentials._KEY_.value:: 
Credential value

thorntail.keycloak.secure-deployments._KEY_.disable-trust-manager:: 
Adapter will not use a trust manager when making adapter HTTPS requests

thorntail.keycloak.secure-deployments._KEY_.enable-basic-auth:: 
Enable Basic Authentication

thorntail.keycloak.secure-deployments._KEY_.enable-cors:: 
Enable Keycloak CORS support

thorntail.keycloak.secure-deployments._KEY_.expose-token:: 
Enable secure URL that exposes access token

thorntail.keycloak.secure-deployments._KEY_.ignore-oauth-query-parameter:: 
disable query parameter parsing for access_token

thorntail.keycloak.secure-deployments._KEY_.min-time-between-jwks-requests:: 
If adapter recognize token signed by unknown public key, it will try to download new public key from keycloak server. However it won't try to download if already tried it in less than 'min-time-between-jwks-requests' seconds

thorntail.keycloak.secure-deployments._KEY_.principal-attribute:: 
token attribute to use to set Principal name

thorntail.keycloak.secure-deployments._KEY_.proxy-url:: 
The URL for the HTTP proxy if one is used.

thorntail.keycloak.secure-deployments._KEY_.public-client:: 
Public client

thorntail.keycloak.secure-deployments._KEY_.public-key-cache-ttl:: 
Maximum time the downloaded public keys are considered valid. When this time reach, the adapter is forced to download public keys from keycloak server

thorntail.keycloak.secure-deployments._KEY_.realm:: 
Keycloak realm

thorntail.keycloak.secure-deployments._KEY_.realm-public-key:: 
Public key of the realm

thorntail.keycloak.secure-deployments._KEY_.redirect-rewrite-rules._KEY_.value:: 
redirect-rewrite-rule value

thorntail.keycloak.secure-deployments._KEY_.register-node-at-startup:: 
Cluster setting

thorntail.keycloak.secure-deployments._KEY_.register-node-period:: 
how often to re-register node

thorntail.keycloak.secure-deployments._KEY_.resource:: 
Application name

thorntail.keycloak.secure-deployments._KEY_.ssl-required:: 
Specify if SSL is required (valid values are all, external and none)

thorntail.keycloak.secure-deployments._KEY_.token-minimum-time-to-live:: 
The adapter will refresh the token if the current token is expired OR will expire in 'token-minimum-time-to-live' seconds or less

thorntail.keycloak.secure-deployments._KEY_.token-store:: 
cookie or session storage for auth session data

thorntail.keycloak.secure-deployments._KEY_.truststore:: 
Truststore used for adapter client HTTPS requests

thorntail.keycloak.secure-deployments._KEY_.truststore-password:: 
Password of the Truststore

thorntail.keycloak.secure-deployments._KEY_.turn-off-change-session-id-on-login:: 
The session id is changed by default on a successful login.  Change this to true if you want to turn this off

thorntail.keycloak.secure-deployments._KEY_.use-resource-role-mappings:: 
Use resource level permissions from token

thorntail.keycloak.secure-deployments._KEY_.verify-token-audience:: 
If true, then during bearer-only authentication, the adapter will verify if token contains this client name (resource) as an audience

thorntail.keycloak.secure-servers._KEY_.adapter-state-cookie-path:: 
If set, defines the path used in cookies set by the adapter. Useful when deploying the application in the root context path.

thorntail.keycloak.secure-servers._KEY_.allow-any-hostname:: 
SSL Setting

thorntail.keycloak.secure-servers._KEY_.always-refresh-token:: 
Refresh token on every single web request

thorntail.keycloak.secure-servers._KEY_.auth-server-url:: 
Base URL of the Realm Auth Server

thorntail.keycloak.secure-servers._KEY_.auth-server-url-for-backend-requests:: 
URL to use to make background calls to auth server

thorntail.keycloak.secure-servers._KEY_.autodetect-bearer-only:: 
autodetect bearer-only requests

thorntail.keycloak.secure-servers._KEY_.bearer-only:: 
Bearer Token Auth only

thorntail.keycloak.secure-servers._KEY_.client-key-password:: 
n/a

thorntail.keycloak.secure-servers._KEY_.client-keystore:: 
n/a

thorntail.keycloak.secure-servers._KEY_.client-keystore-password:: 
n/a

thorntail.keycloak.secure-servers._KEY_.confidential-port:: 
Specify the confidential port (SSL/TLS) used by the Realm Auth Server

thorntail.keycloak.secure-servers._KEY_.connection-pool-size:: 
Connection pool size for the client used by the adapter

thorntail.keycloak.secure-servers._KEY_.cors-allowed-headers:: 
CORS allowed headers

thorntail.keycloak.secure-servers._KEY_.cors-allowed-methods:: 
CORS allowed methods

thorntail.keycloak.secure-servers._KEY_.cors-exposed-headers:: 
CORS exposed headers

thorntail.keycloak.secure-servers._KEY_.cors-max-age:: 
CORS max-age header

thorntail.keycloak.secure-servers._KEY_.credentials._KEY_.value:: 
Credential value

thorntail.keycloak.secure-servers._KEY_.disable-trust-manager:: 
Adapter will not use a trust manager when making adapter HTTPS requests

thorntail.keycloak.secure-servers._KEY_.enable-basic-auth:: 
Enable Basic Authentication

thorntail.keycloak.secure-servers._KEY_.enable-cors:: 
Enable Keycloak CORS support

thorntail.keycloak.secure-servers._KEY_.expose-token:: 
Enable secure URL that exposes access token

thorntail.keycloak.secure-servers._KEY_.ignore-oauth-query-parameter:: 
disable query parameter parsing for access_token

thorntail.keycloak.secure-servers._KEY_.min-time-between-jwks-requests:: 
If adapter recognize token signed by unknown public key, it will try to download new public key from keycloak server. However it won't try to download if already tried it in less than 'min-time-between-jwks-requests' seconds

thorntail.keycloak.secure-servers._KEY_.principal-attribute:: 
token attribute to use to set Principal name

thorntail.keycloak.secure-servers._KEY_.proxy-url:: 
The URL for the HTTP proxy if one is used.

thorntail.keycloak.secure-servers._KEY_.public-client:: 
Public client

thorntail.keycloak.secure-servers._KEY_.public-key-cache-ttl:: 
Maximum time the downloaded public keys are considered valid. When this time reach, the adapter is forced to download public keys from keycloak server

thorntail.keycloak.secure-servers._KEY_.realm:: 
Keycloak realm

thorntail.keycloak.secure-servers._KEY_.realm-public-key:: 
Public key of the realm

thorntail.keycloak.secure-servers._KEY_.redirect-rewrite-rules._KEY_.value:: 
redirect-rewrite-rule value

thorntail.keycloak.secure-servers._KEY_.register-node-at-startup:: 
Cluster setting

thorntail.keycloak.secure-servers._KEY_.register-node-period:: 
how often to re-register node

thorntail.keycloak.secure-servers._KEY_.resource:: 
Application name

thorntail.keycloak.secure-servers._KEY_.ssl-required:: 
Specify if SSL is required (valid values are all, external and none)

thorntail.keycloak.secure-servers._KEY_.token-minimum-time-to-live:: 
The adapter will refresh the token if the current token is expired OR will expire in 'token-minimum-time-to-live' seconds or less

thorntail.keycloak.secure-servers._KEY_.token-store:: 
cookie or session storage for auth session data

thorntail.keycloak.secure-servers._KEY_.truststore:: 
Truststore used for adapter client HTTPS requests

thorntail.keycloak.secure-servers._KEY_.truststore-password:: 
Password of the Truststore

thorntail.keycloak.secure-servers._KEY_.turn-off-change-session-id-on-login:: 
The session id is changed by default on a successful login.  Change this to true if you want to turn this off

thorntail.keycloak.secure-servers._KEY_.use-resource-role-mappings:: 
Use resource level permissions from token

thorntail.keycloak.secure-servers._KEY_.verify-token-audience:: 
If true, then during bearer-only authentication, the adapter will verify if token contains this client name (resource) as an audience


