= MicroProfile JWT RBAC Auth


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>microprofile-jwt</artifactId>
</dependency>
----

.Configuration

thorntail.microprofile.jwt.default-missing-method-permissions-deny-access:: 
If a JAX-RS resource has no class-level security metadata, then if this property is set to `true` and at least one resource method has security metadata all other resource methods without security metadata have an implicit `@DenyAll`, otherwise resource methods without security metadata are not secured

thorntail.microprofile.jwt.token.exp-grace-period:: 
The JWT token expiration grace period in seconds 

thorntail.microprofile.jwt.token.issued-by:: 
The URI of the JWT token issuer

thorntail.microprofile.jwt.token.jwks-refresh-interval:: 
The interval at which the JWKS URI should be queried for keys (in minutes).

thorntail.microprofile.jwt.token.jwks-uri:: 
The JWKS URI from which to load public keys (if 'signer-pub-key' is set, this setting is ignored).

thorntail.microprofile.jwt.token.signer-pub-key:: 
The public key of the JWT token signer. Can be prefixed 'file:' or 'classpath:' for key assets, otherwise the key contents are expected


