= Transactions

Provides support for the Java Transaction API (JTA) according to 
JSR-907.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>transactions</artifactId>
</dependency>
----

.Configuration

swarm.transactions.average-commit-time:: 
The average time of transaction commit in nanoseconds, measured from the moment the client calls commit until the transaction manager determines that the commit attempt was successful.

swarm.transactions.commit-markable-resources._KEY_.batch-size:: 
Batch size for this CMR resource

swarm.transactions.commit-markable-resources._KEY_.immediate-cleanup:: 
Immediate cleanup associated to this CMR resource

swarm.transactions.commit-markable-resources._KEY_.jndi-name:: 
JNDi name of this CMR resource

swarm.transactions.commit-markable-resources._KEY_.name:: 
table name for storing XIDs

swarm.transactions.default-timeout:: 
The default timeout for a transaction managed by the transaction manager.

swarm.transactions.enable-statistics:: 
Whether transaction statistics should be gathered.

swarm.transactions.enable-tsm-status:: 
Whether the transaction status manager (TSM) service, needed for out of process recovery, should be provided or not.

swarm.transactions.hornetq-store-enable-async-io:: 
Whether AsyncIO should be enabled for the journal store.

swarm.transactions.jdbc-action-store-drop-table:: 
Configure if jdbc action store should drop tables.

swarm.transactions.jdbc-action-store-table-prefix:: 
Optional prefix for table used to write transaction logs in configured jdbc action store.

swarm.transactions.jdbc-communication-store-drop-table:: 
Configure if jdbc communication store should drop tables.

swarm.transactions.jdbc-communication-store-table-prefix:: 
Optional prefix for table used to write transaction logs in configured jdbc communication store.

swarm.transactions.jdbc-state-store-drop-table:: 
Configure if jdbc state store should drop tables.

swarm.transactions.jdbc-state-store-table-prefix:: 
Optional prefix for table used to write transaction logs in configured jdbc state store.

swarm.transactions.jdbc-store-datasource:: 
Jndi name of non-XA datasource used. Datasource sghould be define in datasources subsystem. For this would work the non-XA datasource has to be marked as jta="false".

swarm.transactions.journal-store-enable-async-io:: 
Whether AsyncIO should be enabled for the journal store. For this settings being active journal natives libraries needs to be available.

swarm.transactions.jts:: 
If true this enables the Java Transaction Service. Use of the JTS needs configuration in IIOP OpenJDK where Transactions parameter needs to be set to full.

swarm.transactions.log-store.expose-all-logs:: 
Whether to expose all logs like orphans etc. By default only a subset of transaction logs is exposed.

swarm.transactions.log-store.transactions._KEY_.age-in-seconds:: 
The time since this transaction was prepared or when the recovery system last tried to recover it.

swarm.transactions.log-store.transactions._KEY_.id:: 
The id of this transaction.

swarm.transactions.log-store.transactions._KEY_.jmx-name:: 
The JMX name of this transaction.

swarm.transactions.log-store.transactions._KEY_.participants._KEY_.eis-product-name:: 
The JCA enterprise information system's product name.

swarm.transactions.log-store.transactions._KEY_.participants._KEY_.eis-product-version:: 
The JCA enterprise information system's product version

swarm.transactions.log-store.transactions._KEY_.participants._KEY_.jmx-name:: 
The JMX name of this participant.

swarm.transactions.log-store.transactions._KEY_.participants._KEY_.jndi-name:: 
JNDI name of this participant.

swarm.transactions.log-store.transactions._KEY_.participants._KEY_.status:: 
Reports the commitment status of this participant (can be one of Pending, Prepared, Failed, Heuristic or Readonly).

swarm.transactions.log-store.transactions._KEY_.participants._KEY_.type:: 
The type name under which this record is stored.

swarm.transactions.log-store.transactions._KEY_.type:: 
The type name under which this record is stored.

swarm.transactions.log-store.type:: 
Specifies the implementation type of the logging store.

swarm.transactions.node-identifier:: 
Used to set the node identifier on the core environment. Each Xid that Transaction Manager creates will have this identifier encoded within it and ensures Transaction Manager will only recover branches which match the specified identifier. It is imperative that this identifier is unique between Application Server instances which share either an object store or access common resource managers.

swarm.transactions.number-of-aborted-transactions:: 
The number of aborted (i.e. rolledback) transactions.

swarm.transactions.number-of-application-rollbacks:: 
The number of transactions that have been rolled back by application request. This includes those that timeout, since the timeout behavior is considered an attribute of the application configuration.

swarm.transactions.number-of-committed-transactions:: 
The number of committed transactions.

swarm.transactions.number-of-heuristics:: 
The number of transactions which have terminated with heuristic outcomes.

swarm.transactions.number-of-inflight-transactions:: 
The number of transactions that have begun but not yet terminated.

swarm.transactions.number-of-nested-transactions:: 
The total number of nested (sub) transactions created.

swarm.transactions.number-of-resource-rollbacks:: 
The number of transactions that rolled back due to resource (participant) failure.

swarm.transactions.number-of-system-rollbacks:: 
The number of transactions that have been rolled back due to internal system errors.

swarm.transactions.number-of-timed-out-transactions:: 
The number of transactions that have rolled back due to timeout.

swarm.transactions.number-of-transactions:: 
The total number of transactions (top-level and nested) created

swarm.transactions.object-store-path:: 
Denotes a relative or absolute filesystem path denoting where the transaction manager object store should store data. By default the value is treated as relative to the path denoted by the "relative-to" attribute. This settings is valid when default or journal store is used. It's not used when jdbc journal store is used.

swarm.transactions.object-store-relative-to:: 
References a global path configuration in the domain model, defaulting to the Application Server data directory (jboss.server.data.dir). The value of the "Object store path" attribute will treated as relative to this path. Undefine this attribute to disable the default behavior and force the value of the "Object store path" attribute to be treated as an absolute path.

swarm.transactions.port:: 
Port for transaction manager

swarm.transactions.process-id-socket-binding:: 
The name of the socket binding configuration to use if the transaction manager should use a socket-based process id. Will be 'undefined' if 'process-id-uuid' is 'true'; otherwise must be set.

swarm.transactions.process-id-socket-max-ports:: 
The maximum number of ports to search for an open port if the transaction manager should use a socket-based process id. If the port specified by the socket binding referenced in 'process-id-socket-binding' is occupied, the next higher port will be tried until an open port is found or the number of ports specified by this attribute have been tried. Will be 'undefined' if 'process-id-uuid' is 'true'.

swarm.transactions.process-id-uuid:: 
Indicates whether the transaction manager should use a UUID based process id.

swarm.transactions.recovery-listener:: 
Used to specify if the recovery system should listen on a network socket or not.

swarm.transactions.socket-binding:: 
Used to reference the correct socket binding to use for the recovery environment.

swarm.transactions.statistics-enabled:: 
Whether transaction statistics should be gathered.

swarm.transactions.status-port:: 
Status port for transaction manager

swarm.transactions.status-socket-binding:: 
Used to reference the correct socket binding to use for the transaction status manager.

swarm.transactions.use-hornetq-store:: 
Use the journal store for writing transaction logs. Set to true to enable and to false to use the default log store type. The default log store is normally one file system file per transaction log.It's alternative to jdbc based store.

swarm.transactions.use-jdbc-store:: 
Use the jdbc store for writing transaction logs. Set to true to enable and to false to use the default log store type. The default log store is normally one file file per transaction log. It's alternative to journal based store.

swarm.transactions.use-journal-store:: 
Use the journal store for writing transaction logs. Set to true to enable and to false to use the default log store type. The default log store creates normally one file system file per transaction log. The journal one consists from one file for all the transactions. It's alternative to jdbc based store.


