= Undertow

Provides basic HTTP support, including Java Servlets, JavaServer Pages (JSP),
and JavaServer Pages Standard Tag Library (JSTL) according to JSR-340, JSR-245
and JSR-52.


.Maven Coordinates
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>undertow</artifactId>
</dependency>
----

.Configuration

swarm.ajp.enable:: 
Determine if AJP should be enabled

swarm.ajp.port:: 
Set the port for the default AJP listener

swarm.deployment:: 
Map of security configuration by deployment

swarm.http.port:: 
Set the port for the default HTTP listener

swarm.https.certificate.generate:: 
Should a self-signed certificate be generated

swarm.https.certificate.generate.host:: 
Hostname for the generated self-signed certificate

swarm.https.key.alias:: 
Alias to the server certificate key entry in the keystore

swarm.https.key.password:: 
Password to the server certificate

swarm.https.keystore.embedded:: 
Should an embedded keystore be created

swarm.https.keystore.password:: 
Password to the server keystore

swarm.https.keystore.path:: 
Path to the server keystore

swarm.https.only:: 
Only enable the HTTPS  Listener

swarm.https.port:: 
Set the port for the default HTTPS listener

swarm.undertow.application-security-domains._KEY_.enable-jacc:: 
Enable authorization using JACC

swarm.undertow.application-security-domains._KEY_.http-authentication-factory:: 
The HTTP Authentication Factory to be used by deployments that reference the mapped security domain.

swarm.undertow.application-security-domains._KEY_.override-deployment-config:: 
Should the authentication configuration in the deployment be overridden by the factory.

swarm.undertow.application-security-domains._KEY_.referencing-deployments:: 
The deployments currently referencing this mapping.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.client-ssl-context:: 
Reference to the SSL context used to secure back-channel logout connection.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.cookie-name:: 
Name of the cookie

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.credential-reference:: 
The credential reference to decrypt the private key entry.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.domain:: 
The cookie domain that will be used.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.http-only:: 
Set Cookie httpOnly attribute.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.key-alias:: 
Alias of the private key entry used for signing and verifying back-channel logout connection.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.key-store:: 
Reference to key store containing a private key entry.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.path:: 
Cookie path.

swarm.undertow.application-security-domains._KEY_.single-sign-on-setting.secure:: 
Set Cookie secure attribute.

swarm.undertow.buffer-caches._KEY_.buffer-size:: 
The size of an individual buffer, in bytes.

swarm.undertow.buffer-caches._KEY_.buffers-per-region:: 
The numbers of buffers in a region

swarm.undertow.buffer-caches._KEY_.max-regions:: 
The maximum number of regions

swarm.undertow.default-security-domain:: 
The default security domain used by web deployments

swarm.undertow.default-server:: 
The default server to use for deployments

swarm.undertow.default-servlet-container:: 
The default servlet container to use for deployments

swarm.undertow.default-virtual-host:: 
The default virtual host to use for deployments

swarm.undertow.filter-configuration.custom-filters._KEY_.class-name:: 
Class name of HttpHandler

swarm.undertow.filter-configuration.custom-filters._KEY_.module:: 
Module name where class can be loaded from

swarm.undertow.filter-configuration.custom-filters._KEY_.parameters:: 
Filter parameters

swarm.undertow.filter-configuration.error-pages._KEY_.code:: 
Error page code

swarm.undertow.filter-configuration.error-pages._KEY_.path:: 
Error page path

swarm.undertow.filter-configuration.expression-filters._KEY_.expression:: 
The expression that defines the filter

swarm.undertow.filter-configuration.expression-filters._KEY_.module:: 
Module to use to load the filter definitions

swarm.undertow.filter-configuration.mod-clusters._KEY_.advertise-frequency:: 
The frequency (in milliseconds) that mod-cluster advertises itself on the network

swarm.undertow.filter-configuration.mod-clusters._KEY_.advertise-path:: 
The path that mod-cluster is registered under.

swarm.undertow.filter-configuration.mod-clusters._KEY_.advertise-protocol:: 
The protocol that is in use.

swarm.undertow.filter-configuration.mod-clusters._KEY_.advertise-socket-binding:: 
The multicast group and port that is used to advertise.

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.max-attempts:: 
The number of attempts to send the request to a backend server

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.aliases:: 
The nodes aliases

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.cache-connections:: 
The number of connections to keep alive indefinitely

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.contexts._KEY_.requests:: 
The number of requests against this context

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.contexts._KEY_.status:: 
The status of this context

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.elected:: 
The elected count

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.flush-packets:: 
If received data should be immediately flushed

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.load:: 
The current load of this node

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.load-balancing-group:: 
The load balancing group this node belongs to

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.max-connections:: 
The maximum number of connections per IO thread

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.open-connections:: 
The current number of open connections

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.ping:: 
The nodes ping

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.queue-new-requests:: 
If a request is received and there is no worker immediately available should it be queued

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.read:: 
The number of bytes read from the node

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.request-queue-size:: 
The size of the request queue

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.status:: 
The current status of this node

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.timeout:: 
The request timeout

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.ttl:: 
The time connections will stay alive with no requests before being closed, if the number of connections is larger than cache-connections

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.uri:: 
The URI that the load balancer uses to connect to the node

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.nodes._KEY_.written:: 
The number of bytes transferred to the node

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.sticky-session:: 
If sticky sessions are enabled

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.sticky-session-cookie:: 
The session cookie name

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.sticky-session-force:: 
If this is true then an error will be returned if the request cannot be routed to the sticky node, otherwise it will be routed to another node

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.sticky-session-path:: 
The path of the sticky session cookie

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.sticky-session-remove:: 
Remove the session cookie if the request cannot be routed to the correct host

swarm.undertow.filter-configuration.mod-clusters._KEY_.balancers._KEY_.wait-worker:: 
The number of seconds to wait for an available worker

swarm.undertow.filter-configuration.mod-clusters._KEY_.broken-node-timeout:: 
The amount of time that must elapse before a broken node is removed from the table

swarm.undertow.filter-configuration.mod-clusters._KEY_.cached-connections-per-thread:: 
The number of connections that will be kept alive indefinitely

swarm.undertow.filter-configuration.mod-clusters._KEY_.connection-idle-timeout:: 
The amount of time a connection can be idle before it will be closed. Connections will not time out once the pool size is down to the configured minimum (as configured by cached-connections-per-thread)

swarm.undertow.filter-configuration.mod-clusters._KEY_.connections-per-thread:: 
The number of connections that will be maintained to backend servers, per IO thread.

swarm.undertow.filter-configuration.mod-clusters._KEY_.enable-http2:: 
If the load balancer should attempt to upgrade back end connections to HTTP2. If HTTP2 is not supported HTTP or HTTPS will be used as normal

swarm.undertow.filter-configuration.mod-clusters._KEY_.failover-strategy:: 
Determines how a failover node is chosen, in the event that the node to which a session has affinity is not available.

swarm.undertow.filter-configuration.mod-clusters._KEY_.health-check-interval:: 
The frequency of health check pings to backend nodes

swarm.undertow.filter-configuration.mod-clusters._KEY_.http2-enable-push:: 
If push should be enabled for HTTP/2 connections

swarm.undertow.filter-configuration.mod-clusters._KEY_.http2-header-table-size:: 
The size of the header table used for HPACK compression, in bytes. This amount of memory will be allocated per connection for compression. Larger values use more memory but may give better compression.

swarm.undertow.filter-configuration.mod-clusters._KEY_.http2-initial-window-size:: 
The flow control window size that controls how quickly the client can send data to the server

swarm.undertow.filter-configuration.mod-clusters._KEY_.http2-max-concurrent-streams:: 
The maximum number of HTTP/2 streams that can be active at any time on a single connection

swarm.undertow.filter-configuration.mod-clusters._KEY_.http2-max-frame-size:: 
The max HTTP/2 frame size

swarm.undertow.filter-configuration.mod-clusters._KEY_.http2-max-header-list-size:: 
The maximum size of request headers the server is prepared to accept

swarm.undertow.filter-configuration.mod-clusters._KEY_.management-access-predicate:: 
A predicate that is applied to incoming requests to determine if they can perform mod cluster management commands. Provides additional security on top of what is provided by limiting management to requests that originate from the management-socket-binding

swarm.undertow.filter-configuration.mod-clusters._KEY_.management-socket-binding:: 
The socket binding of the mod_cluster management address and port. When using mod_cluster two HTTP listeners should be defined, a public one to handle requests, and one bound to the internal network to handle mod cluster commands. This socket binding should correspond to the internal listener, and should not be publicly accessible.

swarm.undertow.filter-configuration.mod-clusters._KEY_.max-ajp-packet-size:: 
The maximum size for AJP packets. Increasing this will allow AJP to work for requests/responses that have a large amount of headers. This is an advanced option, and must be the same between load balancers and backend servers.

swarm.undertow.filter-configuration.mod-clusters._KEY_.max-request-time:: 
The max amount of time that a request to a backend node can take before it is killed

swarm.undertow.filter-configuration.mod-clusters._KEY_.max-retries:: 
The number of times to attempt to retry a request if it fails. Note that if a request is not considered idempotent then it will only be retried if the proxy can be sure it was not sent to the backend server).

swarm.undertow.filter-configuration.mod-clusters._KEY_.request-queue-size:: 
The number of requests that can be queued if the connection pool is full before requests are rejected with a 503

swarm.undertow.filter-configuration.mod-clusters._KEY_.security-key:: 
The security key that is used for the mod-cluster group. All members must use the same security key.

swarm.undertow.filter-configuration.mod-clusters._KEY_.security-realm:: 
The security realm that provides the SSL configuration

swarm.undertow.filter-configuration.mod-clusters._KEY_.ssl-context:: 
Reference to the SSLContext to be used by this filter.

swarm.undertow.filter-configuration.mod-clusters._KEY_.use-alias:: 
If an alias check is performed

swarm.undertow.filter-configuration.mod-clusters._KEY_.worker:: 
The XNIO worker that is used to send the advertise notifications

swarm.undertow.filter-configuration.request-limits._KEY_.max-concurrent-requests:: 
Maximum number of concurrent requests

swarm.undertow.filter-configuration.request-limits._KEY_.queue-size:: 
Number of requests to queue before they start being rejected

swarm.undertow.filter-configuration.response-headers._KEY_.header-name:: 
Header name

swarm.undertow.filter-configuration.response-headers._KEY_.header-value:: 
Value for header

swarm.undertow.filter-configuration.rewrites._KEY_.redirect:: 
If this is true then a redirect will be done instead of a rewrite

swarm.undertow.filter-configuration.rewrites._KEY_.target:: 
The expression that defines the target. If you are redirecting to a constant target put single quotes around the value

swarm.undertow.handler-configuration.files._KEY_.cache-buffer-size:: 
Size of the buffers, in bytes.

swarm.undertow.handler-configuration.files._KEY_.cache-buffers:: 
Number of buffers

swarm.undertow.handler-configuration.files._KEY_.case-sensitive:: 
Use case sensitive file handling

swarm.undertow.handler-configuration.files._KEY_.directory-listing:: 
Enable directory listing?

swarm.undertow.handler-configuration.files._KEY_.follow-symlink:: 
Enable following symbolic links

swarm.undertow.handler-configuration.files._KEY_.path:: 
Path on filesystem from where file handler will serve resources

swarm.undertow.handler-configuration.files._KEY_.safe-symlink-paths:: 
Paths that are safe to be targets of symbolic links

swarm.undertow.handler-configuration.reverse-proxies._KEY_.cached-connections-per-thread:: 
The number of connections that will be kept alive indefinitely

swarm.undertow.handler-configuration.reverse-proxies._KEY_.connection-idle-timeout:: 
The amount of time a connection can be idle before it will be closed. Connections will not time out once the pool size is down to the configured minimum (as configured by cached-connections-per-thread)

swarm.undertow.handler-configuration.reverse-proxies._KEY_.connections-per-thread:: 
The number of connections that will be maintained to backend servers, per IO thread.

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.enable-http2:: 
If this is true then the proxy will attempt to use HTTP/2 to connect to the backend. If it is not supported it will fall back to HTTP/1.1/

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.instance-id:: 
The instance id (aka JVM route) that will be used to enable sticky sessions

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.outbound-socket-binding:: 
Outbound socket binding for this host

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.path:: 
Optional path if host is using non root resource

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.scheme:: 
What kind of scheme is used

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.security-realm:: 
The security realm that provides the SSL configuration for the connection to the host

swarm.undertow.handler-configuration.reverse-proxies._KEY_.hosts._KEY_.ssl-context:: 
Reference to the SSLContext to be used by this handler.

swarm.undertow.handler-configuration.reverse-proxies._KEY_.max-request-time:: 
The maximum time that a proxy request can be active for, before being killed

swarm.undertow.handler-configuration.reverse-proxies._KEY_.max-retries:: 
The number of times to attempt to retry a request if it fails. Note that if a request is not considered idempotent then it will only be retried if the proxy can be sure it was not sent to the backend server).

swarm.undertow.handler-configuration.reverse-proxies._KEY_.problem-server-retry:: 
Time in seconds to wait before attempting to reconnect to a server that is down

swarm.undertow.handler-configuration.reverse-proxies._KEY_.request-queue-size:: 
The number of requests that can be queued if the connection pool is full before requests are rejected with a 503

swarm.undertow.handler-configuration.reverse-proxies._KEY_.session-cookie-names:: 
Comma separated list of session cookie names. Generally this will just be JSESSIONID.

swarm.undertow.instance-id:: 
The cluster instance id

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.allow-encoded-slash:: 
If a request comes in with encoded / characters (i.e. %2F), will these be decoded.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.allow-equals-in-cookie-value:: 
If this is true then Undertow will allow non-escaped equals characters in unquoted cookie values. Unquoted cookie values may not contain equals characters. If present the value ends before the equals sign. The remainder of the cookie value will be dropped.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.always-set-keep-alive:: 
If this is true then a Connection: keep-alive header will be added to responses, even when it is not strictly required by the specification.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.buffer-pipelined-data:: 
If we should buffer pipelined requests.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.buffer-pool:: 
The listeners buffer pool

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.bytes-received:: 
The number of bytes that have been received by this listener

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.bytes-sent:: 
The number of bytes that have been sent out on this listener

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.decode-url:: 
If this is true then the parser will decode the URL and query parameters using the selected character encoding (UTF-8 by default). If this is false they will not be decoded. This will allow a later handler to decode them into whatever charset is desired.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.disallowed-methods:: 
A comma separated list of HTTP methods that are not allowed

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.error-count:: 
The number of 500 responses that have been sent by this listener

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-ajp-packet-size:: 
The maximum supported size of AJP packets. If this is modified it has to be increased on the load balancer and the backend server.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-buffered-request-size:: 
Maximum size of a buffered request, in bytes. Requests are not usually buffered, the most common case is when performing SSL renegotiation for a POST request, and the post data must be fully buffered in order to perform the renegotiation.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-connections:: 
The maximum number of concurrent connections. Only values greater than 0 are allowed. For unlimited connections simply undefine this attribute value.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-cookies:: 
The maximum number of cookies that will be parsed. This is used to protect against hash vulnerabilities.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-header-size:: 
The maximum size of a http request header, in bytes.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-headers:: 
The maximum number of headers that will be parsed. This is used to protect against hash vulnerabilities.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-parameters:: 
The maximum number of parameters that will be parsed. This is used to protect against hash vulnerabilities. This applies to both query parameters, and to POST data, but is not cumulative (i.e. you can potentially have max parameters * 2 total parameters).

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-post-size:: 
The maximum size of a post that will be accepted, in bytes.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.max-processing-time:: 
The maximum processing time taken by a request on this listener

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.no-request-timeout:: 
The length of time in milliseconds that the connection can be idle before it is closed by the container.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.processing-time:: 
The total processing time of all requests handed by this listener

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.read-timeout:: 
Configure a read timeout for a socket, in milliseconds.  If the given amount of time elapses without a successful read taking place, the socket's next read will throw a {@link ReadTimeoutException}.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.receive-buffer:: 
The receive buffer size, in bytes.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.record-request-start-time:: 
If this is true then Undertow will record the request start time, to allow for request time to be logged. This has a small but measurable performance impact

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.redirect-socket:: 
If this listener is supporting non-SSL requests, and a request is received for which a matching <security-constraint> requires SSL transport, undertow will automatically redirect the request to the socket binding port specified here.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.request-count:: 
The number of requests this listener has served

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.request-parse-timeout:: 
The maximum amount of time (in milliseconds) that can be spent parsing the request

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.resolve-peer-address:: 
Enables host dns lookup

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.rfc6265-cookie-validation:: 
If cookies should be validated to ensure they comply with RFC6265.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.scheme:: 
The listener scheme, can be HTTP or HTTPS. By default the scheme will be taken from the incoming AJP request.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.secure:: 
If this is true then requests that originate from this listener are marked as secure, even if the request is not using HTTPS.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.send-buffer:: 
The send buffer size, in bytes.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.socket-binding:: 
The listener socket binding

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.tcp-backlog:: 
Configure a server with the specified backlog.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.tcp-keep-alive:: 
Configure a channel to send TCP keep-alive messages in an implementation-dependent manner.

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.url-charset:: 
URL charset

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.worker:: 
The listeners XNIO worker

swarm.undertow.servers._KEY_.ajp-listeners._KEY_.write-timeout:: 
Configure a write timeout for a socket, in milliseconds.  If the given amount of time elapses without a successful write taking place, the socket's next write will throw a {@link WriteTimeoutException}.

swarm.undertow.servers._KEY_.default-host:: 
The servers default virtual host

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.directory:: 
Directory in which to save logs

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.extended:: 
If the log uses the extended log file format

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.pattern:: 
The access log pattern.

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.predicate:: 
Predicate that determines if the request should be logged

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.prefix:: 
Prefix for the log file name.

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.relative-to:: 
The directory the path is relative to

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.rotate:: 
Rotate the access log every day.

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.suffix:: 
Suffix for the log file name.

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.use-server-log:: 
If the log should be written to the server log, rather than a separate file.

swarm.undertow.servers._KEY_.hosts._KEY_.access-log-setting.worker:: 
Name of the worker to use for logging

swarm.undertow.servers._KEY_.hosts._KEY_.alias:: 
Aliases for the host

swarm.undertow.servers._KEY_.hosts._KEY_.default-response-code:: 
If set, this will be response code sent back in case requested context does not exist on server.

swarm.undertow.servers._KEY_.hosts._KEY_.default-web-module:: 
Default web module

swarm.undertow.servers._KEY_.hosts._KEY_.disable-console-redirect:: 
if set to true, /console redirect wont be enabled for this host, default is false

swarm.undertow.servers._KEY_.hosts._KEY_.filter-refs._KEY_.predicate:: 
Predicates provide a simple way of making a true/false decision  based on an exchange. Many handlers have a requirement that they be applied conditionally, and predicates provide a general way to specify a condition.

swarm.undertow.servers._KEY_.hosts._KEY_.filter-refs._KEY_.priority:: 
Defines filter order, it should be set to 1 or more, higher number instructs server to be included earlier in handler chain than others under same context.

swarm.undertow.servers._KEY_.hosts._KEY_.http-invoker-setting.http-authentication-factory:: 
The HTTP authentication factory to use for authentication

swarm.undertow.servers._KEY_.hosts._KEY_.http-invoker-setting.path:: 
The path that the services are installed under

swarm.undertow.servers._KEY_.hosts._KEY_.http-invoker-setting.security-realm:: 
The legacy security realm to use for authentication

swarm.undertow.servers._KEY_.hosts._KEY_.locations._KEY_.filter-refs._KEY_.predicate:: 
Predicates provide a simple way of making a true/false decision  based on an exchange. Many handlers have a requirement that they be applied conditionally, and predicates provide a general way to specify a condition.

swarm.undertow.servers._KEY_.hosts._KEY_.locations._KEY_.filter-refs._KEY_.priority:: 
Defines filter order, it should be set to 1 or more, higher number instructs server to be included earlier in handler chain than others under same context.

swarm.undertow.servers._KEY_.hosts._KEY_.locations._KEY_.handler:: 
Default handler for this location

swarm.undertow.servers._KEY_.hosts._KEY_.single-sign-on-setting.cookie-name:: 
Name of the cookie

swarm.undertow.servers._KEY_.hosts._KEY_.single-sign-on-setting.domain:: 
The cookie domain that will be used.

swarm.undertow.servers._KEY_.hosts._KEY_.single-sign-on-setting.http-only:: 
Set Cookie httpOnly attribute.

swarm.undertow.servers._KEY_.hosts._KEY_.single-sign-on-setting.path:: 
Cookie path.

swarm.undertow.servers._KEY_.hosts._KEY_.single-sign-on-setting.secure:: 
Set Cookie secure attribute.

swarm.undertow.servers._KEY_.http-listeners._KEY_.allow-encoded-slash:: 
If a request comes in with encoded / characters (i.e. %2F), will these be decoded.

swarm.undertow.servers._KEY_.http-listeners._KEY_.allow-equals-in-cookie-value:: 
If this is true then Undertow will allow non-escaped equals characters in unquoted cookie values. Unquoted cookie values may not contain equals characters. If present the value ends before the equals sign. The remainder of the cookie value will be dropped.

swarm.undertow.servers._KEY_.http-listeners._KEY_.always-set-keep-alive:: 
If this is true then a Connection: keep-alive header will be added to responses, even when it is not strictly required by the specification.

swarm.undertow.servers._KEY_.http-listeners._KEY_.buffer-pipelined-data:: 
If we should buffer pipelined requests.

swarm.undertow.servers._KEY_.http-listeners._KEY_.buffer-pool:: 
The listeners buffer pool

swarm.undertow.servers._KEY_.http-listeners._KEY_.bytes-received:: 
The number of bytes that have been received by this listener

swarm.undertow.servers._KEY_.http-listeners._KEY_.bytes-sent:: 
The number of bytes that have been sent out on this listener

swarm.undertow.servers._KEY_.http-listeners._KEY_.certificate-forwarding:: 
If certificate forwarding should be enabled. If this is enabled then the listener will take the certificate from the SSL_CLIENT_CERT attribute. This should only be enabled if behind a proxy, and the proxy is configured to always set these headers.

swarm.undertow.servers._KEY_.http-listeners._KEY_.decode-url:: 
If this is true then the parser will decode the URL and query parameters using the selected character encoding (UTF-8 by default). If this is false they will not be decoded. This will allow a later handler to decode them into whatever charset is desired.

swarm.undertow.servers._KEY_.http-listeners._KEY_.disallowed-methods:: 
A comma separated list of HTTP methods that are not allowed

swarm.undertow.servers._KEY_.http-listeners._KEY_.enable-http2:: 
Enables HTTP2 support for this listener

swarm.undertow.servers._KEY_.http-listeners._KEY_.error-count:: 
The number of 500 responses that have been sent by this listener

swarm.undertow.servers._KEY_.http-listeners._KEY_.http2-enable-push:: 
If server push is enabled for this connection

swarm.undertow.servers._KEY_.http-listeners._KEY_.http2-header-table-size:: 
The size of the header table used for HPACK compression, in bytes. This amount of memory will be allocated per connection for compression. Larger values use more memory but may give better compression.

swarm.undertow.servers._KEY_.http-listeners._KEY_.http2-initial-window-size:: 
The flow control window size that controls how quickly the client can send data to the server

swarm.undertow.servers._KEY_.http-listeners._KEY_.http2-max-concurrent-streams:: 
The maximum number of HTTP/2 streams that can be active at any time on a single connection

swarm.undertow.servers._KEY_.http-listeners._KEY_.http2-max-frame-size:: 
The max HTTP/2 frame size

swarm.undertow.servers._KEY_.http-listeners._KEY_.http2-max-header-list-size:: 
The maximum size of request headers the server is prepared to accept

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-buffered-request-size:: 
Maximum size of a buffered request, in bytes. Requests are not usually buffered, the most common case is when performing SSL renegotiation for a POST request, and the post data must be fully buffered in order to perform the renegotiation.

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-connections:: 
The maximum number of concurrent connections. Only values greater than 0 are allowed. For unlimited connections simply undefine this attribute value.

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-cookies:: 
The maximum number of cookies that will be parsed. This is used to protect against hash vulnerabilities.

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-header-size:: 
The maximum size of a http request header, in bytes.

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-headers:: 
The maximum number of headers that will be parsed. This is used to protect against hash vulnerabilities.

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-parameters:: 
The maximum number of parameters that will be parsed. This is used to protect against hash vulnerabilities. This applies to both query parameters, and to POST data, but is not cumulative (i.e. you can potentially have max parameters * 2 total parameters).

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-post-size:: 
The maximum size of a post that will be accepted, in bytes.

swarm.undertow.servers._KEY_.http-listeners._KEY_.max-processing-time:: 
The maximum processing time taken by a request on this listener

swarm.undertow.servers._KEY_.http-listeners._KEY_.no-request-timeout:: 
The length of time in milliseconds that the connection can be idle before it is closed by the container.

swarm.undertow.servers._KEY_.http-listeners._KEY_.processing-time:: 
The total processing time of all requests handed by this listener

swarm.undertow.servers._KEY_.http-listeners._KEY_.proxy-address-forwarding:: 
Enables  handling of x-forwarded-host header (and other x-forwarded-* headers) and use this header information to set the remote address. This should only be used behind a trusted proxy that sets these headers otherwise a remote user can spoof their IP address.

swarm.undertow.servers._KEY_.http-listeners._KEY_.read-timeout:: 
Configure a read timeout for a socket, in milliseconds.  If the given amount of time elapses without a successful read taking place, the socket's next read will throw a {@link ReadTimeoutException}.

swarm.undertow.servers._KEY_.http-listeners._KEY_.receive-buffer:: 
The receive buffer size, in bytes.

swarm.undertow.servers._KEY_.http-listeners._KEY_.record-request-start-time:: 
If this is true then Undertow will record the request start time, to allow for request time to be logged. This has a small but measurable performance impact

swarm.undertow.servers._KEY_.http-listeners._KEY_.redirect-socket:: 
If this listener is supporting non-SSL requests, and a request is received for which a matching <security-constraint> requires SSL transport, undertow will automatically redirect the request to the socket binding port specified here.

swarm.undertow.servers._KEY_.http-listeners._KEY_.request-count:: 
The number of requests this listener has served

swarm.undertow.servers._KEY_.http-listeners._KEY_.request-parse-timeout:: 
The maximum amount of time (in milliseconds) that can be spent parsing the request

swarm.undertow.servers._KEY_.http-listeners._KEY_.require-host-http11:: 
Require that all HTTP/1.1 requests have a 'Host' header, as per the RFC. IF the request does not include this header it will be rejected with a 403.

swarm.undertow.servers._KEY_.http-listeners._KEY_.resolve-peer-address:: 
Enables host dns lookup

swarm.undertow.servers._KEY_.http-listeners._KEY_.rfc6265-cookie-validation:: 
If cookies should be validated to ensure they comply with RFC6265.

swarm.undertow.servers._KEY_.http-listeners._KEY_.secure:: 
If this is true then requests that originate from this listener are marked as secure, even if the request is not using HTTPS.

swarm.undertow.servers._KEY_.http-listeners._KEY_.send-buffer:: 
The send buffer size, in bytes.

swarm.undertow.servers._KEY_.http-listeners._KEY_.socket-binding:: 
The listener socket binding

swarm.undertow.servers._KEY_.http-listeners._KEY_.tcp-backlog:: 
Configure a server with the specified backlog.

swarm.undertow.servers._KEY_.http-listeners._KEY_.tcp-keep-alive:: 
Configure a channel to send TCP keep-alive messages in an implementation-dependent manner.

swarm.undertow.servers._KEY_.http-listeners._KEY_.url-charset:: 
URL charset

swarm.undertow.servers._KEY_.http-listeners._KEY_.worker:: 
The listeners XNIO worker

swarm.undertow.servers._KEY_.http-listeners._KEY_.write-timeout:: 
Configure a write timeout for a socket, in milliseconds.  If the given amount of time elapses without a successful write taking place, the socket's next write will throw a {@link WriteTimeoutException}.

swarm.undertow.servers._KEY_.https-listeners._KEY_.allow-encoded-slash:: 
If a request comes in with encoded / characters (i.e. %2F), will these be decoded.

swarm.undertow.servers._KEY_.https-listeners._KEY_.allow-equals-in-cookie-value:: 
If this is true then Undertow will allow non-escaped equals characters in unquoted cookie values. Unquoted cookie values may not contain equals characters. If present the value ends before the equals sign. The remainder of the cookie value will be dropped.

swarm.undertow.servers._KEY_.https-listeners._KEY_.always-set-keep-alive:: 
If this is true then a Connection: keep-alive header will be added to responses, even when it is not strictly required by the specification.

swarm.undertow.servers._KEY_.https-listeners._KEY_.buffer-pipelined-data:: 
If we should buffer pipelined requests.

swarm.undertow.servers._KEY_.https-listeners._KEY_.buffer-pool:: 
The listeners buffer pool

swarm.undertow.servers._KEY_.https-listeners._KEY_.bytes-received:: 
The number of bytes that have been received by this listener

swarm.undertow.servers._KEY_.https-listeners._KEY_.bytes-sent:: 
The number of bytes that have been sent out on this listener

swarm.undertow.servers._KEY_.https-listeners._KEY_.certificate-forwarding:: 
If certificate forwarding should be enabled. If this is enabled then the listener will take the certificate from the SSL_CLIENT_CERT attribute. This should only be enabled if behind a proxy, and the proxy is configured to always set these headers.

swarm.undertow.servers._KEY_.https-listeners._KEY_.decode-url:: 
If this is true then the parser will decode the URL and query parameters using the selected character encoding (UTF-8 by default). If this is false they will not be decoded. This will allow a later handler to decode them into whatever charset is desired.

swarm.undertow.servers._KEY_.https-listeners._KEY_.disallowed-methods:: 
A comma separated list of HTTP methods that are not allowed

swarm.undertow.servers._KEY_.https-listeners._KEY_.enable-http2:: 
Enables HTTP2 support for this listener

swarm.undertow.servers._KEY_.https-listeners._KEY_.enabled-cipher-suites:: 
Configures Enabled SSL ciphers

swarm.undertow.servers._KEY_.https-listeners._KEY_.enabled-protocols:: 
Configures SSL protocols

swarm.undertow.servers._KEY_.https-listeners._KEY_.error-count:: 
The number of 500 responses that have been sent by this listener

swarm.undertow.servers._KEY_.https-listeners._KEY_.http2-enable-push:: 
If server push is enabled for this connection

swarm.undertow.servers._KEY_.https-listeners._KEY_.http2-header-table-size:: 
The size of the header table used for HPACK compression, in bytes. This amount of memory will be allocated per connection for compression. Larger values use more memory but may give better compression.

swarm.undertow.servers._KEY_.https-listeners._KEY_.http2-initial-window-size:: 
The flow control window size that controls how quickly the client can send data to the server

swarm.undertow.servers._KEY_.https-listeners._KEY_.http2-max-concurrent-streams:: 
The maximum number of HTTP/2 streams that can be active at any time on a single connection

swarm.undertow.servers._KEY_.https-listeners._KEY_.http2-max-frame-size:: 
The max HTTP/2 frame size

swarm.undertow.servers._KEY_.https-listeners._KEY_.http2-max-header-list-size:: 
The maximum size of request headers the server is prepared to accept

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-buffered-request-size:: 
Maximum size of a buffered request, in bytes. Requests are not usually buffered, the most common case is when performing SSL renegotiation for a POST request, and the post data must be fully buffered in order to perform the renegotiation.

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-connections:: 
The maximum number of concurrent connections. Only values greater than 0 are allowed. For unlimited connections simply undefine this attribute value.

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-cookies:: 
The maximum number of cookies that will be parsed. This is used to protect against hash vulnerabilities.

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-header-size:: 
The maximum size of a http request header, in bytes.

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-headers:: 
The maximum number of headers that will be parsed. This is used to protect against hash vulnerabilities.

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-parameters:: 
The maximum number of parameters that will be parsed. This is used to protect against hash vulnerabilities. This applies to both query parameters, and to POST data, but is not cumulative (i.e. you can potentially have max parameters * 2 total parameters).

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-post-size:: 
The maximum size of a post that will be accepted, in bytes.

swarm.undertow.servers._KEY_.https-listeners._KEY_.max-processing-time:: 
The maximum processing time taken by a request on this listener

swarm.undertow.servers._KEY_.https-listeners._KEY_.no-request-timeout:: 
The length of time in milliseconds that the connection can be idle before it is closed by the container.

swarm.undertow.servers._KEY_.https-listeners._KEY_.processing-time:: 
The total processing time of all requests handed by this listener

swarm.undertow.servers._KEY_.https-listeners._KEY_.proxy-address-forwarding:: 
Enables  handling of x-forwarded-host header (and other x-forwarded-* headers) and use this header information to set the remote address. This should only be used behind a trusted proxy that sets these headers otherwise a remote user can spoof their IP address.

swarm.undertow.servers._KEY_.https-listeners._KEY_.read-timeout:: 
Configure a read timeout for a socket, in milliseconds.  If the given amount of time elapses without a successful read taking place, the socket's next read will throw a {@link ReadTimeoutException}.

swarm.undertow.servers._KEY_.https-listeners._KEY_.receive-buffer:: 
The receive buffer size, in bytes.

swarm.undertow.servers._KEY_.https-listeners._KEY_.record-request-start-time:: 
If this is true then Undertow will record the request start time, to allow for request time to be logged. This has a small but measurable performance impact

swarm.undertow.servers._KEY_.https-listeners._KEY_.request-count:: 
The number of requests this listener has served

swarm.undertow.servers._KEY_.https-listeners._KEY_.request-parse-timeout:: 
The maximum amount of time (in milliseconds) that can be spent parsing the request

swarm.undertow.servers._KEY_.https-listeners._KEY_.require-host-http11:: 
Require that all HTTP/1.1 requests have a 'Host' header, as per the RFC. IF the request does not include this header it will be rejected with a 403.

swarm.undertow.servers._KEY_.https-listeners._KEY_.resolve-peer-address:: 
Enables host dns lookup

swarm.undertow.servers._KEY_.https-listeners._KEY_.rfc6265-cookie-validation:: 
If cookies should be validated to ensure they comply with RFC6265.

swarm.undertow.servers._KEY_.https-listeners._KEY_.secure:: 
If this is true then requests that originate from this listener are marked as secure, even if the request is not using HTTPS.

swarm.undertow.servers._KEY_.https-listeners._KEY_.security-realm:: 
The listeners security realm

swarm.undertow.servers._KEY_.https-listeners._KEY_.send-buffer:: 
The send buffer size, in bytes.

swarm.undertow.servers._KEY_.https-listeners._KEY_.socket-binding:: 
The listener socket binding

swarm.undertow.servers._KEY_.https-listeners._KEY_.ssl-context:: 
Reference to the SSLContext to be used by this listener.

swarm.undertow.servers._KEY_.https-listeners._KEY_.ssl-session-cache-size:: 
The maximum number of active SSL sessions

swarm.undertow.servers._KEY_.https-listeners._KEY_.ssl-session-timeout:: 
The timeout for SSL sessions, in seconds

swarm.undertow.servers._KEY_.https-listeners._KEY_.tcp-backlog:: 
Configure a server with the specified backlog.

swarm.undertow.servers._KEY_.https-listeners._KEY_.tcp-keep-alive:: 
Configure a channel to send TCP keep-alive messages in an implementation-dependent manner.

swarm.undertow.servers._KEY_.https-listeners._KEY_.url-charset:: 
URL charset

swarm.undertow.servers._KEY_.https-listeners._KEY_.verify-client:: 
The desired SSL client authentication mode for SSL channels

swarm.undertow.servers._KEY_.https-listeners._KEY_.worker:: 
The listeners XNIO worker

swarm.undertow.servers._KEY_.https-listeners._KEY_.write-timeout:: 
Configure a write timeout for a socket, in milliseconds.  If the given amount of time elapses without a successful write taking place, the socket's next write will throw a {@link WriteTimeoutException}.

swarm.undertow.servers._KEY_.servlet-container:: 
The servers default servlet container

swarm.undertow.servlet-containers._KEY_.allow-non-standard-wrappers:: 
If true then request and response wrappers that do not extend the standard wrapper classes can be used

swarm.undertow.servlet-containers._KEY_.crawler-session-management-setting.session-timeout:: 
The session timeout for sessions that are owned by crawlers

swarm.undertow.servlet-containers._KEY_.crawler-session-management-setting.user-agents:: 
Regular expression that is used to match the user agent of a crawler

swarm.undertow.servlet-containers._KEY_.default-buffer-cache:: 
The buffer cache to use for caching static resources

swarm.undertow.servlet-containers._KEY_.default-encoding:: 
Default encoding to use for all deployed applications

swarm.undertow.servlet-containers._KEY_.default-session-timeout:: 
The default session timeout (in minutes) for all applications deployed in the container.

swarm.undertow.servlet-containers._KEY_.directory-listing:: 
If directory listing should be enabled for default servlets.

swarm.undertow.servlet-containers._KEY_.disable-caching-for-secured-pages:: 
If Undertow should set headers to disable caching for secured paged. Disabling this can cause security problems, as sensitive pages may be cached by an intermediary.

swarm.undertow.servlet-containers._KEY_.disable-file-watch-service:: 
If this is true then the file watch service will not be used to monitor exploded deployments for changes

swarm.undertow.servlet-containers._KEY_.disable-session-id-reuse:: 
If this is true then an unknown session ID will never be reused, and a new session id will be generated. If this is false then it will be re-used if and only if it is present in the session manager of another deployment, to allow the same session id to be shared between applications on the same server.

swarm.undertow.servlet-containers._KEY_.eager-filter-initialization:: 
If true undertow calls filter init() on deployment start rather than when first requested.

swarm.undertow.servlet-containers._KEY_.ignore-flush:: 
Ignore flushes on the servlet output stream. In most cases these just hurt performance for no good reason.

swarm.undertow.servlet-containers._KEY_.jsp-setting.check-interval:: 
Check interval for JSP updates using a background thread. This has no effect for most deployments where JSP change notifications are handled using the File System notification API. This only takes effect if the file watch service is disabled.

swarm.undertow.servlet-containers._KEY_.jsp-setting.development:: 
Enable Development mode which enables reloading JSP on-the-fly

swarm.undertow.servlet-containers._KEY_.jsp-setting.disabled:: 
Disable the JSP container.

swarm.undertow.servlet-containers._KEY_.jsp-setting.display-source-fragment:: 
When a runtime error occurs, attempts to display corresponding JSP source fragment

swarm.undertow.servlet-containers._KEY_.jsp-setting.dump-smap:: 
Write SMAP data to a file.

swarm.undertow.servlet-containers._KEY_.jsp-setting.error-on-use-bean-invalid-class-attribute:: 
Enable errors when using a bad class in useBean.

swarm.undertow.servlet-containers._KEY_.jsp-setting.generate-strings-as-char-arrays:: 
Generate String constants as char arrays.

swarm.undertow.servlet-containers._KEY_.jsp-setting.java-encoding:: 
Specify the encoding used for Java sources.

swarm.undertow.servlet-containers._KEY_.jsp-setting.keep-generated:: 
Keep the generated Servlets.

swarm.undertow.servlet-containers._KEY_.jsp-setting.mapped-file:: 
Map to the JSP source.

swarm.undertow.servlet-containers._KEY_.jsp-setting.modification-test-interval:: 
Minimum amount of time between two tests for updates, in seconds.

swarm.undertow.servlet-containers._KEY_.jsp-setting.optimize-scriptlets:: 
If JSP scriptlets should be optimised to remove string concatenation

swarm.undertow.servlet-containers._KEY_.jsp-setting.recompile-on-fail:: 
Retry failed JSP compilations on each request.

swarm.undertow.servlet-containers._KEY_.jsp-setting.scratch-dir:: 
Specify a different work directory.

swarm.undertow.servlet-containers._KEY_.jsp-setting.smap:: 
Enable SMAP.

swarm.undertow.servlet-containers._KEY_.jsp-setting.source-vm:: 
Source VM level for compilation.

swarm.undertow.servlet-containers._KEY_.jsp-setting.tag-pooling:: 
Enable tag pooling.

swarm.undertow.servlet-containers._KEY_.jsp-setting.target-vm:: 
Target VM level for compilation.

swarm.undertow.servlet-containers._KEY_.jsp-setting.trim-spaces:: 
Trim some spaces from the generated Servlet.

swarm.undertow.servlet-containers._KEY_.jsp-setting.xPowered-by:: 
Enable advertising the JSP engine in x-powered-by.

swarm.undertow.servlet-containers._KEY_.max-sessions:: 
The maximum number of sessions that can be active at one time

swarm.undertow.servlet-containers._KEY_.mime-mappings._KEY_.value:: 
The mime type for this mapping

swarm.undertow.servlet-containers._KEY_.persistent-sessions-setting.path:: 
The path to the persistent session data directory. If this is null sessions will be stored in memory

swarm.undertow.servlet-containers._KEY_.persistent-sessions-setting.relative-to:: 
The directory the path is relative to

swarm.undertow.servlet-containers._KEY_.proactive-authentication:: 
If proactive authentication should be used. If this is true a user will always be authenticated if credentials are present.

swarm.undertow.servlet-containers._KEY_.session-cookie-setting.comment:: 
Cookie comment

swarm.undertow.servlet-containers._KEY_.session-cookie-setting.domain:: 
Cookie domain

swarm.undertow.servlet-containers._KEY_.session-cookie-setting.http-only:: 
Is cookie http-only

swarm.undertow.servlet-containers._KEY_.session-cookie-setting.max-age:: 
Max age of cookie

swarm.undertow.servlet-containers._KEY_.session-cookie-setting.name:: 
Name of the cookie

swarm.undertow.servlet-containers._KEY_.session-cookie-setting.secure:: 
Is cookie secure?

swarm.undertow.servlet-containers._KEY_.session-id-length:: 
The length of the generated session ID. Longer session ID's are more secure. This number refers to the number of bytes of randomness that are used to generate the session ID, the actual ID that is sent to the client will be base64 encoded so will be approximately 33% larger (e.g. a session id length of 30 will result in a cookie value of length 40).

swarm.undertow.servlet-containers._KEY_.stack-trace-on-error:: 
If an error page with the stack trace should be generated on error. Values are all, none and local-only

swarm.undertow.servlet-containers._KEY_.use-listener-encoding:: 
Use encoding defined on listener

swarm.undertow.servlet-containers._KEY_.websockets-setting.buffer-pool:: 
The buffer pool to use for websocket deployments

swarm.undertow.servlet-containers._KEY_.websockets-setting.deflater-level:: 
Configures the level of compression of the DEFLATE algorithm

swarm.undertow.servlet-containers._KEY_.websockets-setting.dispatch-to-worker:: 
If callbacks should be dispatched to a worker thread. If this is false then they will be run in the IO thread, which is faster however care must be taken not to perform blocking operations.

swarm.undertow.servlet-containers._KEY_.websockets-setting.per-message-deflate:: 
Enables websocket's per-message compression extension, RFC-7692

swarm.undertow.servlet-containers._KEY_.websockets-setting.worker:: 
The worker to use for websocket deployments

swarm.undertow.statistics-enabled:: 
Configures if statistics are enabled. Changes take effect on the connector level statistics immediately, deployment level statistics will only be affected after the deployment is redeployed (or the container is reloaded).


