node("docsbuilder-maven") {
  checkout scm
  stage("Build Documentation") {
    sh "pwd && ls -l"
    sh "echo :revnumber: \$(git describe --abbrev=0 --tags) >> ./docs/topics/templates/document-attributes.adoc"
    sh "echo :SegmentTrackerToken: \$LAUNCHPAD_TRACKER_SEGMENT_TOKEN >> ./docs/topics/templates/document-attributes.adoc"
    sh "./scripts/buildGuides.sh"
    sh "mkdir -p ci/openshiftio-appdev-docs/src/main/resources/webroot"
    sh "mv ./html/ ./ci/openshiftio-appdev-docs/src/main/resources/webroot/docs"
  }
  stage("Build and Deploy Server") {
    sh "cd ci/openshiftio-appdev-docs && mvn fabric8:deploy -Popenshift"
  }
}
