node("docsbuilder-maven") {
  checkout scm
  stage("Build Documentation") {
    sh "pwd && ls -l"
    sh "./scripts/buildGuides.sh"
    sh "mkdir -p src/main/resources/webroot"
    sh "mv ./html/ ./ci/openshiftio-appdev-docs/src/main/resources/webroot/docs"
  }
  stage("Build and Deploy Server") {
    sh "cd ci/openshiftio-appdev-docs && mvn fabric8:deploy -Popenshift"
  }
}
