= Interacting with the Unmodified {WildFlySwarm} Booster

Once you have the {WildFlySwarm} booster deployed, you have the following services running:

`{app-name}-name`::
Exposes the following endpoints:

* the `/api/name` endpoint, which returns a name when this service is working, and an error when this service is set up to demonstrate failure.

* the `/api/state` endpoint, which controls the behavior of the `/api/name` endpoint and determines whether the service works correctly or demonstrates failure.

`{app-name}-greeting`::
Exposes the following endpoints:

* the `/api/greeting` endpoint that you can call to get a personalized greeting response.
+
When you call the `/api/greeting` endpoint, it issues a call against the `/api/name` endpoint of the `{app-name}-name` service as part of processing your request.
The call made against the `/api/name` endpoint is protected by the Circuit Breaker.
+
If the remote endpoint is available, it responds with an HTTP code `200` and you receive the following greeting:
+
----
{"content":"Hello, World!"}
----
+
If the remote endpoint is unavailable, it responds with an HTTP code `500` and you receive a predefined fallback response:
+
----
{"content":"Hello, Fallback!"}
----

* the `/api/cb-state` endpoint, which returns the state of the Circuit Breaker. The state can be _open_ or _closed_.

The following steps demonstrate how to verify the service availability, simulate a failure and receive a fallback response.


NOTE: The following steps use the command line to interact with the service. Alternatively, you can use the web interface to perform the same steps.

//TODO: add a warning not to use `http` as it may contain cached responses from the remote endpoint.
. Use `curl` to execute a `GET` request against the `{app-name}-greeting` service. You can also use the `Invoke` button in the web interface to do this.
// include image of the invoke button?
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl http://{app-name}-greeting-{project-name}.{osl-route-hostname}/api/greeting
{"content":"Hello, World!"}
----
+
// Add note about the Toggle button not working
// no scaler implemented error if CLI used to scale down pod
+
. To simulate the failure of the `{app-name}-name` service you can:
+
* use the `Toggle` button in the web interface.
* scale the number of replicas of the pod running the `{app-name}-name` service down to 0.
* execute an HTTP `PUT` request against the `/api/state` endpoint of the `{app-name}-name` service to set its state to `fail`.
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl -X PUT -H "Content-Type: application/json" -d '{"state": "fail"}' http://{app-name}-name-{project-name}.{osl-route-hostname}/api/state
----
+
. The Circuit Breaker state indicator in the web interface changes from `CLOSED` to `OPEN` and the Circuit Breaker issues the fallback response when you invoke the `/api/greeting` endpoint.
+
[source,bash,option="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-greeting-{project-name}.{osl-route-hostname}/api/greeting
{"content":"Hello, Fallback!"}
----
+
. Restore the name `{app-name}-name` service to availability.
To do this you can:
+
* use the `Toggle` button in the web interface.
* scale the number of replicas of the pod running the `{app-name}-name` service back up to 1.
* execute an HTTP `PUT` request against the `/api/state` endpoint of the `{app-name}-name` service to set its state back to `ok`.
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl -X PUT -H "Content-Type: application/json" -d '{"state": "ok"}' http://{app-name}-name-{project-name}.{osl-route-hostname}/api/state
----
+
. Invoke the `/api/greeting` endpoint again.
If the `{app-name}-name` service is available, you should receive the `Hello World!` greeting as the response:
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl http://{app-name}-greeting-{project-name}.{osl-route-hostname}/api/greeting
{"content":"Hello, World!"}
----
