[[build_and_deploy_booster]]
= Build and Deploy Your Booster

include::booster-deploy-openshift-local.adoc[leveloffset=+1]

[[deploy-booster-osl-cli]]
=== Deploy Using the `oc` CLI Client

include::oc-client-deploy-booster-download-note.adoc[leveloffset=+3]

. Get your authentication token for using the `oc` CLI client with your {OpenShiftLocal} account. You can find this in the _Command Line Tools_ section your {OpenShiftLocal} Web console.

. Authenticate your `oc` CLI client with your {OpenShiftLocal} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

. Create a new project in your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

ifndef::circuit-breaker-nodejs[]
. Navigate to the root directory of your booster.

. Use Maven to start the deployment to your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on your {OpenShiftLocal} and to start the pod.
endif::circuit-breaker-nodejs[]

ifdef::circuit-breaker-nodejs[]
. Clone a fork of the booster at `git@github.com:bucharest-gold/nodejs-circuit-breaker.git`, and use the provided `start-openshift.sh` script to start the deployment to {OpenShiftLocal}.

[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:my-boosters/nodejs-circuit-breaker.git
$ cd nodejs-circuit-breaker
$ ./start-openshift.sh
----

These commands use the Nodeshift `npm` module to install your dependencies, launch the S2I build process on your
{OpenShiftLocal} and start the services.
endif::circuit-breaker-nodejs[]

. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                            READY     STATUS      RESTARTS  AGE
{app-name}-greeting-1-aaaaa     1/1       Running   0           17s
{app-name}-greeting-1-deploy    0/1       Completed 0           22s
{app-name}-name-1-aaaaa         1/1       Running   0           14s
{app-name}-name-1-deploy        0/1       Completed 0           28s
----
+
Both the `{app-name}-greeting-1-aaaaa` and `{app-name}-name-1-aaaaa` pods should have a status of `Running` once they are fully deployed and started. You should also wait for your pods to be ready before proceeding, which is shown in the `READY` column. For example, `PROJECT_NAME-1-aaaaa` is ready when the `READY` column is `1/1`.
// :app-name: springboot-cb

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                     HOST/PORT                                                        PATH      SERVICES              PORT      TERMINATION   WILDCARD
{app-name}-greeting   {app-name}-{project-name}.{osl-route-hostname}            {app-name}-greeting   8080                    None
{app-name}-name       {app-name}-{project-name}.{osl-route-hostname}            {app-name}-name       8080                    None
----
+
A pod's route information gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-{project-name}.{osl-route-hostname}` as the base URL to access the applications.

ifndef::circuit-breaker-nodejs[]
include::booster-deploy-openshift-online.adoc[leveloffset=+1]
endif::circuit-breaker-nodejs[]
