[id='spring-web-reactive_{context}']
= Spring Web

The `spring-web` module provides the foundational elements of the reactive capabilities of  Spring WebFlux, including:

* HTTP abstractions
* Reactive Streams adapters for supported servers (Netty, Undertow)
* codecs for encoding and decoding event stream data
* the `WebHandler` API (a counterpart to the Servlet 3.1 I/O API that uses non-blocking contracts)

Based on these capabilities Spring WebFlux provides two programming models:
+
Annotated Controllers::
Consistent with Spring MVC and based on the same annotations from the `spring-web` module.
In addition to the `spring-web` module from SpringMVC, its WebFlux counterpart also supports reactive `@RequestBody` arguments.

Functional Endpoints::
Lambda-based, lightweight, and functional programming model. You can think of this as a small library or a set of utilities that an application can use to route and handle requests. The big difference with annotated controllers is that the application is in charge of request handling from start to finish versus declaring intent through annotations and being called back.
