[id='missions-and-cloud-native-development-on-openshift_{context}']
= Missions and Cloud-Native Development on OpenShift

.What are Missions?
Missions are working applications that showcase different fundamental pieces of building cloud native applications and services.

A mission implements a link:http://microservices.io/patterns/microservices.html[Microservice pattern] such as:

 * Creating REST APIs
 * Interoperating with a database
 * Implementing the Health Check pattern

You can use missions for a variety of purposes:

* A proof of technology demonstration
* A teaching tool, or a sandbox for understanding how to develop applications for your project
* They can also be updated or extended for your own use case

.What is a Booster?
A booster is the implementation of a mission in a specific runtime. Boosters are preconfigured, functioning applications that demonstrate a fundamental aspect of modern application development and run in an environment similar to production.

Each mission is implemented in one or more runtimes. Both the specific implementation and the actual project that contains your code are called a booster.

For example, the {name-mission-http-api} mission is implemented for these runtimes:

* link:{link-mission-http-api-nodejs}[{NodeJS} booster]
* link:{link-mission-http-api-spring-boot}[{SpringBoot} booster]
* link:{link-mission-http-api-vertx}[{VertX} booster]
* link:{link-mission-http-api-wf-swarm}[{WildFlySwarm} booster]
