[id='red-hat-openshift-application-runtimes_{context}']
= Red Hat OpenShift Application Runtimes

The following runtimes are available for OpenShift application development:

* {Thorntail}
+
{Thorntail} is a framework based on the popular WildFly Java application server to enable the creation of small, standalone microservice-based applications. Thorntail is capable of producing so-called just enough app-server to support each component of your system.
+
See link:{link-guide-thorntail}[{name-guide-thorntail}] for information about {Thornail} application development. 

* {SpringBoot}
+
{SpringBoot} makes it easy to create stand-alone, production-grade Spring based Applications that need very little Spring configuration.
+
See link:{link-guide-spring-boot}[{name-guide-spring-boot}] for information about {SpringBoot} application development.
+
See link:{link-guide-spring-boot-1-5}[{name-guide-spring-boot}] for information about {SpringBoot} 1.5 application development.


* {VertX}
+
{VertX} is a tool-kit for building reactive event driven non blocking applications on JVM. 
+
See link:{link-guide-vertx}[{name-guide-vertx}] for information about {Vertx} application development. 

* {Node}
+
{Node} is an asynchronous event driven JavaScript runtime designed to build scalable network applications.
+
See link:{link-guide-nodejs}[{name-guide-nodejs}] for information about {Node} application development. 