[id='repository-filesystem-layout_{context}']

= Repository filesystem layout

The following diagram describes the filesystem layout of the _{name-repo-docs}_ repository:

NOTE: The triple-dot indicates there are more files or directories in the particular directory.

.Filesystem Layout
----
.
├── docs/ <1>
│   ├── topics/ <2>
│   │   ├── images/ <3>
│   │   ├── styles/ <4>
│   │   ├── templates/ <5>
│   │   │   ├── document-attributes.adoc <6>
│   │   │   ├── document-attributes-launcher.adoc <7>
│   │   │   ├── document-attributes-portal.adoc <8>
│   │   │   ├── environment.adoc <9>
│   │   │   └── ...  
│   │   ├── con_circuit-breaker-design-tradeoffs.adoc
│   │   ├── thorntail <10>
│   │   └── ...
│   ├── $GUIDE_NAME/ <11>
│   │   ├── master.adoc <12>
│   │   ├── build_guide.sh <13>
│   │   └── topics/ -> ../topics <14>
│   └── ...
├── scripts/ <15>
│   ├── build_guides.sh <16>
│   ├── validate_guides.sh <17>
│   └── ...
├── cico_build_deploy <18>
├── CHANGELOG.adoc <19>
└── README.adoc
----
<1> The directory with the sources of all the _{name-docs}_ guides, the _launchpad.openshift.io_ page, and the contributor guide.
<2> The directory with the actual sources in AsciiDoc files. This directory is shared among all guides.
<3> The directory with all the images used in the sources.
<4> The directory with all the stylesheets used in the sources.
<5> The directory with all the templates used in the sources.
<6> The file where all the common document attributes are defined.
<7> The file where {name-launcher}{ndash}specific document attributes are defined.
<8> The file where Red Hat Customer Portal{ndash}specific document attributes are defined.
<9> The file that sets whether the documentation is built on the {name-launcher} or on the Red Hat Customer Portal.
<10> The directory with sources synchronized from the {WildFlySwarm} repository.
<11> The directory with the sources of a guide. Each guide has exactly one directory like this.
<12> The main AsciiDoc file of the guide. The files from the `topics` directory are included from this file.
<13> The script for building the particular guide.
<14> A symbolic link to the shared `$REPO_HOME/docs/topics/` directory.
<15> The directory with scripts used for manipulating files in the directory, building, and more.
<16> The script for building all guides at once. This script does not validate the guides.
<17> The script for validating all guides at once.
<18> The script to start local server and to publish to production. For more information, see xref:starting-preview-server_{context}[].
<19> The file with changes made in each release.

WARNING: Do not edit files in the `$REPO_HOME/docs/topics/thorntail` directory, always submit a pull request to the link:{link-repo-wildfly-swarm}[{WildFlySwarm} repository] and synchronize the files afterwards.

.Additional resources

* xref:syncing-with-wildflyswarm-docs_{context}[]
