[id="introduction-to-spring-reactive_{context}"]
= Introduction to {SpringReactive}

The Spring reactive stack is built on link:https://projectreactor.io/docs/netty/release/reference/index.html[Reactor Netty], an asynchronous IO runtime based on link:https://projectreactor.io/docs[Project Reactor] and the link:https://netty.io/[Netty framework], that provides non-blocking TCP, HTTP, and UDP clients and servers, and implements link:https://projectreactor.io/docs/netty/release/reference/index.html#net-backpressure[backpressure] in a manner that complies with the Reactive Streams specification.
Reactor Netty provides the link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[`Flux`] and link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html[`Mono`] functional API types that enable asynchronous event stream processing.

On top of the Reactor library, Spring reactive relies on link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux[WebFlux], an asynchronous event-driven web application framework based on the Reactive Streams specifications.
While WebFlux is designed to work primarily with Spring Reactor, it can also operate in other asynchronous runtime environments, such as Netty or Undertow, due to its compliance with Reactive Streams.

Spring WebFlux and Reactor enable you to create applications that are:

* Non-blocking: The application continues to handle further requests when waiting for a response from a remote component or service that is required to complete the current request.
* Asynchronous: the application responds to events from an event stream (also called an event loop) by generating response events and publishing them back to the event stream where they can be picked up by other clients in the application.
* Event-driven: The application responds to events generated by the user or by another service, such as mouse clicks, HTTP requests, or new files being added to a storage.
* Scalable: Increasing the number of Publishers or Subscribers to match the required event processing capacity of an application only results in a slight increase in the complexity of routing requests between individual clients in the application.
Reactive applications can handle large numbers of events using fewer computing and networking resources as compared to other application programming models.
* Resilient: The application can handle failure of services it depend on without a negative impact on its overall quality of service.

Additional advantages of using Spring WebFlux include:

Similarity with SpringMVC::
The SpringMVC API types and WebFlux API types are similar, and it is easy for developers to apply knowledge of SpringMVC to programming applications with WebFlux.

The Spring Reactive offering by Red{nbsp}Hat brings the benefits of Reactor and WebFlux to OpenShift and stand-alone RHEL, and introduces a set of {VertX} extensions for the WebFLux framework.
This allows you to retain the level of abstraction and rapid prototyping capabilities of {SpringBoot}, and provides an asynchronous IO API that handles the network communications between the services in your application in a fully reactive manner.

Annotated controllers support::
WebFlux retains the endpoint controller annotations introduced by SpringMVC (Both SpringMVC and WebFlux support reactive RxJava2 and Reactor return types).

Functional programming support::
Reactor interacts with the Java 8 Functional API, as well as `CompletablebFuture`, and `Stream` APIs.
In addition to annotation-based endpoints, WebFlux also supports functional endpoints.

.Additional resources

See the following resources for additional in-depth information on the implementation details of technologies that are part of the Spring Reactive stack:

* link:https://www.reactivemanifesto.org/[The Reactive Manifesto]
* link:https://www.reactive-streams.org/[Reactive Streams specification]
* link:https://www.reactive-streams.org/[Reference Documentation for the Reactive Streams specification]
* link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html[Spring Framework reference documentation: Web Applications on Reactive Stack]
* link:https://projectreactor.io/docs/netty/release/reference/index.html[Reactor Netty documentation]
* link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html[API Reference page for the `Mono` class in Project Reactor Documentation]
* link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[API Reference page for the `Flux` class in Project Reactor Documentation]
