[id="server-sent-events_{context}"]
= Server-sent events

Server-sent events (SSE) is a push technology allowing HTTP sever to send unidirectional updates to the client.
SSE works by establishing a connection between the event source and the client.
The event source uses this connection to push events to the client-side.
After the server pushes the events, the connection remains open, and can be used to push subsequent events.
When the client terminates the request on the server, the connection is closed.
SSE represents a more resource-efficient alternative to polling, where a new connection must be established each time the client polls the event source for updates.
As opposed to WebSockets, SSE pushes events in one direction only (that is, from the source to the client).
It does not handle bidirectional communication between the event source and the client.

The specification for SSE is incorporated into HTML5, and is widely supported by web browsers, including their legacy versions.
SSE can be used from the command line, and is relatively simple to set up compared to other protocols.

SSE is suitable for use cases that require frequent updates from the server to the client, while updates from the client side to the server are expected to be less frequent.
Updates form the client side to the server can then be handled over a different protocol, such as REST.
Examples of such use cases include social media feed updates or notifications sent to a client when new files are uploaded to a file server.
