[id="introduction-to-spring-reactive_{context}"]
= Introduction to Spring Reactive

The Spring Reactive stack is built on link:https://projectreactor.io/[Project Reactor], a reactive library for building non-blocking applications on the JVM that implements messaging over HTTP based on the the link:https://www.reactive-streams.org/[Reactive Streams specification] and RxJava2.
Reactor provides the link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[`Flux`] and link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html[`Mono`] functional API types that enable asynchronous event stream processing.

On top of the Reactor library, Spring Reactive relies on link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux[WebFlux], an asynchronous event-driven web application framework based on the Reactive Streams specifications.
While WebFlux is designed to work primarily with Spring Reactor, it can also operate in other asynchronous runtime environments, such as Netty or Undertow, due to its compliance with Reactive Streams.

Spring WebFlux and Reactor enable you to create applications that are:

* Non-blocking, meaning that the application continues to handle further requests when waiting for a response from a remote component or service that is required to complete the handling of the current request.
* Asynchronous, meaning that the application responds to events from an event stream (also called an event loop) by generating response events and publishing them back to the event stream where they can be picked up by other clients in the application.
* Event-Driven, meaning that the application responds to events generated by the user or by another service (such as mouse clicks or HTTP requests).
* Scalable, meaning that increasing the number of Publishers or Subscribers to match the required event processing capacity of an application only results in a slight increase in the complexity of routing requests between individual clients in the application.
Reactive applications can handle large numbers of events using fewer computing and networking resources as compared to other application programming models.
* Resilient, meaning that applications can handle failure of services they depend on without a negative impact on their own overall quality of service.

Additional advantages of using Spring WebFlux include:

Similarity with SpringMVC::
The high degree of similarity between the SpringMVC API types and WebFlux API types, makes it relatively easy for developers to re-apply knowledge of SpringMVC to programming applications with WebFLux.

Annotated controllers support::
WebFlux retains the endpoint controller annotations introduced by SpringMVC (Both SpringMVC and WebFlux support reactive RxJava2 and Reactor return types).
In addition to all the annotation types inherited from Spring MVC, WebFlux also supports `@RequestBody` arguments.

Functional programming support::
Reactor interacts with the Java 8 Functional API, as well as `CompletablebFuture`, and `Stream` APIs.
In addition to annotation-based endpoints, WebFlux also supports functional endpoints.

.Additional resources

See the following resources for additional in-depth information on the implementation details of technologies that are part of the Spring Reactive stack:

* link:https://www.reactivemanifesto.org/[The Reactive Manifesto]
* link:https://www.reactive-streams.org/[Reference Documentation for the Reactive Streams specification]
* link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html[Spring Framework reference documentation: Web Applications on Reactive Stack]
* link:https://projectreactor.io/docs/core/release/reference/[Project Reactor reference documentation]
* link:https://netty.io/[Netty project documentation]
* link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html[API Reference page for the `Mono` class in Project Reactor Documentation]
* link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[API Reference page for the `Flux` class in Project Reactor Documentation]
