[id='supported-build-strategies-for-openshift-deployment']
= Supported Build Strategies for OpenShift Deployment

When using link:{link-launcher-oso}[{name-launcher-oso}], you can create and deploy an example application to OpenShift using the _Build and Deploy to OpenShift_ build process, which is based on the link:{link-guide-thorntail}#the-source-to-image-s2i-build-process[Source-to-Image (S2I) build process]. _Build and Deploy to OpenShift_ configures OpenShift to pull the code of your example application from your GitHub repository, build the code, and deploy it to OpenShift.

The benefit of this process is that it handles all the configuration, building, and deployment steps needed to get your example application running in OpenShift. It also allows you to quickly deploy code updates and see your changes in OpenShift.

OpenShift supports different link:https://docs.openshift.com/online/dev_guide/builds/index.html[build strategies] including Source-to-Image and Jenkins Pipeline. The {ProductName} example applications use the link:https://docs.openshift.com/online/architecture/core_concepts/builds_and_image_streams.html#source-build[Source-to-Image strategy] for simplicity of use and implementation. Other build strategies, such as the Jenkins Pipeline, are more complex, for example employing multiple servers for building or using webhooks to trigger builds.

Example applications created using the _Build and Deploy to OpenShift_ build process can also be executed locally, as well as built locally and manually deployed to OpenShift. For more information on these options, see the `README.adoc` file of your example application.
