
[id='introduction-to-productname_{context}']
= Introduction to {ProductName}
This section provides a brief overview of the foundational concepts behind {ProductName}.

{ProductName} is:

* A collection of runtimes, such as {WildFlySwarm} and {SpringBoot}, designed to run on OpenShift.
* A prescriptive approach to cloud-native development on OpenShift.

The goal of {ProductName} is to provide prescriptive architectures, design patterns, tools, and best practices in ready-made example applications that you can execute on OpenShift to enable cloud-native development.

.Cloud-native Development
Cloud-native development is an approach to developing, deploying, and running applications that take full advantage of cloud computing.

.OpenShift
link:https://www.openshift.com[Red Hat OpenShift] is a container application platform that brings link:https://www.redhat.com/en/topics/containers/what-is-docker[Docker] and link:https://www.redhat.com/en/topics/containers/what-is-kubernetes[Kubernetes] to the enterprise. link:{link-launcher-oso}[{OpenShiftOnline}] is a public cloud hosted by Red Hat. A {OpenShiftLocal} is a local cloud that you can install and execute on your local machine; this functionality is provided for example by link:https://developers.redhat.com/products/cdk/overview/[{CDK}] or link:https://www.openshift.org/minishift/[{Minishift}].


[[launcher-details]]
.{name-launcher-oso}
link:{link-launcher-oso}[{name-launcher-oso}] is a project generator offered by Red Hat to accelerate your experience with cloud-native development on OpenShift. It provides an easy way to create, build, and deploy example applications to OpenShift. To use link:{link-launcher-oso}[{name-launcher-oso}]:

* Navigate to link:{link-launcher-oso}[{name-launcher-oso}].
* Choose the details for your example application.
* Deploy application to OpenShift automatically or manually.

You can find more details on using {name-launcher-oso} in the xref:deploying-an-example-application-to-openshiftonline_{context}[] section.

.The {name-launcher} Tool
The {name-launcher} is the upstream project from which link:{link-launcher-oso}[{name-launcher-oso}] is based.

You can also install and execute the {name-launcher} tool on your {OpenShiftLocal} to use the same capabilities within your {OpenShiftLocal}. For more information, see the link:{link-guide-minishift-installation}#installing-launcher-tool_minishift[Installing the {name-launcher} Tool] chapter of the {name-guide-minishift-installation} guide.

.Example applications
An example application implements a link:http://microservices.io/patterns/microservices.html[Microservice pattern] such as:

* Health Check
* REST or HTTP endpoint
* link:https://docs.openshift.com/online/dev_guide/configmaps.html[Externalized Configuration]
* Circuit Breaker

Example applications use these patterns to show how to create the fundamental building blocks of cloud-native applications and services, such as:

* Creating HTTP APIs.
* Integrating your application with a relational database to provide persistent data storage.
* Implementing the health check and circuit-breaker patterns to ensure that your services can withstand a traffic overload and network issues.
* Externalizing the configuration of your applications to make them more secure and easier to scale.
//* Securing your applications with {RHSSO} to provide authentication and authorization functionality

Each example application is implemented in one or more runtimes. Both the specific implementation and the actual project that contains your code are called an example application. An example application can be updated or extended for your own use case.

[#build-and-deploy-process]
.Process for Building and Deploying to OpenShift

When using link:{link-launcher-oso}[{name-launcher-oso}], you can create and deploy an example application to OpenShift using the _Build and Deploy to OpenShift_ build process, which is based on the link:{link-guide-thorntail}#the-source-to-image-s2i-build-process[Source-to-Image (S2I) build process]. _Build and Deploy to OpenShift_ configures OpenShift to pull the code of your example application from your GitHub repository, build the code, and deploy it to OpenShift.

The benefit of this process is that it handles all the configuration, building, and deployment steps needed to get your example application running in OpenShift. It also allows you to quickly deploy code updates and see your changes in OpenShift.

OpenShift supports different link:https://docs.openshift.com/online/dev_guide/builds/index.html[build strategies] including Source-to-Image and Jenkins Pipeline. The {ProductName} example applications use the link:https://docs.openshift.com/online/architecture/core_concepts/builds_and_image_streams.html#source-build[Source-to-Image strategy] for simplicity of use and implementation. Other build strategies, such as the Jenkins Pipeline, are more complex, for example employing multiple servers for building or using webhooks to trigger builds.

Example applications created using the _Build and Deploy to OpenShift_ build process can also be executed locally, as well as built locally and manually deployed to OpenShift. For more information on these options, see the `README.adoc` file of your example application.
