[id='purpose-of-the-health-check-pattern_{context}']
= Health check pattern

The purpose of this use case is to demonstrate the health check pattern through the use of probing.
Probing is used to report the liveness and readiness of an application.
In this use case, you configure an application which exposes an HTTP `health` endpoint to issue HTTP requests.
If the container is alive, according to the liveness probe on the `health` HTTP endpoint, the management platform receives `200` as return code and no further action is required.
If the `health` HTTP endpoint does not return a response, for example if the thread is blocked, then the application is not considered alive according to the liveness probe.
In that case, the platform kills the pod corresponding to that application and recreates a new pod to restart the application.

This use case also allows you to demonstrate and use a readiness probe.
In cases where the application is running but is unable to handle requests, such as when the application returns an HTTP `503` response code during restart, this application is not considered ready according to the readiness probe.
If the application is not considered ready by the readiness probe, requests are not routed to that application until it is considered ready according to the readiness probe.
