[id='what-is-vertx_{context}']
= What is {VertX}

{VertX} is a toolkit for writing reactive, non-blocking, asynchronous applications that run on the JVM (Java Virtual Machine).
{VertX} provides a non-prescriptive and flexible way to write efficient, multi-language (polyglot) applications.
{VertX} is also designed to be truly cloud-native by efficiently allowing many processes to switch between one or very few threads.
This allows {VertX} applications and services to more effectively use their CPU quotas in cloud environments and avoids the unnecessary overhead caused when creating new threads.
Check out xref:additional-vertx-resources_{context}[Additional Resources] for further reading on {VertX}.

Using the {VertX} runtime in OpenShift makes it simpler and easier to build reactive systems with {VertX}.
The {VertX} runtime enables you to run {VertX} applications and services in OpenShift while providing all the advantages and conveniences of the OpenShift platform such as rolling updates, service discovery, and canary deployments.
OpenShift also makes it easier for your applications to implement common microservice patterns such as externalized configuration, health check, circuit breaker, and failover.

