[id='health-check-concepts_{context}']
= Health Check Concepts

In order to understand the health check pattern, you need to first understand the following concepts:

Liveness::
Liveness defines whether an application is running or not. Sometimes a running application moves into an unresponsive or stopped state and needs to be restarted. Checking for liveness helps determine whether or not an application needs to be restarted.

Readiness::
Readiness defines whether a running application can service requests. Sometimes a running application moves into an error or broken state where it can no longer service requests. Checking readiness helps determine whether or not requests should continue to be routed to that application.

Fail-over::
Fail-over enables failures in servicing requests to be handled gracefully. If an application fails to service a request, that request and future requests can then _fail-over_ or be routed to another application, which is usually a redundant copy of that same application.

Resilience and Stability::
Resilience and Stability enable failures in servicing requests to be handled gracefully. If an application fails to service a request due to connection loss, in a resilient system that request can be retried after the connection is re-established.

Probe::
A probe is a Kubernetes action that periodically performs diagnostics on a running container.

