[id='about-circuit-breaker_{context}']
= About Circuit Breaker

// TODO: maybe break this down into a briefer, list-like section
The Circuit Breaker is a pattern intended to mitigate the impact of network failure and high latency on service architectures where services synchronously invoke other services.
In such cases, if one of the services becomes unavailable due to network failure or incurs unusually high latency values due to overwhelming traffic, other services attempting to call its endpoint may end up exhausting critical resources in an attempt to reach it, rendering themselves unusable.
This condition is also known as cascading failure and can render the entire microservice architecture unusable.

Essentially, the Circuit Breaker acts as a proxy between a protected function and a remote function, which monitors for failures.
Once the failures reach a certain threshold, the circuit breaker trips, and all further calls to the circuit breaker return with an error or a predefined fallback response, without the protected call being made at all.
The Circuit Breaker usually also contain an error reporting mechanism that notifies you when the Circuit Breaker trips.

[discrete]
== Why Circuit Breaker is Important

In an architecture where multiple services depend on each other for functionality, a failure in one service can rapidly propagate to its dependent services, causing the entire architecture to collapse.
Implementing a Circuit Breaker pattern helps prevent this.
With the Circuit Breaker pattern implemented, a service client invokes a remote service endpoint via a proxy at regular intervals.
If the calls to the remote service endpoint fail repeatedly and consistently, the Circuit Breaker trips, making all calls to the service fail immediately over a set timeout period and returns a predefined fallback response.
When the timeout period expires, a limited number of test calls are allowed to pass through to the remote service to determine whether it has healed, or remains unavailable.
If these test calls fail, the Circuit Breaker keeps the service unavailable and keeps returning the fallback responses to incoming calls.
If the test calls succeed, the Circuit Breaker closes, fully enabling traffic to reach the remote service again.
