[id='missions-and-cloud-native-development-on-openshift_{context}']
[id='examples-and-cloud-native-development-on-openshift_{context}']
= Example applications and cloud-native development on OpenShift

When developing applications on OpenShift, you can use examples to kickstart your development.

[discrete]
== Example applications

Examples are working applications that showcase different fundamental pieces of building cloud native applications and services.

The examples implement a link:http://microservices.io/patterns/microservices.html[Microservice pattern] such as:

* Creating REST APIs
* Interoperating with a database
* Implementing the Health Check pattern

You can use the examples for a variety of purposes:

* A proof of technology demonstration
* A teaching tool, or a sandbox for understanding how to develop applications for your project
* They can also be updated or extended for your own use case

Each example application is implemented in one or more runtimes.
The {name-example-http-api} example is implemented for these runtimes:

* link:{link-example-http-api-nodejs}[{Node}]
* link:{link-example-http-api-spring-boot}[{SpringBoot}]
* link:{link-example-http-api-vertx}[{VertX}]
* link:{link-example-http-api-thorntail}[{WildFlySwarm}]
