
[#introduction-to-productname]
= Introduction to {ProductName}
This section provides a brief overview of the foundational concepts behind {ProductName}.

{ProductName} is:

* A collection of runtimes, such as {WildFlySwarm} and {SpringBoot}, designed to run on OpenShift.
* A prescriptive approach to cloud-native development on OpenShift.

The goal of {ProductName} is to provide opinionated architectures, design patterns, tools, and best practices in ready-made example applications you can execute on OpenShift to enable cloud-native development.

.Cloud-native Development
Cloud-native development is an approach to developing, deploying, and running applications that fully embrace the advantages of cloud computing.

.OpenShift
link:https://www.openshift.com[Red Hat OpenShift] is a container application platform that brings link:https://www.redhat.com/en/topics/containers/what-is-docker[Docker] and link:https://www.redhat.com/en/topics/containers/what-is-kubernetes[Kubernetes] to the enterprise. link:{link-launcher-oso}[{OpenShiftOnline}] is a public cloud hosted by Red Hat. A {OpenShiftLocal} is a local cloud that you can install and execute on your local machine; this functionality is provided for example by link:https://developers.redhat.com/products/cdk/overview/[{CDK}] or link:https://www.openshift.org/minishift/[{Minishift}].


[[launcher-details]]
.{launcher-oso}
link:{link-launcher-oso}[{launcher-oso}] is a project generator offered by Red Hat to accelerate your experience with cloud-native development on OpenShift. It provides a hassle-free way of creating example applications, called boosters, as well as an easy way to build and deploy those boosters to OpenShift. To use link:{link-launcher-oso}[{launcher-oso}]:

* Navigate to link:{link-launcher-oso}[{launcher-oso}].
* Choose the details for your example application.
* Deploy application OpenShift automatically or manually.

You can find more details on using {launcher-oso} in the xref:deploying-a-booster-to-openshiftonline_{context}[] section.

.The {launcher} Tool
The {launcher} is the upstream project from which link:{link-launcher-oso}[{launcher-oso}] is based.

You can also install and execute the {launcher} tool on your {OpenShiftLocal} to use the same capabilities within your {OpenShiftLocal}. For more information, see the link:{link-launcher-openshift-local-install-guide}#install-launcher-app[Installing the {launcher} Tool] chapter of the {minishift-installation-guide-name} guide.

.Missions and Boosters
A mission implements a link:http://microservices.io/patterns/microservices.html[Microservice pattern] such as:

* Health Check
* REST or HTTP endpoint
* link:https://docs.openshift.com/online/dev_guide/configmaps.html[Externalized Configuration]
* Circuit Breaker

Missions use these patterns to show how to create the fundamental building blocks of cloud-native applications and services, such as:

* Creating HTTP APIs.
* Integrating your application with a relational database to provide persistent data storage.
* Implementing the health check and circuit-breaker patterns to ensure that your services can withstand a traffic overload and network issues.
* Externalizing the configuration of your applications to make them more secure and easier to scale.
//* Securing your applications with {RHSSO} to provide authentication and authorization functionality

Each mission is implemented in one or more runtimes. Both the specific implementation and the actual project that contains your code are called a booster. Any booster can be updated or extended for your own use case.

[#build-and-deploy-process]
.Process for Building and Deploying to OpenShift

When using link:{link-launcher-oso}[{launcher-oso}], you can create and deploy a booster to OpenShift using the _Build and Deploy to OpenShift_ build process, which is based on the link:{link-wf-swarm-runtime-guide}#s2i-build-process[Source-to-Image (S2I) build process]. _Build and Deploy to OpenShift_ configures OpenShift to pull the code of your booster from your GitHub repository, build the code, and deploy it to OpenShift.

The benefit of this process is that it handles all the configuration, building, and deployment steps needed to get your booster running in OpenShift. It also allows you to quickly deploy code updates to help you rapidly iterate and see your changes in OpenShift.

OpenShift supports different link:https://docs.openshift.com/online/dev_guide/builds/index.html[build strategies] including Source-to-Image and Jenkins Pipeline. The {ProductName} boosters use the link:https://docs.openshift.com/online/architecture/core_concepts/builds_and_image_streams.html#source-build[Source-to-Image strategy] for simplicity of use and implementation. Other build strategies, such as the Jenkins Pipeline, are more complex, for example employing multiple servers for building or using webhooks to trigger builds.

Boosters created using the _Build and Deploy to OpenShift_ build process can also be executed locally, as well as built locally and manually deployed to OpenShift. For more information on these options, see the `README.adoc` file of your booster.
