[id='springboot-features-and-frameworks-summary_{context}']
= {SpringBoot} features and frameworks summary


This guide covers the design of modern applications using link:https://projects.spring.io/spring-boot/[Spring Boot]. These concepts support developing Web or Websocket applications using either a HTTP connector or non-blocking HTTP connector.
The applications can be packaged and deployed without modification or updated to use cloud native features on OpenShift.

The features in the table below are available as a collection of missions which run on OpenShift. Some features are native to Kubernetes, others are available from link:https://github.com/spring-cloud-incubator/spring-cloud-kubernetes[Spring Cloud Kubernetes].
Features such as Actuator are available directly in {SpringBoot}.

.Features and Frameworks Summary
[width="100%",options="header"]
|====================================================================
|Feature |Problem Addressed |Cloud Native |Framework

a|
Circuit Breaker

a|
Switches between services and continues to process incoming requests without interruption in case of service failure.

a|
Yes

a|
link:https://github.com/spring-cloud/spring-cloud-netflix[Spring Cloud Netflix] - Hystrix


a|
Health Check

a|
Checks readiness and liveness of the service. Service restarts automatically if probing fails.

a|
Yes

a|
Spring Boot Actuator


a|
Service Discovery

a|
Discovers Service/Endpoint deployed on OpenShift and exposed behind a service or route using the service name matching a DNS entry.

a|
Yes - using Kubernetes API

a|
link:https://github.com/spring-cloud-incubator/spring-cloud-kubernetes[Spring Cloud Kubernetes] - DiscoveryClient


a|
Server Side Load Balancing

a|
Handles load increases by deploying multiple service instances, and by transparently distributing the load across them.

a|
Yes - Using internal Kubernetes Load Balancer

a|
-


a|
Client Side Load Balancing

a|
Transparently handle load balancing on the client for better control and load distribution across multiple service instances.

a|
No

a|
link:https://github.com/spring-cloud-incubator/spring-cloud-kubernetes[Spring Cloud Kubernetes] - Ribbon


a|
Externalize Parameters

a|
Makes the application independent of the environment where it runs.

a|
Yes - Kubernetes ConfigMap or Secret

a|
link:https://github.com/spring-cloud-incubator/spring-cloud-kubernetes[Spring Cloud Kubernetes] - ConfigMap


|====================================================================
