[[build_and_deploy_booster]]
= Build and Deploy Your Booster

== Deploy your Booster to {OpenShiftOnline}

[[deploy-booster-oso-cli]]
=== Deploy Using the `oc` CLI Client

. Get your authentication token for using the `oc` CLI client with your {OpenShiftOnline} account. You can find this in the link:{link-oso-console-cli-token}[{OpenShiftOnline} Web console^].

. Authenticate your `oc` CLI client with your {OpenShiftOnline} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

. Create a new project in {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project NEW-PROJECT-NAME
----

. Navigate to the root directory of your booster.

. Deploy your ConfigMap configuration to {OpenShiftOnline} using the `app-config.yml` in the root of the booster.
+
[source,options="nowrap"]
----
$ oc create configmap app-config --from-file=app-config.yml
----

. Verify your ConfigMap configuration has been deployed.
+
[source,options="nowrap"]
----
$ oc get configmap app-config -o yaml

apiVersion: v1
data:
  app-config.yml: |-
    greeting:
      message: Hello World!
...
----

. Use maven to start the deployment to {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on {OpenShiftOnline} and to start the pod.


. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa       1/1       Running     0          58s
{app-name}-s2i-1-build   0/1       Completed   0          2m
----
+
Your `{app-name}-1-aaaaa` pod should have a status of `Running` once its fully deployed and started.

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                     PATH      SERVICES             PORT      TERMINATION
{app-name}   {app-name}-myproject.192.168.99.100.nip.io      {app-name}   8080
----
+
A pod's route information gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-myproject.192.168.99.100.nip.io` as the base URL to access the application.

== Deploy your Booster to {OpenShiftLocal}

. Before you can use {OpenShiftLocal}, you need to have it installed, configured, and running. You can find more details in link:{link-openshift-local-guide}[{openshift-local-guide-name}]. 

. Once you have {OpenShiftLocal} running, check the console output for the URL you can use to access it.
+
.Example Console Output from {OpenShiftLocal} Startup
[source,bash,options="nowrap",subs="attributes+"]
----
...
-- Removing temporary directory ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----

=== Deploy Using the `oc` CLI Client

You can deploy your booster to {OpenShiftLocal} by following the same process in xref:deploy-booster-oso-cli[], but instead of using the {OpenShiftOnline}, use your {OpenShiftLocal} URL to access the Web console and with the `oc` CLI client.