= Interact with the Unmodified {VertX} Booster

The booster provides a default HTTP endpoint that accepts GET requests.

. Use `curl` to execute a `GET` request against the booster. You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{osl-route-hostname}/api/greeting
{"content":"Hello, World from a ConfigMap !"}
----
. Update the deployed ConfigMap configuration.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc edit configmap app-config
----
+
Change the value for the `message` key to `Bonjour, %s from a ConfigMap !` and save the file.


. Update of the config map should be read by the application within an acceptable time (a few seconds) without requiring a restart of the application.
. Use `curl` to execute a `GET` request against the booster with the updated ConfigMap configuration. You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{osl-route-hostname}/api/greeting
{"content":"Bonjour, World from a ConfigMap !"}
----
+
You should see your updated greeting.

= Running Integration Tests

This booster contains a set of integration tests.
To run them, you must be connected to an OpenShift instance and select the project that will be used for testing.

To run the integration tests, execute the following command:

[source,bash,options="nowrap",subs="attributes+"]
--
$ mvn clean verify -Popenshift,openshift-it
--
[WARNING]
--
Be sure that view access rights for service account are added before executing tests.

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc policy add-role-to-user view -n $(oc project -q) -z default
----
--