= Interact with the Unmodified {SpringBoot} Booster

The booster provides a default HTTP endpoint that accepts GET requests.

. Use `curl` to execute a `GET` request against the booster. You can also use a browser to do this.
+
[source,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-myproject.192.168.99.100.nip.io/api/greeting
{"content":"Hello World from a ConfigMap!"}
----

. Update the deployed ConfigMap configuration.
+
[source,options="nowrap",subs="attributes+"]
----
$ oc edit configmap {app-name}
----
+
Change the value for the `greeting.message` key to `Bonjour!` and save the file. After you save this, the changes will be propagated to your OpenShift instance.

. Rollout the new version of your application so the ConfigMap configuraiton changes are picked up.
+
[source,options="nowrap",subs="attributes+"]
----
$ oc rollout latest dc/{app-name}
----

. Check the status of your booster and ensure your new pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa       1/1       Running     0          58s
{app-name}-s2i-1-build   0/1       Completed   0          2m
----
+
You `{app-name}-1-aaaaa` pod should have a status of `Running` once it's fully deployed and started.

. Use `curl` to execute a `GET` request against the booster with the updated ConfigMap configuration. You can also use a browser to do this.
+
[source,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-myproject.192.168.99.100.nip.io/api/greeting
{"content":"Bonjour!"}
----
+
You should see your updated greeting.
