[[build_and_deploy_booster]]
= Build and Deploy Your Booster

include::booster-deploy-openshift-local.adoc[leveloffset=+1]

include::booster-deploy-launchpad-openshift-local.adoc[leveloffset=+2]

[[deploy-booster-osl-cli]]
=== Deploy Using the `oc` CLI Client

. Get your authentication token for using the `oc` CLI client with {OpenShiftLocal}. You can find this in the {OpenShiftLocal} Web console. In the above example, your token would be located at `https://192.168.99.100:8443/console/command-line`.

. Authenticate your `oc` CLI client with your {OpenShiftLocal} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-osl-auth} --token=MYTOKEN
----

. Create a new project in {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

ifdef::configmap-vertx,configmap-spring-boot-tomcat[]
. Add a policy for the project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc policy add-role-to-user view -n $(oc project -q) -z default
----
endif::configmap-vertx,configmap-spring-boot-tomcat[]

. Navigate to the root directory of your booster.

ifdef::configmap-vertx[]
. Deploy your ConfigMap configuration to {OpenShiftLocal} using `app-config.yml`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=app-config.yml
----

. Verify your ConfigMap configuration has been deployed.
+
[source,bash,options="nowrap"]
----
$ oc get configmap app-config -o yaml

apiVersion: v1
data:
  app-config.yml: |-
      message : "Hello, %s from a ConfigMap !"
      level : INFO
...
----
endif::configmap-vertx[]
ifdef::configmap-wf-swarm[]
. Deploy your ConfigMap configuration to {OpenShiftLocal} using `app-config.yml` in the root of the booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=app-config.yml
----

. Verify your ConfigMap configuration has been deployed.
+
[source,bash,options="nowrap"]
----
$ oc get configmap app-config -o yaml

apiVersion: v1
data:
  app-config.yml: |-
    greeting:
      message: Hello %s from a ConfigMap!
...
----
endif::configmap-wf-swarm[]

. Use maven to start the deployment to {OpenShiftLocal}.
+
ifdef::configmap-vertx,configmap-spring-boot-tomcat[]
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
endif::configmap-vertx,configmap-spring-boot-tomcat[]
ifdef::configmap-wf-swarm[]
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
endif::configmap-wf-swarm[]
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on {OpenShiftLocal} and to start the pod.


. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                                       READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa               1/1       Running     0          58s
{app-name}-s2i-1-build           0/1       Completed   0          2m
----
+
Your `{app-name}-1-aaaaa` pod should have a status of `Running` once its fully deployed and started.
ifdef::configmap-vertx[]
You should also wait for your pod to be _ready_ before proceeding, which is shown in the `READY` column. For example, `{app-name}-1-aaaaa` is _ready_ when the `READY` column is `1/1`.
endif::configmap-vertx[]

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME         HOST/PORT                                     PATH      SERVICES             PORT      TERMINATION
{app-name}   {app-name}-{project-name}.192.168.99.100.nip.io              {app-name}           8080
----
+
A pod's route information gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-{project-name}.192.168.99.100.nip.io` as the base URL to access the application.

ifdef::configmap-spring-boot-tomcat[]
. Verify your ConfigMap configuration has been deployed.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get configmap {app-name} -o yaml

apiVersion: v1
data:
  application.properties: |
    greeting.message: Hello %s from a ConfigMap!
...
----
endif::configmap-spring-boot-tomcat[]


include::booster-deploy-openshift-online.adoc[leveloffset=+1]
