= Interacting with the Unmodified {WildFlySwarm} Booster

The booster provides a default HTTP endpoint that accepts GET requests.

. Use `curl` to execute a `GET` request against the booster. You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/greeting
{"content":"Hello World from a ConfigMap!"}
----

. Update the deployed ConfigMap configuration.
+
[source,bash,options="nowrap"]
----
$ oc edit configmap app-config
----
+
Change the value for the `greeting.message` key to `Bonjour %s from a ConfigMap!` and save the file. After you save this, the changes will be propagated to your OpenShift instance.

. Rollout the new version of your application so the ConfigMap configuration changes are picked up.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc rollout latest dc/{app-name}
----

. Check the status of your booster and ensure your new pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa       1/1       Running     0          58s
{app-name}-s2i-1-build   0/1       Completed   0          2m
----
+
The `{app-name}-1-aaaaa` pod should have a status of `Running` once its fully deployed and started.
Your specific pod name will vary.
The number in the middle will increase with each new build.
The letters at the end are generated when the pod is created.


. Execute a `GET` request using `curl` against the booster with the updated ConfigMap configuration to see your updated greeting.
You can also do this from your browser using the web form provided by the application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/greeting
{"content":"Bonjour World from a ConfigMap!"}
----
