
= Before you start

To contribute to the Fabric8 Launcher documentation, you need to configure the following tools and accounts:

== Tools _(required)_

You must install the following tools on your system:

Asciidoctor::
+
--
A quick and light tool for local builds that allows you to check factual correctness or flow of information.

To install Asciidoctor on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install asciidoctor
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://asciidoctor.org/#installation[official Asciidoctor documentation].
--

Meld (optional)::
A graphical tool for comparing files. This tool is useful for comparing Git revisions and resolving merge conflicts.
+
To install Meld on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install meld
----

[[_accounts]]
== Accounts _(required)_

To contribute, you must have a link:https://github.com/join[GitHub account] with GPG configured. To configure GPG:

WARNING: On RHEL, CentOS, or Fedora, use the `gpg2` binary instead of `gpg`. On MacOS, use the `gpg` binary. 

.Configuring GPG

The command options you use to configure `gpg2` or `gpg` are the same for both binaries.

. link:https://help.github.com/articles/generating-a-new-gpg-key/[Generate a new GPG key].
. link:https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account[Add the GPG key to your GitHub account].
. link:https://help.github.com/articles/telling-git-about-your-gpg-key/[Tell git about the signing key] on your machine.

. In the _{name-repo-docs}_ repository, set automatic signing with your GPG key:
+
--
[source,bash]
----
$ git config commit.gpgsign true
----

For more information, see link:https://help.github.com/articles/signing-commits-using-gpg/[Signing commits using GPG].
--
. On RHEL, CentOS, or Fedora, set the commit signing program to `gpg2`. On MacOS, set the commit signing program to `gpg`.
+
[source,bash,options="nowrap"]
----
$ git config --global gpg.program gpg2
----

== Setting up Git hooks _(recommended)_

To make a contribution to the {name-repo-docs} repository, you need to set up the Git hooks directory. These hooks automatically make sure at commit time that your contribution does not break important parts of the repository.

.Procedure

.Setting up Git Hooks in {name-repo-docs} Repository
. In a terminal application, navigate to the directory with the {name-repo-docs} repository.
. Set the Git hook directory to `$REPO_HOME/.githooks`:
+
[source,bash,options="nowrap"]
----
$ git config core.hooksPath .githooks
----
