
[#releasing_new_version]
= Releasing New Version

This section contains all information you need to release a new version of the documentation set to production. This update can happen anytime after the catalog has been updated, including after the release train has been completed.

[discrete]
== Procedure

.Releasing New Version to Production
. Ensure the catalog has been updated. Contact the development team for this information.

. Synchronize the {WildFlySwarm} sources. For more information, see xref:syncing-with-wildfly-swarm-docs[].

. Tag the release:
.. Execute the `tag_release.sh` script in the `$REPO_HOME/scripts` directory:
+
--
[source,bash]
----
$ ./tag_release.sh
----

The script automatically tags the commit with the current date in the `YYYY-MM-DD` format.
If you want to tag with a different date or manually, execute the following command:
[source,bash]
----
$ git tag 2017-04-21
----
If you are re-releasing the same day, a suffix `_2`, `_3`, etc. is appended.

--
.. Push the changes and tags:
+
--
[source,bash]
----
$ git push --follow-tags $REMOTE
----

Replace `$REMOTE` with the name of the upstream remote.
--

. Request publication:
.. File a pull request in the link:https://github.com/openshiftio/saas-launchpad/blob/master/launchpad-services/launcher-documentation.yaml#L2[openshiftio/saas-launchpad] repository, where you change the `hash` value to the hash of the commit you want to publish from the link:{link-repo-docs}[{repo-docs-name}] repository. Usually, this will be the latest commit in the `master` branch.
.. Wait for the pull request to be accepted. When that happens, verify that the link:{link-docs}[production build] succeeded.
.. Once your changes have been merged and the build succeeds, delete the topic branch you used to introduce the update.
+
[source,bash,options="nowrap",subs="attributes+"]
--
$ git branch -d $TOPIC_BRANCH_NAME
--
