
= Repository Filesystem Layout

The following diagram describes the filesystem layout of the _appdev-documentation_ repository:

NOTE: The triple-dot indicates there are more files or directories in the particular directory.

.Filesystem Layout
----
.
├── docs/ <1>
│   ├── topics/ <2>
│   │   ├── images/ <3>
│   │   ├── styles/ <4>
│   │   ├── templates/ <5>
│   │   │   ├── document-attributes.adoc <6>
│   │   │   ├── ...
│   │   ├── configmap-mission-design-tradeoffs.adoc
│   │   ├── ...
│   ├── $GUIDE_NAME/ <7>
│   │   ├── master.adoc <8>
│   │   ├── build_guide.sh <9>
│   │   └── topics/ -> ../topics <10>
│   ├── ...
├── scripts/ <11>
│   ├── build_guides.sh <12>
│   ├── validate_guides.sh <13>
│   ├── ...
├── cico_build_deploy <14>
├── CHANGELOG.adoc <15>
└── README.adoc
----
<1> The directory with the sources of all the _{docs-name}_ guides, the _launchpad.openshift.io_ page, and the contributor guide.
<2> The directory with the actual sources in AsciiDoc files. This directory is shared among all guides.
<3> The directory with all the images used in the sources.
<4> The directory with all the stylesheets used in the sources.
<5> The directory with all the templates used in the sources.
<6> The file where all the common document attributes are defined.
<7> The directory with the sources of a guide. Each guide has exactly one directory like this.
<8> The main AsciiDoc file of the guide. The files from the `topics` directory are included from this file.
<9> The script for building the particular guide.
<10> A symbolic link to the shared `$REPO_HOME/docs/topics/` directory.
<11> The directory with scripts used for manipulating files in the directory, building, and more.
<12> The script for building all guides at once. This script does not validate the guides.
<13> The script for validating all guides at once.
<14> The script to start local server and to publish to production. For more information, see xref:_starting_preview_server[].
<15> The file with changes made in each release.
