
:runtime: ${runtime}

ifeval::["{runtime}" == "Spring Boot"]
:localRunCMD: mvn spring-boot:run
:OSORunCMD: mvn clean fabric8:deploy -Popenshift
:guideURL: http://appdev.openshift.io/docs/spring-boot-runtime.html
:fileLocation: src/main/resources/static/index.html
endif::[]

ifeval::["{runtime}" == "Eclipse Vert.x"]
:localRunCMD: mvn vertx:run
:OSORunCMD: mvn clean fabric8:deploy -Popenshift
:guideURL: http://appdev.openshift.io/docs/vertx-runtime.html
:fileLocation: /src/main/resources/webroot/index.html
endif::[]

ifeval::["{runtime}" == "WildFly Swarm"]
:localRunCMD: mvn wildfly-swarm:run
:OSORunCMD: mvn clean fabric8:deploy -Popenshift
:guideURL: http://appdev.openshift.io/docs/wf-swarm-runtime.html
:fileLocation: /src/main/webapp/index.html
endif::[]



= ${mission} - ${runtime} Booster


IMPORTANT: While you can run and interact with this booster on our local host, it requires that you also have a database installed and configured. This booster runs best when deployed on OpenShift with a PostgreSQL database. For more details on using this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:{guideURL}[${runtime} Runtime Guide].


== Run this Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

$ oc new-app -e POSTGRESQL_USER=luke -ePOSTGRESQL_PASSWORD=secret -ePOSTGRESQL_DATABASE=my_data openshift/postgresql-92-centos7 --name=my-database

# Wait for `my-database` application to be running. 

$ {OSORunCMD}
----

== Interact with this Booster on a Single-node OpenShift Cluster

To interact with your booster while it's running on a Single-node Openshift Cluster, you first need to obtain it's URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route MY_APP_NAME -o jsonpath={$.spec.host}

MY_APP_NAME-MY_PROJECT_NAME.192.168.42.158.nip.io
----


You can use the form from at browser at your application's url or you can use the `curl` command:

.List all entries in the database
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://MY_APP_NAME-MY_PROJECT_NAME.192.168.42.158.nip.io/api/fruits

[ {
  "id" : 1,
  "name" : "Apple",
}, {
  "id" : 2,
  "name" : "Orange",
}, {
  "id" : 3,
  "name" : "Pear",
} ]
----

.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
----
curl http://MY_APP_NAME-MY_PROJECT_NAME.192.168.42.158.nip.io/api/fruits/3

{
  "id" : 3,
  "name" : "Pear",
}
----


.Create a new entry:
[source,bash,options="nowrap",subs="attributes+"]
----
curl -H "Content-Type: application/json" -X POST -d '{"name":"apple"}'  http://MY_APP_NAME-MY_PROJECT_NAME.192.168.42.158.nip.io/api/fruits

{
  "id" : 4,
  "name" : "apple",
}
----


.Update an Entry
[source,bash,options="nowrap",subs="attributes+"]
----
curl -H "Content-Type: application/json" -X PUT -d '{"name":"pineapple"}'  http://MY_APP_NAME-MY_PROJECT_NAME.192.168.42.158.nip.io/api/fruits/1

{
  "id" : 1,
  "name" : "pineapple",
}
----


.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
----
curl -X DELETE http://MY_APP_NAME-MY_PROJECT_NAME.192.168.42.158.nip.io/api/fruits/1
----

NOTE: If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.


== CI/CD Deployment
As part of the process of creating this booster, launch.openshift.io set up a project with a CI/CD deployment of this booster. You can see the status of this deployment in the link:https://manage.openshift.com[OpenShift Online Web console]. You can also learn more about this booster and rest of the ${runtime} runtime in the link:{guideURL}[${runtime} Runtime Guide].

