= Deploy the Database Application and CRUD API to OpenShift
//maven, not pipeline
.Start the Database
To create a new PostgreSQL database application, execute the following command:

[source,bash,option='nowrap']
--
oc new-app -e POSTGRESQL_USER=swarm -ePOSTGRESQL_PASSWORD=password -ePOSTGRESQL_DATABASE=fruits openshift/postgresql-92-centos7 --name=my-database
--

.Deploy the CRUD HTTP Application
To build and deploy the CRUD application on the OpenShift instance into which you are currently logged, execute the following command:
// The database credentials are stored in an OpenShift secret deployed during the application deployment.

[source,bash]
--
mvn clean fabric8:deploy -Popenshift -Dskiptests
--

Wait for the deployment process to complete.

////
.Determine the Route of your application
[source,bash]
--
oc get routes
--
[source,option="nowrap"]
----
$ oc get routes
NAME                 HOST/PORT                                         PATH      SERVICES             PORT      TERMINATION
app1                 app1.192.168.99.100.xip.io                        app1                           8080
----
////
