[[common-crud-database-interaction]]
= Interacting with the CRUD API

.  Once the application is running, you can access it using the _application URL_. To obtain the URL, execute the following command:
+
[source,bash,options="nowrap",subs="attributes+"]
--
oc get route {app-name} -o jsonpath={$.spec.host}
--
+
[source,option="nowrap",subs="attributes+"]
----
{app-name}-myproject.192.168.99.100.nip.io
----

. To access the web interface of the database application, navigate to the _application URL_ in your browser:
+
[source,bash,subs="attributes+"]
--
http://{app-name}-myproject.192.168.99.100.nip.io
--
+
Alternatively, you can make requests directly on the `api/fruits/*` endpoint using `curl`:
+
.List all entries in the database:
[source,bash,subs="attributes+"]
--
curl http://{app-name}-myproject.192.168.99.100.nip.io/api/fruits
--
+
----
[ {
  "id" : 1,
  "name" : "Apple",
  "stock" : 10
}, {
  "id" : 2,
  "name" : "Orange",
  "stock" : 10
}, {
  "id" : 3,
  "name" : "Pear",
  "stock" : 10
} ]
----
+
.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
--
curl http://{app-name}-myproject.192.168.99.100.nip.io/api/fruits/3
--
+
----
{
  "id" : 3,
  "name" : "Pear",
  "stock" : 10
}
----

+
.Create a new entry:
[source,bash,options="nowrap",subs="attributes+"]
--
curl -H "Content-Type: application/json" -X POST -d '{"name":"apple"}'  http://{app-name}-myproject.192.168.99.100.nip.io/api/fruits
--
+
----
{
  "name" : "apple",
  "id" : 4
}
----
+
.Update an Entry
[source,bash,options="nowrap",subs="attributes+"]
--
curl -H "Content-Type: application/json" -X PUT -d '{"name":"pineapple"}'  http://{app-name}-myproject.192.168.99.100.nip.io/api/fruits/1
--
+
----
{
  "name" : "pineapple",
  "id" : 1
}
----
+
.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
--
curl -X DELETE http://{app-name}-myproject.192.168.99.100.nip.io/api/fruits/1
--

If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.
