[[common-crud-database-interaction]]
= Interacting with the Application API

.  Once the application is running, you can access it using the _application URL_. To obtain the URL, execute the following command:
+
[source,bash,options="nowrap",subs="attributes+"]
--
oc get route {app-name} -o jsonpath={$.spec.host}
--
+
[source,bash,option="nowrap",subs="attributes+"]
----
{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com
----

. To access the web interface of the database application, navigate to the _application URL_ in your browser:
+
[source,bash,subs="attributes+"]
--
http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com
--
+
Alternatively, you can make requests directly on the `api/fruits/*` endpoint using `curl`:
+
.List all entries in the database:
[source,bash,subs="attributes+"]
--
curl http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/fruits
--
+
----
[ {
  "id" : 1,
  "name" : "Apple",
}, {
  "id" : 2,
  "name" : "Orange",
}, {
  "id" : 3,
  "name" : "Pear",
} ]
----
+
.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
--
curl http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/fruits/3
--
+
----
{
  "id" : 3,
  "name" : "Pear",
}
----

+
.Create a new entry:
[source,bash,options="nowrap",subs="attributes+"]
--
curl -H "Content-Type: application/json" -X POST -d '{"name":"apple"}'  http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/fruits
--
+
----
{
  "id" : 4,
  "name" : "apple",
}
----
+
.Update an Entry
[source,bash,options="nowrap",subs="attributes+"]
--
curl -H "Content-Type: application/json" -X PUT -d '{"name":"pineapple"}'  http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/fruits/1
--
+
----
{
  "id" : 1,
  "name" : "pineapple",
}
----
+
.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
--
curl -X DELETE http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com/api/fruits/1
--

If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.
