[[common-crud-database-interaction]]
= Interacting with the Application API

.  Once the application is running, you can access it using the _application URL_. To obtain the URL, execute the following command:
+
[source,bash,options="nowrap",subs="attributes+"]
--
$ oc get route {app-name}
--
+
[source,bash,option="nowrap",subs="attributes+"]
----
NAME                 HOST/PORT                                         PATH      SERVICES             PORT      TERMINATION
{app-name}           {app-name}-{project-name}.{os-route-hostname}              {app-name}           8080
----

. To access the web interface of the database application, navigate to the _application URL_ in your browser:
+
[source,bash,subs="attributes+"]
--
http://{app-name}-{project-name}.{os-route-hostname}
--
+
Alternatively, you can make requests directly on the `api/fruits/*` endpoint using `curl`:
+
.List all entries in the database:
[source,bash,subs="attributes+"]
--
$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/fruits
--
+
ifdef::node-js[]
----
[ {
  "id" : 1,
  "name" : "Apple",
  "stock" : "10"
}, {
  "id" : 2,
  "name" : "Orange",
  "stock" : "10"
}, {
  "id" : 3,
  "name" : "Pear",
  "stock" : "10"
} ]
----
endif::node-js[]
ifndef::node-js[]
----
[ {
  "id" : 1,
  "name" : "Cherry",
}, {
  "id" : 2,
  "name" : "Apple",
}, {
  "id" : 3,
  "name" : "Banana",
} ]
----
endif::node-js[]
+
.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
--
$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/fruits/3
--
+
ifdef::node-js[]
----
{
  "id" : 3,
  "name" : "Pear",
  "stock" : "10"
}
----
endif::node-js[]
ifndef::node-js[]
----
{
  "id" : 3,
  "name" : "Banana",
}
----
endif::node-js[]
+
.Create a new entry:
ifdef::node-js[]
[source,bash,options="nowrap",subs="attributes+"]
--
$ curl -H "Content-Type: application/json" -X POST -d '{"name":"peach","stock":"1"}'  http://{app-name}-{project-name}.{os-route-hostname}/api/fruits
--
+
----
{
  "id" : 4,
  "name" : "peach",
  "stock" : "1"
}
----
endif::node-js[]
ifndef::node-js[]
[source,bash,options="nowrap",subs="attributes+"]
--
$ curl -H "Content-Type: application/json" -X POST -d '{"name":"pear"}'  http://{app-name}-{project-name}.{os-route-hostname}/api/fruits
--
+
----
{
  "id" : 4,
  "name" : "pear",
}
----
endif::node-js[]
+
.Update an Entry
ifdef::node-js[]
[source,bash,options="nowrap",subs="attributes+"]
--
$ curl -H "Content-Type: application/json" -X PUT -d '{"name":"pineapple","stock":"100"}'  http://{app-name}-{project-name}.{os-route-hostname}/api/fruits/1
--
+
----
{
  "id" : 1,
  "name" : "pineapple",
  "stock" : "100"
}
----
endif::node-js[]
ifndef::node-js[]
[source,bash,options="nowrap",subs="attributes+"]
--
$ curl -H "Content-Type: application/json" -X PUT -d '{"name":"pineapple"}'  http://{app-name}-{project-name}.{os-route-hostname}/api/fruits/1
--
+
----
{
  "id" : 1,
  "name" : "pineapple",
}
----
endif::node-js[]
+
.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
--
$ curl -X DELETE http://{app-name}-{project-name}.{os-route-hostname}/api/fruits/1
--

If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.
