= Pushing Changes to a {OpenShiftLocal}

Local development is a fine initial approach, but one of the big opportunities microservices presents is developing for the cloud _first_. This means pushing changes to the cloud and testing them as they are being developed. This can reduce problems that arise from "Well, it worked on my machine". 

. link:{link-launcher-openshift-local-install-guide}#installing-a-openshiftlocal[Install] and link:{link-launcher-openshift-local-install-guide}#starting-and-configuring-the-openshiftlocal-for-the-launcher-application[start] a {OpenShiftLocal} using the instructions in the _{minishift-installation-guide-name} guide_.
. Login to your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new project in your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project my-wfs-booster
----

. Build your booster and push it to your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
+
This maven command builds your booster on your local machine and then deploys the built booster to your {OpenShiftLocal}.

. Wait for your booster to complete deployment.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
NAME                            READY     STATUS      RESTARTS   AGE
wfswarm-rest-http-1-deploy      1/1       Running     0          13s
wfswarm-rest-http-1-123ab       0/1       Running     0          8s
wfswarm-rest-http-s2i-1-build   0/1       Completed   0          2m
----
+
Your booster is deployed when the main pod has a status of `Completed` and `READY` is `1/1`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
NAME                            READY     STATUS      RESTARTS   AGE
wfswarm-rest-http-1-123ab       1/1       Running     0          1m
wfswarm-rest-http-s2i-1-build   0/1       Completed   0          4m
----
+
In the above example, `wfswarm-rest-http-1-123ab` is the main pod.


. Get the url for your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route wfswarm-rest-http
NAME                HOST/PORT                                              PATH      SERVICES            PORT      TERMINATION   WILDCARD
wfswarm-rest-http   wfswarm-rest-http-my-wfs-booster.{osl-route-hostname}             wfswarm-rest-http   8080                    None
----

. Interact with your booster.
+
Use `curl` to execute a `GET` request against the booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl wfswarm-rest-http-my-wfs-booster.{osl-route-hostname}/api/greeting
{"content":"Hi there, World!"}
$ curl wfswarm-rest-http-my-wfs-booster.{osl-route-hostname}/api/greeting?name=Sarah
{"content":"Hi there, Sarah!"}
----

You have deployed your booster to your local cloud and are able to interact with it. To push changes, re-run your maven command and wait for the main pod to be ready.
