= Using {launcher} with {OpenShiftOnline}

This section takes you through using {launcher} with {OpenShiftOnline} to create and deploy mission booster applications.

. Navigate to link:{link-launcher-oso}[{launcher}] using your browser.
. Select _Prepare for Takeoff_.
. Choose a launch option, for example _Use {OpenShiftOnline} to build and deploy_.
+
IMPORTANT: When using _Use {OpenShiftOnline} to build and deploy_, ensure you have followed the link to grant {launcher} access to your GitHub and {OpenShiftOnline} accounts. When you are on the `sso.openshift.io` page, you will need to click _Add_ for *BOTH* _GitHub_ and _OpenShift v3_ 

. Choose the mission, for example `REST API Level 0` and click _Next_.
. Choose the runtime you would like to run, for example `{VertX}`.
+
NOTE: Each mission illustrates a concept and is implemented as a booster in at least one runtime. You can come back to {launcher} later and try another mission and runtime.

. Enter an _OpenShift Project name_. You can also update any of the additional metadata fields or leave them as the default. Click _Next_.

Your booster is now prepared for launch. Depending on your launch option, you can follow the steps for xref:launcher-launch-booster-cd[] or xref:launcher-launch-booster-manual[] outlined in the _Using {launcher} with a {OpenShiftLocal}_ section.