= Pushing Changes to {OpenShiftOnline}

You can also use the same process for pushing changes to a {OpenShiftLocal} with {OpenShiftOnline}.

. Navigate to https://manage.openshift.com and log in.
. Click _Open Web Console_.
. Click on help in the upper right corner and select _Command Line Tools_.
. Use the command shown on that page to log in to {OpenShiftOnline} using a token, for example:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login https://api.starter-us-east-1.openshift.com --token=aaaa-bbccddeeffgg11223344
----

. Create a new project in {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project my-oso-wfs-booster
----

. Build your booster and push it to {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
+
This maven command builds your booster on your local machine and then deploys the built booster to {OpenShiftOnline}.

. Wait for your booster to complete deployment.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
NAME                            READY     STATUS      RESTARTS   AGE
wfswarm-rest-http-1-deploy      1/1       Running     0          13s
wfswarm-rest-http-1-123ab       0/1       Running     0          8s
wfswarm-rest-http-s2i-1-build   0/1       Completed   0          2m
----
+
Your booster is deployed when the main pod has a status of `Completed` and `READY` is `1/1`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
NAME                            READY     STATUS      RESTARTS   AGE
wfswarm-rest-http-1-123ab       1/1       Running     0          1m
wfswarm-rest-http-s2i-1-build   0/1       Completed   0          4m
----
+
In the above example, `wfswarm-rest-http-1-123ab` is the main pod


. Get the url for your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route wfswarm-rest-http
NAME                HOST/PORT                                              PATH      SERVICES            PORT      TERMINATION   WILDCARD
wfswarm-rest-http   wfswarm-rest-http-my-oso-wfs-booster.{osl-route-hostname}  
           wfswarm-rest-http   8080                    None
----

. Interact with your booster.
+
Use `curl` to execute a `GET` request against the booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl wfswarm-rest-http-my-oso-wfs-booster.{osl-route-hostname}/api/greeting/
{"content":"Hi there, World!"}
$ curl wfswarm-rest-http-my-oso-wfs-booster.{osl-route-hostname}/api/greeting?name=Sarah
{"content":"Hi there, Sarah!"}
----
