= Install the Launchpad on {OpenShiftLocal}

The Launchpad is where everything starts; it helps you create projects called _boosters_ intended to jumpstart your development with a fully-working application.  Each booster fulfills a _mission_, which defines the primary objective of your new project.  As an example, a mission might define how to open an HTTP endpoint or interact with a relational database.  Over time we'll continue to grow the available missions, showing you how to accomplish tasks common to real enterprise development.  And because the Launchpad sets you up with a continuous delivery pipeline, you'll be on your way to evolve the example to fit your needs.

The boosters are implemented in various runtimes such as {VertX}, {WildFlySwarm}, and {SpringBoot}, and within a mission are designed to be functionally equivalent.  Feel free to explore how the different frameworks compare!

Before you can use the Launchpad locally, you'll need to install it on {OpenShiftLocal} and configure it to integrate with your GitHub account.  {OpenShiftLocal} runs the OpenShift Container Platform using a virtual machine technology supported by your operating system.  Follow the instructions in link:{link-launchpad-openshift-local-install-guide}[{minishift-installation-guide-name}] to get this set up.