[[update-cd]]
= Update Using Continuous Delivery

This approach allows you to deploy updates directly from the GitHub repository created by the {launcher}. 

To update your booster using continuous delivery:

. Clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/PROJECT-NAME.git
----

. Open your project in your desired IDE or editor, such as xref:use_jbds[JBDS].

. Perform any updates you want to the the project. For example, if you were using the {VertX} HTTP booster, you could update the `src/main/resources/webroot/index.html` to have a different title in the `<h1>` element.
+
.Example update to `index.html`
[source,xml,options="nowrap",subs="attributes+"]
----
<div class="container">

    <div>
        <h1>Vert.x HTTP Booster - Updated</h1>
----

. Commit and push your changes back to GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git add src/main/resources/webroot/index.html
$ git commit -m "Updated title of main page"
$ git push
----

. Navigate back to the {OpenShiftLocal} Web console and ensure your mission's project is selected.

. Click on _Builds_ then _Pipelines_.

. Click _Start Pipeline_ to start a new build with your updates.
+
A new build will appear in the _Recent Runs_ list and the status of the `Build` and `Deploy` stages will appear. Optionally, you can click _View Log_ in your build to see the logs in Jenkins.

. After the `Deploy` stage is complete, return to the deployed version of your mission's booster application and observe that your changes appear.

== Optional: Trigger Builds Automatically with UltraHook

To configure {OpenShiftLocal} to automatically trigger a build when a new commit is made to GitHub, we will use the Ultrahook's proxy cloud application.
This application exposes a public endpoint that Github will call when an event (commit pushed example) is issued. If the ultrahook client is running on your local
machine, then it will forward the HTTP request to an Openshift Build Trigger endpoint in order to initiate the start of your booster's project build:

. Sign up for an UltraHook API Key link:http://www.ultrahook.com/register[here] and remember your _namespace_ from the form.

. Follow the instructions on the confirmation page to install UltraHook.

. From your project's overview page, click _Builds_ then _Pipelines_ then _Edit Pipeline_.

. Click _Show advanced options_.

. Under _Triggers_, copy the URL under _GitHub webhooks_.

. From the terminal, start UltraHook.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ ultrahook -k YOUR_ULTRAHOOK_KEY github MINISHIFT_WEBHOOK_URL
----

. Navigate to the _Webhooks_ section of your booster's GitHub project: `http://github.com/USERNAME/PROJECTNAME/settings/hooks/`

. Click _Add webhook_.

. In the _Add webhook_ enter:
+
** For _Payload URL_ enter the `http://github.ULTRAHOOK_NAMESPACE.ultrahook.com` replacing `ULTRAHOOK_NAMESPACE` with your namespace.
** For _Content type_ choose `application/json`.
** For _Which events would you like to trigger this webhook?_, choose `Just the push event`.

. Click _Add webhook_.

Every new commit pushed to the GitHub project of the booster will now issue an event that the ultrahook client (if it is running!) will capture in order
to call the https://docs.openshift.org/latest/dev_guide/builds/index.html#build-triggers[trigger] endpoint of our pipeline BuildConfig.

You might have noticed that one webhook was already set up in GitHub.
With {OpenShiftLocal}, that webhook points to a local IP address, which can't work.
You can delete that webhook and keep the UltraHook one.
