[[cd-oso]]
= Continuous Delivery using {OpenShiftOnline}

After using {launcher} to launch your booster, click on the _See it here!_ link under _Creating your project on the OpenShift cloud_ to go to your booster's page in the OpenShift Web console.

To view the build status of your project from the OpenShift Web console:

. Click _View Log_ in the pipeline at the top.
+
NOTE: It may take a few minutes for the link to appear.

. Click _Login with OpenShift_ at the login prompt for Jenkins.
. Click _Login with Red Hat_.
. Ensure all the boxes are checked and click _Allow selected permissions_.
+
This grants the OpenShift Web console the correct permissions and directs you to the Jenkins pod that is deploying your application.

Once your deployment is complete, interact with your booster using the url for the booster application at the top of the page. You can find more details on interacting with your booster in it's `README.adoc` on GitHub.

IMPORTANT: Your booster application is not the same as your Jenkins pod, and it will only appear after the Jenkins pod deploys it. This may take a few minutes.


To push changes to this booster in {OpenShiftOnline}, you can push a new commit to the GitHub repository:


. If you have not already done so, clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/PROJECT-NAME.git
----

. Open your project in your desired IDE or editor, such as xref:use_jbds[JBDS].
. Make an update to the project.
. Save your changes.
. Commit and push your changes back to GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git add .
$ git commit -m "Made an update"
$ git push
----

. Navigate Openshift Web Console and confirm a new deployment has started.
. Confirm your changes once your deployment is complete.


This confirms you have continuous delivery working with your booster, which automatically pushes changes in your booster to your {OpenShiftOnline} account.