= Using a {OpenShiftLocal} to Create a Booster
In addition to using {OpenShiftOnline} to create a booster, you can also use {OpenShiftLocal}. A {OpenShiftLocal} provides an out-of-the-box solution for setting up such an environment on your local machine without the need for extensive setup and configuration. Specifically, you can use the xref:launcher-details[{launcher} application] to clone a new booster repository to your GitHub account and have it deployed to your {OpenShiftLocal} using the xref:build-and-deploy-process[Build and Deploy process].

[sidebar]
.Before You Start...
--
* link:https://developers.redhat.com[Have a Red Hat Developers account]
* link:https://github.com[Have a GitHub account]
* link:{link-openshift-local-guide}[Have a {OpenShiftLocal} installed]
* link:{link-launcher-openshift-local-install-guide}#create-launcher-app[Have the {launcher} application installed to your {OpenShiftLocal}].
--

. Navigate to the {launcher} application on your {OpenShiftLocal} using your browser.
+
[NOTE]
====
Use the following command to open the Web Console of your {OpenShiftLocal} in your browser in order to navigate to your {launcher} application:

[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift console
----
====
. Select _Launch Your Project_.
. Select _Use {OpenShiftOnline}_.
. Follow the instructions to create a booster of your choice.
+
Doing this, you:
+
** Create a new GitHub repository in your account containing the code of your booster.
** Configure your {OpenShiftLocal} to build and deploy your code from your repository’s master branch.

. Click the _See it here!_ link under _Creating your project on the OpenShift cloud_ to go to the page of your booster's in the OpenShift Web console.

To navigate to the {OpenShiftLocal} Web console and view the status of your build, click _Take a look at your build_. You can expand your deployment and view the details as it deploys. Your deployment is complete when you see _Build #1 is complete_ under _Builds_ and you see `1 pod` in the blue circle.

When your deployment is complete, interact with your booster using the URL at the top of the page. For more details about interacting with your booster, see the `README.adoc` file in the booster's repository.

== Updating Your Booster and Deploying the Changes
At this point, you have created a new booster repository in your GitHub account and deployed it to your {OpenShiftLocal}. To push changes to this booster in your {OpenShiftLocal}, you can push a new commit to the GitHub repository and start a new build.

. Clone your project from GitHub:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/PROJECT-NAME.git
----

. Open your project in your desired IDE or editor, such as xref:use_devstudio[JBDS].
. Make an update to the project.
. Save your changes.
. Commit and push your changes back to GitHub:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git add .
$ git commit -m "Made an update"
$ git push
----

. Navigate back to the {OpenShiftLocal} Web console and ensure the project of your mission is selected.
. Click on the three dots on the right side of your application's deployment and choose _Start Build_.
+
A new build begins running. You can see more details about your build under the _Builds_ section. Your deployment is complete when you see _Build #2 is complete_ under _Builds_ and a `#2` next to the application's name under _Deployment_.
+
NOTE: This number will increase for each additional build and deployment.

. Confirm your changes when your deployment is complete.

