[[ultrahook-setup]]
= Triggering Builds Automatically with UltraHook

To configure your {OpenShiftLocal} to automatically trigger a build when a new commit is made to GitHub, we will use the UltraHook's proxy cloud application. This application exposes a public endpoint that GitHub will call when an event is issued, for example when a commit is pushed. If the UltraHook client is running on your local machine, then it will forward the HTTP request to an OpenShift Build Trigger endpoint in order to initiate the start of your booster's project build:

. link:http://www.ultrahook.com/register[Sign up for an UltraHook API Key] and remember your _namespace_ from the form.

. Follow the instructions on the confirmation page to install UltraHook.

. From your project's overview page, click _Builds_ then _Pipelines_ then _Edit Pipeline_.

. Click _Show advanced options_.

. Under _Triggers_, copy the URL under _GitHub webhooks_.

. From the terminal, start UltraHook.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ ultrahook -k YOUR_ULTRAHOOK_KEY github MINISHIFT_WEBHOOK_URL
----

. Navigate to the _Webhooks_ section of your booster's GitHub project: `+++http://github.com/USERNAME/PROJECTNAME/settings/hooks/+++`

. Click _Add webhook_.

. In the _Add webhook_ enter:
+
** For _Payload URL_ enter the `+++http://github.ULTRAHOOK_NAMESPACE.ultrahook.com+++` replacing `ULTRAHOOK_NAMESPACE` with your namespace.
** For _Content type_ choose `application/json`.
** For _Which events would you like to trigger this webhook?_, choose `Just the push event`.

. Click _Add webhook_.

Every new commit pushed to the GitHub project of the booster will now issue an event that the UltraHook client, if it is running, will capture in order to call the https://docs.openshift.org/latest/dev_guide/builds/index.html#build-triggers[trigger] endpoint of our pipeline BuildConfig.

You might have noticed that one webhook was already set up in GitHub. With your {OpenShiftLocal}, that webhook points to a local IP address, which will not work. You can delete that webhook and keep the UltraHook one.
