[[oso-create-booster]]
= Using {OpenShiftOnline} to Create a Booster
{OpenShiftOnline} is a robust target cloud environment for your applications and services. The xref:launcher-details[{launcher} application] provides a fast and easy way to create, build, and deploy a Mission booster directly to {OpenShiftOnline}.

[sidebar]
.Before You Start...
--
* link:https://www.openshift.com[Have an {OpenShiftOnline} account]
* link:https://developers.redhat.com[Have a Red Hat Developers account]
* link:https://github.com[Have a GitHub account]
--

. Navigate to link:{link-launcher-oso}[{launcher}] using your browser.
. Select _Launch your Project_.
+
IMPORTANT: This steps requires you to login using Red Hat Developers account.

. Choose your deployment type.
. Follow the instructions to create a booster of your choice.

The _Deploy in OpenShift Online_ option creates a new GitHub repository containing your booster and launches it to {OpenShiftOnline} while _Build and Run Locally_ creates a ZIP containing your booster that you can download to build and run locally.

Both options also provide a `README.adoc` file with details on building, deploying, and interacting with your booster from your local host.
