= Continuous Delivery using {OpenShiftLocal}

In addition to building on your local machine and pushing to a local or public cloud, you also have the ability to set up continuous delivery for a booster. Specifically, you can use the {launcher} application to clone a new booster repository to your GitHub account and have it deployed to your {OpenShiftLocal}.

. link:{link-launcher-openshift-local-install-guide}#create-launcher-app[Install the {launcher}] application to your {OpenShiftLocal}.
. Navigate to the {launcher} application on your {OpenShiftLocal} using your browser.
+
[NOTE]
====
Use the following command to open the Web Console of your {OpenShiftLocal} in your browser in order to navigate to your {launcher} application:

[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift console
----
====
. Select _Prepare for Takeoff_.
. Select _Use {OpenShiftOnline} to build and deploy_.
. Follow the instructions to create a booster of your choice.
+
Doing this, you:
+
** Create a new GitHub repository in your account containing the code of your booster.
** Create a pipeline to continuously deliver the code of your booster.
** The pipeline then builds and deploys the code of your booster to your {OpenShiftLocal}.

. Click the _See it here!_ link under _Creating your project on the OpenShift cloud_ to go to the page of your booster's in the OpenShift Web console.

To view the status of your project:

. Click _View Log_ in the pipeline at the top.
+
NOTE: It can take a few minutes for the link to appear.

. Click _Login with OpenShift_ at the login prompt for Jenkins.
. Log in with your {OpenShiftLocal} credentials, for example `developer` for the username and password.
. Ensure all the boxes are checked and click _Allow selected permissions_.
+
Doing this grants the OpenShift Web console the correct permissions and directs you to the Jenkins pod that is deploying your application.

When your deployment is complete, interact with your booster using the URL at the top of the page. For more details about interacting with your booster, see the `README.adoc` file in the booster repository.

IMPORTANT: Your booster application is not the same as your Jenkins pod, and it will only appear after the Jenkins pod deploys it. This can take a few minutes.

At this point, you have created a new booster repository in your GitHub account and deployed it to {OpenShiftLocal}. To push changes to this booster in {OpenShiftLocal}, you can push a new commit to the GitHub repository and start a build pipeline.


. Clone your project from GitHub:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/PROJECT-NAME.git
----

. Open your project in your desired IDE or editor, such as xref:use_jbds[JBDS].
. Make an update to the project.
. Save your changes.
. Commit and push your changes back to GitHub:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git add .
$ git commit -m "Made an update"
$ git push
----

. Navigate back to the {OpenShiftLocal} Web console and ensure the project of your mission is selected.
. Click _Builds_ -> _Pipelines_.
. Click _Start Pipeline_ to start a new build with your updates.
+
A new build appears in the _Recent Runs_ list with the status of the `Build` and `Deploy` stages. Optionally, click _View Log_ in your build to see the logs in Jenkins.

. Confirm your changes were applied when your deployment is complete.

