[[launcher-launch-booster]]
= Launching the Booster

To launch your booster from the launch screen, you have the following options.

[[launcher-launch-booster-cd]]
== Launching Using Continuous Delivery

To launch using continuous delivery, click the _Launch on OpenShift_ button.

This will:

* Create a new GitHub repository associated with your account containing the mission's code.
* Create a pipeline to continuously deliver your mission's code.
* The pipeline will then build and deploy your mission's code to your {OpenShiftLocal}.  The first launch and deployment should take under 10 minutes on most systems (depending upon resources and internet connection) as the Docker images powering the build are downloaded and cached. While the Docker images are being downloaded, you will see _Jenkins doesn't have label..._ , which is expected. Subsequent runs will be faster.

NOTE: In the GitHub repository, a webhook is created under _Settings_ -> _Webhooks_. When launching boosters with a {OpenShiftLocal}, this link points to your {OpenShiftLocal} and will not be accessible from outside the host your {OpenShiftLocal} is running on.

Click on the _See it here!_ link under _Creating your project on the OpenShift cloud_ to go to your booster's page in the OpenShift Web console.

To view the status of your project:

* In the pipeline at the top, click _View Log_.
+
NOTE: It may take a few minutes for the link to appear.

* This will prompt you with a log in for Jenkins. Click _Login with OpenShift_
* Use your {OpenShiftLocal} credentials, for example `developer` for both the username and password.
* Ensure all the boxes are checked and click _Allow selected permissions_.

You will be redirected to the startup logs in the `jenkins` pod. You have also given your {OpenShiftLocal} access to the `jenkins` pod and its logging information. Once you see the build start in the Jenkins logs, if you return to the _Overview_ page for your project in your {OpenShiftLocal}, you can see that the pipelines now show the build status.

Once your booster is deployed, you can then interact with its application or applications. You can find more details on how to interact with a mission's booster in the _interaction section_ of each mission's guide. For example, if you deployed the {VertX} {name-mission-http-api} mission booster, use the link:{link-mission-http-api-vertx}#interact[Interacting with the Unmodified {VertX} Booster] section in {mission-http-api-vertx-guide-name}. You can find a full list of mission guides in xref:available-missions[].

NOTE: Each mission guide covers deploying as well as interacting with the booster. If you have already deployed your booster using the steps above, skip the _deployment section_ in the mission guide which covers the process for xref:launcher-launch-booster-manual[launching manually].

[[launcher-launch-booster-manual]]
== Launching Manually

To launch manually, click on _Download as Zip_.

This will download a zip archive containing your booster project that you have to manually build and deploy. Each mission's guide provides complete instructions for building and deploying the booster project. For example, if you deployed the {VertX} {name-mission-http-api} mission, use the link:{link-mission-http-api-vertx}#rest_build_and_deploy_booster[Build and Deploy Your Booster] section in {mission-http-api-vertx-guide-name}. You can find more details on how to interact with a mission in the _interaction section_ of each mission's guide. You can find a full list of mission guides in xref:available-missions[].
