= Interacting with the Unmodified {Node} Booster

Once you have the {Node} booster deployed, you will have a service called `{app-name}` running that exposes the following REST endpoints:

/api/greeting::
This endpoint returns a JSON containing greeting of `name` parameter (or World as default value).

/api/stop::
This endpoint forces the service to become unresponsive which is meant to simulate a failure in the service.

The following steps demonstrate how to verify the service availability and simulate a failure. This failure of an available service causes the OpenShift self-healing capabilities to be trigger on the service.

NOTE: The below steps use the command line to interact with the service. Alternatively, you can use the web interface to perform the same steps (See #4).

. Use `curl` to execute a `GET` request against the `{app-name}` service. You can also use a browser to do this.
+
[source,bash,option="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/greeting
{"content":"Hello, World!"}
----

. Invoke the `/api/stop` endpoint and verify the availability of the `/api/greeting` endpoint shortly after that.
+
Invoking the `/api/stop` endpoint simulates an internal service failure and triggers the OpenShift self-healing capabilities. When invoking `/api/greeting` after simulating the failure, the service should return a HTTP status `503`.
+
[source,bash,option="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/stop
Stopping HTTP server, Bye bye world !

(followed by)

$ curl http://{app-name}-{project-name}.{os-route-hostname}/api/greeting
Not online
----

. Use `oc get pods -w` to continuously watch the self-healing capabilities in action.
+
While invoking the service failure, you can watch the self-healing capabilities in action on OpenShift console, or with the `oc` client tools. You should see the number pods in a `READY` state move to zero (`0/1`) and after a short period (less than one minute) move back up to one (`1/1`). In addition the `RESTARTS` count increases every time you you invoke the service failure.
+
[source,bash,option="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                           READY     STATUS    RESTARTS   AGE
{app-name}-1-26iy7   0/1       Running   5          18m
{app-name}-1-26iy7   1/1       Running   5         19m
----

. Optional: Use the web interface to invoke the service.
+
Alternatively to the interaction using the terminal window, you can use the web interface provided by the service to invoke the different methods and watch the service move through the life cycle phases.
+
[source,bash,option="nowrap",subs="attributes+"]
--
http://{app-name}-{project-name}.{os-route-hostname}
--

include::health-check-mission-web-console-log-output.adoc[]
