[[health_check_build_and_deploy_booster]]
= Build and Deploy the Booster

include::booster-deploy-openshift-local.adoc[leveloffset=+1]

[[health_check_deploy-booster-osl-cli]]
=== Deploy Using the `oc` CLI Client

include::oc-client-deploy-booster-download-note.adoc[leveloffset=+3]

include::booster-deploy-get-cli-token.adoc[levelloffset=+3]

. Create a new project in your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

ifndef::http-api-nodejs[]
. Use maven to start the deployment to {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on {OpenShiftLocal} and to start the pod.
endif::http-api-nodejs[]

ifdef::http-api-nodejs[]
. Use npm to start the deployment to {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install && npm run openshift
----
+
These commands install any missing package dependencies, then using the xref:about-nodeshift[Nodeshift] package, launch the S2I process on {OpenShiftLocal} to start the pod.
endif::http-api-nodejs[]


. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa   1/1       Running   0           14s
{app-name}-1-deploy  0/1       Completed 0           22s
----
+
Your `{app-name}-1-aaaaa` pod should have a status of `Running` once it's fully deployed and started. You should also wait for your pod to be ready before proceeding, which is shown in the `READY` column. For example, `PROJECT_NAME-1-aaaaa` is ready when the `READY` column is `1/1`.


. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                   HOST/PORT                                            PATH      SERVICES               PORT      TERMINATION   WILDCARD
{app-name}   {app-name}-{project-name}.{osl-route-hostname}           {app-name}   8080                    None
----
+
A pod's route information gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-{project-name}.{osl-route-hostname}` as the base URL to access the applications.



include::booster-deploy-openshift-online.adoc[leveloffset=+1]
