= Interact with the Unmodified {WildFlySwarm} Booster

Once you have the {WildFlySwarm} booster deployed, you will have a service called  `{app-name}` running that exposes a two REST endpoints: `/api/greeting` which returns a name as a String and `/api/killme`, which forces the service to become unresponsive as means to simulate a failure.

In the following we demonstrate the basic interactions on the command line that can be used verify the service availability and simulate a failure that causes the Openshift self-healing capabilities to be trigger on the service. Alternatively you can use the service web interface to perform these steps (See #4).

. Use `curl` to execute a `GET` request against the `{app-name}` service. You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl http://{app-name}-{project-name}.192.168.64.3.nip.io/api/greeting
{"content":"Hello, World!"}
----

. To simulate a service internal failure and to trigger the openshift selfhealing capabilities, invoke the `/api/killme` endpoint and verify the availability of the `/api/greeting` endpoint shortly after that. It should return a HTTP status 503:
+
[source,bash,option="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.192.168.64.3.nip.io/api/killme

(followed by)

$ curl http://{app-name}-{project-name}.192.168.64.3.nip.io/api/greeting

<html>
  <head><title>Error</title></head>
  <body>503 - Service Unavailable</body>
</html>
----

. While performing these operations you can use the Openshift console, or the `oc` client tools to watch the self-healing capabilities in action. Use `oc get pods -w` to continuously watch the service state from another terminal window. You should see that number pods in a `READY` state moves to zero (`0/1`) and after a while (~30 sec to 1 min) back up to one (`1/1`). In addition the `RESTARTS` count increases every time you kill the service:
+
[source,bash,options="nowrap",subs="attributes"]
----
$ oc get pods -w
NAME                           READY     STATUS    RESTARTS   AGE
{app-name}-1-26iy7   0/1       Running   5          18m
{app-name}-1-26iy7   1/1       Running   5         19m

----

. Alternatively to the interaction using the terminal window, you can use the web interface provided by the service to invoke the different methods and watch the service move through the life cycle phases:
+
[source,bash,option="nowrap",subs="attributes"]
--
$ http://{app-name}-{project-name}.192.168.64.3.nip.io
--

. Optional: Use the web interface to view the log output generated by the application at each stage of the self-healing process.
+
1. Navigate to your project
2. On the sidebar, click on _Applications_, then _Pods_
3. Click on the `{app-name}-1-26iy7` pod to display the details page.
4. Select the _Events_ tab to view the log output.
