= Update your Booster Manually

. Clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/PROJECT-NAME.git
----

. Open your project in your desired IDE or editor.

. Perform any updates you want to the the project.

. Ensure you are logged in with your `oc` CLI client.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login OPENSHIFT_URL
  ...follow prompts for username and password

  - or -

$ oc login OPENSHIFT_URL --token=$MYTOKEN
 ...@see how to obtain your token in note below

$ oc project PROJECT_NAME
----
+
NOTE: You can find your token in your Open Web console. For example, if your OPENSHIFT_URL is `https://console.starter-us-east-1.openshift.com`, your token would be located at `https://console.starter-us-east-1.openshift.com/console/command-line`. 

. Use maven to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on OpenShift and to start the pod.
+
NOTE: A mission's booster may contain tests that assume the build process is running on OpenShift. Since you are building your mission's booster outside of OpenShift before deploying it, you can use `-DskipTests` to skip the testing process. 
. Navigate to project's overview page in the OpenShift Web console.

You will notice a new deployment running. Once complete, click on the link for booster application at the top of the page and observe your changes appear.