:icons: font

.Next Steps: Update your Booster Manually

You can build and deploy your booster application using the Fabric8 Maven Plugin to launch the link:{link-wf-swarm-runtime-guide}#s2i-build-process[S2I process] on OpenShift.

. Clone your project from GitHub.
+
[source,bash,subs="attributes+"]
----
$ git clone git@github.com:USERNAME/PROJECT-NAME.git
----

. Open your project in your desired IDE or editor.
. Perform any updates you want to the project.

. Log in with your `oc` CLI client and change to your booster's project.
+
[source,bash,subs="attributes+"]
----
$ oc login OPENSHIFT_CONSOLE_URL
$ oc project PROJECT_NAME
----

. Use Maven to start the deployment to OpenShift.
+
[source,bash,subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
//+
//NOTE: A mission's booster may contain tests that assume the build process is running on OpenShift. Since you are building your mission's booster outside of OpenShift before deploying it, you can use `-DskipTests` to skip the testing process.

. Click _See it here!_ in _Creating your project on OpenShift Online_.

Notice a new deployment is running! Once complete, click on the link for booster application at the top of the page and observe your changes appear.
