[[install-local-cloud]]
= Prerequisite: Install a {OpenShiftLocal}

In order to use the {launcher} application on a local cloud, you must have a {OpenShiftLocal} installed and configured. You can use either {Minishift} `{MinishiftVersion}` or {CDK} `{CDKVersion}`.

== Install {Minishift}
The installation steps for {Minishift} are available link:https://docs.openshift.org/latest/minishift/getting-started/installing.html[in the OpenShift documentation] and vary by platform.

. Verify you have {Minishift} installed and configured.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift version
minishift v1.3.1+f4900b07
----

. Determine the command to add the correct version of the `oc` binary to your path and run the command.
+
WARNING: The below command may return `Cannot find OpenShift client binary.` if you have never started {Minishift}. To resolve this issue, you need to allow {Minishift} to start up at least once (`minishift start`). Once {Minishift} has completed its initial startup, you need to stop it (`minishift stop`) before proceeding.
+
.Example Result of `oc-env`
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v1.5.1:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)

$ eval $(minishift oc-env)
----
+
WARNING: You must have the `oc` binary installed and it *MUST* match the version of {Minishift} you are using.


. Verify the `oc` CLI tools is on your path.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
----


== Install {CDK}

The installation steps for {CDK} are available link:https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.0/html-single/installation_guide/[in {CDK} Installation Guide] and vary by platform.


. Verify you have {CDK} and the `oc` CLI tools installed and configured.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift version
Minishift version: 1.0.0+4f8cb6d
CDK Version: 3.0.0
----

. Determine the command to add the correct version of the `oc` binary to your path and run the command.
+
WARNING: The below command may return `Cannot find OpenShift client binary.` if you have never started {Minishift}. To resolve this issue, you need to allow {Minishift} to start up at least once (`minishift start`). Once {Minishift} has completed its initial startup, you need to stop it (`minishift stop`) before proceeding.
+
.Example Result of `oc-env`
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v3.5.5.8:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)

$ eval $(minishift oc-env)
----
+
WARNING: You must use the `oc` binary installed with {CDK}.

. Verify the `oc` CLI tools is on your path.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc version
oc v3.5.5.8
kubernetes v1.5.2+43a9be4
features: Basic-Auth
----
