// name variable defined locally, because it is only used in this topic
:nexus-project-name: NEXUS_PROJECT_NAME

= Using a Nexus Repository Server With the {launcher} Application on your {OpenShiftLocal}

While developing your cloud-native applications with Java and Maven you may be required to build them repeatedly.
You can deploy a Nexus Repository server alongside the {launcher} application on your {OpenShiftLocal} and use it to fetch artifacts from the Maven Central Repository and cache them locally.
This helps you speed up your builds and rolling updates and alleviates network load during build time.

== Setting up Your {OpenShiftLocal} for using Nexus.

* Run a {OpenShiftLocal} on your machine. For detailed instructions on how to do this, follow the instructions in link:{link-launcher-openshift-local-install-guide}[{minishift-installation-guide-name}].
S
* Configure your {OpenShiftLocal} to use at least 4096 MiB of RAM.
+
[source,bash,subs="attributes+"]
--
minishift delete # Delete the existing instance of the {OpenShiftLocal}
minishift config set memory 4096 # configure your {OpenShiftLocal} to use the required amount of RAM. You must create a new instance of the {OpenShiftLocal} for these changes to take effect.
minishift start # this creates a new instance of the {OpenShiftLocal} with the updated configuration
--
+
[WARNING]
--
The procedure described below works with {Minishift} version `1.3.1`.
It has not been tested for use with CDK.
--

* link:{link-launcher-openshift-local-install-guide}#create-launcher-app[Deploy the {launcher} application] to your {OpenShiftLocal}.

* link:{link-getting-started-guide}#_continuous_delivery_using_single_node_openshift_cluster[Deploy a Booster application] to your {OpenShiftLocal}.

== Setting up the Nexus Application

. Log in to your {OpenShiftLocal} instance.
+
[source,bash,subs="attributes+"]
--
oc login https://{osl-login-url} -u developer -p developer
--
+
. *OPTIONAL*: You can reuse the Docker daemon instance used by your {OpenShiftLocal} to download the latest version of the Nexus Docker container image.
+
[source,bash,subs="attributes+"]
--
eval $(minishift docker-env)
docker pull openshift/jenkins-2-centos7
docker pull openshiftio/launchpad-jenkins-slave
docker pull sonatype/nexus
--
+
.  Create a new project to contain the Nexus server. You can also use the _New Project_ button on the Web console to do this.
+
[source,bash,subs="attributes+"]
--
oc new-project {nexus-project-name}
--
+
. Deploy the Nexus container image.
+
[source,bash,subs="attributes+"]
--
oc new-app sonatype/nexus
--
+
. Expose the service route URL of the Nexus server.
+
[source,bash,subs="attributes+"]
--
oc expose svc/nexus
--
+
. Attach a 1 GiB persistent storage volume to the Nexus application.
+
[source,bash,subs="attributes+"]
--
oc volumes dc/nexus --add --name 'nexus-volume-1' --type 'pvc' --mount-path '/sonatype-work/' --claim-name 'nexus-pv' --claim-size '1Gi' --overwrite
--
+
. Find the external address of the Nexus instance:
+
[source,bash,subs="attributes+"]
--
oc get routes
--
+
[source,bash,subs="attributes+"]
----
NAME      HOST/PORT                              PATH      SERVICES   PORT       TERMINATION
nexus     nexus-{nexus-project-name}.{osl-route-hostname}             nexus      8080:8080
----
+
[NOTE]
--
Nexus comes pre-configured for the Maven Central Repository, but you may need other repositories for your application. To access images provided by Red Hat, add the `jboss-ga` Maven repository to your Nexus instance.
--
+
.  Navigate to the project containing your Booster application.
+
[source,bash,subs="attributes+"]
--
oc project {project-name}
--
+
. Assign the `admin` role to your Jenkins application and the `edit` permissions to your OpenShift account.
Skip this step if you have already assigned these permissions.
+
[source,bash,subs="attributes+"]
--
oc policy add-role-to-user edit system:serviceaccount:{project-name}:default
oc policy add-role-to-user admin system:serviceaccount:{project-name}:jenkins
--
+
. Obtain the Jenkins server URL and use it to access the Jenkins instance from your browser.
+
[source,bash,subs="attributes+"]
--
oc get routes jenkins
--
+
[source,bash,subs="attributes+"]
--
NAME      HOST/PORT                                         PATH      SERVICES   PORT      TERMINATION
jenkins   jenkins-{app-name}-{project-name}.{osl-route-hostname}             jenkins    <all>     edge/Redirect
--
+
. Navigate to `jenkins-{app-name}-{project-name}.{osl-route-hostname}/configure`, and log in using your OpenShift credentials to access the Jenkins configuration page.
+
. On the configuration page:
* go to the section titled _Kubernetes Pod Template_,
* find the template named `launchpad-maven`,
* in the section under this template, click the _Add Evironmental Variable_ button, and select the _Global Environmental Variable_ option from the drop-down menu.
+
. Define a new environment variable:
* Name: `MAVEN_MIRROR_URL`
* Value: `http://nexus-{nexus-project-name}.{osl-route-hostname}/nexus/content/groups/public/`
+
[NOTE]
--
The actual value of the `MAVEN_MIRROR_URL` environmental variable corresponds to the service route of the pod running the Nexus server instance on your {OpenShiftLocal}.

To obtain this route, navigate to the project that contains your Nexus instance and execute the command `oc get routes nexus`.
--
+
. Click _Apply_ to confirm the configuration changes.
+
. Redeploy the Jenkins server instance with the latest configuration changes.
+
[source,bash,subs="attributes+"]
--
oc rollout latest dc/jenkins
--
+
[WARNING]
--
KNOWN ISSUE: Redeploying your instance of Jenkins server causes other ongoing builds to hang.
--
+
. In the Web console, navigate to the project that contains your Booster application.
. Navigate to _Builds_ > _Pipelines_ using the web console Sidebar.
. Click the _Start Pipeline_ button to rebuild your Booster application.
