// name variable defined locally, because it is only used in this topic
:nexus-project-name: NEXUS_PROJECT_NAME

= Using a Nexus Repository Server With the {launcher} Application on a {OpenShiftLocal}

While developing your cloud-native applications with Java and Maven you may be required to build them repeatedly.
You can deploy a Nexus Repository server alongside the {launcher} application on your {OpenShiftLocal} and use it to fetch artifacts from the Maven Central Repository and cache them locally.
This helps you speed up your builds and rolling updates and alleviates network load during build time.

== Prerequisites for Deploying Nexus on {OpenShiftLocal}.


* Set up your {OpenShiftLocal}. For detailed steps on how to do this, follow the instructions in link:{link-launcher-openshift-local-install-guide}[{minishift-installation-guide-name}].

////
* Set up your project for use with Maven. For more information on how to do this see the link:https://maven.apache.org/guides/getting-started/index.html[Maven Getting Started Guide^]
////

////
* Verify that your application image has a `MAVEN_MIRROR_URL` environment variable. If it does not have this environmental variable, follow the link:https://books.sonatype.com/nexus-book/reference/config.html[Nexus documentation^] to configure your build.
////

////
* Ensure that you give each pod enough resources to function. You may have to edit the link:https://docs.openshift.com/container-platform/3.4/dev_guide/deployments/how_deployments_work.html#creating-a-deployment-configuration[pod template] in the Nexus deployment configuration to request more resources.
////

* Configure your {OpenShiftLocal} to use at least 4096 MiB of RAM and use the required `oc` CLI tool version.
+
[source,bash,subs="attributes+"]
--
minishift delete # Delete the previous instance of {OpenShiftLocal}
minishift config set memory 4096
minishift config set openshift-version v3.6.0
minishift start
--
+
[WARNING]
--
The procedure described below works with {Minishift} version `1.5.0`.
It has not been tested for use with CDK.
You must use `oc` version `3.6.0` or later.
--

* Deploy the {launcher} application to your {OpenShiftLocal}.

* Deploy a Booster application to your {OpenShiftLocal}.

== Configuring your {OpenShiftLocal} to Use Nexus.

. Log in to your {OpenShiftLocal} instance.
+
[source,bash,subs="attributes+"]
--
oc login https://{osl-login-url} -u developer -p developer
--
+
. You can reuse the Docker daemon instance used by {OpenShiftLocal} to download the latest versions of the Nexus Docker container image.
+
[source,bash,subs="attributes+"]
--
eval $(minishift docker-env)
docker pull openshift/jenkins-2-centos7
docker pull openshiftio/launchpad-jenkins-slave
docker pull sonatype/nexus
--

== Setting up the Nexus Application

.  Create a new project to contain the Nexus server. You can also use the _New Project_ button on the Web console to do this.
+
[source,bash,subs="attributes+"]
--
oc new-project {nexus-project-name}
--
+
. Deploy the Nexus container image.
+
[source,bash,subs="attributes+"]
--
oc new-app sonatype/nexus
--
+
. Expose the service route URL of the Nexus server.
+
[source,bash,subs="attributes+"]
--
oc expose svc/nexus
--
+
. Attach a 1 GiB persistent storage volume to the Nexus application.
+
// NOTE: seems that minishift (with oc v 3.6.0alpha1) is fine with USING '1G'  for volume size, while openshift Online requires the syntax '1Gi'.
+
[source,bash,subs="attributes+"]
--
oc volumes dc/nexus --add --name 'nexus-volume-1' --type 'pvc' --mount-path '/sonatype-work/' --claim-name 'nexus-pv' --claim-size '1Gi' --overwrite
--
+
. Find the external address of the Nexus instance:
+
[source,bash,subs="attributes+"]
--
oc get routes
--
+
[source,bash,subs="attributes+"]
----
NAME      HOST/PORT                              PATH      SERVICES   PORT       TERMINATION
nexus     nexus-{nexus-project-name}.{osl-route-hostname}             nexus      8080:8080
----
+
[NOTE]
--
Nexus comes pre-configured for the Maven Central Repository, but you may need other repositories for your application. To access images provided by Red Hat, add the `jboss-ga` Maven repository to your Nexus instance.
--
+
.  Navigate to the project containing your Booster application.
+
[source,bash,subs="attributes+"]
--
oc project {project-name}
--
+
. Assign the `admin` role to your Jenkins application and the `edit` permissions to your OpenShift account.
Skip this step if you have already assigned these permissions.
+
[source,bash,subs="attributes+"]
--
oc policy add-role-to-user edit system:serviceaccount:{project-name}:default
oc policy add-role-to-user admin system:serviceaccount:{project-name}:jenkins
--
+
. Obtain the Jenkins server URL and use it to access the Jenkins instance from your browser.
+
[source,bash,subs="attributes+"]
--
oc get routes jenkins
--
+
[source,bash,subs="attributes+"]
--
NAME      HOST/PORT                                         PATH      SERVICES   PORT      TERMINATION
jenkins   jenkins-{app-name}-{project-name}.{osl-route-hostname}             jenkins    <all>     edge/Redirect
--
+
. Navigate to `jenkins-{app-name}-{project-name}.{osl-route-hostname}/configure`, and log in using your OpenShift credentials to access the Jenkins configuration page.
+
. Go to the section titled _Kubernetes Pod Template_,  click on _Add Evironmental Variable_, and select _Global Environmental Variable_ option from the drop-down menu.
+
. Define a new environment variable:
* Name: `MAVEN_MIRROR_URL`
* Value: `nexus-{nexus-project-name}.{osl-route-hostname}/nexus/content/groups/public/`
+
[NOTE]
--
The actual value of the `MAVEN_MIRROR_URL` environmental variable corresponds to the service route of the pod running the Nexus server instance on your {OpenShiftLocal}.

To obtain this route, navigate to the project that contains your Nexus instance and execute the command `oc get routes nexus`.
--
+
. Click _Apply_ to confirm the configuration changes.
+
. Redeploy the Jenkins server instance with the latest configuration changes.
+
[source,bash,subs="attributes+"]
--
oc rollout latest dc/jenkins
--
+
[WARNING]
--
KNOWN ISSUE: Redeploying your instance of Jenkins server causes other ongoing builds to hang.
--
+
.  Navigate to the project that contains your Booster and use the Web console to go to _Builds_ > _Pipelines_ and click _Start Pipeline_ to rebuild your Booster application.
