[[mission-secured-deploy-rhsso-zip]]
= Deploying Using the `oc` CLI Client

:sso-app-name: secure-sso
:sso-auth-url: https://{sso-app-name}-MY_PROJECT_NAME.{osl-route-hostname}/auth

include::oc-client-deploy-booster-download-note.adoc[leveloffset=+1]

. Get your authentication token for using the `oc` CLI client with your {OpenShiftLocal} account. You can find this in the _Command Line Tools_ section your {OpenShiftLocal} Web console.

. Authenticate your `oc` CLI client with your {OpenShiftLocal} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

. Create a new project in your {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

. Deploy the SSO server.
+
[source,bash,options="nowrap"]
----
$ cd sso
$ mvn fabric8:deploy
----

. Determine the SSO_AUTH_SERVER_URL value.
+
[[SSO_AUTH_SERVER_URL]]
For the Secured REST booster, you need to configure the {RHSSO} authorization endpoint. The booster project generates
`target/sso-client.jar` when you built the {RHSSO} server. You can run `target/sso-client.jar` from the command line to determine the `SSO_AUTH_SERVER_URL`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ java -jar target/sso-client.jar --displaySSOURL
Successful oc get routes: Yes
Using auth server URL: {sso-auth-url}
Available application endpoint names: []
----
+
The line starting with `Using auth server URL:` is the line that provides the `SSO_AUTH_SERVER_URL`. In this case it is `{sso-auth-url}`. You will need this value later.

. Package and deploy your {runtime-name} booster to your {OpenShiftLocal}
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd ../app
$ mvn fabric8:deploy -DSSO_AUTH_SERVER_URL=<SSO_AUTH_SERVER_URL from above...> -Popenshift -DskipTests=true
$ cd ..
----
+
IMPORTANT: Make sure you pass in the SSO_AUTH_SERVER_URL you obtained during the xref:SSO_AUTH_SERVER_URL[previous step].
+
This process will generate the uber JAR file as well as the OpenShift resources and deploy them to the current project on your {OpenShiftLocal} server.
