[id='deploying-an-application-to-standalone-rhel_{context}']
= Deploying an application to standalone Red Hat Enterprise Linux

You can deploy a {runtime} application to Red Hat Enterprise Linux.

.Prerequisites

* A Maven-based application
* RHEL 7 installed
* OpenJDK 8 installed
* Maven 3.5 or later installed


.Procedure

// TODO:
//define parameter: name-runtime
//define parameter:
. Ensure that you specify the link:https://maven.repository.redhat.com/[Red Hat Maven repository] in the `pom.xml` of your project, and that the {parameter-runtime-name} plugin is configured properly:
+
[source,xml,options="nowrap",subs="attributes+"]
----
...
<repositories>
  <repository>
    <id>{red-hat-ga-repo-id}</id>
    <name>{red-hat-ga-repo-name}</name>
    <url>{red-hat-ga-repo-url}</url>
  </repository>
</repositories>
...
<pluginRepositories>
    <pluginRepository>
      <id>{red-hat-ga-repo-id}</id>
      <name>{red-hat-ga-repo-name}</name>
      <url>{red-hat-ga-repo-url}</url>
    </pluginRepository>
  </pluginRepositories>
...
<build>
  <plugins>
    <plugin>
      <groupId>{group-name-runtime-plugin}</groupId>
      <artifactId>{artifact-name-runtime-plugin}</artifactId>
      <version>{version-runtime-plugin}</version>
ifdef::built-for-vertx[]
      <executions>
        <execution>
          <id>vmp</id>
          <goals>
            <goal>initialize</goal>
            <goal>package</goal>
          </goals>
        </execution>
      </executions>
endif::[]
ifdef::built-for-thorntail[]
      <executions>
        <execution>
          <goals>
            <goal>package</goal>
          </goals>
        </execution>
      </executions>
endif::[]
    </plugin>
  </plugins>
</build>
...
----

//:version-runtime-plugin: ${vertx-maven-plugin.version}

. Package your application.
// fat jar packaging is configured in the runtime plugins by default.
Consider packaging your application as a fat JAR to include all of the necessary dependencies.
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn clean package
----

. Start your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ java -jar target/my-app.jar
----

.Verification steps

. Use 'curl' or your browser to verify your application is running at `http://localhost:8080`
+
[source,bash,options="nowrap"]
----
curl http://localhost:8080
----
