[id='installing-a-openshiftlocal_{context}']
[#installing-a-openshiftlocal]
= Installing a {OpenShiftLocal}

To use the {launcher} tool on a local cloud, you must have a {OpenShiftLocal} installed and configured. You can use either {Minishift} or {CDK}.

.Prerequisites

* link:https://developers.redhat.com[Have a Red Hat Developers account]

.Procedure

. Follow the instructions for installing the {OpenShiftLocal}:
+
--
* The installation steps for {Minishift} are available link:https://docs.openshift.org/latest/minishift/getting-started/installing.html[in the OpenShift documentation].
* The installation steps for {CDK} are available link:https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.0/html-single/installation_guide/[in the {CDK} Installation Guide].

NOTE: The steps for installing {OpenShiftLocal} vary by platform.
--
. Verify you have the {OpenShiftLocal} installed and configured:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift version
----
. Start and stop the {OpenShiftLocal}:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift start
...
$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
----
. Determine the command to add the correct version of the `oc` binary to your path and run the command:
+
.Example Result of `oc-env` on {CDK}
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v3.5.5.8:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)

$ eval $(minishift oc-env)
----
+
WARNING: You must have the `oc` binary installed and it _must_ match the version of the {OpenShiftLocal} you are using.

