= Add Debug Logging on {SpringBoot}

Add debug logging to your application.

.Prerequisites 
* An application you want to debug. For example, the xref:mission-rest-http-spring-boot[{name-mission-http-api} booster].

.Procedure

. Declare a `org.apache.commons.logging.Log` object using the `org.apache.commons.logging.LogFactory` for the class you want to add logging.
+
[source,java,options="nowrap",subs="attributes+"]
----
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
...
private static Log logger = LogFactory.getLog(TheClass.class);
----
+
For example, if you wanted to add logging to the `GreetingEndpoint` class in the xref:mission-rest-http-spring-boot[{name-mission-http-api} booster], you would use `GreetingEndpoint.class`.

. Add debugging statements using `logger.debug("my logging message")`.
+
.Example logging statement
[source,java,options="nowrap",subs="attributes+"]
----
@GET
@Path("/greeting")
@Produces("application/json")
public Greeting greeting(@QueryParam("name") @DefaultValue("World") String name) {
    String message = String.format(properties.getMessage(), name);
    
    logger.debug("Message: " + message);
    
    return new Greeting(message);
}
----

. Add a `logging.level.fully.qualified.name.of.TheClass=DEBUG` in `src/main/resources/application.properties`.
+
For example, if you added a logging statement to `io.openshift.booster.service.GreetingEndpoint` you would use:
+
[source,properties,options="nowrap",subs="attributes+"]
----
logging.level.io.openshift.booster.service.GreetingEndpoint=DEBUG
----
+
This enables log messages at the `DEBUG` level and above to be shown in the logs for your class. 
