[id='using-server-sent-events-in-a-reactive-spring-boot-application_{context}']
= Using Server-sent events in a reactive {SpringBoot} application

Create a simple service that accepts HTTP requests and returns a stream of server-sent events (SSE).
When the client establishes a connection to the server and the streaming starts, the connection remains open. The server re-uses the connection to continuously push new events to the client.
Canceling the request closes the connection and stops the stream, causing the client to stop receiving updates form the server.

.Prerequisites

* JDK 8 or JDK 11 installed
* Maven installed
* A Maven-based application project link:{link-guide-spring-boot}#configuring-your-application-to-use-spring-boot_spring-boot[configured to use Spring Boot]


.Procedure

. Add `vertx-spring-boot-starter-http` as a dependency in the `pom.xml` file of your project.
+
.`pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
...
  <dependencies>
  ...
include::resources/spring-boot/reactive-examples/example-sse-service-pom.xml[tags=sse-service-pom-dependencies]
  ...
  <dependencies>
...
</project>
----

. Create the main class of your application:
+
.`SseExampleApplication.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-sse-application.java[]
----

. Create a Server-sent Event controller class for your application.
In this example, the class generates a stream of random integers and sends them to a terminal application.
+
.`SseController.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-sse-service-sse-controller.java[]
----

. OPTIONAL: Run and test your application locally:
.. Navigate to the root directory of your Maven project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd myApp
----

.. Package your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean package
----

.. Start your application from the command line:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ java -jar target/vertx-spring-boot-sample-sse.jar
----
.. In a new terminal window, issue a HTTP request to `localhost`.
You start receiving a continuous stream of random integers from the server-sent event controller:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl localhost:8080
data:-2126721954

data:-573499422

data:1404187823

data:1338766210

data:-666543077
...
----
+
Press `Ctrl`+`C` to cancel your HTTP request and terminate the stream of responses.


.Additional resources

* You can link:{link-guide-spring-boot}#deploying-runtime-application-to-openshift_spring-boot[deploy your application to an OpenShift cluster] using Fabric8 Maven Plugin.

* You can also configure your application for link:{link-guide-spring-boot}#deploying-runtime-application-to-standalone-red-hat-enterprise-linux_spring-boot[deployment on standalone Red{nbsp}Hat Enterprise Linux].

ifdef::launcher-docs-only[]
* To learn more about the implementation of server-sent events in Spring 5, see the link:https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/codec/ServerSentEvent.html[API Documentation].

* For a practical perspective on using server-sent events in Spring, see the following link:https://apifriends.com/api-streaming/server-sent-events/[article] that provides a usecase-based analysis of server-sent events.
endif::[]
