// This is a parameterized module. Parameters used:
//
//  context: used in anchor IDs to conflicts due to duplicate IDs.
//  parameter-maven-command: This is used to substitute the Maven command appropriate to the runtime being used.
//  parameter-response: The expected response provided by the Java application. Can either be formatted as plain text or a JSON object.
//  parameter-runtime: Ensures that xrefs link to examples for the appropriate runtime.
//
// Rationale: This procedure is the same for 2 or more runtimes.

[id='developing-runtime-application_{context}']
= Developing {runtime} application

For a basic {runtime} application, you need to create the following:

* A Java class containing {runtime} methods.
* A `pom.xml` file containing information required by Maven to build the application.

The following procedure creates a simple `Greeting` application that returns "{parameter-response}" as response.

ifdef::built-for-spring-boot[]
ifndef::built-for-spring-boot-1-5[]
include::note_spring-boot-2-supported-builder-images.adoc[]
endif::[]
endif::[]

.Prerequisites

* Maven installed.
ifdef::built-for-spring-boot-1-5[]
* OpenJDK 8 installed.
endif::[]
ifndef::built-for-spring-boot-1-5[]
* {prerequisite-jdk-version}
endif::[]

.Procedure
. Create a new directory `myApp`, and navigate to it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mkdir myApp
$ cd myApp
----
+
This is the root directory for the application.

. Create directory structure `src/main/java/com/example/` in the root directory, and navigate to it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mkdir -p src/main/java/com/example/
$ cd src/main/java/com/example/
----

. Create a Java class file `MyApp.java` containing the application code.
+
ifdef::built-for-vertx[]
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertxGreetingApp.java[]
----
endif::[]
ifdef::built-for-spring-boot[]
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/springBootGreetingApp.java[]
----
endif::[]

. Create a `pom.xml` file in the application root directory `myApp` with the following content:
+
ifdef::built-for-vertx[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertx-starter-example-pom.xml[]
----
endif::[]
ifdef::built-for-spring-boot[]
ifndef::built-for-spring-boot-1-5[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/spring-boot-2-1-starter-example-pom.xml[]
----
endif::[]
endif::[]
ifdef::built-for-spring-boot-1-5[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/spring-boot-starter-example-pom.xml[]
----
endif::[]

. Build the application using Maven from the root directory of the application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{parameter-maven-command}
----

. Verify that the application is running.
+
Using `curl` or your browser, verify your application is running at `http://localhost:8080`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080
{parameter-response}
----

.Additional information

* As a recommended practice, you can configure liveness and readiness probes to enable health monitoring for your application when running on OpenShift.
To learn how application health monitoring on OpenShift works, try the xref:example-health-check-{parameter-runtime}[Health Check example].
