// Section TBD
[id='deploying-the-messaging-work-queue-booster-using-the-oc-cli-client_{context}']
= Deploying the {name-mission-messaging-work-queue} Booster using the `oc` CLI Client

.Prerequisites

* The booster application created using {parameter-deployment}.
ifndef::parameter-openshiftlocal[For more information, see xref:deploying-the-booster-using-launcher-oso_{context}[].]
ifdef::parameter-openshiftlocal[]
For more information, see xref:deploying-the-booster-using-the-launcher-tool_{context}[].
* Your {launcher} tool URL.
endif::[]

* The `oc` client authenticated. For more information, see xref:authenticating-the-oc-cli-client_{context}[].

.Procedure
. Clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/{project-name}.git
----
+
Alternatively, if you downloaded a ZIP file of your project, extract it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ unzip {project-name}.zip
----

. Create a new project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

. Import the templates for the messaging broker, worker, and frontend components.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc apply -f templates
----

. Deploy the messaging broker.
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc new-app --template=amq63-basic \
  -p APPLICATION_NAME=work-queue-broker \
  -p IMAGE_STREAM_NAMESPACE=$(oc project -q) \
  -p MQ_PROTOCOL=amqp \
  -p MQ_QUEUES=work-queue/requests \
  -p MQ_TOPICS=work-queue/worker-updates \
  -p MQ_USERNAME=work-queue \
  -p MQ_PASSWORD=work-queue
----

. Deploy the messaging service frontend that serves the web interface of the messaging service and communicates with the workers.
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc new-app --template=nodejs-messaging-work-queue-frontend
----

. Deploy a messaging worker that serves as the backend of the messaging service.
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc new-app --template=nodejs-messaging-work-queue-worker
----

////
// does this apply?
ifdef::node-js[]
. Use `start-openshift.sh` to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ ./start-openshift.sh
----
endif::node-js[]

ifndef::node-js[]
. Use Maven to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
endif::node-js[]
////

. Check the status of your booster and ensure all of your pods are running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
work-queue-broker-amq-1-7jwwx     1/1       Running     0          8m
work-queue-broker-amq-1-deploy    1/1       Running     0          5m
{app-name}-worker-1-build         0/1       Completed   0          5m
{app-name}-frontend-1-build       0/1       Completed   0          7m
{app-name}-worker-1-8t2hs         1/1       Running     0          3m
{app-name}-frontend-1-cjnd6       1/1       Running     0          3m
----
+
Your 3 pods should have a status of `Running` once they are fully deployed and started.

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES              PORT      TERMINATION   WILDCARD
frontend             frontend-{app-name}.{os-route-hostname}                                 {app-name}-frontend   8080                    None
----
+
The route information of a pod gives you the base URL which you use to access it. In the example above, you would use `\http://frontend-{app-name}.{os-route-hostname}` as the base URL to access the messaging service interface.
