// This is a parameterized module. Parameters used:
//
//  context: context of usage, e.g. "osl", "oso", "ocp", "rest-api", etc. This can also be a composite, e.g. "rest-api-oso"
//
// Rationale: This procedure is identical in all deployments.


[#getting-the-launcher-tool-url-and-credentials_{context}]
= Getting the {launcher} Tool URL and Credentials

You need the {launcher} tool URL and user credentials to create and deploy boosters on {OpenShiftLocal}. This information is provided when the {OpenShiftLocal} is started.

.Prerequisites

* The {launcher} tool installed, configured, and running. For more information, see the link:{link-launcher-openshift-local-install-guide}[{minishift-installation-guide-name}] guide.

.Procedure

. Navigate to the console where you started {OpenShiftLocal}.
. Check the console output for the URL and user credentials you can use to access the running {launcher}:
+
.Example Console Output from a {OpenShiftLocal} Startup
[source,bash,options="nowrap",subs="attributes+"]
----
...
-- Removing temporary directory ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.152:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----
