[#starting-your-application-on-openshift-in-debugging-mode_{context}]
= Starting Your Application on OpenShift in Debugging Mode

To debug your {runtime}-based application on OpenShift remotely, you must set the `JAVA_DEBUG` environment variable inside the container to `true` and configure port forwarding so that you can connect to your application from a remote debugger.

.Prerequisites

* Your application running on OpenShift.
* The `oc` binary installed on your machine.
* The ability to execute the `oc port-forward` command in your target OpenShift environment.

.Procedure

. Using the `oc` command, list the available deployment configurations:
+
[source,bash]
----
$ oc get dc
----

. Set the `JAVA_DEBUG` environment variable in the deployment configuration of your application to `true`, which configures the JVM to open the port number `5005` for debugging. For example:
+
[source,bash,subs="attributes+"]
----
$ oc set env dc/{app-name} JAVA_DEBUG=true
----

. Redeploy the application if it is not set to redeploy automatically on configuration change. For example:
+
[source,bash,subs="attributes+"]
----
$ oc rollout latest dc/{app-name}
----

. Configure port forwarding from your local machine to the application pod:
.. List the currently running pods and find one containing your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pod
NAME                            READY     STATUS      RESTARTS   AGE
{app-name}-3-1xrsp          0/1       Running     0          6s
...
----

.. Configure port forwarding:
+
--
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc port-forward {app-name}-3-1xrsp $LOCAL_PORT_NUMBER:5005
----

Here, `$LOCAL_PORT_NUMBER` is an unused port number of your choice on your local machine.
Remember this number for the remote debugger configuration.
--

. When you are done debugging, unset the `JAVA_DEBUG` environment variable in your application pod. For example:
+
[source,bash,subs="attributes+"]
----
$ oc set env dc/{app-name} JAVA_DEBUG-
----

.Related Information

You can also set the `JAVA_DEBUG_PORT` environment variable if you want to change the debug port from the default, which is `5005`.
