// Redefines the value of the URL placeholder from minishift-specific to a more general value.
:value-url-osl-auth: OPENSHIFT_CLUSTER_URL

[id='installing-launcher-tool-using-an-operator_{context}']
= Installing the {name-launcher} tool using an operator

Set up an operator to install the {name-launcher} tool on an OpenShift cluster.
The following procedure works with clusters running on OpenShift 3.11.

.Prerequisites

* Github account
* Admin access to an OpenShift cluster
// This works for OCP v3.11

.Procedure

. Assign the `cluster-admin` role to your user account on the OpenShift cluster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc adm policy --as system:admin add-cluster-role-to-user cluster-admin USER_ACCOUNT_NAME
----

. Log in to your {OpenShiftCluster} using your user account with `cluster-admin` credentials:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {value-url-osl-auth}
----

. Create a project to host the Launcher:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project launcher-infra
----

// TODO: this will later be part of the multi-user laucher deployment
. Register your {name-launcher} instance with OAuth.
+
--
.. Log in to GitHub

.. link:https://github.com/settings/applications/new[Create a new GitHub OAuth application].
+
Use `launcher` as the application name.

.. Use `http://temporary` as a temporary value for the _Homepage URL_ and _Authorization callback URL_ fields.
You must replace these value with the {name-launcher} frontend route URL when you obtain it.

.. Click _Register Application_ to confirm your settings to obtain the Client ID and Client Secret for your {name-launcher} app.

.. Create an OAuth secret for your {name-launcher} instance using the Client ID and Client Secret.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create secret generic launcher-oauth-github --from-literal=clientId=LAUNCHER_GITHUB_OAUTH_CLIENT_ID --from-literal=secret=LAUNCHER_GITHUB_OAUTH_CLIENT_SECRET
----

// where exactly do you specify the URL in the YAML?
.. Edit the custom resource definition YAML for your {name-launcher} instance to specify your OpenShift Web Console URL. 
// Perhaps creating a new CRD from a template might be closer to real-life usage?  
+
.launcher_cr.yaml
[source,yaml,options="nowrap",subs="attributes+"]
----
apiVersion: launcher.fabric8.io/v1alpha2
kind: Launcher
metadata:
  name: launcher
spec:
# OpenShift Configuration
  openshift:
    consoleUrl: YOUR_OPENSHIFT_WEB_CONSOLE_URL # Replace this with your OpenShift Web Console URL
# OAuth Configuration
  oauth:
    enabled: true
----

.. Obtain the frontend URL of your {name-launcher} instance:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route launcher --template={{.spec.host}}
----

// or is it a different project?
//also, the 
.. Create an OAuth client instance in your `launcher-operator` project.
Ensure that you provide the OpenShift secret and frontend URL you obtained earlier.
+
[source,options="nowrap",subs="attributes+"]
----
$ oc create -f <(echo '
  kind: OAuthClient
  apiVersion: oauth.openshift.io/v1
  metadata:
    name: launcher
  secret: YOUR_LAUNCHER_OPENSHIFT_SECRET # Replace this with the secret you generated using your OAuth Client ID and Client Secret
  redirectURIs:
    - "http://YOUR_LAUNCHER_FRONTEND_URL" # Replace this with the fronted route URL of your {name-launcher} instance
  grantMethod: prompt
  ')
----

.. Update the values of the _Homepage URL_ and _Authorization callback URL_ fields in your {name-launcher} OAuth app configuration settings on GitHub to point to your launcher frontend route URL.
--
//TODO: Revise this step. It should not involve direct downloads from Github. The deployment templates should be accessible as a resource list (see also RHOARDOC-1644) that can be downloaded in 1 step.
. Download and extract the link:https://github.com/fabric8-launcher/launcher-operator/archive/master.zip[ZIP file] containing the operator and navigate to the directory containing the extracted resources.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd launcher-operator
----

//TODO: this needs to be updated when the previous step gets revised.
. Process the YAML templates in the `/deploy` subdirectory:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$  oc create -R -f ./deploy
----
+
Based on the templates, OpenShift automatically installs:
+
* a custom resource definition for the {name-launcher} app
* a service account for the Launcher operator
* a deployment of the Launcher operator
* an access role definition for the Launcher operator
* access role bindings for the Launcher operator

. Install the `launcher_cr.yaml` custom resource to initiate the deployment of the {name-launcher} tool.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create -f example/launcher_cr.yaml
----

. Monitor the status of the {name-launcher} tool until it completes start up.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                           READY     STATUS              RESTARTS   AGE
configmapcontroller-1-deploy   1/1       Running             0          46s
configmapcontroller-1-aaaaa    0/1       ContainerCreating   0          44s
launcher-backend-1-deploy      1/1       Running             0          46s
...
launcher-backend-2-aaaaa       0/1       Running             0         5s
launcher-frontend-2-aaaaa      0/1       Running             0         6s
----

////
. Obtain the route of your {name-launcher} tool.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                HOST/PORT                                         PATH      SERVICES            PORT      TERMINATION   WILDCARD
launcher-frontend   launcher-frontend.launcher.{value-route-osl-hostname}                launcher-frontend   <all>                   None
----
////

. Navigate to the frontend route URL to start using {name-launcher}.

.Additional Resources
* See the link:{link-guide-getting-started}[{name-guide-getting-started}] for a walk-through of launching an example application.
* Read the runtime guides for an overview of the runtimes and their examples:
** link:{link-guide-spring-boot}[{name-guide-spring-boot}]
** link:{link-guide-vertx}[{name-guide-vertx}]
** link:{link-guide-thorntail}[{name-guide-thorntail}]
** link:{link-guide-nodejs}[{name-guide-nodejs}]
