// This is a parameterized module. Parameters used:
//
//  context: context of usage, e.g. "osl", "oso", "ocp", "rest-api", etc. This can also be a composite, e.g. "rest-api-oso"
//
// Rationale: This procedure is identical in all deployments.

[#deploying-the-circuit-breaker-booster-using-the-oc-cli-client_{context}]
= Deploying the {name-mission-circuit-breaker} Booster using the `oc` CLI Client

.Prerequisites

* The booster application created using {parameter-deployment}.
ifndef::parameter-openshiftlocal[For more information, see xref:deploying-the-booster-using-launcher-oso_{context}[].]
ifdef::parameter-openshiftlocal[]
For more information, see xref:deploying-the-booster-using-launcher-osl_{context}[].
* Your {launcher} tool URL.
endif::[]

* The `oc` client authenticated. For more information, see xref:authenticating-the-oc-cli-client_{context}[].

.Procedure
. Clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/{project-name}.git
----
+
Alternatively, if you downloaded a ZIP file of your project, extract it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ unzip {project-name}.zip
----

. Create a new OpenShift project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

ifndef::circuit-breaker-nodejs[]
. Use Maven to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the link:{link-s2i-process}[S2I process] on OpenShift and to start the pod.
endif::circuit-breaker-nodejs[]

ifdef::circuit-breaker-nodejs[]
. Use the provided `start-openshift.sh` script to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ chmod +x start-openshift.sh
$ ./start-openshift.sh
----
+
These commands use the xref:about-nodeshift[Nodeshift] `npm` module to install your dependencies, launch the S2I build process on OpenShift, and start the services.
endif::circuit-breaker-nodejs[]


. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-greeting-1-aaaaa     1/1       Running   0           17s
{app-name}-greeting-1-deploy    0/1       Completed 0           22s
{app-name}-name-1-aaaaa         1/1       Running   0           14s
{app-name}-name-1-deploy        0/1       Completed 0           28s
----
+
Both the `{app-name}-greeting-1-aaaaa` and `{app-name}-name-1-aaaaa` pods should have a status of `Running` once they are fully deployed and started. 
You should also wait for your pods to be ready before proceeding, which is shown in the `READY` column. 
For example, `{app-name}-greeting-1-aaaaa` is ready when the `READY` column is `1/1`.
Your specific pod names will vary.
The number in the middle will increase with each new build.
The letters at the end are generated when the pod is created.


. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{app-name}-greeting   {app-name}-{project-name}.{os-route-hostname}            {app-name}-greeting   8080                    None
{app-name}-name       {app-name}-{project-name}.{os-route-hostname}            {app-name}-name       8080                    None
----
+
The route information of a pod gives you the base URL which you use to access it. In the example above, you would use `\http://{app-name}-{project-name}.{os-route-hostname}` as the base URL to access the application.
