// This is a parameterized module. Parameters used:
//
//  parameter-uberjar-documented: Set if the current runtime has the chapter about creating uberjars
//
// Rationale: This procedure is identical in multiple Java-based deployments.

[id='starting-an-uberjar-in-debugging-mode_{context}']
= Starting an uberjar in debugging mode

If you chose to package your application as a {runtime} uberjar, debug it by executing it with the following parameters.

.Prerequisites

* An uberjar with your application

.Procedure

. In a console, navigate to the directory with the uberjar.
. Execute the uberjar with the following parameters.
Ensure that all the parameters are specified before the name of the uberjar on the line.
+
[source,bash,options="nowrap"]
----
$ java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$PORT_NUMBER -jar $UBERJAR_FILENAME
----
+
`$PORT_NUMBER` is an unused port number of your choice. 
Remember this number for the remote debugger configuration.
+
If you want the JVM to pause and wait for remote debugger connection before it starts the application, change `suspend` to `y`.

ifdef::parameter-uberjar-documented[]
.Additional resources

* xref:creating-an-uberjar[]
endif::[]
