[#deploying-an-application-to-openshift]
= Deploying an Application to OpenShift

This procedure shows you how to:

* Build your application and deploy it to OpenShift using the Fabric8 Maven Plugin.
* Use the command line to interact with your application running on OpenShift.

.Prerequisites

* The `oc` CLI client installed.
* Maven installed.
* A Maven-based application.

.Procedure

. Log in to your OpenShift instance with the `oc` client.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login ...
----

. Create a new project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. In a terminal application, navigate to the directory containing your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd myApp
----

. Use Maven to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the link:{link-s2i-process}[S2I process] on OpenShift and to start the pod.

. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa               1/1       Running     0          58s
{app-name}-s2i-1-build           0/1       Completed   0          2m
----
+
Your `{app-name}-1-aaaaa` pod should have a status of `Running` once it is fully deployed and started.

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{app-name}         {app-name}-{project-name}.{os-route-hostname}      {app-name}      8080
----
+
The route information of a pod gives you the base URL which you use to access it. In the example above, you would use `\http://{app-name}-{project-name}.{os-route-hostname}` as the base URL to access the application.

. Using `curl` or your browser, verify your application is running in OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{app-name}-{project-name}.{os-route-hostname}
{"content":"Greetings!"}
----
