[id='using-oauth2-authentication-in-a-reactive-spring-boot-application_{context}']
= Using OAuth2 authentication in a reactive {SpringBoot} application.

Set up link:https://oauth.net/2/[OAuth2 authentication] for your reactive {SpringBoot} application and authenticate using your client ID and client secret.

.Prerequisites

* JDK 8 or JDK 11 installed
* A GitHub account
* Maven installed
* A Maven-based application project link:{link-guide-spring-boot}#configuring-your-application-to-use-spring-boot_spring-boot[configured to use Spring Boot]


.Procedure

. link:https://github.com/settings/developers[Register a new OAuth 2 application] on your Github account.
Ensure that you provide the following values in the registration form:

* Homepage URL: `http://localhost:8080`
* Authorization callback URL: `http://localhost:8080/login/oauth2/code/github`
+
Ensure that you save the client ID and a client secret that you receive upon completing the registration.

. Add the following dependencies in the `pom.xml` file of your project:

* `vertx-spring-boot-starter-http`
* `spring-boot-starter-security`
* `spring-boot-starter-oauth2-client`
* `reactor-netty`
+
Note that the `reactor-netty` client is required to ensure that `spring-boot-starter-oauth2-client` works properly.
+
.`pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
...
  <dependencies>
  ...
include::resources/spring-boot/reactive-examples/example-0auth2-with-reactive-http-application-webflux-pom.xml[tags=http-service-oauth2-pom-dependencies]
  ...
  <dependencies>
...
</project>
----

. Create an endpoint controller class for your application:
+
.`HelloController.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-oauth2-http-webflux-endpoint-controller.java[]
----

. Create the main class of your application:
+
.`OAuthSampleApplication.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-oauth2-webflux-application.java[]
----

. Create a YAML configuration file to store the OAuth2 client ID and client secret you received from GitHub upon registering your application.
+
.`src/main/resources/application.yml`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-oauth2-client-configuration.yaml[]
----

. OPTIONAL: Run and test your application locally:

.. Navigate to the root directory of your Maven project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd myApp
----

.. Package your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean package
----

.. Start your application from the command line:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ java -jar target/vertx-spring-boot-sample-http-oauth.jar
----

.. Navigate to `http://localhost:8080` using a web browser.
You are redirected to an OAuth2 application authorization screen on GitHub.
If prompted, log in using your GitHub account credentials.

.. Click _Authorize_ to confirm.
You are redirected to a screen showing a personalized greeting message.

.Additional resources

* You can link:{link-guide-spring-boot}#deploying-runtime-application-to-openshift_spring-boot[deploy your application to an OpenShift cluster] using Fabric8 Maven Plugin.

* You can also configure your application for link:{link-guide-spring-boot}#deploying-runtime-application-to-standalone-red-hat-enterprise-linux_spring-boot[deployment on standalone Red{nbsp}Hat Enterprise Linux].

* For more information, see the link:https://spring.io/guides/tutorials/spring-boot-oauth2/[OAuth2 tutorial] in the Spring community documentation.
Alternatively, see the tutorial on using link:https://developer.okta.com/blog/2019/03/12/oauth2-spring-security-guide?utm_campaign=text_website_all_multiple_dev_dev_oauth2-spring-security_null&utm_source=oauthio&utm_medium=cpc[OAuth2 with Spring Security].

* For the full OAuth2 authentication framework specification, see document link:https://tools.ietf.org/html/rfc6749[RFC-6749].
