= Starting your Application Locally and Attaching the Native Debugger
The native debugger enables you to debug your {NodeJS}&#x2013;based application using the built-in debugging client.

.Prerequisites 
* An application you want to debug.

.Procedure
. Start the application with the debugger enabled.
+
The native debugger is automatically attached and provides a debugging prompt.
+
.Example application with the debugger enabled
[source,bash,options="nowrap",subs="attributes+"]
----
$ node inspect app.js
< Debugger listening on ws://127.0.0.1:9229/12345678-aaaa-bbbb-cccc-0123456789ab
< For help see https://nodejs.org/en/docs/inspector
< Debugger attached.
...
debug>
----
+
If you have a different entry point for your application, you need to change the command to specify that entry point:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ node inspect path/to/entrypoint
----
+
For example, when using the link:https://expressjs.com/en/starter/generator.html[express generator] to create your application, the entry point is set to `./bin/www` by default. Some of the boosters, such as the xref:mission-http-api-nodejs[{name-mission-http-api} booster], use `./bin/www` as an entry point.

. Use the debugger prompt to perform link:https://nodejs.org/api/debugger.html#debugger_command_reference[debugging commands].