[id='merging-contributions_{context}']

= Merging contributions

When you or someone else has xref:reviewing-changes_{context}[reviewed the changes] in a pull request, you can merge them into `upstream/master`.

IMPORTANT: Do not merge your own pull requests unless absolutely necessary. You are accountable for any errors, merge conflicts, or bugs resulting from incorrect merging. Let another contributor with the appropriate repository access privileges do it.

.Prerequisites

* GitHub account with merge access to the _{repo-docs-name}_ repository and GPG configured.

.Procedure

.Merging a Pull Request
. Ensure that you have the contributor's fork of the _{repo-docs-name}_ repository in your list of remotes:
+
[source,bash,options="nowrap"]
----
$ git remote -v
----

. To add a remote fork for to you Git directory:
.. Navigate to the contributor's fork on link:https://github.com/[GitHub].
.. Click the _Clone or Download_ button.
.. Select _Use SSH_.
.. Copy the repository URL beginning with `git@github.com:`.
.. Execute the following command, replacing `username` with the user name of the contributor:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git remote add username git@github.com:username/{repo-docs-name}.git
----
.. Use `git remote -v` to verify that the fork is now listed among your remotes.
.. Execute `git remote update` to fetch the latest state of the remotes to your working directory.

. Create a new branch and set it to track the remote branch that introduces the changes in the pull request:
+
--
[source,bash,options="nowrap"]
----
$ git checkout -b pr-to-merge username/featurebranch
----

You should see the following message:

[source,bash]
----
Branch pr-to-merge set up to track remote branch <topic_branch> from <username> by rebasing.
Switched to a new branch 'pr-to-merge'
----
--

. Fetch the latest state of `upstream` and rebase your topic branch:
+
--
[source,bash,options="nowrap"]
----
$ git fetch upstream
$ git rebase upstream/master
----

If you have multiple commits on your feature branch, squash them into a single commit before merging.
--

. Test if all the books build correctly with your changes by executing the `$REPO_HOME/scripts/build_guides.sh` script. If the output contains no errors, the guides build correctly.

. Checkout your local `master` branch:
+
[source,bash,options="nowrap"]
----
$ git checkout master
----

. Rebase your local `master` branch against `upstream/master`:
+
[source,bash,options="nowrap"]
----
$ git rebase upstream/master
----

. Merge your topic branch into `master`:
+
[source,bash,options="nowrap"]
----
$ git merge pr-to-merge
----

. Execute `$REPO_HOME/scripts/build_guides.sh` to test whether the guides build correctly with the changes introduced by your merge.

. Push the latest changes into `upstream`:
+
--
[source,bash,options="nowrap"]
----
$ git push upstream master
----

The changes are now merged into `upstream/master`.
--

. Close the pull request for the changes you just merged:
.. Obtain the commit hash of the last commit on `master`:
+
[source,,bashoptions="nowrap"]
----
$ git log -1 HEAD
----
.. Navigate to the pull request on GitHub.
.. Paste the commit following line into a new comment, replacing <commit-hash> with the SHA-1 of your commit:
+
----
merged: <commit-hash>
----
.. Click _Close and comment_.

