[[use_devstudio]]
= Using Red Hat JBoss Developer Studio with a Booster Project
Red Hat JBoss Developer Studio is an integrated development environment, or IDE, that provides tooling for writing software. You can use it to make changes to your booster's code.

[sidebar]
.Prerequisites
--
* Have a booster deployed to xref:deploying-a-booster-to-oso[{OpenShiftOnline}] or xref:osl-create-booster[{OpenShiftLocal}] using the _Deploy in OpenShift Online_ option.
* Have Red Hat JBoss Developer Studio link:https://developers.redhat.com/products/devstudio/download/[downloaded from the Red Hat Developer Portal] and installed.
--

== Importing your Booster's Code
Importing your booster's code creates a project in Red Hat JBoss Developer Studio and enables you to start making changes.

.Procedure
. Ensure Developer Studio is running.
. Click _File_ -> _Import_.
. Choose _Maven_ -> _Existing Maven Projects_.
. Click _Browse_, navigate to the root of your booster project, and click _Open_.
. Ensure the `pom.xml` file is selected and click _Finish_.
. Start editing your project after your import is complete.


== Committing and Pushing Changes to your Booster's GitHub Repository:
Red Hat JBoss Developer Studio provides tooling for committing and pushing code through `git` directly in the IDE. Alternatively, you can use Red Hat JBoss Developer Studio to make changes and push those changes with the `git` CLI.

.Procedure
. Ensure you have saved all files with changes that you intend to commit.
. Right click on the root of the project _Project Explorer_ or _Package Explorer_ view.
. Choose _Team_ -> _Commit..._.
. Drag all the changes you want to commit from the _Unstaged Changes_ section to the _Staged Changes_ section.
. Enter your commit message and click _Commit and Push_.
. Click _OK_ in the _Push Results_ window when prompted.
. Observe your changes are now available in your GitHub repository.
