// This is a parameterized module. Parameters used:
//
//  parameter-runtime-name: human-readable name of the runtime. This is used in readable text
//  context: used in anchor IDs to conflicts due to duplicate IDs
//
// Rationale: This procedure is the same for 2 or more runtimes.

[id='preparing-an-application-for-openshift-deployment_{context}']
= Preparing an application for OpenShift deployment

You can easily prepare your existing application to deploy on OpenShift.

.Prerequisites

* A {parameter-runtime-name}{ndash}based application

.Procedure

. Add the following profile to the `pom.xml` file in the root directory of your application:
+
ifdef::built-for-vertx[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertx-openshift-pom-config-example.xml[]
----
endif::[]
ifdef::built-for-spring-boot[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/spring-boot-openshift-pom-config-example.xml[]
----
endif::[]

+
In this profile, the Fabric8 Maven plugin is invoked for building and deploying the application to OpenShift.
ifdef::built-for-vertx[]
. Create a `deployment.yaml` file in the `src/main/fabric8` directory and add the `JAVA_OPTIONS` described in the example.
+
[source,yaml,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertx-fmp-deployment.yaml[]
----
endif::[]
. Deploy the application to OpenShift according to instructions in xref:deploying-an-application-to-openshift-using-fabric8-plugin_{context}[].
