[id='updating-the-deployment-configuration-of-a-booster_{context}']
= Updating the deployment configuration of a booster

The deployment configuration for a booster contains information related to deploying and running the booster in OpenShift, such as route information or readiness probe location. 
The deployment configuration of a booster is stored in a set of YAML files. 
For boosters that use the Fabric8 Maven Plugin, the YAML files are located in the `src/main/fabric8/` directory. For boosters using Nodeshift, the YAML files are located in the `.nodeshift` directory.

[IMPORTANT]
====
The deployment configuration files used by the Fabric8 Maven Plugin and Nodeshift do not have to be full OpenShift resource definitions. 
Both Fabric8 Maven Plugin and Nodeshift can take the deployment configuration files and add some missing information to create a full OpenShift resource definition.
The resource definitions generated by the Fabric8 Maven Plugin are available in the `target/classes/META-INF/fabric8/` directory.
The resource definitions generated by Nodeshift are available in the `tmp/nodeshift/resource/` directory.
====


.Prerequisites
* An existing booster project.
* The `oc` CLI client installed.

.Procedure

. Edit an existing YAML file or create an additional YAML file with your configuration update.
** For example, if your booster already has a YAML file with a `readinessProbe` configured, you could change the `path` value to a different available path to check for readiness:
+
[source,yaml,options="nowrap",subs="attributes+"]
----
spec:
  template:
    spec:
      containers:
        readinessProbe:
          httpGet:
            path: /path/to/probe
            port: 8080
            scheme: HTTP
...
----
** If a `readinessProbe` is not configured in an existing YAML file, you can also create a new YAML file in the same directory with the `readinessProbe` configuration.

. Deploy the updated version of your booster using Maven or npm.

. Verify your configuration updates show in the deployed version of your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc export all --as-template='my-template'

apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: my-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  ...
  spec:
    ...
    template:
      ...
      spec:
        containers:
          ...
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /path/to/different/probe
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          ...
----


.Additional resources
If you updated the configuration of your application directly using the web-based console or the `oc` CLI client, export and add these changes to your YAML file. 
Use the `oc export all` command to show the configuration of your deployed application.
