
[id='committing-and-pushing-changes-to-the-github-repository-of-your-booster-with-visual-studio-code_{context}']
[id='committing-and-pushing-canges-to-the-github-repository-of-your-example-application-with-visual-studio-code_{context}']
= Committing and pushing changes to the GitHub repository of your example application with Visual Studio Code

Visual Studio Code provides tooling for committing and pushing code through Git directly in the IDE. Alternatively, you can use Visual Studio Code to make changes and push those changes with the Git CLI.

.Prerequisites

. All files with changes that you intend to commit are saved.

.Procedure

. In Visual Studio Code, on the left side, click the _Source Control_ icon.
. Under _Changes_ click the _+_ icon for each file you want to stage. Alternatively, you can click on the _+_ icon next to _Changes_ to stage all files.
. In the field above _Staged Changes_, enter a commit message and click the check icon to commit your changes.
. Click the _..._ icon and select _Push_ to push your changes.
. Observe your changes are now available in your GitHub repository.
