
[#specifying-custom-logging-framework-for-your-application_{context}]
= Specifying a custom logging framework for your application

If you do not want {VertX} to use `java.util.logging`, configure `io.vertx.core.logging.Logger to use a different logging framework, for example, `Log4J` or `SLF4J`:

.  Set the value of the `vertx.logger-delegate-factory-class-name` system property to the name of the class that implements the `LogDelegateFactory` interface.
{Vertx} provides the pre-built implementations for the following libraries with their corresponding pre-defined classnames listed below:
+
[options="header"]
|===
| Library | Class name
| `Log4J` v1 |`io.vertx.core.logging.Log4jLogDelegateFactory`
| `Log4J` v2 | `io.vertx.core.logging.Log4j2LogDelegateFactory`
| `SLF4J` |  `io.vertx.core.logging.SLF4JLogDelegateFactory`
|===
+
When implementing logging using a custom library, ensure that the relevant `Log4J` or `SLF4J` jars are included among the dependencies for your application.
+
[CAUTION]
--
The _Log4J_ v1 delegate provided with {VertX} does not support parameterized messages.
The delegates for _Log4J v2_ and _SLF4J_ both use the `{}` syntax.
The `java.util.logging` delegate relies on link:https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html[`java.text.MessageFormat`] that uses the `{n}` syntax.
--
