[id='creating-a-spring-boot-2-1-application_{context}']
= Creating a {SpringBoot} 2.1.x application

Create a simple `Greeting` application to run on OpenShift using {runtime}.
The following procedure shows you how to:

* Write some simple application code that makes use of functionalities provided by {runtime}.
* Declare dependencies and configure the application build using a `pom.xml` file.
* Specify a BOM in your application to ensure you are using the correct runtime artifact versions.
* Start your application on localhost and verify that it works.


.Prerequisites

* Maven installed.
* {prerequisite-jdk-version}

.Procedure

. Create the application directory and navigate to it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mkdir myApp
$ cd myApp
----

. Create a `pom.xml` file.
+
include::note_spring-boot-2-supported-builder-images.adoc[]
+
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/spring-boot-2-1-starter-example-pom.xml[]
----

. Create new classes in the `src/main/java/com/example/` directory.
+
--
As a recommended practice, ensure that the location of your classes within the directory structure of your project reflects the value that you set for `groupId` in your `pom.xml` file.
For example, for `<groupId>my.awesome.project</groupId>`, the location of the classes should be `src/main/java/my/awesome/project/`.

.Example `src/main/java/com/example/Message.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/Message.java[]
----

.Example `src/main/java/com/example/Controller.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/Controller.java[]
----

.Example `src/main/java/com/example/MyApp.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/MyApp.java[]
----
--

. Start your application. Execute the following command in the directory containing you application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{parameter-maven-command}
----

. Using `curl` or your browser, verify your application is running at `http://localhost:8080`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080
{parameter-response}
----

.Additional information

* As a recommended practice, you can configure liveness and readiness probes to enable health monitoring for your application when running on OpenShift.
To learn how application health monitoring on OpenShift works, try the xref:mission-health-check-{parameter-runtime}[Health Check booster].
