// Redefines the value of the URL placeholder from minishift-specific to a more general value.
:value-url-osl-auth: OPENSHIFT_CLUSTER_URL

[id='installing-launcher-tool-using-an-operator_{context}']
= Installing the {name-launcher} tool using an operator

Set up an operator to install the {name-launcher} tool on an OpenShift cluster.
Configure OAuth2 authentication to enable multiple users to access the same instance of {name-launcher}.

.Prerequisites

* Github account
* Admin access to an OpenShift cluster
* {OpenShiftCluster} installed

.Procedure

. Assign the `cluster-admin` role to your user account on the OpenShift cluster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc adm policy --as system:admin add-cluster-role-to-user cluster-admin USER_ACCOUNT_NAME
----

. Log in to your {OpenShiftCluster} using your user account with `cluster-admin` credentials:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {value-url-osl-auth}
----

. Create a project to host the Launcher:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project launcher-infra
----

. Register your {name-launcher} instance with OAuth on GitHub.
This enables multiple users to use the same instance by authenticating their GitHub user accounts against the the OAuth application that your {name-launcher} instance is registered to.
+
--
.. Log in to GitHub

.. link:https://github.com/settings/applications/new[Create a new GitHub OAuth application].
+
Use `launcher` as the application name.

.. Use `http://temporary` as a temporary value for the _Homepage URL_ and _Authorization callback URL_ fields.
You must replace these value with the {name-launcher} frontend route URL when you obtain it.

.. Click _Register Application_ to confirm your settings to obtain the Client ID and Client Secret for your {name-launcher} app.

.. Create an OAuth secret for your {name-launcher} instance using the Client ID and Client Secret.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create secret generic launcher-oauth-github --from-literal=clientId=LAUNCHER_GITHUB_OAUTH_CLIENT_ID --from-literal=secret=LAUNCHER_GITHUB_OAUTH_CLIENT_SECRET
----
--
+
. Download and extract the link:https://github.com/fabric8-launcher/launcher-operator/archive/master.zip[ZIP file] containing the operator and navigate to the directory containing the extracted resources.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd launcher-operator
----

. Create and deploy the application resources defined by the YAML templates in the `/deploy` subdirectory:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$  oc create -R -f ./deploy
----
+
Based on the templates, OpenShift automatically installs:
+
* a custom resource definition for the {name-launcher} app
* a service account for the Launcher operator
* a deployment of the Launcher operator
* an access role definition for the Launcher operator
* access role bindings for the Launcher operator

. OPTIONAL: Verify that the pod containing the deployment operator is running and that its state is indicated as `READY`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$  oc get pods -w
NAME                                READY     STATUS       RESTARTS   AGE
launcher-operator-fffff0000-abc12   1/1       Running      0          3m
----
+
Press `CTRL`+`Z` to stop watching the pods.

. Edit the `launcher_cr.yaml` custom resource located in the `example/` subdirectory.
Use your OpenShift Console URL as the value of `consoleUrl`:
+
.example/launcher_cr.yaml
[source,yaml,options="nowrap",subs="attributes+"]
----
apiVersion: launcher.fabric8.io/v1alpha2
kind: Launcher
metadata:
  name: launcher
spec:

# OpenShift Configuration
  openshift:
    apiUrl: https://openshift.default.svc.cluster.local
    consoleUrl: # Replace this value with the URL you use to access your OpenShift Web Console (for example: 'https://192.168.64.4:8443').#

# OAuth Configuration
  oauth:
    enabled: true
    keycloakUrl: http://keycloakUrl # TODO: What is the approriate URL to use instead of the default here?#
    keycloakRealm: launcher
    keycloakClientId: launcher

  git:
    providers:
    - id: GitHub
      clientId: "LAUNCHER_GITHUB_OAUTH_CLIENT_ID"
      clientSecret: "LAUNCHER_GITHUB_OAUTH_CLIENT_SECRET"
----

. Create the application components of the {name-launcher} tool defined in the `example/launcher_cr.yaml` template to start the deployment.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create -f example/launcher_cr.yaml
----

. Wait until the pod containing the {name-launcher} application is in a `READY` state:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                                READY     STATUS              RESTARTS   AGE
launcher-application-1-aaaaa        1/1       Running             0           8s
...
----
+
Press `CTRL`+`Z` to stop watching the pods.

. Obtain the frontend URL of your {name-launcher} instance:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route launcher --template={{.spec.host}}
http://YOUR_LAUNCHER_FRONTEND_URL
----

. Create an OAuth client instance in your `launcher-operator` project.
Ensure that you provide the OpenShift secret and frontend URL values that you obtained earlier:
+
[source,options="nowrap",subs="attributes+"]
----
$ oc create -f <(echo '
  kind: OAuthClient
  apiVersion: oauth.openshift.io/v1
  metadata:
    name: launcher
  secret: YOUR_LAUNCHER_OPENSHIFT_SECRET # Replace this with the secret you generated using your OAuth Client ID and Client Secret
  redirectURIs:
    - "http://YOUR_LAUNCHER_FRONTEND_URL" # Replace this with the fronted route URL of your {name-launcher} instance
  grantMethod: prompt
  ')
----

. Update the values of the _Homepage URL_ and _Authorization callback URL_ fields in your {name-launcher} OAuth app configuration settings on GitHub to the value of your launcher frontend route URL.

. Navigate to the frontend route URL using a web browser to start using {name-launcher}.

.Additional Resources

* See the {name-guide-getting-started} section on link:{link-guide-getting-started}#creating-and-deploying-an-example-application-using-your-openshiftlocal_getting-started[using {name-launcher} to deploy example apps] to explore example applications available for different link:{link-guide-getting-started}#available-runtimes_getting-started[runtimes].
* You can also see the guide to link:{link-guide-getting-started}#creating-a-new-application-using-the-launcher-tool_getting-started[creating a new application using {name-launcher}] for instructions on creating custom applications using the {name-launcher} tool.
* See the runtime guides for an overview of the runtimes and their examples:
** link:{link-guide-spring-boot}[{name-guide-spring-boot}]
** link:{link-guide-vertx}[{name-guide-vertx}]
** link:{link-guide-thorntail}[{name-guide-thorntail}]
** link:{link-guide-nodejs}[{name-guide-nodejs}]


:value-url-osl-auth!:
