// This is a parameterized module. Parameters used:
//
//  context: used in anchor IDs to conflicts due to duplicate IDs.
//  parameter-maven-command: This is used to substitute the Maven command appropriate to the runtime being used.
//  parameter-response: The expected response provided by the Java application. Can either be formatted as plain text or a JSON object.
//  parameter-runtime: Ensures that xrefs link to boosters for the appropriate runtime.
//
// Rationale: This procedure is the same for 2 or more runtimes.

[id='creating-an-application_{context}']
= Creating an application

Create a simple `Greeting` application to run on OpenShift using {runtime}.
The following procedure shows you how to:

* Write some simple application code that makes use of functionalities provided by {runtime}.
* Declare dependencies and configure the application build using a `pom.xml` file.
* Specify a BOM in your application to ensure you are using the correct runtime artifact versions.
* Start your application on localhost and verify that it works.


.Prerequisites

* Maven installed.
* JDK 8 or later installed.

.Procedure

. Create the application directory and navigate to it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mkdir myApp
$ cd myApp
----

. Create a `pom.xml` file.
+
ifdef::built-for-vertx[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertx-starter-example-pom.xml[]
----
endif::[]
ifdef::built-for-spring-boot[]
ifndef::built-for-spring-boot-1-5[]
include::note_spring-boot-2-supported-builder-images.adoc[]
+
endif::built-for-spring-boot-1-5[]
[source,xml,options="nowrap",subs="attributes+"]
----
\include::resources/spring-boot/spring-boot-starter-example-pom.xml[]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>my-app</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <name>MyApp</name>
  <description>My Application</description>

  <!-- Specify the JDK builder image used to build your application. -->
  <properties>
    <fabric8.generator.from>{name-s2i-image-openjdk}</fabric8.generator.from>
  </properties>

  <!-- Import dependencies from the RHOAR Spring Boot BOM. -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>me.snowdrop</groupId>
        <artifactId>spring-boot-bom</artifactId>
        <version>{version-spring-boot-bom}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
ifdef::built-for-spring-boot-1-5[]
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-spring-boot-starter-jaxrs</artifactId>
    </dependency>
endif::[]
ifndef::built-for-spring-boot-1-5[]
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-spring-boot-starter</artifactId>
    </dependency>
endif::[]
    <dependency>
      <groupId>com.fasterxml.jackson.jaxrs</groupId>
      <artifactId>jackson-jaxrs-json-provider</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>{version-spring-boot-maven-plugin}</version>
      </plugin>
    </plugins>
  </build>

  <!-- Specify the repositories containing RHOAR artifacts -->
  <repositories>
    <repository>
      <id>{red-hat-ga-repo-id}</id>
      <name>{red-hat-ga-repo-name}</name>
      <url>{red-hat-ga-repo-url}</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>{red-hat-ga-repo-id}</id>
      <name>{red-hat-ga-repo-name}</name>
      <url>{red-hat-ga-repo-url}</url>
    </pluginRepository>
  </pluginRepositories>

  <profiles>
    <profile>
      <id>openshift</id>
      <build>
        <plugins>
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>fabric8-maven-plugin</artifactId>
            <version>{version-fabric8-maven-plugin}</version>
            <executions>
              <execution>
                <goals>
                  <goal>resource</goal>
                  <goal>build</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
----
endif::[]

. Create a new class in `src/main/java/com/example/`.
+
As a recommended practice, ensure that the location of your class within the directory structure of your project reflects the value that you set for `groupId` in your `pom.xml` file.
For example, for `<groupId>my.awesome.project</groupId>`, the location of the class should be `src/main/java/my/awesome/project/`.
+
.Example `src/main/java/com/example/MyApp.java`
+
ifdef::built-for-vertx[]
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertxGreetingApp.java[]
----
endif::[]
ifdef::built-for-spring-boot[]
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/springBootGreetingApp.java[]
----
endif::[]

. Start your application. Execute the following command in the directory containing you application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{parameter-maven-command}
----

. Using `curl` or your browser, verify your application is running at `http://localhost:8080`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080
{parameter-response}
----

.Additional information

* As a recommended practice, you can configure liveness and readiness probes to enable health monitoring for your application when running on OpenShift.
To learn how application health monitoring on OpenShift works, try the xref:mission-health-check-{parameter-runtime}[Health Check booster].
