[#starting-your-spring-boot-application-locally-in-debugging-mode]
= Starting Your {SpringBoot} Application Locally in Debugging Mode

One of the ways of debugging a Maven-based project is manually launching the application while specifying a debugging port, and subsequently connecting a remote debugger to that port.
This method is applicable at least to the following deployments of the application:

* When launching the application manually using the `mvn spring-boot:run` goal.
* When using the Arquillian adapter for {runtime}.

.Prerequisites

* A Maven-based application

.Procedure

. In a console, navigate to the directory with your application.
. Launch your application and specify the necessary JVM arguments and the debug port using the following syntax:
+
--
[source,bash,options="nowrap"]
----
$ mvn spring-boot:run -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=$PORT_NUMBER"
----

Here, `$PORT_NUMBER` is an unused port number of your choice.
Remember this number for the remote debugger configuration.
--

