= Creating a {NodeJS} Application

In addition to xref:mission-http-api-nodejs[using a booster], you can also create new {NodeJS} applications from scratch and deploy them to OpenShift.

== Creating an Application

.Prerequisites
* `npm` installed.

.Procedure

. Create the application folder.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mkdir myApp
----

. Initialize your application with npm.
+
The rest of this example assumes the entry point is `app.js`, which you are prompted to set when running `npm init`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd myApp
$ npm init
----

. Create the entry point in a new file called `app.js`.
+
.Example `app.js`
[source,javascript,options="nowrap"]
----
const http = require('http');

const server = http.createServer((request, response) => {
  response.statusCode = 200;
  response.setHeader('Content-Type', 'application/json');
  
  const greeting = {content: 'Hello, World!'};
  
  response.write(JSON.stringify(greeting));
  response.end();
});

server.listen(8080, () => {
  console.log('Server running at http://localhost:8080');
});
----


. Start your application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ node app.js
Server running at http://localhost:8080
----

. Using `curl` or your browser, verify your application is running at `http://localhost:8080`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080
{"content":"Hello, World!"}
----

[#proc_deploy-new-nodejs-app-openshift]
== Deploying an Application to OpenShift

.Prerequisites

* The `oc` CLI client installed.
* `npm` installed.

.Procedure

. Add `nodeshift` to your application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install nodeshift --save
----

. Add the `openshift` and `start` entries to the `scripts` section in `package.json`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{
  "name": "myApp",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "openshift": "nodeshift --strictSSL=false --metadata.out=deployment-metadata.json --build.forcePull=true {nodeshiftNodeVersion}",
    "start": "node app.js",
    ...
  }
  ...
}
----
+
The `openshift` script uses `nodeshift` to deploy the application to OpenShift.

. _Optional_: Add a `files` section in `package.json`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{
  "name": "myApp",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    ...
  },
  "files": [
    "package.json",
    "app.js"
  ]
  ...
}
----
+
The `files` section tells `nodeshift` what files and directories to include when deploying to OpenShift.
`nodeshift` uses the link:https://github.com/npm/node-tar[`node-tar`] module to create a tar file based on the files and directories you list in the `files` section.
This tar file is used when `nodeshift` deploys your application to OpenShift.
If the `files` section is not specified, `nodeshift` will send the entire current directory, excluding:
+
* `node_modules/`
* `.git/`
* `tmp/`
+
It is recommended that you include a `files` section in `package.json` to avoid including unnecessary files when deploying to OpenShift.

. Log in to your OpenShift instance with the `oc` client.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login ...
----

. Use `nodeshift` to deploy the application to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm run openshift
----

. Expose the application in OpenShift using link:https://docs.openshift.com/online/dev_guide/routes.html[a route].
+
.Example for exposing a service using a route
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create route edge my-route --service=myApp --port=8080
----


Optionally, you can create a `.nodeshift` directory at the root of your project to include deployment yaml files. These files will create items such as routes when deploying your application to OpenShift using nodeshift. For example, to add a route during deployment, you could create a `.nodeshift/route.yaml` with the following:

.Example `.nodeshift/route.yaml`
[source,yaml,options="nowrap",subs="attributes+"]
----
apiVersion: v1
kind: Route
metadata:
  name: myApp
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
----