[[debug-logging]]
= Runtime Application Debug Logging

Debug logging is a way to add granular logging to an application that is explicitly enabled when performing debugging. This allows you to keep the logging capability in your application and only enable it when needed.


== Add Debug Logging
There are several options for debug logging. This example uses the link:https://www.npmjs.com/package/debug[debug package].

[discrete]
=== Prerequisites 
* An application you want to debug. For example, xref:mission-http-api-nodejs[a booster].

[discrete]
=== Procedure

. Add the `debug` logging definition.
+
[source,js,options="nowrap",subs="attributes+"]
----
var debug = require('debug')('mybooster');
----

. Add debug statements.
+
[source,js,options="nowrap",subs="attributes+"]
----
app.use('/api/greeting', (request, response) => {
  const name = request.query ? request.query.name : undefined;
  //log name in debugging
  debug('name: '+name);
  response.send({content: `Hello, ${name || 'World'}`});
});
----

== Show Debug Logging on Localhost

Use the `DEBUG` environment variable when starting your application to enable debug logging.

[discrete]
=== Prerequisites 
* An application with debug logging.

[discrete]
=== Procedure

. Set the `DEBUG` environment variable to enable debug logging in your application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ DEBUG=mybooster npm start
----
+
The `DEBUG` environment variable uses link:https://www.npmjs.com/package/debug#wildcards[wildcards] to filter debugging messages.

. Test your application to invoke debug logging. 
+
For example, when debug logging in the xref:mission-http-api-nodejs[{name-mission-http-api} booster] is set to log the `name` variable in the `/api/greeting` method:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting?name=Sarah
----

. View your application logs to see your debug messages.
+
[source,options="nowrap",subs="attributes+"]
----
mybooster name: Sarah +3m
----


== Show Debug Logging on OpenShift

Use the the `DEBUG` environment variable in your application pod in OpenShift to enable debug logging.

[discrete]
=== Prerequisites 
* An application with debug logging.
* The `oc` CLI client installed.


[discrete]
=== Procedure

. Use the `oc` CLI client to log into your OpenShift instance.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login ...
----

. Deploy your application to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm run openshift
----
+
This runs the `openshift` npm script, which wraps direct calls to xref:about-nodeshift[nodeshift].

. Find the name of your pod and follow the logs to watch it start.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
....
$ oc logs -f pod/POD_NAME
----
+
IMPORTANT: After your pod has started, keep watching the logs.

. Test your application. 
+
For example, if you had debug logging in the xref:mission-http-api-nodejs[{name-mission-http-api} booster] to log the `name` variable in the `/api/greeting` method:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
...
$ curl $APPLICATION_ROUTE/api/greeting?name=Sarah
----

. Return to your pod logs and notice there are no debug logging messages in the logs. 

. Set the `DEBUG` environment variable in your application pod to enable debug logging.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc set env pod/POD_NAME DEBUG=mybooster
----

. Return to your pod logs to watch the update roll out.
+
IMPORTANT: After the update has rolled out, keep watching the logs. This is where the debug logging will appear.

. Test the application to invoke debug logging. 
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
...
$ curl $APPLICATION_ROUTE/api/greeting?name=Sarah
----

. View the application logs to see the debug messages.
+
[source,options="nowrap",subs="attributes+"]
----
...
mybooster name: Sarah +3m
----



To disable debug logging, remove the `DEBUG` environment variable from the pod:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc set env pod/POD_NAME DEBUG-
----

[discrete]
=== Related Information
More details on environment variables are avialable in the link:https://docs.openshift.com/online/dev_guide/environment_variables.html[OpenShift documentation].
