
[#_configure-netty-logging-vertx]
= Configuring Netty Logging

link:http://netty.io/wiki/user-guide-for-4.x.html[_Netty_^] is a library used by VertX to manage asynchronous network communication in applications.

Netty:

* allows quick and easy development of network applications, such as protocol servers and clients,
* simplifies and streamlines network programming, such as TCP and UDP socket server development,
* provides a unified API for managing blocking and non-blocking connections.

Netty does not rely on an external logging configuration using system properties.
Instead, it implements a logging configuration based on logging libraries visible to Netty classes in your project.
Netty tries to use the libraries in the following order:

. `SLF4J`,

. `Log4J`,

. `java.util.logging`, as a fallback option.

You can set `io.netty.util.internal.logging.InternalLoggerFactory` directly to a particular logger:
//TODO: add context: where can the developer do this?
// at the beginning of the application's `main` method.


[source,java,options="nowrap",subs="attributes+"]
--
// Force logging to Log4j
InternalLoggerFactory.setDefaultFactory(Log4JLoggerFactory.INSTANCE);
--
