// This is a parameterized module. Parameters used: 
// 
//  context: context of usage, e.g. "osl", "oso", "ocp", "rest-api", etc. This can also be a composite, e.g. "rest-api-oso"
//
// Rationale: This procedure is identical in all deployments.


[#getting-launcher-url-and-credentials-on-openshiftlocal_{context}]
= Getting the {launcher} Service URL and Credentials on {OpenShiftLocal}

You need the {launcher} service URL and user credentials to create and deploy boosters on {OpenShiftLocal}. These data are provided by the {OpenShiftLocal} binary when you start it.

.Prerequisites

* The {launcher} service installed, configured, and running. For more information, see the link:{link-launcher-openshift-local-install-guide}[{openshift-local-guide-name}] guide.

.Procedure

. Navigate to the console where you started {OpenShiftLocal}.
. Check the console output for the URL and user credentials you can use to access the running {launcher}:
+
.Example Console Output from a {OpenShiftLocal} Startup
[source,bash,options="nowrap",subs="attributes+"]
----
...
-- Removing temporary directory ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.152:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----

