// This is a parameterized module. Parameters used:
//
//  parameter-url: URL to query when interacting with the application
//  parameter-response: Response received from the application
//  context: used in anchor IDs to conflicts due to duplicate IDs
//
// Rationale: This procedure is the same for 2 or more runtimes.


[id='deploying-runtime-application-to-openshift-using-fabric8-maven-plugin_{context}']
= Deploying {runtime} application to OpenShift using Fabric8 Maven plugin 


To deploy your {runtime} application to OpenShift, you must perform the following:

* Log in to your OpenShift instance.
* Deploy the application to the OpenShift instance. 

.Prerequisites

* `oc` CLI client installed.
* Maven installed.

.Procedure

. Log in to your OpenShift instance with the `oc` client.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login ...
----

. Create a new project in the OpenShift instance.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {value-name-project}
----

. Deploy the application to OpenShift using Maven from the application’s root directory. The root directory of an application contains the `pom.xml` file.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the {name-launcher} to launch the link:{link-s2i-process}[S2I process] on OpenShift and start the pod.

. Verify the deployment.
.. Check the status of your application and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{value-name-app}-1-aaaaa               1/1       Running     0          58s
{value-name-app}-s2i-1-build           0/1       Completed   0          2m
----
+
The `{value-name-app}-1-aaaaa` pod should have a status of `Running` once it is fully deployed and started.
+
Your specific pod name will vary.

.. Determine the route for the pod.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{value-name-app}         {value-name-app}-{value-name-project}.{value-route-openshift-hostname}      {value-name-app}      8080
----
+
The route information of a pod gives you the base URL which you use to access it. 
+
In this example, `\http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}` is the base URL to access the application.

.. Verify that your application is running in OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl {parameter-url}
{parameter-response}
----
