
[id='releasing-launcher-docs_{context}']
= Releasing {name-docs} docs

This section contains all information you need to release a new version of the documentation set to production. This update can happen anytime after the catalog has been updated, including after the release train has been completed.

.Procedure

.Releasing New Version to Production
. Synchronize the {WildFlySwarm} sources. For more information, see xref:syncing-with-wildflyswarm-docs_{context}[].

. Tag the release:
.. Execute the `tag_release.sh` script in the `$REPO_HOME/scripts` directory:
+
--
[source,bash]
----
$ ./tag_release.sh
----

The script automatically tags the commit with the current date in the `YYYY-MM-DD` format.
If you want to tag with a different date or manually, execute the following command:
[source,bash]
----
$ git tag 2017-04-21
----
If you are re-releasing the same day, a suffix `_2`, `_3`, etc. is appended.

--
.. Push the changes and tags:
+
--
[source,bash]
----
$ git push --tags $REMOTE
----

Replace `$REMOTE` with the name of the upstream remote.
--

. Request publication:
.. File a pull request in the link:https://github.com/openshiftio/saas-launchpad/blob/master/launchpad-services/launcher-documentation.yaml#L2[openshiftio/saas-launchpad] repository, where you change the `hash` value to the hash of the commit you want to publish from the link:{link-repo-docs}[{name-repo-docs}] repository. Usually, this will be the latest commit in the `master` branch.
.. Wait for the pull request to be accepted. When that happens, verify that the link:{link-docs}[production build] succeeded.
.. Once your changes have been merged and the build succeeds, delete the topic branch you used to introduce the update.
+
[source,bash,options="nowrap",subs="attributes+"]
--
$ git branch -d $TOPIC_BRANCH_NAME
--

. Announce the publication:
+
--
Send an e-mail containing a link to the new version and the diff from the live version to the following mailing lists:

* obsidian-pm-list@redhat.com
* obsidian-team-list@redhat.com
* rhoar-docs-team@redhat.com
* rhoar-qe-team@redhat.com

Send the e-mail also to the following mailing lists if the publication concerns the respective runtime specifically:

* Node.js: node-devel@redhat.com
* Spring Boot: rh-spring-engineering@redhat.com
* Thorntail: thorntail-internal@redhat.com
* Vert.x: vertx-devel@redhat.com

.Sample e-mail content
====
You can use the following template for the e-mail:

WARNING: Replace the placeholders with real data before sending.

----
Hello,

We have released the upstream documentation today.

Docs link: https://launcher.fabric8.io/docs/
Tag: https://github.com/fabric8-launcher/launcher-documentation/releases/tag/$NEW_TAG
Diff: https://github.com/fabric8-launcher/launcher-documentation/compare/$PREVIOUS_TAG...$NEW_TAG

The following issues were fixed:

...

We plan to do a downstream docs sync on $RELEASE_DATE.

Please reach out to rhoar-docs-team@redhat.com if you have any questions.
----
====

--

