// This is a parameterized module. Parameters used:
//
//   parameter-openshiftlocal: A local OpenShift installation is used, so a URL is required for proceeding.
//   parameter-deployment: A string containing the deployment to use, possibly in the form of a link
//
// Rationale: This procedure is identical in all deployments


[#authenticating-the-oc-cli-client-to-access-launcher_{context}]
= Authenticating the `oc` CLI Client to access {launcher}

To work with the {launcher} application on {parameter-deployment} using the `oc` command-line client, you need to authenticate it using the token the {launcher} application provides you.

.Prerequisites

ifdef::parameter-openshiftlocal[]
* The URL of your running {launcher} instance. For more information, see xref:getting-launcher-url-and-credentials-on-openshiftlocal_{context}[].
endif::[]
ifndef::parameter-openshiftlocal[]
* An account at {parameter-deployment}.
endif::[]

.Procedure
. Navigate to the {parameter-deployment} URL in a browser.
. Click on the question mark icon in the top right-hand corner of the Web console, next to your user name.
. Select _Command Line Tools_ in the drop-down menu.
. Find the text box that contains the `oc login ...` command with the hidden token, and click the button next to it to copy its content to your clipboard.
. Paste the command you copied in the previous step into a terminal application to authenticate your `oc` CLI client with your {parameter-deployment} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

