[id='deploying-a-booster-to-openshiftcontainerplatform_{context}']
[id='deploying-an-example-to-openshiftcontainterplatform_{context}']
= Deploying an example to {OpenShiftContainerPlatform}

.Prerequisites

* Have an example created using link:{link-launcher-oso}[{name-launcher-oso}] or the {name-launcher} tool in xref:creating-and-deploying-an-example-application-using-your-openshiftlocal_{context}[a {OpenShiftLocal}].
* Have access to an {OpenShiftContainerPlatform} Web console.
* Have the `oc` CLI client installed.

.Procedure

. Clone the Github repository with your example application, or download and extract the example application ZIP archive.
. Get the command containing your authentication token for using the `oc` CLI client with your {OpenShiftContainerPlatform} Web Console:
.. Login to your {OpenShiftContainerPlatform} Web console.
.. Click on the question mark icon in the top right-hand corner of the Web console, next to your user name.
.. Select _Command Line Tools_ in the drop-down menu.
.. Find the text box that contains the `oc login ...` command with the hidden token, and click the button next to it to copy its content to your clipboard.
. Paste the command you copied in the previous step into a terminal to authenticate your `oc` CLI client with your {OpenShiftContainerPlatform} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login OCP_URL --token=MYTOKEN
----

. Create a new project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {value-name-project}
----

. Navigate to the root directory of your application.

. Deploy your example to {OpenShiftContainerPlatform}.
.. If your example uses Maven: 
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
.. If your example uses `npm`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install && npm run openshift
----

. Open the `README.adoc` file in your example application's project and follow the instructions for interacting with your example application.

.Additional resources
Take a look at the different runtime guides to learn more about the runtimes and their example applications:

* link:{link-guide-spring-boot}[{name-guide-spring-boot}]
* link:{link-guide-vertx}[{name-guide-vertx}]
* link:{link-guide-thorntail}[{name-guide-thorntail}]
* link:{link-guide-nodejs}[{name-guide-nodejs}]
