[id='using-hystrix-dashboard-to-monitor-the-circuit-breaker_{context}']
= Using Hystrix Dashboard to Monitor the Circuit Breaker

Hystrix Dashboard lets you easily monitor the health of your services in real time by aggregating Hystrix metrics data from an event stream and displaying them on one screen.

[discrete]
== Prerequisites

* The application deployed

[discrete]
== Procedure

. Log in to your {OpenShiftLocal} cluster.
+
[source,bash,subs="attributes+",options="nowrap"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

. To access the Web console, use your browser to navigate to your {OpenShiftLocal} URL.

. Navigate to the project that contains your Circuit Breaker application.
+
[source,bash,subs="attributes+",options="nowrap"]
----
$ oc project {project-name}
----

. Import the link:https://raw.githubusercontent.com/snowdrop/openshift-templates/master/hystrix-dashboard/hystrix-dashboard.yml[YAML template] for the Hystrix Dashboard application.
You can do this by clicking _Add to Project_, then selecting the _Import YAML / JSON_ tab, and copying the contents of the YAML file into the text box.
Alternatively, you can execute the following command:
+
[source,bash,subs="attributes+",options="nowrap"]
----
$ oc create -f https://raw.githubusercontent.com/snowdrop/openshift-templates/master/hystrix-dashboard/hystrix-dashboard.yml
----

. Click the _Create_ button to create the Hystrix Dashboard application based on the template.
Alternatively, you can execute the following command.
+
[source,bash,subs="attributes+",options="nowrap"]
----
$ oc new-app --template=hystrix-dashboard
----

. Wait for the pod containing Hystrix Dashboard to deploy.

. Obtain the route of your Hystrix Dashboard application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route hystrix-dashboard
NAME                HOST/PORT                                                    PATH      SERVICES            PORT      TERMINATION   WILDCARD
hystrix-dashboard   hystrix-dashboard-{project-name}.{osl-route-hostname}                 hystrix-dashboard   <all>                   None
----

. To access the Dashboard, open the Dashboard application route URL in your browser.
Alternatively, you can navigate to the _Overview_ screen in the Web console and click the route URL in the header above the pod containing your Hystrix Dashboard application.

. To use the Dashboard to monitor the `{app-name}-greeting` service, replace the default event stream address with the following address and click the _Monitor Stream_ button.
+
--
ifdef::spring-boot[]
[source,subs="attributes+",options="nowrap"]
----
http://{app-name}-greeting-{project-name}.{osl-route-hostname}/hystrix.stream
----
endif::[]
ifndef::spring-boot[]
[source,subs="attributes+",options="nowrap"]
----
http://{app-name}-greeting/hystrix.stream
----
endif::[]
--

[discrete]
== Additional resources

* The Hystrix Dashboard link:https://github.com/Netflix/Hystrix/wiki/Dashboard[wiki page]
