[id='interacting-with-the-unmodified-configmap-booster-for-vertx_{context}']
[id='interacting-with-the-unmodified-configmap-example-for-vertx_{context}']
= Interacting with the unmodified {name-mission-configmap} example for {VertX}

The example provides a default HTTP endpoint that accepts GET requests.

.Prerequisites

* Your application running
* The `curl` binary or a web browser

.Procedure

. Use `curl` to execute a `GET` request against the example.
You can also use a browser to do this.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/greeting
{"content":"Hello, World from a ConfigMap !"}
----
. Update the deployed ConfigMap configuration.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc edit configmap app-config
----
+
Change the value for the `message` key to `Bonjour, %s from a ConfigMap !` and save the file.


. Update of the ConfigMap should be read by the application within an acceptable time (a few seconds) without requiring a restart of the application.

. Execute a `GET` request using `curl` against the example with the updated ConfigMap configuration to see your updated greeting.
You can also do this from your browser using the web form provided by the application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/greeting
{"content":"Bonjour, World from a ConfigMap !"}
----
