
[id='creating-custom-booster-catalog_{context}']
= Creating Custom Booster Catalog

By default, the {launcher} tool uses a booster catalog from the link:https://github.com/openshiftio/booster-catalog[openshiftio/booster-catalog] repository.
If you do not want to use the default catalog, you can create one from scratch, or fork the default catalog and make changes to it. This chapter describes the procedure for modifying the default catalog.

[discrete]
== Prerequisites

* A GitHub account

[discrete]
== Procedure

.Creating Custom Booster Catalog
. Navigate to the link:https://github.com/openshiftio/booster-catalog[openshiftio/booster-catalog] repository, which hosts the default booster catalog.
. Fork the repository by clicking _Fork_ in the top right corner of the page.
. Clone the forked repository locally to your hard drive.
. Make changes to the catalog, for example:
** Modify the existing booster listing by modifying the YAML files in the mission and runtime directories.
** Create a new listing by creating a new YAML file with the following structure in one of the runtime directories:
+
.Catalog YAML File
====
[source,yaml,opts="nowrap"]
----
githubRepo: USER/REPO
gitRef: BRANCH
----

In the example above, _USER_ is the GitHub user name or organization name and _REPO_ is the name of the repository where the booster is located.
_BRANCH_ is the branch in the booster repository you want to make available in the catalog.
====
** Modify the `metadata.json` file where additional information about the boosters are stored.
. Commit and push your changes to your forked repository.

