[id='creating-custom-booster-catalog_{context}']
[id='creating-a-custom-examples-catalog_{context}']
= Creating a custom {name-examples-catalog}

By default, the {name-launcher} tool uses an examples catalog from the link:https://github.com/openshiftio/booster-catalog[openshiftio/booster-catalog] repository.
If you do not want to use the default catalog, you can create one from scratch, or fork the default catalog and make changes to it. This chapter describes the procedure for modifying the default catalog.

.Prerequisites

* A GitHub account

.Procedure

.Creating a Custom {name-examples-catalog}
. Navigate to the link:https://github.com/openshiftio/booster-catalog[openshiftio/booster-catalog] repository, which hosts the default catalog.
. Fork the repository by clicking _Fork_ in the top right corner of the page.
. Clone the forked repository locally to your hard drive.
. Make changes to the catalog, for example:
** Modify the existing example application listing by modifying the YAML files in the directories for each application or runtime.
** Create a new listing by creating a new YAML file with the following structure in one of the runtime directories:
+
.Catalog YAML File
====
[source,yaml,opts="nowrap"]
----
githubRepo: USER/REPO
gitRef: BRANCH
----

In the example above, _USER_ is the GitHub user name or organization name and _REPO_ is the name of the repository where the example application is located.
_BRANCH_ is the branch in the repository you want to make available in the catalog.
====
** Modify the `metadata.yaml` file where additional information about the example applications is stored.
. Commit and push your changes to your forked repository.
