// This is a parameterized module. Parameters used:
//
//  context: used in anchor IDs to conflicts due to duplicate IDs.
//  env-var-name: Name of environment variable
//  env-var-val: value of environment variable
//  port: debugging port on OpenShift
//
// Rationale: This procedure is the same for 2 or more runtimes.

[id='starting-your-application-on-openshift-in-debugging-mode_{context}']
= Starting Your Application on OpenShift in Debugging Mode

To debug your {runtime}-based application on OpenShift remotely, you must set the `{env-var-name}` environment variable inside the container to `{env-var-val}` and configure port forwarding so that you can connect to your application from a remote debugger.

[discrete]
== Prerequisites

* Your application running on OpenShift.
* The `oc` binary installed on your machine.
* The ability to execute the `oc port-forward` command in your target OpenShift environment.

[discrete]
== Procedure

. Using the `oc` command, list the available deployment configurations:
+
[source,bash]
----
$ oc get dc
----

ifndef::nodejs[]
. Set the `{env-var-name}` environment variable in the deployment configuration of your application to `{env-var-val}`, which configures the JVM to open the port number `{port}` for debugging. 
endif::nodejs[]
ifdef::nodejs[]
. Set the `{env-var-name}` environment variable in the deployment configuration of your application to `{env-var-val}` to enable debugging.
endif::nodejs[]
For example:
+
[source,bash,subs="attributes+"]
----
$ oc set env dc/{app-name} {env-var-name}={env-var-val}
----

. Redeploy the application if it is not set to redeploy automatically on configuration change. For example:
+
[source,bash,subs="attributes+"]
----
$ oc rollout latest dc/{app-name}
----

. Configure port forwarding from your local machine to the application pod:
.. List the currently running pods and find one containing your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pod
NAME                            READY     STATUS      RESTARTS   AGE
{app-name}-3-1xrsp          0/1       Running     0          6s
...
----

.. Configure port forwarding:
+
--
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc port-forward {app-name}-3-1xrsp $LOCAL_PORT_NUMBER:{port}
----

Here, `$LOCAL_PORT_NUMBER` is an unused port number of your choice on your local machine.
Remember this number for the remote debugger configuration.
--

ifdef::nodejs[]
. Attach the V8 inspector and perform debugging commands. 
+
For example, if using Google Chrome:
+
.. Navigate to `chrome://inspect`.
.. Click _Configure_.
.. Add `127.0.0.1:$LOCAL_PORT_NUMBER`.
.. Click _Done_.
.. Select your application from below _Remote Target_.
.. You can now see the source of your application and can perform debugging actions.
endif::nodejs[]

. When you are done debugging, unset the `{env-var-name}` environment variable in your application pod. For example:
+
[source,bash,subs="attributes+"]
----
$ oc set env dc/{app-name} {env-var-name}-
----

ifndef::nodejs[]
[discrete]
== Additional resources

You can also set the `{env-var-name}_PORT` environment variable if you want to change the debug port from the default, which is `{port}`.
endif::nodejs[]
