[id='configuring-your-application-to-use-vertx_{context}']
= Configuring your application to use {VertX}

Reference the {VertX} BOM (Bill of Materials) artifact in the `pom.xml` file at the root directory of your application.

.Prerequisites

* A Maven-based application

.Procedure

. Open the `pom.xml` file, add the `io.vertx:vertx-dependencies` artifact to the `<dependencyManagement>` section, and specify the `<type>pom</type>` and `<scope>import</scope>`:
+
--
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
  ...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-dependencies</artifactId>
        <version>${vertx.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  ...
</project>
----
--
. Include the following properties to track the version of {VertX} and the Vert.x Maven Plugin you are using:
+
--
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
  ...
  <properties>
    <vertx.version>${vertx.version}</vertx.version>
    <vertx-maven-plugin.version>${vertx-maven-plugin.version}</vertx-maven-plugin.version>
  </properties>
  ...
</project>
----
--

. Reference `vertx-maven-plugin` as the plugin used to package your application:
+
--
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
  ...
  <build>
    <plugins>
        ...
        <plugin>
            <groupId>io.reactiverse</groupId>
            <artifactId>vertx-maven-plugin</artifactId>
            <version>${vertx-maven-plugin.version}</version>
            <executions>
                <execution>
                    <id>vmp</id>
                    <goals>
                        <goal>initialize</goal>
                        <goal>package</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <redeploy>true</redeploy>
            </configuration>
        </plugin>
        ...
    </plugins>
  </build>
  ...
</project>
----
--

. Include `repositories` and `pluginRepositories` to specify the repositories that contain the artifacts and plugins to build your application:
+
--
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
...
  <repositories>
    <repository>
      <id>{red-hat-ga-repo-id}</id>
      <name>{red-hat-ga-repo-name}</name>
      <url>{red-hat-ga-repo-url}</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>{red-hat-ga-repo-id}</id>
      <name>{red-hat-ga-repo-name}</name>
      <url>{red-hat-ga-repo-url}</url>
    </pluginRepository>
  </pluginRepositories>
...
</project>
----
--

.Additional resources

* For more information about packaging your {VertX} application, see the link:https://vmp.fabric8.io/#packaging[Vert.x Maven Plugin] documentation.
