= Running Integration Tests

.Prerequisites

* You are logged into an OpenShift instance.
* You are currently inside the project that you intend to use for testing.

.Procedure

ifdef::secured-wf-swarm-mission[]
[IMPORTANT]
--
The `keycloak-authz-client` library for {WildFlySwarm} is provided as a link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview] with limited supportability.
--
endif::secured-wf-swarm-mission[]

ifdef::secured-wf-swarm-mission,secured-spring-boot-mission[]
. Deploy the {RHSSO} server:
+
[source,bash,options="nowrap",subs="attributes+"]
--
oc apply -f service.sso.yaml
--
+
. Wait until the {RHSSO} server is ready. Go to the Web console or view the output of `oc get pods` to check if the pod is ready.
+
. Run the integration tests passing in the URL of the {RHSSO} server as a parameter:
+
[source,bash,options="nowrap",subs="attributes+"]
--
$ mvn clean verify -Popenshift,openshift-it -DSSO_AUTH_SERVER_URL=$(oc get route secure-sso -o jsonpath='{"https://"}{.spec.host}{"/auth\n"}')
--
+
. Once the test are finished, remove the {RHSSO} server:
+
[source,bash,options="nowrap",subs="attributes+"]
--
oc delete -f service.sso.yaml
--
endif::secured-wf-swarm-mission,secured-spring-boot-mission[]

//steps specific to Vert.x
ifdef::secured-vertx-mission[]
. Create the {RHSSO} server application:
+
[source,bash,options="nowrap",subs="attributes+"]
--
oc create -f service.sso.yaml
--
+
. Wait until the {RHSSO} server is ready. Go to the Web console or view the output of `oc get pods` to check if the pod running the {RHSSO} server is ready.
+
. Deploy the Secured HTTP API application:
+
[source,bash,options="nowrap",subs="attributes+"]
--
mvn fabric8:deploy -Popenshift
--
+
. Wait until the Secured HTTP API is ready. Go to the Web console or view the output of `oc get pods` to check if the pod running the HTTP API endpoint is ready.
+
. Run the integration tests:
+
[source,bash,options="nowrap",subs="attributes+"]
--
mvn verify -Popenshift-it
--
endif::secured-vertx-mission[]
