= Show Debug Logging on OpenShift

Start your application and interact with it to see the debugging statements in OpenShift.

.Prerequisites 
* An application with debug logging.
* The `oc` CLI client installed.


.Procedure

. Use the `oc` CLI client to log into your OpenShift instance.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login ...
----

. Deploy your application to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----

. Find the name of your pod and follow the logs to watch it start.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
....
$ oc logs -f pod/POD_NAME
----
+
IMPORTANT: After your pod has started, keep watching the logs.

. Test your application. 
+
For example, if you had debug logging in the xref:mission-http-api-spring-boot-tomcat[{name-mission-http-api} booster] to log the `message` variable in the `/api/greeting` method:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
...
$ curl $APPLICATION_ROUTE/api/greeting?name=Sarah
----

. Return to your pod logs and notice there are debug logging messages in the logs.
+
[source,bash,options="nowrap",subs="attributes+"]
----
i.o.booster.service.GreetingEndpoint     : Message: Hello, Sarah!
---- 

To disable debug logging, remove `logging.level.fully.qualified.name.of.TheClass=DEBUG` from `src/main/resources/application.properties` and redeploy your application.
