// This is a parameterized module. Parameters used:
//
// parameter-jar-file-name: runtime-specific default target Maven build artifact name.
// parameter-version-runtime-plugin: runtime-specific name for the runtime version property variable in the POM file.
// parameter-artifact-name-runtime-plugin: runtime plugin name in the POM file.
// parameter-group-name-runtime-plugin: runtime plugin Maven artifact group name.
// parameter-runtime-name: Runtime specific atribute for substituting the approrpiate expanded rumtime name.
// parameter-link-appdev-guide: link to the procedure providing a complete example of the appropriate runtime-specific POM file configuration.
//  context: used in anchor IDs to conflicts due to duplicate IDs.
//
// Rationale: This procedure is the same for 2 or more runtimes.
[id='preparing-runtime-application-for-standalone-red-hat-enterprise-linux_{context}']
= Preparing {runtime} application for standalone Red Hat Enterprise Linux deployment

ifdef::built-for-vertx[]
For deploying an {runtime} application to standalone Red Hat Enterprise Linux, you must first package the application using Maven.
endif::[]
ifndef::built-for-vertx[]
For deploying a {runtime} application to standalone Red Hat Enterprise Linux, you must first package the application using Maven.
endif::[]

.Prerequisites

* Maven installed.

.Procedure

. Add the following content to the `pom.xml` file in the application's root directory:
+
[source,xml,options="nowrap",subs="attributes+"]
----
ifdef::built-for-spring-boot,built-for-spring-boot-1-5[]
  ...
  <!-- Specify target artifact type for the repackage goal. -->
  <packaging>jar</packaging>
endif::[]
  ...
  <build>
    <plugins>
      <plugin>
        <groupId>{parameter-group-name-runtime-plugin}</groupId>
        <artifactId>{parameter-artifact-name-runtime-plugin}</artifactId>
        <version>{parameter-version-runtime-plugin}</version>
ifdef::built-for-vertx[]
        <executions>
          <execution>
            <id>vmp</id>
            <goals>
              <goal>initialize</goal>
              <goal>package</goal>
            </goals>
          </execution>
        </executions>
endif::[]
ifdef::built-for-thorntail[]
        <executions>
          <execution>
            <goals>
              <goal>package</goal>
            </goals>
          </execution>
        </executions>
endif::[]
ifdef::built-for-spring-boot,built-for-spring-boot-1-5[]
        <executions>
          <execution>
              <goals>
               <goal>repackage</goal>
             </goals>
          </execution>
        </executions>
endif::[]
      </plugin>
    </plugins>
  </build>
  ...
----

. Package your application using Maven.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean package
----
