[id='starting-your-application-locally-and-attaching-the-v8-inspector_{context}']
= Starting your Application Locally and Attaching the V8 Inspector
The V8 inspector enables you to debug your {Node}{ndash}based application using other tools, such as link:https://developers.google.com/web/tools/chrome-devtools/[Chrome DevTools], that use the link:https://chromedevtools.github.io/debugger-protocol-viewer/1-2/[Chrome Debugging Protocol].

.Prerequisites 
* An application you want to debug.
* The V8 inspector installed, such as the one provided in link:https://www.google.com/chrome/index.html[the Google Chrome Browser].


.Procedure
. Start your application with the link:https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js[V8 inspector integration enabled].
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ node --inspect app.js
----
+
If you have a different entry point for your application, you need to change the command to specify that entry point:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ node --inspect path/to/entrypoint
----
+
For example, when using the link:https://expressjs.com/en/starter/generator.html[express generator] to create your application, the entry point is set to `./bin/www` by default. Some of the boosters, such as the xref:mission-rest-http-nodejs[{name-mission-http-api} booster], use `./bin/www` as an entry point.

. Attach the V8 inspector and perform debugging commands. 
+
For example, if using Google Chrome:
+
.. Navigate to `chrome://inspect`.
.. Select your application from below _Remote Target_.
.. You can now see the source of your application and can perform debugging actions.