// This is a parameterized module. Parameters used:
//
//   parameter-custom-catalog: A custom catalog is used instead of the default one
//
// Rationale: This module is useful both when setting up minishift as is and when testing a local
// booster catalog.

[id='installing-launcher-tool-addon_{context}']
= Installing {launcher} Tool as an Add-on
link:https://docs.openshift.org/latest/minishift/using/addons.html[Add-ons] enable you to extend the behavior of {OpenShiftLocal}, and the {launcher} tool link:https://github.com/minishift/minishift-addons/tree/master/add-ons/fabric8-launcher[provides an add-on] as an installation option.

.Prerequisites
* xref:starting-and-configuring-the-openshiftlocal-for-the-launcher-tool_{context}[{OpenShiftLocal} running].
* A link:{link-launcher-openshift-local-install-guide}#creating-a-github-personal-access-token[GitHub personal access token].

.Procedure

. Download and install the {launcher} add-on.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:minishift/minishift-addons.git
$ minishift addon install minishift-addons/add-ons/fabric8-launcher/
$ minishift addons apply fabric8-launcher \ 
      --addon-env GITHUB_USERNAME=GH_USERNAME --addon-env GITHUB_TOKEN=TOKEN <1>
----
<1> Use your GitHub username and personal access token
+
Installing the add-on creates a new project called `rhoarpad` where the {launcher} tool runs.

. Monitor the status of the {launcher} tool until it completes start up.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc project rhoarpad
$ oc get pods -w
NAME                           READY     STATUS              RESTARTS   AGE
configmapcontroller-1-deploy   1/1       Running             0          46s
configmapcontroller-1-aaaaa    0/1       ContainerCreating   0          44s
launcher-backend-1-deploy      1/1       Running             0          46s
...
launcher-backend-2-aaaaa       0/1       Running             0         5s
launcher-frontend-2-aaaaa      0/1       Running             0         6s
----

. Obtain the route of your {launcher} tool.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME       HOST/PORT                                PATH      SERVICES            PORT      TERMINATION   WILDCARD
launcher   launcher-rhoarpad.{osl-route-hostname}             launcher-frontend   <all>                   None
----

. Navigate to your {launcher} tool and start using your {launcher} tool to launch booster applications.
+
This is the same service as `{link-launcher-oso}` but running in a {OpenShiftLocal}.

.Additional Resources
* See the link:{link-getting-started-guide}[{getting-started-guide-name}] for a walk-through of running a booster application.
* Read the runtime guides for an overview of the runtimes and their boosters:
** link:{link-spring-boot-runtime-guide}[{spring-boot-runtime-guide-name}]
** link:{link-vertx-runtime-guide}[{vertx-runtime-guide-name}]
** link:{link-wf-swarm-runtime-guide}[{wf-swarm-runtime-guide-name}]
** link:{link-nodejs-runtime-guide}[{nodejs-runtime-guide-name}]