// This is a parameterized module. Parameters used:
//
//  context: context of usage, e.g. "osl", "oso", "ocp", "rest-api", etc. This can also be a composite, e.g. "rest-api-oso"
//
// Rationale: This procedure is identical in all deployments.


[id='deploying-the-configmap-booster-using-the-oc-cli-client_{context}']
= Deploying the {name-mission-configmap} booster using the `oc` CLI client

.Prerequisites

* The booster application created using {parameter-deployment}.
ifndef::parameter-openshiftlocal[For more information, see xref:deploying-the-booster-using-launcher-oso_{context}[].]
ifdef::parameter-openshiftlocal[]
For more information, see xref:deploying-the-booster-using-the-launcher-tool_{context}[].
* Your {launcher} tool URL.
endif::[]

* The `oc` client authenticated. For more information, see xref:authenticating-the-oc-cli-client_{context}[].

.Procedure
. Clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/{value-name-project}.git
----
+
Alternatively, if you downloaded a ZIP file of your project, extract it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ unzip {value-name-project}.zip
----

. Create a new OpenShift project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {value-name-project}
----

ifdef::built-for-vertx,built-for-spring-boot,built-for-nodejs[]
. Assign view access rights to the service account before deploying your booster, so that the booster can access the OpenShift API in order to read the contents of the ConfigMap.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc policy add-role-to-user view -n $(oc project -q) -z default
----
endif::built-for-vertx,built-for-spring-boot,built-for-nodejs[]

. Navigate to the root directory of your booster.

ifdef::built-for-vertx,built-for-nodejs[]
. Deploy your ConfigMap configuration to OpenShift using `app-config.yml`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=app-config.yml
----

. Verify your ConfigMap configuration has been deployed.
+
[source,bash,options="nowrap"]
----
$ oc get configmap app-config -o yaml

apiVersion: v1
data:
  app-config.yml: |-
      message : "Hello, %s from a ConfigMap !"
      level : INFO
...
----
endif::built-for-vertx,built-for-nodejs[]
ifdef::built-for-thorntail[]
. Deploy your ConfigMap configuration to OpenShift using `app-config.yml` in the root of the booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=app-config.yml
----

. Verify your ConfigMap configuration has been deployed.
+
[source,bash,options="nowrap"]
----
$ oc get configmap app-config -o yaml

apiVersion: v1
data:
  app-config.yml: |-
    greeting:
      message: Hello %s from a ConfigMap!
...
----
endif::built-for-thorntail[]
ifdef::built-for-spring-boot[]
. Deploy your ConfigMap configuration to OpenShift using `application.yml`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=application.yml
----

. Verify your ConfigMap configuration has been deployed.
+
[source,bash,options="nowrap"]
----
$ oc get configmap app-config -o yaml

apiVersion: v1
data:
  application.yml: |
     # This properties file should be used to initialise a ConfigMap
     greeting:
       message: "Hello %s from a ConfigMap!"
...
----
endif::built-for-spring-boot[]

ifndef::built-for-nodejs[]
. Use Maven to start the deployment to OpenShift.
+
ifdef::built-for-vertx,built-for-spring-boot[]
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
endif::built-for-vertx,built-for-spring-boot[]
ifdef::built-for-thorntail[]
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DskipTests
----
endif::built-for-thorntail[]
+
This command uses the Fabric8 Maven Plugin to launch the link:{link-s2i-process}[S2I process] on OpenShift and to start the pod.
endif::built-for-nodejs[]

ifdef::built-for-nodejs[]
. Use `npm` to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install && npm run openshift
----
+
These commands install any missing module dependencies, then using the xref:about-nodeshift[Nodeshift] module, deploy the booster on OpenShift.
endif::built-for-nodejs[]

. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                                       READY     STATUS      RESTARTS   AGE
{value-name-app}-1-aaaaa               1/1       Running     0          58s
{value-name-app}-s2i-1-build           0/1       Completed   0          2m
----
+
The `{value-name-app}-1-aaaaa` pod should have a status of `Running` once its fully deployed and started.
ifdef::built-for-vertx[]
You should also wait for your pod to be _ready_ before proceeding, which is shown in the `READY` column. For example, `{value-name-app}-1-aaaaa` is _ready_ when the `READY` column is `1/1`.
endif::built-for-vertx[]
Your specific pod name will vary.
The number in the middle will increase with each new build.
The letters at the end are generated when the pod is created.


. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{value-name-app}         {value-name-app}-{value-name-project}.{value-route-openshift-hostname}      {value-name-app}      8080
----
+
The route information of a pod gives you the base URL which you use to access it. In the example above, you would use `\http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}` as the base URL to access the application.
