// This is a parameterized module. Parameters used:
//
//  parameter-runtime-name: human-readable name of the runtime. This is used in readable text
//  context: used in anchor IDs to conflicts due to duplicate IDs
//
// Rationale: This procedure is the same for 2 or more runtimes.

[id='preparing-runtime-application-for-openshift-deplyoment_{context}']
= Preparing {runtime} application for OpenShift deployment

For deploying your {runtime} application to OpenShift, it must contain:

* Launcher profile information in the application’s `pom.xml` file.
ifdef::built-for-vertx[]
* A deployment yaml file containing environment details.
endif::[]

In the following procedure, a profile with Fabric8 Maven plugin is used for building and deploying the application to OpenShift.

.Prerequisites

* Maven is installed.
* Docker or podman authentication into link:https://access.redhat.com/containers/[Red Hat Container Catalog] to access RHEL 8 images.

.Procedure

. Add the following content to the `pom.xml` file in the application root directory:
+
ifdef::built-for-vertx[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertx-openshift-pom-config-example.xml[]
----
endif::[]

ifdef::built-for-thorntail[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/thorntail/thorntail-openshift-pom-config-example.xml[]
----
endif::[]
ifdef::built-for-spring-boot[]
[source,xml,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/spring-boot-openshift-pom-config-example.xml[]
----
endif::[]

. Replace the `fabric8.generator.from` property in the `pom.xml` file to specify OpenJDK image.

* RHEL 7 with OpenJDK 8
+
[source,xml,options="nowrap",subs="attributes+"]
----
<fabric8.generator.from>{name-2si-image-openjdk8-rhel7}</fabric8.generator.from>
----

* RHEL 7 with OpenJDK 11
+
[source,xml,options="nowrap",subs="attributes+"]
----
<fabric8.generator.from>{name-2si-image-openjdk11-rhel7}</fabric8.generator.from>
----

* RHEL 8 with OpenJDK 8
+
[source,xml,options="nowrap",subs="attributes+"]
----
<fabric8.generator.from>{name-2si-image-openjdk8-rhel8}</fabric8.generator.from>
----

* RHEL 8 with OpenJDK 11
+
[source,xml,options="nowrap",subs="attributes+"]
----
<fabric8.generator.from>{name-2si-image-openjdk11-rhel8}</fabric8.generator.from>
----

ifdef::built-for-vertx[]
. Create `deployment.yaml` file in `src/main/fabric8` directory with the following content:
+
[source,yaml,options="nowrap",subs="attributes+"]
----
include::resources/vert-x/vertx-fmp-deployment.yaml[]
----
endif::[]
