// This is a parameterized module. Parameters used:
//
//   parameter-debug-property: The Java application property used to specify the debug port
//   parameter-maven-goal: Name of the runtime and the goal for executing debugging, e. g. "vertx:run"
//
// Rationale: This procedure is identical in Swarm and Vert.x


[id='starting-your-application-locally-in-debugging-mode_{context}']
= Starting your application locally in debugging mode

One of the ways of debugging a Maven-based project is manually launching the application while specifying a debugging port, and subsequently connecting a remote debugger to that port.
This method is applicable at least to the following deployments of the application:

ifdef::built-for-vertx[* When launching the application manually using the `mvn {parameter-maven-goal}` goal. This starts the application with debugging enabled.]
ifdef::wf-swarm[]
* When launching the application manually using the `mvn {parameter-maven-goal}` goal.
* When starting the application without waiting for it to exit using the `mvn wildfly-swarm:start` goal.
This is useful especially when performing integration testing.
* When using the Arquillian adapter for {runtime}.
endif::[]

[discrete]
== Prerequisites

* A Maven-based application

[discrete]
== Procedure

. In a console, navigate to the directory with your application.
. Launch your application and specify the debug port using the `-D{parameter-debug-property}` argument:
+
--
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn {parameter-maven-goal} -D{parameter-debug-property}=$PORT_NUMBER
----

Here, `$PORT_NUMBER` is an unused port number of your choice.
Remember this number for the remote debugger configuration.

ifdef::built-for-vertx[Use the `-Ddebug.suspend=true` argument to make the application wait until a debugger is attached to start.]
--

