[id='adding-new-guide_{context}']
= Adding New Guide

To add a new guide to the existing documentation set, perform the following steps:

[discrete]
== Procedure

.Adding New Guide
. Create a new directory for the guide under `docs/`, for example `docs/my-new-guide`.
. Create basic infrastructure in the directory of the new guide:
** Create a `master.adoc` file.
** Create a symbolic link called `topics` that points to `../topics`:
+
[source,options="nowrap"]
----
$ ln -s ../topics topics
----
** Copy the `build_guide.sh` script from another guide's folder. Modify the script so that the `GUIDE_HTML_NAME` variable is set to the directory name of the new book, for example:
+
[source,options="nowrap"]
----
GUIDE_HTML_NAME=my-new-guide
----
. Add the default content to the `master.adoc` file:
+
[source,asciidoc,options="nowrap"]
----
\include::topics/templates/document-attributes.adoc[]

:my-new-guide:

= {my-new-guide-guide-name}
----
. Add the new guide name to the `docs/topics/templates/document-attributes.adoc` file:
+
[source,asciidoc,options="nowrap"]
----
:my-new-guide-guide-name: My New Guide
----
. Ensure the new guide builds correctly by executing the `scripts/build_guides.sh` script.
. Open the generated HTML file to ensure everything is rendered correctly:
+
--
[source,bash,options="nowrap"]
----
$ firefox html/my-new-guide.html
----

In the command above, replace `firefox` with the browser of your choice.
--
. Write the content of the guide. When you are ready for some initial review and feedback, file a pull request to the `master` branch in the link:{link-repo-docs}[{repo-docs-name}] repository.
