
[#accessing-debug-log-output-on-openshift_{context}]
= Accessing Debug Log Output on OpenShift

This procedure shows you how to view the debug log output of your Java application running in a container on OpenShift.

.Prerequisites
* An application with debug logging runnig on OpenShift.
* The `oc` client authenticated.

.Procedure

. Using the `oc` command, list the available deployment configurations:
+
[source,bash]
----
$ oc get dc
----

// does the same env var apply for Vert.x?
. Set the `JAVA_ENABLE_DEBUG` environment variable in the deployment configuration of your application to `true`:
+
[source,bash,subs="attributes+"]
----
$ oc set env dc/{app-name} JAVA_ENABLE_DEBUG=true
----
+
. If configured to do so, you application will redeploy after the configuration change.
To manually redeploy your application, execute:
+
[source,bash,subs="attributes+"]
----
$ oc rollout latest dc/{app-name}
----
+
. Obtain the name of your pod:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
----
+
// Add alternative workflow using web console?
. Follow the console log output for the pod you have just redeployed:
+
----
$ oc logs -f pod/{app-name}-2-aaaaa
----
+
. Keep the terminal window displaying the log output open, so you can continue following the log output.
+
. Interact with your application.
+
// the `mission-http-api-{context}` anchor is a workaround to allow sharing content between runtimes. The Anchor naming scheme should be revised as per RHOARDOC-793.
For example, if you had debug logging in the xref:mission-http-api-{context}[{name-mission-http-api} booster] to log the `name` variable in the `/api/greeting` method:

.. Obtain the route of your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route/{app-name}
----
+
.. Make an HTTP request on the `/api/greeting` endpoint of your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl {app-name}.{os-route-hostname}/api/greeting?name=Sarah
----
+
// Maybe use a `java.util.logging` example instead of SLF4J?
. Examine the output in the terminal window that displays the logs to view the output:
+
[source,options="nowrap",subs="attributes+"]
----
...
Feb 11, 2017 10:23:42 AM io.openshift.{app-name}
INFO: Greeting: Hello, Sarah
...
----
+
. To disable debug logging, unset the `JAVA_ENABLE_DEBUG` environment variable:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc set env dc DC_NAME DEBUG-
----

.Related Information

More details on environment variables are available in the link:https://docs.openshift.com/online/dev_guide/environment_variables.html[OpenShift documentation].
