[id='preparing-a-application-for-openshift-deplyoment_{context}']
= Preparing {Node} application for OpenShift deployment

To prepare a {Node} application for OpenShift deployment, you must perform the following steps:

* Add `nodeshift` to the application.
* Add `openshift` and `start` entries to the `package.json` file.  

.Prerequisites
* `npm` installed.

.Procedure
. Add `nodeshift` to your application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install nodeshift --save
----

. Add the `openshift` and `start` entries to the `scripts` section in `package.json`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{
  "name": "myApp",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "openshift": "nodeshift --strictSSL=false --metadata.out=deployment-metadata.json --build.forcePull=true {version-node-nodeshift}",
    "start": "node app.js",
    ...
  }
  ...
}
----
+
The `openshift` script uses `nodeshift` to deploy the application to OpenShift.

. _Optional_: Add a `files` section in `package.json`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
{
  "name": "myApp",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    ...
  },
  "files": [
    "package.json",
    "app.js"
  ]
  ...
}
----
+
The `files` section tells `nodeshift` what files and directories to include when deploying to OpenShift.
`nodeshift` uses the link:https://github.com/npm/node-tar[`node-tar`] module to create a tar file based on the files and directories you list in the `files` section.
This tar file is used when `nodeshift` deploys your application to OpenShift.
If the `files` section is not specified, `nodeshift` will send the entire current directory, excluding:
+
* `node_modules/`
* `.git/`
* `tmp/`
+
It is recommended that you include a `files` section in `package.json` to avoid including unnecessary files when deploying to OpenShift.
