[id='configuring-your-vertx-application-to-use-agroal_{context}']
= Configuring your {VertX} application to use Agroal

// hard-coded version, beacuse it does not change
Starting with {VertX} release `3.5.1.redhat-003`, Agroal replaced C3PO as the default JDBC connection pool. C3PO and Agroal use different property names and upgrading to a newer release of {VertX} might break the JDBC connection pool configuration of your {VertX} applications.
Update the property names in the configuration of your JDBC connection pool to avoid this issue.

NOTE: To continue using C3P0 as the JDBC connection pool for your application, set the value of the `provider_class` property in your JDBC connection pool configuration to `io.vertx.ext.jdbc.spi.impl.C3P0DataSourceProvider`.

.Procedure

. Update the following property names within your JDBC connection pool configuration to match the connection pool you use:

[options="header"]
|===
| C3P0 property name | Agroal property name
| url | jdbcUrl
| driver_class | driverClassName
| user | principal
| password | credential
| castUUID | castUUID
|===

.Additional information

* Example JDBC connection pool configuration using C3P0:
+
[source,java,options="nowrap"]
--
JsonObject config = new JsonObject()
	.put("url", JDBC_URL)
	// set C3P0 as the JDBC connection pool:
	.put("provider_class", "io.vertx.ext.jdbc.spi.impl.C3P0DataSourceProvider")
	.put("driver_class", "org.postgresql.Driver")
	.put("user", JDBC_USER)
	.put("password", JDBC_PASSWORD)
	.put("castUUID", true);
--

* Example JDBC connection pool configuration using Agroal:
+
[source,java,options="nowrap"]
--
JsonObject config = new JsonObject()
	.put("jdbcUrl", JDBC_URL)
	.put("driverClassName", "org.postgresql.Driver")
	.put("principal", JDBC_USER)
	.put("credential", JDBC_PASSWORD)
	.put("castUUID", true);
--
