[id='creating-basic-and-form-based-authentication-in-reactive-spring-boot-http-application-with-webflux_{context}']
= Using basic and form-based authentication in a reactive {SpringBoot} WebFlux application.

Create a reactive HTTP web service with Spring Security and WebFlux that uses basic and form-based authentication.

.Prerequisites

* Java JDK 8 or Java JDK 11 installed
* Maven installed
* A Maven-based application project configured link:{link-guide-spring-boot}#configuring-your-application-to-use-spring-boot_spring-boot[configured to use Spring Boot]


.Procedure

. Add `vertx-spring-boot-starter-http` and `spring-boot-starter-security` as dependencies in the `pom.xml` file of your project.

.`pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<project>
...
  <dependencies>
  ...
include::resources/spring-boot/reactive-examples/example-http-service-authenticated-webflux-pom.xml[tags=http-service-authenticated-pom-dependencies]
  ...
  <dependencies>
...
</project>
----

. Create an endpoint controller class for your application:
+
.`HelloController.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-http-service-authenticated-endpoint-controller.java[]
----

. Create the main class of your application:
+
.`HttpSecuritySampleApplication.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-http-service-authenticated.java[]
----

. Create a `SecurityConfiguration` class that stores the user credentials for accessing the `/hello` endpoint.
+
.`SecurityConfiguration.java`
[source,java,options="nowrap",subs="attributes+"]
----
include::resources/spring-boot/reactive-examples/example-http-service-authenticated-security-configuration.java[]
----

. OPTIONAL: Run and test your application locally:

.. Navigate to the root directory of your Maven project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd myApp
----

.. Package your application:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean package
----

.. Start your application from the command line:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ java -jar target/vertx-spring-boot-sample-http-security.jar
----

.. Navigate to `http://localhost:8080` using a web browser to access the login screen.

.. Log in using the credentials below:
+
--
* username: user
* password: user
--
+
You receive a customized greeting when you are logged in:
+
----
Hello, user!
----

.. Navigate to `http://localhost:8080/logout` using and use the _Log out_ button to log out of your application.

.. Alternatively, use a terminal to make an unauthenticated HTTP request on `localhost:8080`.
You receive HTTP `401 Unauthorized` response from your application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl -I http://localhost:8080
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="Realm"
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1 ; mode=block
Referrer-Policy: no-referrer
----

.. Issue an authenticated request using the example user credentials.
You receive a personalized response.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl -u user:user http://localhost:8080
Hello, user!
----

.Additional resources

* You can link:{link-guide-spring-boot}#deploying-runtime-application-to-openshift_spring-boot[deploy your application to an OpenShift cluster] using Fabric8 Maven Plugin.

* You can also configure your application for link:{link-guide-spring-boot}#deploying-runtime-application-to-standalone-red-hat-enterprise-linux_spring-boot[deployment on standalone Red{nbsp}Hat Enterprise Linux].

* For the full specification of the Basic HTTP authentication scheme, see document link:https://tools.ietf.org/html/rfc7617[RFC-7617].

* For the full specification of HTTP authentication extensions for interactive clients, including form-based authentication, see document link:https://tools.ietf.org/html/rfc8053[RFC-8053].
