[id='interacting-with-the-crud-api-on-node_{context}']
= Interacting with the {name-example-crud} API on {Node}

When you have finished creating your example application, you can interact with it the following way:

.Prerequisites

* Your application running
* The `curl` binary or a web browser

.Procedure

. Obtain the URL of your application by executing the following command:
+
--
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route {value-name-app}
----

[source,option="nowrap",subs="attributes+"]
----
NAME                 HOST/PORT                                         PATH      SERVICES             PORT      TERMINATION
{value-name-app}           {value-name-app}-{value-name-project}.{value-route-openshift-hostname}              {value-name-app}           8080
----
--

. To access the web interface of the database application, navigate to the _application URL_ in your browser:
+
--
[source,bash,subs="attributes+"]
----
http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}
----

Alternatively, you can make requests directly on the `api/fruits/*` endpoint using `curl`:

.List all entries in the database:
[source,bash,subs="attributes+"]
----
$ curl http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/fruits
----

[source,json,subs="attributes+"]
----
[ {
  "id" : 1,
  "name" : "Apple",
  "stock" : 10
}, {
  "id" : 2,
  "name" : "Orange",
  "stock" : 10
}, {
  "id" : 3,
  "name" : "Pear",
  "stock" : 10
} ]
----

.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/fruits/3
----

[source,json,options="nowrap",subs="attributes+"]
----
{
  "id" : 3,
  "name" : "Pear",
  "stock" : 10
}
----

.Create a new entry:
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl -H "Content-Type: application/json" -X POST -d '{"name":"Peach","stock":1}'  http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/fruits
----

[source,json,options="nowrap",subs="attributes+"]
----
{
  "id" : 4,
  "name" : "Peach",
  "stock" : 1
}
----

.Update an Entry
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl -H "Content-Type: application/json" -X PUT -d '{"name":"Apple","stock":100}'  http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/fruits/1
----

[source,json,options="nowrap",subs="attributes+"]
----
{
  "id" : 1,
  "name" : "Apple",
  "stock" : 100
}
----

.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl -X DELETE http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}/api/fruits/1
----
--

[discrete]
== Troubleshooting

* If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.
