// This is a parameterized module. Parameters used:
//
//  context: context of usage, e.g. "osl", "oso", "ocp", "rest-api", etc. This can also be a composite, e.g. "rest-api-oso"
//
// Rationale: This procedure is identical in all deployments.


[id='deploying-the-crud-example-application-using-the-oc-cli-client_{context}']
= Deploying the {name-example-crud} example application using the `oc` CLI client

.Prerequisites

* The example application created using {parameter-deployment}.
ifndef::parameter-openshiftlocal[For more information, see xref:deploying-the-example-application-using-launcher-oso_{context}[].]
ifdef::parameter-openshiftlocal[]
For more information, see xref:deploying-the-example-application-using-the-launcher-tool_{context}[].
* Your {name-launcher} tool URL.
endif::[]

* The `oc` client authenticated. For more information, see xref:authenticating-the-oc-cli-client_{context}[].

.Procedure
. Clone your project from GitHub.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:USERNAME/{value-name-project}.git
----
+
Alternatively, if you downloaded a ZIP file of your project, extract it.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ unzip {value-name-project}.zip
----

. Create a new OpenShift project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {value-name-project}
----

. Navigate to the root directory of your application.

. Deploy the PostgreSQL database to OpenShift.
Ensure that you use the following values for user name, password, and database name when creating your database application.
The example application is pre-configured to use these values.
Using different values prevents your application from integrating with the database.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-app -e POSTGRESQL_USER=luke -ePOSTGRESQL_PASSWORD=secret -ePOSTGRESQL_DATABASE=my_data openshift/postgresql-92-centos7 --name=my-database
----

. Check the status of your database and ensure the pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
my-database-1-aaaaa   1/1       Running   0         45s
my-database-1-deploy   0/1       Completed   0         53s
----
+
The `my-database-1-aaaaa` pod should have a status of `Running` and should be indicated as ready once it is fully deployed and started.
Your specific pod name will vary.
The number in the middle will increase with each new build.
The letters at the end are generated when the pod is created.


ifndef::built-for-nodejs[]
. Use maven to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the link:{link-s2i-process}[S2I process] on OpenShift and to start the pod.
endif::built-for-nodejs[]

ifdef::built-for-nodejs[]
. Use `npm` to start the deployment to OpenShift.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install && npm run openshift
----
+
These commands install any missing module dependencies, then using the xref:about-nodeshift[Nodeshift] module, deploy the example application on OpenShift.
endif::built-for-nodejs[]

. Check the status of your application and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{value-name-app}-1-aaaaa       1/1       Running     0          58s
{value-name-app}-s2i-1-build   0/1       Completed   0          2m
----
+
Your `{value-name-app}-1-aaaaa` pod should have a status of `Running` and should be indicated as ready once it is fully deployed and started.

. After your example application is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                     PATH      SERVICES             PORT      TERMINATION
{value-name-app}   {value-name-app}-{value-name-project}.{value-route-openshift-hostname}      {value-name-app}   8080
----
+
The route information of a pod gives you the base URL which you use to access it. In the example above, you would use `\http://{value-name-app}-{value-name-project}.{value-route-openshift-hostname}` as the base URL to access the application.
