[[create-gh-personal-access-token]]
= Creating a GitHub Personal Access Token
In order to install the {launcher} application on a {OpenShiftLocal}, you must provide the {launcher} application with a GitHub personal access token. This enables the {launcher} application to create booster applications and save them as git repositories in your GitHub namespace. This chapter shows you how to create a GitHub personal access token.

[sidebar]
.Prerequisites
--
* A link:http://github.com[GitHub account].
--

.Procedure
. Using a web browser, navigate to `https://github.com/settings/tokens`.
. Select _Generate new token_.
. Add a token description, for example `{launcher} on a {OpenShiftLocal}`.
. Using the check boxes, select the following parent scopes and all their children:
** `repo`
** `admin:repo_hook`
. Click  _Generate token_.
. Save the hex code of the personal access token. You need this to complete the installation of the {launcher} application on your {OpenShiftLocal}.
+
IMPORTANT: This hex code only appears once and cannot be recreated. If you lose this hex code you will need to create a new personal access token in order to install the {launcher} application on a {OpenShiftLocal} again.
