// This is a parameterized module. Parameters used:
//
//
//  parameter-example: id of the mission. This is used in anchors file imports.
//  parameter-example-name: used in the mission title
//
// Rationale: This procedure is identical in all deployments.
// TODO: Add conditional includes for Node.

[#interacting-with-the-unmodified-booster-{context}]
[id='interacting-with-the-unmodified-example-application_{context}']
= Interacting with the unmodified {runtime} {parameter-example-name} example application

After you have the {runtime} example application deployed, you have the following services running:

`{value-name-app}-name`::
Exposes the following endpoints:

* the `/api/name` endpoint, which returns a name when this service is working, and an error when this service is set up to demonstrate failure.

* the `/api/state` endpoint, which controls the behavior of the `/api/name` endpoint and determines whether the service works correctly or demonstrates failure.

`{value-name-app}-greeting`::
Exposes the following endpoints:

* the `/api/greeting` endpoint that you can call to get a personalized greeting response.
+
When you call the `/api/greeting` endpoint, it issues a call against the `/api/name` endpoint of the `{value-name-app}-name` service as part of processing your request.
The call made against the `/api/name` endpoint is protected by the Circuit Breaker.
+
If the remote endpoint is available, the `name` service responds with an HTTP code `200` (`OK`) and you receive the following greeting from the `/api/greeting` endpoint:
+
----
{"content":"Hello, World!"}
----
+
If the remote endpoint is unavailable, the `name` service responds with an HTTP code `500` (`Internal server error`) and you receive a predefined fallback response from the `/api/greeting` endpoint:
+
----
{"content":"Hello, Fallback!"}
----

* the `/api/cb-state` endpoint, which returns the state of the Circuit Breaker.
The state can be:
** _open_ : the circuit breaker is preventing requests from reaching the failed service,
** _closed_: the circuit breaker is allowing requests to reach the service.
ifdef::built-for-vertx[]
** _half-open_: the circuit breaker is allowing a request to reach the service. If the request succeeds, the state of the service is reset to closed. If the request fails, the timer is restarted.
endif::[]

The following steps demonstrate how to verify the availability of the service, simulate a failure and receive a fallback response.

//TODO: add a warning not to use `http` as it may contain cached responses from the remote endpoint.
. Use `curl` to execute a `GET` request against the `{value-name-app}-greeting` service. You can also use the `Invoke` button in the web interface to do this.
// include image of the invoke button?
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl http://{value-name-app}-greeting-{value-name-project}.{value-route-osl-hostname}/api/greeting
{"content":"Hello, World!"}
----
+
// Add note about the Toggle button not working
// no scaler implemented error if CLI used to scale down pod
+
. To simulate the failure of the `{value-name-app}-name` service you can:
+
* use the `Toggle` button in the web interface.
* scale the number of replicas of the pod running the `{value-name-app}-name` service down to 0.
* execute an HTTP `PUT` request against the `/api/state` endpoint of the `{value-name-app}-name` service to set its state to `fail`.
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl -X PUT -H "Content-Type: application/json" -d '{"state": "fail"}' http://{value-name-app}-name-{value-name-project}.{value-route-osl-hostname}/api/state
----
+
. Invoke the `/api/greeting` endpoint. When several requests on the `/api/name` endpoint fail:
.. the Circuit Breaker opens,
.. the state indicator in the web interface changes from `CLOSED` to `OPEN`,
.. the Circuit Breaker issues a fallback response when you invoke the `/api/greeting` endpoint:
+
[source,bash,option="nowrap",subs="attributes+"]
----
$ curl http://{value-name-app}-greeting-{value-name-project}.{value-route-osl-hostname}/api/greeting
{"content":"Hello, Fallback!"}
----
+
. Restore the name `{value-name-app}-name` service to availability.
To do this you can:
+
* use the `Toggle` button in the web interface.
* scale the number of replicas of the pod running the `{value-name-app}-name` service back up to 1.
* execute an HTTP `PUT` request against the `/api/state` endpoint of the `{value-name-app}-name` service to set its state back to `ok`.
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl -X PUT -H "Content-Type: application/json" -d '{"state": "ok"}' http://{value-name-app}-name-{value-name-project}.{value-route-osl-hostname}/api/state
----
+
. Invoke the `/api/greeting` endpoint again. When several requests on the `/api/name` endpoint succeed:
.. the Circuit Breaker closes,
.. the state indicator in the web interface changes from `OPEN` to `CLOSED`,
.. the Circuit Breaker issues a returns the `Hello World!` greeting when you invoke the `/api/greeting` endpoint:
+
[source,bash,options="nowrap",subs="attributes"]
----
$ curl http://{value-name-app}-greeting-{value-name-project}.{value-route-osl-hostname}/api/greeting
{"content":"Hello, World!"}
----
