[id='deploying-a-springboot-application-using-war-files_{context}']
= Deploying a {SpringBoot} application using WAR files
// Consider placing this in the Spring Boot runtime documentation instead?
// You can Package and deploy your application as a war file

ifdef::built-for-spring-boot-1-5[]
[IMPORTANT]
--
Red Hat does not support packaging and deploying {SpringBoot} applications using WAR files in {SpringBoot} 1.5.x.
--
endif::built-for-spring-boot-1-5[]

As an alternative to the supported application packaging and deployment workflow using fat JAR files, you can package and deploy a {SpringBoot} application as a WAR (Web Application Archive) file.
You must configure your build and deployment settings to ensure that your application builds and deploys correctly on OpenShift.

.Prerequisites

* A {SpringBoot} application, such as xref:spring-boot-available-missions-and-boosters[an example].
* Fabric8 Maven Plugin used to deploy your application to OpenShift.
* Spring Boot Maven Plugin used to package your application.

.Procedure

. Add `war` packaging to the `pom.xml` file of your project:
+
.Example `pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<project ...>
  ...
  <packaging>war</packaging>
  ...
</project>
----

. Specify `spring-boot-starter-tomcat` as a dependency of your application:
+
.Example `pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<project ...>
  ...
  <dependencies>
    ...
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>
    ...
  </dependencies>
  ...
</project>
----

. Ensure the `repackage` Maven goal for the Spring Boot Maven plugin is defined in the `pom.xml` file:
+
.Example `pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<project ...>
...
  <build>
    ...
    <plugins>
      ...
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
...
</project>
----
+
This ensures that the Spring Boot classes used to launch the application are included in the WAR file, and that the corresponding properties for these classes are defined in the `MANIFEST.mf` file of the WAR file:
+
** `Main-Class: org.springframework.boot.loader.WarLauncher`
** `Spring-Boot-Classes: WEB-INF/classes/`
** `Spring-Boot-Lib: WEB-INF/lib/`
** `Spring-Boot-Version: {version-spring-boot}`


. Add the `ARTIFACT_COPY_ARGS` environment variable to the `pom.xml` file.
+
The Fabric8 Maven Plugin consumes this variable during the build process and ensures that the _Build and Deploy_ tool uses the WAR file (rather than the default fat JAR file) to create the application container image:
+
.Example `pom.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
    ...
    <profile>
      <id>openshift</id>
      <build>
        <plugins>
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>fabric8-maven-plugin</artifactId>
            <executions>
              ...
            </executions>
            <configuration>
                <images>
                    <image>
                        <name>${project.artifactId}:%t</name>
                        <alias>${project.artifactId}</alias>
                        <build>
                            <from>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:${openjdk18-openshift.version}</from>
                            <assembly>
                                <basedir>/deployments</basedir>
                                <descriptorRef>artifact</descriptorRef>
                            </assembly>
                            <env>
                                <ARTIFACT_COPY_ARGS>*.war</ARTIFACT_COPY_ARGS>
                                <JAVA_APP_DIR>/deployments</JAVA_APP_DIR>
                            </env>
                            <ports>
                                <port>8080</port>
                            </ports>
                        </build>
                    </image>
                </images>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    ...
----
// add link to Build and Deploy section in GSG
// not sure if  correct build tool name
//capitalize DOCKER?
// do we term it s2i or build and deploy?
//and that the environment Variable will be used by OpenShift during the S2I Build Process with the WAR binary content pushed.
//Such information should be defined using the `Fabric8 Maven Plugin` by adding within the `<configuration>` xml tag, the definition of the Docker
//image to be created with the env var.


. Add the `JAVA_APP_JAR` environment variable to the `src/main/fabric8/deployment.yml` file.
+
This variable instructs the Fabric8 Maven Plugin to launch your application using the WAR file included with the container.
If `src/main/fabric8/deployment.yml` does not exist, you can create it.
// do we explicitly tell what the variable value should be?
//You can also make this modification by editing the  can be done by specifying an env var within the  under the specification of the container to be created.
//DeploymentConfig file
//JAVA_APP_JAR=mvc-jsp-0.0.1-SNAPSHOT.war
+
.Example `deployment.yml`
[source,yaml,options="nowrap",subs="attributes+"]
----
spec:
  template:
    spec:
      containers:
        ...
          env:
          - name: JAVA_APP_JAR
            value: ${project.artifactId}-${project.version}.war
----

. Build and deploy your application:
+
[source,bash]
--
mvn clean fabric8:deploy -Popenshift
--
