
[id='releasing-launcher-docs_{context}']
= Releasing {name-docs} docs

This section contains all information you need to release a new version of the documentation set to production. This update can happen anytime after the catalog has been updated, including after the release train has been completed.

.Procedure

.Releasing New Version to Production
. Synchronize the {WildFlySwarm} sources. For more information, see xref:syncing-with-wildflyswarm-docs_{context}[].

. Tag the release:
.. Execute the `tag_release.sh` script in the `$REPO_HOME/scripts` directory:
+
--
[source,bash]
----
$ ./tag_release.sh
----

The script automatically tags the commit with the current date in the `YYYY-MM-DD` format.
If you want to tag with a different date or manually, execute the following command:
[source,bash]
----
$ git tag 2017-04-21
----
If you are re-releasing the same day, a suffix `_2`, `_3`, etc. is appended.

--
.. Push the changes and tags:
+
--
[source,bash]
----
$ git push --tags $REMOTE
----

Replace `$REMOTE` with the name of the upstream remote.
--

. Request publication:
.. Fork link:https://github.com/openshiftio/saas-launchpad.git[openshiftio/saas-launchpad].
.. Clone your fork:
+
[source,bash]
----
git clone git@github.com/$GIT_USER/openshiftio/saas-launchpad.git
----
Replace `$GIT_USER` with your Git user name.

.. Add the repository as a remote on your fork:
+
[source,bash]
----
git remote add upstream git@github.com:$GIT_USER/openshiftio/saas-launchpad.git
----
.. Fetch upstream.
.. Create a topic branch:
+
[source,bash]
----
git checkout -v $BRANCH_NAME upstream/master
----
.. Edit the SHA hash in link:https://github.com/openshiftio/saas-launchpad/blob/master/launchpad-services/launcher-documentation.yaml[launcher-documentation.yaml] on the topic branch and push your change to origin.
+
The SHA hash is from the commit you want to publish from the link:{link-repo-docs}[{name-repo-docs}] repository.
 Usually, this is the latest commit in the `master` branch.
+
[source,bash]
----
$ git push origin/$BRANCH_NAME
----
.. File a pull request in the link:https://github.com/openshiftio/saas-launchpad[openshiftio/saas-launchpad] repository.
.. Wait for the pull request to be accepted. When that happens, verify that the link:{link-docs}[production build] succeeded.
.. Once your changes have been merged and the build succeeds, delete the topic branch you used to introduce the update.
+
[source,bash,options="nowrap",subs="attributes+"]
--
$ git branch -d $TOPIC_BRANCH_NAME
--

.Next steps

. Synchronize the sources to the Customer Portal stage.
. Announce the publication.
