[id='creating-and-deploying-a-booster-using-your-openshiftlocal_{context}']
[id='creating-and-deploying-an-example-using-your-openshiftlocal_{context}']
= Creating and deploying a booster using your {OpenShiftLocal}

You can quickly create, build, and deploy a booster to a {OpenShiftLocal} using the {name-launcher} tool. The {name-launcher} tool creates a new repository in your GitHub account containing the booster's code and deploys it to your {OpenShiftLocal}. It can also create a ZIP of the booster for you to download and run on your localhost.

.Prerequisites

* link:https://developers.redhat.com[Have a Red Hat Developers account]
* link:https://github.com[Have a GitHub account]
* link:{link-guide-minishift-installation}[Have a {OpenShiftLocal} installed]
* link:{link-guide-minishift-installation}#installing-launcher-tool_minishift[Have the {name-launcher} tool installed to your {OpenShiftLocal}].

.Procedure

. Navigate to the {name-launcher} tool on your {OpenShiftLocal} using your browser.
** Optionally, use the following command to open the Web Console of your {OpenShiftLocal} in your browser in order to navigate to your {name-launcher} tool:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift console
----

. Select _Launch Your Project_.
. Follow the instructions to create a booster based on a mission, runtime, and target environment.
. Open the `README.adoc` file in your booster project for more details about interacting with your booster.

.Additional resources

Take a look the different runtime guides to learn more about runtimes as well as their boosters:

* link:{link-guide-spring-boot}[{name-guide-spring-boot}]
* link:{link-guide-vertx}[{name-guide-vertx}]
* link:{link-guide-thorntail}[{name-guide-thorntail}]
* link:{link-guide-nodejs}[{name-guide-nodejs}]
