[id='rest-resources_{context}']
= REST resources

More background and related information on REST can be found here:

* link:https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm[Architectural Styles and
the Design of Network-based Software Architectures - Representational State Transfer (REST)]
* link:https://martinfowler.com/articles/richardsonMaturityModel.html[Richardson Maturity Model]

ifndef::built-for-nodejs[* link:https://www.jcp.org/en/jsr/detail?id=311[JSR 311: JAX-RS: The JavaTM API for RESTful Web Services]]
ifdef::built-for-nodejs[* link:https://expressjs.com/[Express Web Framework]]
ifdef::built-for-spring-boot[* link:https://spring.io/guides/gs/rest-service/[Building a RESTful Service with Spring]]
ifdef::built-for-vertx[* link:http://vertx.io/blog/some-rest-with-vert-x/[Some Rest with {VertX}]]
ifdef::built-for-thorntail[* link:http://resteasy.jboss.org/docs.html[RESTEasy Documentation]]
ifndef::built-for-spring-boot[* link:{link-mission-http-api-spring-boot}[{mission-http-api-spring-boot-guide-name}]]
ifndef::built-for-vertx[* link:{link-mission-http-api-vertx}[{mission-http-api-vertx-guide-name}]]
ifndef::built-for-thorntail[* link:{link-mission-http-api-wf-swarm}[{mission-http-api-wf-swarm-guide-name}]]
ifndef::built-for-nodejs[* link:{link-mission-http-api-nodejs}[{mission-http-api-nodejs-guide-name}]]

