[id='configmap-resources_{context}']
= {name-example-configmap} resources

More background and related information on {name-example-configmap} and ConfigMap can be found here:

* link:https://docs.openshift.org/latest/dev_guide/configmaps.html[OpenShift ConfigMap Documentation]

* link:https://blog.openshift.com/configuring-your-application-part-1/[Blog Post about ConfigMap in OpenShift]

ifdef::built-for-spring-boot[* link:http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Externalized Configuration with {SpringBoot}]]

ifdef::built-for-vertx[* link:http://vertx.io/docs/vertx-config/js/[Externalized Configuration with {VertX}]]

ifndef::built-for-spring-boot[* link:{link-example-configmap-spring-boot}[{name-example-configmap} for {SpringBoot}]]

ifndef::built-for-vertx[* link:{link-example-configmap-vertx}[{name-example-configmap} for {VertX}]]

ifndef::built-for-thorntail[* link:{link-example-configmap-thorntail}[{name-example-configmap} for {WildFlySwarm}]]

ifndef::built-for-nodejs[* link:{link-example-configmap-nodejs}[{name-example-configmap} for {Node}]]
