[id='rhsso-deployment-configuration_{context}']

= {RHSSO} deployment configuration

The `service.sso.yaml` file in this booster contains all OpenShift configuration items to deploy a pre-configured {RHSSO} server.
The SSO server configuration has been simplified for the sake of this exercise and does provide an out-of-the-box configuration, with pre-configured users and security settings.
The `service.sso.yaml` file also contains very long lines, and some text editors, such as link:https://wiki.gnome.org/Apps/Gedit[gedit], may have issues reading this file.

WARNING: It is not recommended to use this SSO configuration in production.
Specifically, the simplifications made to the booster security configuration impact the ability to use it in a production environment.

.SSO Booster Simplifications
[width="100%",options="header"]
|====================================================================
|Change |Reason |Recommendation

a|
The default configuration includes both public and **private keys in the yaml configuration files**.

a|
We did this because the end user can deploy Red Hat SSO module and have it in a usable state without needing to know the internals or how to configure Red Hat SSO.

a|
In production, do not store private keys under source control.
They should be added by the server administrator.


a|
The configured **clients accept any callback url**.

a|
To avoid having a custom configuration per runtime we avoid the verification of the callback as required by the OAuth2 specification.

a|
An application-specific callback URL should be provided with a valid domain name.

a|
**Clients do not require SSL/TLS and the secured applications are not exposed over HTTPS**.

a|
The boosters are simplified by not requiring certificates generated for each runtime.

a|
In production a secure application should use HTTPS rather than plain HTTP.

a|
**The token timeout has been increased to 10 minutes from the default of 1 minute.**

a|
Provides a better user experience when working with the command line examples

a|
From a security perspective, the window an attacker would have to guess the access token is extended.
It is recommended to keep this window short as it makes it much harder for a potential attacker to guess the current token.

|====================================================================

