[id='messaging-work-queue-resources_{context}']
= Messaging Work Queue Resources

More background and related information on messaging can be found here:

* link:http://www.enterpriseintegrationpatterns.com/patterns/messaging/Introduction.html[Enterprise Integration Patterns: An overview of messaging service concepts^]

* link:http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-messaging-v1.0.html[AMQP 1.0 Messaging Protocol specifications^]

* link:https://access.redhat.com/documentation/en-us/red_hat_jboss_a-mq/6.3/html-single/red_hat_jboss_a-mq_for_openshift/index[Documentation on Red{nbsp}Hat JBoss AMQ 6.3 for OpenShift^]

* link:https://qpid.apache.org/components/index.html#messaging-servers[Messaging server types and implementations for message-oriented middleware^]

// check if links really work
ifndef::spring-boot[* link:{link-mission-messaging-work-queue-spring-boot}[{name-mission-messaging-work-queue} Mission - {SpringBoot} Booster]]

ifndef::vert-x[* link:{link-mission-messaging-work-queue-vertx}[{name-mission-messaging-work-queue} Mission - {VertX} Booster]]

ifndef::wf-swarm[* link:{link-mission-messaging-work-queue-wf-swarm}[{name-mission-messaging-work-queue} Mission - {WildFlySwarm} Booster]]

ifndef::node-js[* link:{link-mission-messaging-work-queue-nodejs}[{name-mission-messaging-work-queue} Mission - {Node} Booster]]
