[id='configmap-resources_{context}']
= {name-mission-configmap} resources

More background and related information on {name-mission-configmap} and ConfigMap can be found here:

* link:https://docs.openshift.org/latest/dev_guide/configmaps.html[OpenShift ConfigMap Documentation]

* link:https://blog.openshift.com/configuring-your-application-part-1/[Blog Post about ConfigMap in OpenShift]

ifdef::built-for-spring-boot[* link:http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Externalized Configuration with {SpringBoot}]]

ifdef::built-for-vertx[* link:http://vertx.io/docs/vertx-config/js/[Externalized Configuration with {VertX}]]

ifdef::built-for-thorntail[* link:https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/v/eee1f5ba4dd4f13855cbe98addd365ba29033810/configuration/index.html[Externalized Configuration with {WildFlySwarm}]]

ifndef::built-for-spring-boot[* link:{link-mission-configmap-spring-boot}[{name-mission-configmap} mission - {SpringBoot} booster]]

ifndef::built-for-vertx[* link:{link-mission-configmap-vertx}[{name-mission-configmap} mission - {VertX} booster]]

ifndef::built-for-thorntail[* link:{link-mission-configmap-thorntail}[{name-mission-configmap} mission - {WildFlySwarm} booster]]

ifndef::built-for-nodejs[* link:{link-mission-configmap-nodejs}[{name-mission-configmap} mission - {Node} booster]]

