
[id='glossary']
= Glossary

== Product and project names

{launcher-oso}:: link:{link-launcher-oso}[{launcher-oso}] is a standalone getting started experience offered by Red Hat for jumpstarting cloud-native application development on OpenShift. It provides a hassle-free way of creating functional example applications, called missions, as well as an easy way to build and deploy those missions to OpenShift. 

{launcher}:: The {launcher} is the upstream project on which link:{link-launcher-oso}[{launcher-oso}] is based.

{OpenShiftLocal}:: An OpenShift cluster running on your machine using Minishift.


== Terms specific to {launcher}

[[glossary_booster]]
Booster:: A language-specific implementation of a particular xref:glossary_mission[mission] on a particular xref:glossary_runtime[runtime]. Boosters are listed in a xref:glossary_booster_catalog[booster catalog].
+
For example, a booster is a web service with a REST API implemented using the {WildFlySwarm} runtime.

[[glossary_booster_catalog]]
Booster Catalog:: A Git repository that contains information about boosters.

[[glossary_mission]]
Mission:: An application specification, for example _a web service with a REST API._
+
Missions generally do not specify which language or platform they should run on; the description only contains the intended functionality.

[[glossary_runtime]]
Runtime:: A platform that executes xref:glossary_booster[boosters].
For example, {WildFlySwarm} or {VertX}.

