[id='breakdown-of-wildflyswarm-pom-components_{context}']
= Breakdown of {WildFlySwarm} POM Components

.link:https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http/blob/master/pom.xml[wfswarm-rest-http/pom.xml]
[source,xml,options="nowrap",subs="attributes+"]
----
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~
  ~  Copyright 2016-2017 Red Hat, Inc, and individual contributors.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent> <1>
    <groupId>io.openshift</groupId>
    <artifactId>booster-parent</artifactId>
    <version>4</version>
  </parent>

  <groupId>io.openshift.booster</groupId>
  <artifactId>wfswarm-rest-http</artifactId>
  <version>7-SNAPSHOT</version>
  <packaging>war</packaging>

  <name>Simple HTTP Example</name>
  <description>WildFly Swarm - Rest</description>

  <properties> <2>
    <version.wildfly.swarm>2017.6.0</version.wildfly.swarm>
    <version.resteasy>3.0.19.Final</version.resteasy>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.wildfly.swarm</groupId>
        <artifactId>bom</artifactId> <3>
        <version>${version.wildfly.swarm}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jaxrs</artifactId> <4>
    </dependency>

    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-client</artifactId> <5>
      <version>${version.resteasy}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>arquillian</artifactId> <6>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId> <7>
      <version>1.1.12.Final</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.wildfly.swarm</groupId>
        <artifactId>wildfly-swarm-plugin</artifactId> <8>
        <version>${version.wildfly.swarm}</version>
        <executions>
          <execution>
            <goals>
              <goal>package</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-war-plugin</artifactId> <9>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>openshift</id> <10>
      <build>
        <plugins>
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>fabric8-maven-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>resource</goal>
                  <goal>build</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <generator>
                <includes>
                  <include>wildfly-swarm</include>
                </includes>
                <excludes>
                  <exclude>webapp</exclude>
                </excludes>
              </generator>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>openshift-it</id> <11>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
----

<1> link:https://github.com/openshiftio/booster-parent/blob/master/pom.xml[Parent POM] which contains the necessary dependencies and the required versions for the booster projects.
<2> Properties for setting the {WildFlySwarm} and RESTEasy version.
<3> link:https://github.com/wildfly-swarm/wildfly-swarm/blob/master/boms/bom/pom.xml[BOM] for building {WildFlySwarm} applications with Maven.
<4> link:https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/v/2017.6.0/getting-started/concepts.html[Swarm Fraction] that brings link:https://jcp.org/en/jsr/detail?id=339[JAX-RS] functionality for creating REST services.
<5> link:https://docs.jboss.org/resteasy/docs/3.1.3.Final/userguide/html_single/#RESTEasy_Client_Framework[RESTEasy client] dependency for connecting to other REST services which is used in testing.
<6> link:https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/v/2017.6.0/getting-started/concepts.html[Swarm Fraction] that brings link:http://arquillian.org[Arquillian] functionality for testing.
<7> link:http://arquillian.org/guides/getting_started/#add_the_arquillian_apis[Arquillian APIs] for testing with link:http://junit.org[JUnit].
<8> link:https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/v/2017.6.0/getting-started/tooling/maven-plugin.html[{WildFlySwarm} Maven Plugin] used to create the application link:https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/v/2017.6.0/getting-started/concepts.html[uberjar].
<9> The link:https://maven.apache.org/plugins/maven-war-plugin/[Maven WAR Plugin] collects all artifact dependencies, classes and resources of your web application, and packages them into a WAR file.
<10> The profile for building and deploying the booster to OpenShift. It uses the link:http://fabric8.io/gitbook/mavenPlugin.html[Fabric8 Maven Plugin (FMP)] to build and deploy the application with the S2I Build Process.
<11> The profile for running integration tests when the application is deployed on OpenShift. For example, a test can require a database pod or a ConfigMap value.
