= Modify the Spring Boot Quickstart to Add Additional HTTP Endpoints

. Add a `WorldGreeting` class to `src/main/java/org/obsidiantoaster/quickstart/service`.
+
[source,java,options="nowrap"]
----
package org.obsidiantoaster.quickstart.service;

import java.util.concurrent.atomic.AtomicLong;

public class WorldGreeting {

	private static final AtomicLong counter = new AtomicLong();
	private String language;
	private String prefix;
	
	public WorldGreeting() {
    
		this.language = null;
		this.prefix = null;
	}
	
	public WorldGreeting(String language, String prefix) {
		super();
		this.language = language;
		this.prefix = prefix;
	}
	
	public Greeting getGreeting(String name) {
    
  	String suffix = "";
  	
  	if(name != null && !name.isEmpty())
  	{
  		suffix = ", "+name;
  	}
  	
  	return new Greeting(counter.incrementAndGet(), prefix + suffix + "!");
	}
	
	public String getLanguage() {
		return language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public String getPrefix() {
		return prefix;
	}
	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}
}
----

. Add a list of `WorldGreeting` objects to `GreetingController` and a default constructor.
+
[source,options="nowrap"]
----
private static List<WorldGreeting> greetings; 

public GreetingController() {
  
  greetings = new ArrayList<WorldGreeting>();
  greetings.add(new WorldGreeting("default","Hello"));	
}
----

. Add some additional HTTP endpoints to `GreetingController`.
+
[source,options="nowrap"]
----
@RequestMapping(path="/saveWorldGreeting",method=RequestMethod.POST)
public WorldGreeting saveWorldGreeting(@RequestBody WorldGreeting worldGreeting) {
  
  greetings.add(worldGreeting);
  
  return worldGreeting;
}


@RequestMapping("/internationalGreeting")
public Greeting internationalGreeting(@RequestParam(name="language", defaultValue="default")String language, 
                                  @RequestParam(value="name", defaultValue="")String name) {
                                    
  List<WorldGreeting> languageGreetings = 
      greetings.stream().filter(g -> g.getLanguage().equals(language)).collect(Collectors.toList());
  
  return languageGreetings.get(0).getGreeting(name);
}


@RequestMapping("/{language}/greeting")
public Greeting anotherInternationalGreeting(@PathVariable(value="language")String language, 
                                         @RequestParam(value="name", defaultValue="")String name) {
                                           
  return internationalGreeting(language, name);
}


@RequestMapping("/supportedLanguages")
public List<String> supportedLanguages() {
  
  List<String> languages = new ArrayList<String>();
  
  for(WorldGreeting wg:greetings)
  {
    languages.add(wg.getLanguage());
  }
  
  return languages;
}
----

. Build and deploy your updates to the quickstart. You can find more details on this in xref:build_and_deploy_quickstart[].

. Check the current available languages.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.xip.io/supportedLanguages
["default"]
----

. Get the default greeting.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.xip.io/default/greeting
{"id":1,"content":"Hello!"}
----

. Get the default greeting with a name.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.xip.io/default/greeting?name=Sarah
{"id":2,"content":"Hello, Sarah!"}
----

. Post an additional greeting in Spanish.
+
[source,options="nowrap"]
----
$ curl -H "Content-Type: application/json" -X POST -d "{\"language\":\"Spanish\",\"prefix\":\"Hola\"}" http://app1.192.168.99.100.xip.io/saveWorldGreeting
----

. Check the current available languages.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.xip.io/supportedLanguages
["default","Spanish"]
----

. Get the Spanish greeting.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.xip.io/Spanish/greeting
{"id":3,"content":"Hola, Sarah!"}
----

. Add a unit test for the HTTP endpoints in `src/test/java/org/obsidiantoaster/quickstart/RestApplicationTest.java`.
+
[source,java,options="nowrap"]
----
@Test
public void test_modified_service_invocation() {
    	     	 
  String appURL = "http://app1.192.168.99.100.xip.io";

  String response  = template.getForObject(appURL+"/supportedLanguages",String.class);
  Assert.assertTrue(response.equals("[\"default\"]"));

  long now = System.currentTimeMillis();
  String tempLang = "temp"+now;
  String tempGreeting = "hello-"+now;
  WorldGreeting wgRequest = new WorldGreeting(tempLang,tempGreeting);
  WorldGreeting wgResponse = template.postForEntity(appURL+"/saveWorldGreeting", wgRequest, WorldGreeting.class).getBody();
  Assert.assertTrue(wgRequest.equals(wgResponse));
            
  response  = template.getForObject(appURL+"/supportedLanguages",String.class);
  Assert.assertTrue(response.contains(tempLang));
}
----
