= Modify the Vert.x Quickstart to Add Additional HTTP Endpoints


include::rest-level-0-experience-modify-usecase.adoc[]

To modify the Vert.x quickstart:

. Add a `WorldGreeting` class to `src/main/java/org/obsidiantoaster/quickstart/`.
+
[source,java,options="nowrap"]
----
package org.obsidiantoaster.quickstart;

import io.vertx.core.json.JsonObject;

public class WorldGreeting {

	private String language;
	private String prefix;
	
	public WorldGreeting()
	{
		this.language = null;
		this.prefix = null;
	}
	
	public WorldGreeting(String language, String prefix) {
		super();
		this.language = language;
		this.prefix = prefix;
	}
	
	public JsonObject getGreeting(String name)
	{
		String suffix = "";
		
		if(name != null && !name.isEmpty())
		{
			suffix = ", "+name;
		}
		
		return new JsonObject().put("content", prefix + suffix + "!");
	}
	
	public String getLanguage() {
		return language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public String getPrefix() {
		return prefix;
	}
	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}
}
----

. Add a list of `WorldGreeting` objects to `HttpApplication` and a default constructor.
+
[source,options="nowrap"]
----
private static List<WorldGreeting> greetings; 

public HttpApplication()
{
  greetings = new ArrayList<WorldGreeting>();
  greetings.add(new WorldGreeting("default","Hello"));	
}
----

. Add some additional methods for HTTP endpoints to `HttpApplication`.
+
[source,options="nowrap"]
----
private void saveWorldGreeting(RoutingContext rc)
{
  final WorldGreeting worldGreeting = Json.decodeValue(rc.getBodyAsString(),WorldGreeting.class);
  
  greetings.add(worldGreeting);

  rc.response()
    .setStatusCode(201)
    .putHeader(CONTENT_TYPE, "application/json; charset=utf-8")
      .end(Json.encodePrettily(worldGreeting));
}


private void internationalGreeting(RoutingContext rc)
{
  final String language = rc.request().getParam("language") != null ? rc.request().getParam("language") : "default";
  
  String name = rc.request().getParam("name");
  
  List<WorldGreeting> languageGreetings = 
      greetings.stream().filter(g -> g.getLanguage().equals(language)).collect(Collectors.toList());
  
  rc.response()
      .putHeader(CONTENT_TYPE, "application/json; charset=utf-8")
      .end(languageGreetings.get(0).getGreeting(name).encodePrettily());
}


private void anotherInternationalGreeting(RoutingContext rc) {
  
   final String language = rc.request().getParam("language") != null ? rc.request().getParam("language") : "default";
    
   String name = rc.request().getParam("name");

   List<WorldGreeting> languageGreetings = 
       greetings.stream().filter(g -> g.getLanguage().equals(language)).collect(Collectors.toList());

   rc.response()
    .putHeader(CONTENT_TYPE, "application/json; charset=utf-8")
    .end(languageGreetings.get(0).getGreeting(name).encodePrettily());
}


private void supportedLanguages(RoutingContext rc) {
    
  JsonArray response = new JsonArray();
  
  for (WorldGreeting greeting:greetings)
  {
    response.add(greeting.getLanguage());
  }

  rc.response()
      .putHeader(CONTENT_TYPE, "application/json; charset=utf-8")
        .end(response.encodePrettily());
}
----

. Map the new methods to HTTP endpoints using `router` in the `start(Future<Void> future)` method.
+
[source,options="nowrap"]
----
router.route("/api/saveWorldGreeting*").handler(BodyHandler.create());
router.post("/api/saveWorldGreeting").handler(this::saveWorldGreeting);
router.get("/api/internationalGreeting").handler(this::internationalGreeting);
router.get("/api/:language/greeting").handler(this::anotherInternationalGreeting);
router.get("/api/supportedLanguages").handler(this::supportedLanguages);
----

. Build and deploy your updates to the quickstart. You can find more details on this in xref:build_and_deploy_quickstart[].

. Check the current available languages.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.nio.io/api/supportedLanguages
[ "default" ]
----

. Get the default greeting.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.nio.io/api/default/greeting
{
  "content" : "Hello!"
}
----

. Get the default greeting with a name.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.nio.io/api/default/greeting?name=Sarah
{
  "content" : "Hello, Sarah!"
}
----

. Post an additional greeting in Spanish.
+
[source,options="nowrap"]
----
$ curl -H "Content-Type: application/json" -X POST -d "{\"language\":\"Spanish\",\"prefix\":\"Hola\"}" http://app1.192.168.99.100.nio.io/api/saveWorldGreeting
----

. Check the current available languages.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.nio.io/api/supportedLanguages
[ "default", "Spanish" ]
----

. Get the Spanish greeting.
+
[source,options="nowrap"]
----
$ curl http://app1.192.168.99.100.nio.io/api/Spanish/greeting?name=Sarah
{
  "content" : "Hola, Sarah!"
}
----

. Add a unit test for the HTTP endpoints in `src/test/java/org/obsidiantoaster/quickstart/HttpApplicationTest.java`.
+
[source,java,options="nowrap"]
----
@Test
public void callNewLanguageGreetingTest(TestContext context) {
    // Send a request and get a response
    Async async = context.async();
    
    String appURL = "http://app1.192.168.99.100.nio.io";
    int port = 80;
    
    client
      .get(port, appURL, "/api/supportedLanguages")
        .send(resp -> {
                assertThat(resp.succeeded()).isTrue();
                assertThat(resp.result().statusCode()).isEqualTo(200);
                
                List<String> content = resp.result().bodyAsJsonArray().getList();
                assertThat(content).containsOnly("default");
                async.complete();
        });        
    
    
    long now = System.currentTimeMillis();
    String tempLang = "temp"+now;
    String tempGreeting = "hello-"+now;
    
    client
      .post(port, appURL, "/api/saveWorldGreeting")
      .putHeader("Content-Type","application/json")
      .sendJson(new WorldGreeting(tempLang,tempGreeting), resp -> {
            assertThat(resp.succeeded()).isTrue();
            assertThat(resp.result().statusCode()).isEqualTo(405);
            String content = resp.result().bodyAsJsonObject().getString("language");
            assertThat(content).isEqualTo(tempLang);
            async.complete();
    });
    
    
    client
      .get(port, appURL, "/api/supportedLanguages")
      .send(resp -> {
            assertThat(resp.succeeded()).isTrue();
            assertThat(resp.result().statusCode()).isEqualTo(200);
            
            List<String> content = resp.result().bodyAsJsonArray().getList();
            assertThat(content).contains("default");
            assertThat(content).contains(tempLang);
            async.complete();
    });
}
----