
:runtime: ${runtime}

ifeval::["{runtime}" == "Spring Boot"]
:localRunCMD: mvn spring-boot:run
:OSORunCMD: mvn clean fabric8:deploy -Popenshift -DskipTests
:guideURL: http://appdev.openshift.io/docs/spring-boot-runtime.html
:fileLocation: src/main/resources/static/index.html
endif::[]

ifeval::["{runtime}" == "Eclipse Vert.x"]
:localRunCMD: mvn vertx:run
:OSORunCMD: mvn clean fabric8:deploy -Popenshift -DskipTests
:guideURL: http://appdev.openshift.io/docs/vertx-runtime.html
:fileLocation: src/main/resources/webroot/index.html
endif::[]

ifeval::["{runtime}" == "WildFly Swarm"]
:localRunCMD: mvn wildfly-swarm:run
:OSORunCMD: mvn clean fabric8:deploy -Popenshift -DskipTests
:guideURL: http://appdev.openshift.io/docs/wf-swarm-runtime.html
:fileLocation: src/main/webapp/index.html
endif::[]

ifeval::["{runtime}" == "Node.js"]
:localRunCMD: npm start
:OSORunCMD: npm run openshift
:guideURL: http://appdev.openshift.io/docs/nodejs-runtime.html
:fileLocation: public/index.html
endif::[]



= ${mission} - ${runtime} Booster

== Run this Booster Locally

To run this booster on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:${loggedUser}/${targetRepository}

$ cd ${targetRepository}

$ {localRunCMD}
----

== Interact with this Booster Locally

To interact with your booster while it's running locally, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----


== Update this Booster
To update your booster:

. Stop your booster.
. Make your change (e.g. edit link:https://github.com/${loggedUser}/${targetRepository}/edit/master/{fileLocation}[`{fileLocation}`]).
. Restart your booster.
. Confirm your change appears.


== Run this Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or {CDK}, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

$ {OSORunCMD}
----

== CI/CD Deployment
As part of the process of creating this booster, launch.openshift.io set up a project with a CI/CD deployment of this booster. You can see the status of this deployment in the link:https://manage.openshift.com[OpenShift Online Web console]. You can also learn more about this booster and rest of the ${runtime} runtime in the link:{guideURL}[${runtime} Runtime Guide].

