[[rest_build_and_deploy_booster]]
= Build and Deploy Your Booster

include::booster-deploy-openshift-online.adoc[leveloffset=+1]

// this is intentionally a level 3
=== Deploy Using the `oc` CLI Client

include::oc-client-deploy-booster-download-note.adoc[leveloffset=+3]

. Get your authentication token for using the `oc` CLI client with your {OpenShiftOnline} account. You can find this in the _Command Line Tools_ section your {OpenShiftOnline} Web console.

. Authenticate your `oc` CLI client with your {OpenShiftOnline} account by using your authentication token.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login {link-oso-auth} --token=MYTOKEN
----

. Create a new project in {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

ifndef::http-api-nodejs[]
. Use maven to start the deployment to {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on {OpenShiftOnline} and to start the pod.
endif::http-api-nodejs[]

ifdef::http-api-nodejs[]
. Use npm to start the deployment to {OpenShiftOnline}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm run openshift
----
+
This command uses the Nodeshift npm module to launch the S2I process on {OpenShiftOnline} and to start the pod.
endif::http-api-nodejs[]

. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa               1/1       Running     0          58s
{app-name}-s2i-1-build           0/1       Completed   0          2m
----
+
You `app1` pod should have a status of `Running` once its fully deployed and started.

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{app-name}         {app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com      {app-name}      8080
----
+
A pod's route information gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-{project-name}.1ab5.starter-us-east-1.openshiftapps.com` as the base URL to access the application.


include::booster-deploy-openshift-local.adoc[leveloffset=+1]
