[[rest_build_and_deploy_booster]]
= Building and Deploying the Booster

include::booster-deploy-openshift-online.adoc[leveloffset=+1]

include::booster-deploy-openshift-local.adoc[leveloffset=+1]

// this is intentionally a level 3
=== Deploying Using the `oc` CLI Client

include::oc-client-deploy-booster-download-note.adoc[leveloffset=+3]

include::booster-deploy-get-cli-token.adoc[levelloffset=+3]

. Create a new project in {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project {project-name}
----

. Navigate to the root directory of your booster.

ifndef::http-api-nodejs[]
. Use maven to start the deployment to {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----
+
This command uses the Fabric8 Maven Plugin to launch the S2I process on {OpenShiftLocal} and to start the pod.
endif::http-api-nodejs[]

ifdef::http-api-nodejs[]
. Use `npm` to start the deployment to {OpenShiftLocal}.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ npm install && npm run openshift
----
+
These commands install any missing package dependencies, then using the xref:about-nodeshift[Nodeshift] package, launch the S2I process on {OpenShiftLocal} to start the pod.
endif::http-api-nodejs[]

. Check the status of your booster and ensure your pod is running.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
{app-name}-1-aaaaa               1/1       Running     0          58s
{app-name}-s2i-1-build           0/1       Completed   0          2m
----
+
You `{app-name}-1-aaaaa` pod should have a status of `Running` once its fully deployed and started.

. Once your booster is deployed and started, determine its route.
+
.Example Route Information
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get routes
NAME                 HOST/PORT                                                     PATH      SERVICES        PORT      TERMINATION
{app-name}         {app-name}-{project-name}.{osl-route-hostname}      {app-name}      8080
----
+
The route information of a pod gives you the base URL which you use to access it. In the example above, you would use `http://{app-name}-{project-name}.{osl-route-hostname}` as the base URL to access the application.

include::booster-deploy-ocp.adoc[leveloffset=+1]