= Configuring Your {OpenShiftLocal}
Before you can run the Secured Booster, you must update your {OpenShiftLocal} from the default configuration. You only need to do this once for the secured booster missions.
They all share the same {RHSSO}/{OpenShiftLocal} setup.
You can use your {OpenShiftLocal} to run your secured booster, but you need to update it from the default configuration.

Before you can use your {OpenShiftLocal}, you need to have it installed, configured, and running. You can find details on installing a {OpenShiftLocal} for your platform in link:{link-launcher-openshift-local-install-guide}#installing-a-openshiftlocal[{minishift-installation-guide-name}].

.Updating your {OpenShiftLocal} from the default Configuration

{RHSSO} will not start up unless you switch from the default configuration. The SSO Booster currently only works with the CentOS base image. If you have already run the `minishift` command with a different memory setting and iso-url value,
you need to stop it and completely delete the `~/.minishift` directory before running the startup sequence.

. Delete the current {OpenShiftLocal} configuration and restart it with a new ISO.

[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift delete
$ rm -r ~/.minishift
$ minishift start --memory=6144 --iso-url=centos
----
