= SSO Adapter Configuration

The SSO adapter is the _client side_, or client to the SSO server, component that enforces security on the web resources. In this specific case, it is the Greeting service.

Both the SSO adapter and endpoint security are configured in `application.properties`. 

.Example application.properties file

[source,bash,options="nowrap",subs="attributes+"]
----
$ # Adapter configuration
keycloak.realm=master <1>
keycloak.realm-key=... <2>
keycloak.auth-server-url=${sso.auth.server.url} <3>
keycloak.resource=secured-booster-endpoint <4>
keycloak.credentials.secret=1daa57a2-b60e-468b-a3ac-25bd2dc2eadc <5>
keycloak.use-resource-role-mappings=true <6>
keycloak.bearer-only=true <7>
# Endpoint security configuration
keycloak.securityConstraints[0].securityCollections[0].name=admin stuff <8>
keycloak.securityConstraints[0].securityCollections[0].authRoles[0]=booster-admin <9>
keycloak.securityConstraints[0].securityCollections[0].patterns[0]=/api/greeting <10>
----

<1> The security realm to be used.
<2> PEM format of the realm public key. You can obtain this from the administration console.
<3> The address of the {RHSSO} server (Interpolation at build time).
<4> The actual keycloak _client_ configuration.
<5> Secret to access authentication server.
<6> Check the token for application level role mappings for the user.
<7> If enabled the adapter will not attempt to authenticate users, but only verify bearer tokens.
<8> A simple name for the security constraint.
<9> A roles needed to access a secured endpoint.
<10> A secured endpoints path pattern.