= SSO Adapter Configuration

The SSO adapter is the _client side_, or client to the SSO server, component that enforces security on the web resources. In this specific case, it is the greeting service.

.Enacting security
[source,java,options="nowrap",subs="attributes+"]
----
router.route("/greeting")         <1>
  .handler(JWTAuthHandler.create( <2>
    JWTAuth.create(vertx,         <3>
      config)));                  <4>

----

<1> Locate the HTTP route to secure.
<2> Instantiate a new JWT security handler.
<3> The authorization enforcer is created.
<4> The configuration to the enforcer.

The enforcer is configured using JSON with the exact same format keycloak exports from the configuration console. In this case the JSON file is reconstructed from the deployment environment variables as:

[source,bash,options="nowrap",subs="attributes+"]
----
JsonObject config = new JsonObject()
  	.put("realm", System.getenv("REALM")) <1>
  	.put("public-key", System.getenv("REALM_PUBLIC_KEY")) <3>
  	.put("auth-server-url", System.getenv("SSO_AUTH_SERVER_URL")) <4>
  	.put("ssl-required", "external")
  	.put("resource", System.getenv("CLIENT_ID")) <2>
  	.put("credentials", new JsonObject()
    	.put("secret", System.getenv("SECRET")))
  	// since we're consuming keycloak JWTs we need to locate the permission claims in the token
  	.put("permissionsClaimKey", "realm_access/roles"); <5>
----

<1> The security realm to be used.
<2> The actual keycloak _client_ configuration.
<3> PEM format of the realm public key. You can obtain this from the administration console. 
<4> The address of the {RHSSO} server (Interpolation at build time)
<5> Where the authorization enforcer should lookup permissions.