= Project Structure

The SSO booster project contains:

* the sources for the Greeting service, which is the one which we are going to to secure
* a template file (`service.sso.yaml`) to stand up the SSO server 
* the Keycloak adapter configuration to secure the service

= Standing up {RHSSO}
The `service.sso.yaml` file contains all OpenShift configuration items to stand up a pre-configured {RHSSO} server. The SSO server configuration has been simplified for the sake of this exercise and does provide an out-of-the-box configuration, with pre-configured users and security settings.

IMPORTANT: It is not recommended to use this SSO configuration in production. Specifically, the simplifications made to the booster security configuration impact the ability to use it in a production environment.

.SSO Booster Simplifications
[width="100%",options="header"]
|====================================================================
|Change |Reason |Recommendation

a|
The default configuration includes both public and **private keys in the yaml configuration files**.

a|
We did this because the end user can deploy Red Hat SSO module and have it in a usable state without needing to know the internals or how to configure Red Hat SSO.

a|
In production, it is recommend to not store any private key under source control and have it added by the server administrator.


a|
The configured **clients accept any callback url**.

a|
To avoid having a custom configuration per runtime we avoid the verification of the callback as mandated by the OAuth2 specification.

a|
An application-specific callback URL should be provided with a valid domain name.

a|
**Clients do not require SSL/TLS and the secured applications are not exposed over HTTPS**.

a|
The boosters are simplified by not requiring certificates generated for each runtime.

a|
In production a secure application should use HTTPS rather than plain HTTP.

a|
**The token timeout has been increased to 10 minutes from the default of 1 minute.**

a|
Provides a better user experience when working with the command line examples

a|
From a security perspective, the window an attacker would have to guess the access token is extended. It is recommended to keep this window short as it makes it much harder for a potential attacker to guess the current token.

|====================================================================


= {RHSSO} Realm Model

The `master` realm is used to secure this booster. There are two pre-configured application client definitions that provide a model for command line clients and the secured REST endpoint. 

There are also two pre-configured users in the {RHSSO} `master` realm that can be used to validate various authentication and authorization outcomes:  `admin` and `alice`.

[[sso-users]]
== {RHSSO} Users
The realm model for the secured boosters includes two users:

admin::
The `admin` user has a password of `admin` and is the realm administrator. This user has full access to the {RHSSO} administration console, but none of the role mappings that are required to access the secured endpoints. You can use this user to illustrate the behavior of an authenticated, but unauthorized user.

alice:: 
The `alice` user has a password of `password` and is the canonical application. This user will demonstrate successful authenticated and authorized access to the secured endpoints. An example representation of the role mappings is provided in this decoded JWT bearer token:
+
[source,json,options="nowrap"]
----
{
  "jti": "5a785440-8cb4-4500-a9fc-0c3aec1e62d5",
  "exp": 1489698336,
  "nbf": 0,
  "iat": 1489698276,
  "iss": "https://secure-sso-sso.{osl-route-hostname}/auth/realms/master", <1>
  "aud": "demoapp",
  "sub": "c0175ccb-0892-4b31-829f-dda873815fe8",
  "typ": "Bearer",
  "azp": "demoapp",
  "session_state": "7d296305-0c71-4dda-80d9-5b5ea4a584c1",
  "client_session": "31cd83c8-6315-4daf-9aa7-e50e80611c2d",
  "allowed-origins": [],
  "realm_access": {
    "roles": [ <2>
      "vertx-admin"
    ]
  },
  "resource_access": { <3>
    "secured-swarm-endpoint": {
      "roles": [
        "swarm-admin" <4>
      ]
    },
    "secured-vertx-endpoint": {
      "roles": [
        "vertx-admin" <5>
      ]
    },
    "secured-springboot-endpoint": {
      "roles": [
        "springboot-admin" <6>
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "view-profile"
      ]
    }
  },
  "name": "Alice InChains",
  "preferred_username": "alice", <7>
  "given_name": "Alice",
  "family_name": "InChains",
  "email": "alice@keycloak.org"
}
----
+
<1> The `iss` field corresponds to the {RHSSO} realm instance URL that issues the token. This must be configured in the secured endpoint deployments in order for the token to be verified.
<2> The `roles` object provides the roles that have been granted to the user at the global realm level. In this case
`alice` has been granted the `vertx-admin` role. We will see that the {VertX} secured endpoint will look to the
realm level for authorized roles.
<3> The `resource_access` object contains resource specific role grants. Under this object you will find an object
for each of the secured endpoints.
<4> The `resource_access.secured-swarm-endpoint.roles` object contains the roles granted to `alice` for the `secured-swarm-endpoint` resource.
<5> The `resource_access.secured-vertx-endpoint.roles` object contains the roles granted to `alice` for the `secured-vertx-endpoint` resource.
<6> The `resource_access.secured-springboot-endpoint.roles` object contains the roles granted to `alice` for the `secured-springboot-endpoint` resource.
<7> The `preferred_username` field provides the username that was used to generate the access token.

== The Application Clients
The OAuth 2.0 specification allows you to define a role for application clients that access secured resources on behalf of resource owners. The `master` realm has four application clients defined:

demoapp::
This is a `confidential` type client with a client secret that is used to obtain an access token that contains grants for the `alice` user which enable `alice` to access the {WildFlySwarm}, {VertX} and {SpringBoot} based REST booster deployments.

secured-booster-endpoint::
The `secured-booster-endpoint` is a bearer-only type of client that requires a `booster-admin` role for accessing the associated resources, specifically the Greeting service.