= {Vertx} Runtime Information

.Certified {Vertx} Version

{Vertx} version `3.4.2-redhat-006` is certified to run on OpenShift and provided as part of the Red Hat subscription.
The certified {Vertx} runtime artifacts are available from the link:https://maven.repository.redhat.com/ga/[Red Hat Middleware JBoss General Availability Maven Repository].
// link to release notes for full list of components

.Installing {Vertx}

To start developing applications using {Vertx}, download the BOM file containing the certified runtime artifacts available from the link:https://maven.repository.redhat.com/ga/[Red Hat Middleware JBoss General Availability Maven Repository].

.Configuring {Vertx}

To configure your application to use {Vertx}:

. Reference the required artifacts in the dependency file of your application.
. Reference `vertx-maven-plugin` as a plugin used to package your application:
+
[source,xml]
--
...
<build>
  <plugins>
    <plugin>
      <groupId>io.fabric8</groupId>
      <artifactId>vertx-maven-plugin</artifactId>
      <version>${vertx-maven-plugin.version}</version>
      <executions>
        <execution>
          <id>vmp</id>
          <goals>
            <goal>initialize</goal>
            <goal>package</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <redeploy>true</redeploy>
      </configuration>
    </plugin>
  </plugins>
</build>
...
--

For more information on packaging your {Vertx} application, see the link:https://vmp.fabric8.io/[Vert.x Maven Plugin] documentation.
