include::topics/templates/document-attributes.adoc[]

= {experience-http-api-guide-name}

The {ProductShortName} API Level 0 Experience provides a basic example of mapping business operations to a remote procedure call endpoint over HTTP using a REST framework. This corresponds to link:https://martinfowler.com/articles/richardsonMaturityModel.html#level0[Level 0 in the Richardson Maturity Model]. Creating an HTTP endpoint using REST and its underlying principals to define your API enables you to quickly prototype and design your API in a flexible manner. More background information on REST is available in xref:about_rest[].

This is an introduction to the mechanics of opening a service that is called remotely.

Building your API with {ProductShortName} gives you all the advantages that come with using microservices including flexibility and choice of framework and languages. At the same time {ProductShortName} provides useful infrastructure for interoperability and running your microservices such as `ConfigMap`, health checking, and single sign-on.


== Creating an HTTP Endpoint with {ProductShortName}

include::topics/experience-deploy-quickstart.adoc[leveloffset=+2]

include::topics/rest-level-0-experience-basic-interaction.adoc[leveloffset=+2]

include::topics/rest-level-0-experience-modify-wf-swarm.adoc[leveloffset=+2]

include::topics/rest-level-0-experience-modify-vert-x.adoc[leveloffset=+2]

include::topics/rest-level-0-experience-modify-spring-boot.adoc[leveloffset=+2]


== Design Tradeoffs

[width="100%",options="header"]
|====================================================================
|Pros           |Cons
a|
* Fast prototyping
* Flexible API Design
* HTTP endpoints allow clients to be language agnostic
a|
* As an application or service matures, the API Level 0 approach may not scale well to properly support a clean API design or use cases involving database interactions. Any operations involving shared, mutable state must be integrated with an appropriate backing datastore. All requests handled by an API designed in this manner will be scoped only to the container servicing the request. Therefore there is no guarantee that subsequent requests will be served by the same container.
|====================================================================


[[about_rest]]
== REST Resources

More background and related information on REST can be found here:

* link:https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm[Architectural Styles and
the Design of Network-based Software Architectures - Representational State Transfer (REST)]
* link:https://martinfowler.com/articles/richardsonMaturityModel.html[Richardson Maturity Model]
// Not sure about this one * link:http://restfulapi.net[Overview of REST concepts]
* link:https://www.jcp.org/en/jsr/detail?id=311[JSR 311: JAX-RS: The JavaTM API for RESTful Web Services]
* link:http://resteasy.jboss.org/docs.html[RESTEasy Documentation]
* link:https://spring.io/guides/gs/rest-service/[Building a RESTful Service with Spring]
* link:http://vertx.io/blog/some-rest-with-vert-x/[Some Rest with Vert.x]

